### PR TITLE
9141/feature/add share modal authors

### LINKED ISSUE #9141: Add share links to author pages
### Describe the problem that you'd like solved

It's more cumbersome to share author pages than it could be.  Today, the URL most be copied manually, then shared with others.

### Proposal & Constraints

Other pages, like the books page, contain a share modal that gives a number of options for sharing links.  Let's add this to author pages, as well.

### Additional context

This is related to #452, which is primarily concerned with adding a QR code option to the share modal.  This issue was created to reduce the scope of the aforementioned issue.

### Stakeholders

@LeadSongDog

### PR DESCRIPTION
**Pull request by aggelasdinou**
Closes #9141

This pull request is adding the Share Modal on the authors page next to the edit button and edit info. 

### Testing

View the changes in any author's page.

### Screenshot

before:
image

after:
image

### Stakeholders

@jimchamp

### CODE REVIEW

**Review by jimchamp — CHANGES_REQUESTED** [review]
Thanks, @aggelasdinou.  It looks like you pushed some unrelated changes, and some files that contain unresolved merge conflicts.  Could you rebase your changes on the latest version of `master`, correct any merge conflicts, and ensure that only code related to the issue that you're solving has been pushed to this branch?

**Comment by jimchamp** [comment]
It looks like this PR has been abandoned.  If you are still working on this @aggelasdinou, please comment here within the next three days.

**Comment by aggelasdinou** [comment]
I ll try to get it working correctly ,should i open a new pull request after?

**Comment by jimchamp** [comment]
Don't create a new PR.  When you push updates to [your branch](https://github.com/aggelasdinou/openlibrary/tree/9141/feature/add_shareModal_authors), this PR will be updated with the new code.

**Comment by jimchamp** [comment]
Closing as abandoned.  Feel free to re-open this if you are still working on it, @aggelasdinou.

**Pull request closed without merging**
