### PR TITLE
Drop unused entry point and templates for login and password

### PR DESCRIPTION
**Pull request by jdlrobson**
Openlibrary uses Archive.org for account management.
Defer to infogami for vanilla installs (if those are even supported)

Fixes: #2502

Closes #

### Testing

Make sure you can login.
Confirm the pages /account/email and /account/password are gone

### CODE REVIEW

**Comment by jdlrobson** [comment]
❌ No occurrences of /account/email
❌ No occurrences of /account/password

>    account.js
Looked into this and it does appear unused. The functions require form elements with classes email or password so these are now removed.

>    static/css/legacy.less
Fixed. Remaining issues point to forgot.html and openlibrary/templates/account/email/forgot-ia.html which still exist.

>    upstream/account.py
>     upstream/tests/test_account.py
This seems to be unrelated code. I don't wish to touch it not knowing what the plugin upstream is for.

**Comment by cdrini** [comment]
Tested:
- ✅ Can login
- ✅ Can logout
...🤷‍♀️

**Comment by jdlrobson** [comment]
> Ok, we can remove the forms stuff (they look super easy to remove);
Not super easy for me I'm afraid. Those methods are used in account_password class in account.py as well - I'm not sure if those classes can just be removed or there are other impacts.

TBH I have little knowledge of the python architecture and would appreciate someone else picking up the remaining parts of this task.

**Comment by jdlrobson** [comment]
Okay this became simpler after a rebase. e8ba7c03363db9d2661d187e8b0acbcff1359b50 drops those functions.

**Comment by cdrini** [comment]
Let's not delete `send_email_change_email` (sorry if my message was misleading!); it uses a template, and a bunch of other things. I created an issue to do that separately (#2702). I'll try reverting that part and then merge this pr :+1:

**Pull request merged**
