### PR TITLE
Fix author autocomplete showing death = birth

### PR DESCRIPTION
**Pull request by kaarora123**
Fixes issue #745

### CODE REVIEW

**Comment by mekarpeles** [comment]
Lgtm thanks!

**Comment by mekarpeles** [comment]
@kaarora123 do you have a twitter handle? We'd love to shout-out a thanks for your contribution!

**Comment by cdrini** [comment]
Thanks for the fix, @kaarora123 ! Note that it won't be deployed to production on openlibrary.org until the GitHub master gets deployed to production. You can check the commit listed at the very bottom of openlibrary.org ( 7a2acf7 as of writing) and compare it to the repo's commit history ( https://github.com/internetarchive/openlibrary/commits/master ) to see if your change has made it to prod yet.

Cheers!

**Comment by mekarpeles** [comment]
deploying f1f7e01 to prod now

**Comment by kaarora123** [comment]
@mekarpeles @cdrini Thank you for being so kind and helping me out for my first contribution! 

@mekarpeles Unfortunately, I don't have a twitter account but I'll be making one soon. Thank you though!

**Pull request merged**
