### PR TITLE
Re-enable Solr tests, and move Core tests to top level tests dir

### PR DESCRIPTION
**Pull request by hornc**
Trying this out on CI for the moment to confirm that it does pass with Travis too.

### CODE REVIEW

**Comment by bfalling** [comment]
Hey @hornc! Is this PR one that you want to pick up again?

Also, re: test dirs... Aside from the fact that I notice the Makefile doesn't run most of the tests(!), it seems like what tests do exist are held in separate directories interleaved with the code. I generally favor going the route of separating all tests out into their own directory, in order to avoid cluttering the code tree.

Any strong thoughts (from anyone -- @tfmorris, @gdamdam, etc.) on how you think we should organize tests going forward?

**Comment by hornc** [comment]
Hi @bfalling , this was an attempt to take advantage of existing tests that weren't being run in the Makefile, as you note. In the process of making these tests pass I noticed there seemed to be duplicate methods, and I had trouble determining whether the tested methods were even being used in production, so I think this PR needs another review to check whether the tests are still relevant.

I don't really have strong views on where the tests should be. I do see value in keeping the tests close to the code they test, but currently there seems to be no standard structure, and the code tree seems already overly complex, so choosing a test organization strategy across the entire project is the important thing.

I'll rebase this PR and dig further into the solr code to check what is still relevant.

**Comment by hornc** [comment]
I see this as part of the issue you raised recently https://github.com/internetarchive/openlibrary/issues/316    This was intended to be a start to the test consolidation process, and a way for me to get up to speed on OL's Solr code.

**Comment by hornc** [comment]
Hey @bfalling , I have rebased this old PR, checked the Solr tests still seem generally valid, and moved them all to `openlibrary/tests` as we discussed in #316  I have also moved all the Core tests to the same location, and simplified the Makefile test task. There is still some further tidy up required for #316 , but I think this is a good start!

Please review and let me know if you want anything tweaked.

**Comment by bfalling** [comment]
Looks great, @hornc. Thanks!

**Comment by tfmorris** [comment]
Sorry for the late reply, but re test directory organization I don't have a strong opinion. Separating the trees at the top level seems to be the current fashion, so I'm fine with that.

**Pull request merged**
