### PR TITLE
Remove unused subjects.js

### PR DESCRIPTION
**Pull request by cdrini**
Refactor. Found no references to `Subject(` in the js or in the python referencing this object. My guess was this was an attempted restructure which was never actually switched to/used.

### Testing
- ✅ Confirm subjects pages still work.

### CODE REVIEW

**Comment by mekarpeles** [comment]
@cdrini did we test the published graph? e.g. selecting regions and seeing if the subjects page reloads w/ the right queries?

**Comment by cdrini** [comment]
Yep! Works as it did :)

**Comment by cdrini** [comment]
It's up on testing.openlibrary.org

**Review by jimchamp — APPROVED** [review]
`subjects.js` was used to support the home page subjects carousels, when those were a thing.

**Pull request merged**
