### PR TITLE
Fix tap-highlight-color

### LINKED ISSUE #5369: Remove tap-highlight-color for better Mobile UI
### Describe the problem that you'd like solved

The default behavior is that any element (or containing element) that has `cursor: pointer` explicitly set and is clicked will flash blue momentarily. (Only for mobile devices)
### Proposal & Constraints

But in order to improve the UI keeping in mind, the PWA should we remove the default and set it to `-webkit-tap-highlight-color: transparent;`

According to my research, there are no accessibility requirements in [WCAG](https://www.w3.org/TR/WCAG21/) that require the use of `-webkit-tap-highlight-color`.
### Additional context

Current behaviour (When we click the navigation dropdown menu):
image

### Stakeholders

@cdrini @bpmcneilly

### PR DESCRIPTION
**Pull request by Yashs911**
Closes #5369 

### Stakeholders

@cdrini

### CODE REVIEW

**Comment by cdrini** [comment]
@jimchamp Would you be able to take a look at this one today? @Yashs911 's other PR requires it.

**Comment by jimchamp** [comment]
I'm still seeing the blue flash in Chrome's mobile view:
blue_flash

**Comment by Yashs911** [comment]
Yes, it's still there but only limited to the summary tag, instead on openlibrary.org it is applied to the list item.

**Comment by jimchamp** [comment]
Ahh, got it.  I thought that this PR was meant to remove the blue flash entirely.

It is better than before.  Can confirm that the entire list of links does not flash blue when the summary item is clicked. Lgtm!

**Pull request merged**
