### PR TITLE
Add vim and emacs to Dockerfile.olbase

### PR DESCRIPTION
**Pull request by cclauss**
A sub-task of #4060

### Testing
```
docker-compose build --pull && docker-compose up -d && docker exec -it openlibrary_web_1 /bin/bash
vi
emacs
```

### CODE REVIEW

**Review by cdrini — CHANGES_REQUESTED** [review]

**Comment by cclauss** [comment]
Install vim and emacs in olbase, not oldev

**Comment by hornc** [comment]
@cdrini this seems unnecessary -- vim and emacs are not required to run OL in production, and it's increasing the image size considerably. Text editors shouldn't be even needed in the dev image.

I have noticed that the current production image is based on `oldev` and contains all the test requirements. When I created `olbase` and `oldev` the intent was to create a functional production image based on `olbase`, without the test and other support and test database etc.

**Comment by cclauss** [comment]
I agree that the extra weight of vim + emacs seems troublesome.  In yesterday's deploy, our docker save, docker load, and rsync times were all noticeably longer than the previous week.  We can install one of these two tools just-in-time should the need arise.

**Comment by cclauss** [comment]
On the olbase vs. oldev thing, I am less convinced.  I prefer to run exactly the same code that was tested.  I doubt that our testing dependencies are very heavy.

**Pull request merged**
