### PR TITLE
updating team fellows for 2024

### LINKED ISSUE #9226: Updated Team page for 2024 fellows

### PR DESCRIPTION
**Pull request by mekarpeles**
Addresses team page portion of #9226

### CODE REVIEW

**Comment by mekarpeles** [comment]
Squash before merge

**Comment by scottbarnes** [comment]
We need to change `team.js` it seems.

I think the diff below for `openlibrary/plugins/openlibrary/js/team.js` will get the page to a vaguely tolerable place to the moment, but we probably need a separate issue for figuring out how to handle past volunteers, and fellows who might appear in more than one year.

I believe the current design reflects what we had discussed before to minimize the amount of upkeep this file needs, but it may fall short. Anyhow:
```diff
diff --git a/openlibrary/plugins/openlibrary/js/team.js b/openlibrary/plugins/openlibrary/js/team.js
index 9550ab819..5380d8ade 100644
--- a/openlibrary/plugins/openlibrary/js/team.js
+++ b/openlibrary/plugins/openlibrary/js/team.js
@@ -1,5 +1,6 @@
 import team from '../../../templates/about/team.json';
 export function initTeamFilter() {
+    const currentYear = new Date().getFullYear().toString();
     // Photos
     const default_profile_image =
     '../../../static/images/openlibrary-180x180.png';
@@ -46,10 +47,10 @@ export function initTeamFilter() {
       !matchSubstring(person.roles, 'staff')
     );
     const currentFellows = fellows.filter((person) =>
-        matchSubstring(person.roles, '2023')
+        matchSubstring(person.roles, currentYear)
     );
     const pastFellows = fellows.filter(
-        (person) => !matchSubstring(person.roles, '2023')
+        (person) => !matchSubstring(person.roles, currentYear)
     );
 
     // ********** VOLUNTEERS **********
@@ -219,10 +220,10 @@ export function initTeamFilter() {
           !matchSubstring(person.roles, 'staff')
             );
             const currentFellows = fellows.filter((person) =>
-                matchSubstring(person.roles, '2023')
+                matchSubstring(person.roles, currentYear)
             );
             const pastFellows = fellows.filter(
-                (person) => !matchSubstring(person.roles, '2023')
+                (person) => !matchSubstring(person.roles, currentYear)
             );
 
             const volunteers = filteredTeam.filter(
```

image

**Comment by mekarpeles** [comment]
@scottbarnes any chance we can submit the above diff as a PR to reference and land before this one?

**Review by scottbarnes — APPROVED** [review]
LGTM.

**Pull request merged**
