### PR TITLE
Add:Make data dumps for /type/page.

### LINKED ISSUE #8401: Make data dumps for /type/page
### Describe the problem that you'd like solved

I would like to get a data dump of just the `/type/page` entities.
I can see that there are some in the `all_types_dump` but it's too big for me to download.

I was just running:
`curl -s -L https://openlibrary.org/data/ol_dump_latest.txt.gz | gunzip -c | grep '/type/page'`

### Why?
1. I've been working on cleaning up our docs and I'd like to be able to more easily search the docs that are on openlibrary.org using tools like grep.
2. As I understand it, the sitemap.xml is generated by these dumps and I'm wondering if we should in the future make the sitemaps have our pages on them for easier searching.
3. I'm wondering if we can put them into solr and have a nice search for our docs but before doing that I'd like to be able to see what docs we actually have.

### Proposal & Constraints

I poked around briefly at the data dump code and I think it could be as simple as adding it here:
https://github.com/internetarchive/openlibrary/blob/085702675121b98907255ae204abca44cba7c51a/openlibrary/data/dump.py#L215-L221

We'd also want to make one of these special links like: https://openlibrary.org/data/ol_dump_authors_latest.txt.gz to redirect to the pages dump.

### Additional context

https://github.com/internetarchive/openlibrary/wiki/Sitemap-Generation
https://github.com/internetarchive/openlibrary/wiki/Generating-Data-Dumps
https://openlibrary.org/developers/dumps

### PR DESCRIPTION
**Pull request by xonx4l**
issue-:#8401

Closes #8401

Added Make data dumps for /type/page.

### CODE REVIEW

**Review by cdrini — CHANGES_REQUESTED** [review]
Hi @xonx4l . Please follow the pull request template. We will not be able to review your pull request unless we can confirm that the changes have been tested.

**Comment by cdrini** [comment]
Hi @xonx4l , could you please add the steps you used to test this code? Also it appears there are some CI failures related to linting that need to be addressed.

**Comment by RayBB** [comment]
@xonx4l please let me know if you'll be able to continue working on this. If not I'd like to give someone else a chance as this feature will be very useful for me in the near future.

**Comment by cdrini** [comment]
Seeing as this has stagnated for over two weeks, closing to allow someone else to tackle. Please feel free to re-open if you have the time to continue on it, @xonx4l !

**Pull request closed without merging**
