### PR TITLE
Update Croatian translation

### PR DESCRIPTION
**Pull request by milotype**

### CODE REVIEW

**Comment by cdrini** [comment]
Awesome, thanks @milotype ! I've placed this on testing.openlibrary.org ; do you want to give it a whirl to see if everything looks as you expected?

**Comment by milotype** [comment]
@cdrini Thank you!
In general it looks ok, but there are still many strings which do not translate ...

I'm not a programmer, but some similar issues are: #2819, #4679, #791

**SUGGESTION:**
If possible, I'd suggest to use a translation platform like Weblate for the UI, which _Internet Archive_ is already using (https://hosted.weblate.org/projects/internetarchive/).

P.S.
I'm just a translator who likes to help translating projects like yours. I can't really help with programmer's issues. Sorry!

**Comment by cdrini** [comment]
If you'd like to tackle #4679 , you can do that straight on openlibrary.org! I'll just need your OL username so I can give you permission.

We've been looking at Weblate, and it's something we want to explore, but haven't gotten the chance to yet :( I'm currently planning on making some tweaks to our i18n flow to make things easier. For example, for Croatian, we'll need to run the "extract" step to pull out all the strings in the HTML files that have been added. You can currently do that, but it also regenerates all the other languages, and causes some other small issues. But you're free to try it! That should create more strings in the .po file for you to translate. The steps are listed here: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/i18n/README.md#extracting-strings-from-htmlpython-files-generating-the-pot-file

**Comment by milotype** [comment]
Thank you for the reply … my username is "milotype".

At https://openlibrary.org/subjects.hr?m=edit <https://openlibrary.org/subjects.hr?m=edit> I do not have permission. Please grant me permission.

If I may, I'll contact you again, if I don't know what to do …

Cheers,
Milo

**Comment by cdrini** [comment]
You should now have permissions! See #4679 , and let me know if you have any issues!

**Pull request merged**
