### PR TITLE
Change work from edition page

### LINKED ISSUE #654: Add to edition /edit UI: Admin-only raw input to set `work_id`
Currently there is no way to move an edition from one work to another.

This issue proposes a new UI field (only accessible to admins or trusted-users for starters) which shows the edition's current work_id, with the option to change it. In the future, we may have a public facing UI (similar to the author search/select tool) for changing an edition's work.

One question which has been raised is, what happens if/when a work's last edition is moved/re-assigned? For now, we're going to leave these childless works dangling and not redirect. In the future they will either be merged + redirected, or editions will be added to them.

In the latter case, the work is likely valid but the wrong addition is associated with it; e.g. the work is for Lord of the Rings: Return of the King, but the edition was accidentally Lord of the Rings: Two Towers. In this case, Lord of the Rings: Two Towers should be moved to the appropriate Work (if one exists) and the Return of the King work should remain empty (though this may break the UI and we should plan/test accordingly)

### PR DESCRIPTION
**Pull request by cdrini**
ol move edition

Depends on #660 . Ignore the first 2 commits, since they're the refactoring done there. Resolves #654.

- It doesn't seem like solr is automatically updated, but needs some more research
- Creating a new work from the editions page is not implemented
- Doesn't check if moving last edition from a work

### CODE REVIEW

**Comment by hornc** [comment]
@cdrini , when I try to run this PR locally I get and js console error on page load:
```
edit:511 Uncaught TypeError: $(...).setup_multi_input_autocomplete is not a function
    at HTMLDocument.<anonymous> (edit:511)
    at Function.<anonymous> (jquery-1.3.2.min.js:19)
    at Function.each (jquery-1.3.2.min.js:12)
    at Function.ready (jquery-1.3.2.min.js:19)
    at HTMLDocument.<anonymous> (jquery-1.3.2.min.js:19)
```

and the admin /  librarian mode js button no longer works. I think something has broke in the js. I'm using   Chrome to test.

**Comment by cdrini** [comment]
@hornc The JS (and CSS) has to be regenerated; run `make js css` in `/openlibrary` to get everything updated.

**Comment by hornc** [comment]
Nice! The search and suggest drop-down works really nicely! (and seamlessly in the dev environment too ;)  )

Here are my initial comments:
### 1) labels
The label "What works are associated with this edition?" implies many works can be associated, and perhaps the hierarchy of works to editions is inverted?

Suggestion:

**This Edition**
**Is an Edition of the following Work:**

suggestion for the info text:
_"Sometimes Editions can be associated with the wrong Work. You can correct that here."_
Maybe add a warning about the effects of a change? "Making a change here will move this Edition to another Open Library Work, which will affect searches etc"  I can't think of a short, clear way to spell out the consequences right now :)

### 2) Author / Work select inputs
This comment goes for the author select too, so covers things outside this PR, but it has always frustrated me that, once the focus is off the input, the field looks like free-text, yet there is a OLID locked in behind the scenes that cannot be viewed unless you go back into edit mode and re-select.

Having a link to the selected Work / Author for verification purposes would be great. Changing the input type to display the current selected work/author in something other than a text-input would be less misleading too. This is really a comment on the pre-existing Author selection :)

**Comment by hornc** [comment]
Now I'm reviewing the edit form for an Edition in general, and there are some issues around what fields belong to the Work and which to the specific edition.

I believe the top **Title** and **Author** fields, and the entire **What's It About?** tab are Work fields, although the UI does not make this clear. 

@cdrini is there a way to reload the entire form using the newly selected work's data so that all references to the original work are removed, and replaced with the new work? The re-loading and changing of fields will be a bit disruptive, but it might be a good indicator that a big change has been proposed, and if too much on the screen changes and looks incorrect I'd hope the user would back off and cancel instead of saving.  Adding a warning message saying something like "You have changed the Work level item of this record, please review the following fields carefully before saving!"

I haven't checked the code in detail, so this may be quite difficult, but I'm putting it out there, maybe as future functionality?

**Comment by cdrini** [comment]
1) Labels
How does this look:
image

 
2) Misleading autocomplete input appearance - completely agree! I have some ideas for a good UI on how to fix this, but I think I'd like it as a separate PR for simplicity's sake.

3) Work-edition editing relationship
Yeah, that's still a little awkward :( I added a warning to the field (see image above), but I don't know if there's an easy way to handle that without a decent number of changes. I think ideally the UI should probably just separate the work/edition edit pages, but I'm not even sure if that's best :P

**Comment by mekarpeles** [comment]
If you rebase, it should fi the travis issues

**Comment by LeadSongDog** [comment]
Should most classifications not be work fields rather than edition?

**Comment by cdrini** [comment]
@LeadSongDog Not sure I understand; could you expand?

**Comment by LeadSongDog** [comment]
If on, say Wikipedia, a link to an OL book is added, it will often just be the URL copied from a browser address bar. If that URL has perishable content such as the slug then the link fails when the title is corrected. Eliminate the slug and that problem doesn't arise.

**Comment by LeadSongDog** [comment]
A Dewey or LC Class is not edition specific (though the year may be appended to an LC Class for specific editions. It is essentially a subject indication that persists across editions.

**Comment by mekarpeles** [comment]
I think @LeadSongDog may be right on this point, though I'm not sure it impacts this feature? It's likely a separate issue we should open re: LC + Dewey #s

**Pull request merged**
