### PR TITLE
Remove version tags

### LINKED ISSUE #9092: Remove version tags from docker compose files
### Problem

[They haven't been needed](https://github.com/compose-spec/compose-spec/blob/master/04-version-and-name.md) for a long time (since like 2019) and as of the latest docker I'm getting warnings they're depreciated.

Warnings when running `docker compose up`
```
WARN[0003] The "HOST" variable is not set. Defaulting to a blank string.
WARN[0003] /Users/ray/workspace/openlibrary/compose.yaml: `version` is obsolete
```

#### Evidence / Screenshot
image

### Reproducing the bug

_No response_

### Context

_No response_

#### Proposal & constraints

Simple as removing those lines. An easy first issue for someone :)

### PR DESCRIPTION
**Pull request by BaasanbayarOverflow**
Closes #9092

Fix

### Technical

Removed "VERSION" tags from docker compose files

### Stakeholders

@RayBB

### CODE REVIEW

**Review by RayBB — APPROVED** [review]
Great job thanks for doing this! 👍 
We just need staff to merge now!

**Comment by RayBB** [comment]
@scottbarnes can you merge this?

**Comment by scottbarnes** [comment]
@RayBB, I imagine it's exceedingly unlikely this change will face any opposition, but other things being equal, PRs aren't meant to be merged until the associated issue has gone through triage on Monday so that the core team can be aware of all potential changes and have time to raise any issues.

**Comment by RayBB** [comment]
@scottbarnes thanks for the heads up that's good to know. Is this written anywhere in the process docs? Maybe we should add a note to be clear about it.

**Comment by scottbarnes** [comment]
> @scottbarnes thanks for the heads up that's good to know. Is this written anywhere in the process docs? Maybe we should add a note to be clear about it.

To my knowledge it's not. But yes it should be somewhere. I think one of the issues we face is that we want things *somewhere* but it's not always obvious where it should be. Not that this excuses it not being documented. 

I'll take responsibility for trying to find a place for this.

**Pull request merged**
