### PR TITLE
Book Page: Deduplicate work description / Remove work-level classifications

### PR DESCRIPTION
**Pull request by jimchamp**
This PR includes two book page changes:
1. Work descriptions are only displayed once per page.
2. Work-level classifications are removed altogether.

### CODE REVIEW

**Comment by mekarpeles** [comment]
lgtm

**Comment by LeadSongDog** [comment]
I don’t understand. Absent a specific edition-level classification, why would we not show the work classification?

**Comment by cdrini** [comment]
Work-level classification is sort of deprecated? I think there used to be a bot or something that added that info to the work from editions, but I don't think there is anymore, and they can't be edited via the UI.

In search and for openlibrary.org/explore, the longest classification (assumed to be the most precise) is chosen as the work's classification for sorting.

Is the issue here when you land on an edition that doesn't have a classification, but a sibling edition that *does* have a classification (or at the work), that its preferable to show something over nothing?

**Comment by LeadSongDog** [comment]
#897 #3302 #3309 and a bit of #661 relate.
Why and where would work-level classification have been deprecated? Editions are often imported with minimal metadata: storing the classification at the work level means all sibling editions are classified, not just the few imported with complete metadata. It’s an easy win, why ignore it?

**Comment by tfmorris** [comment]
That's so weird. Why aren't classifications, like subjects, authors, etc, considered work level metadata?

**Pull request merged**
