### PR TITLE
Borrow templates not needed

### PR DESCRIPTION
**Pull request by jdlrobson**
These redirect to `subjects/in_library` and thus can be removed.

### CODE REVIEW

**Comment by mekarpeles** [comment]
I wondered about this but I think DAISY downloads may redirect to this page still

**Comment by jdlrobson** [comment]
"I wondered about this but I think DAISY downloads may redirect to this page still"

Could you provide some insight (URL/replication steps) to what this means so I can investigate?

**Comment by mekarpeles** [comment]
See related: https://github.com/internetarchive/openlibrary/pull/819

**Comment by jdlrobson** [comment]
Not 100% sure im getting all the context but sounds like its an admin route?
How can i access admin interface locally??

**Comment by jdlrobson** [comment]
I'm a bit confused @mekarpeles I'm only deleting a subset of the templates attempted to delete in #819 . There are absolutely no references in the codebase. This actually gives me even more confidence that the removals in this patchset are fine!

The comment in https://github.com/internetarchive/openlibrary/pull/819/files#r172676687 for instance is quite rightly pointing out that that patch was deleting too many of those templates. I'm only deleting 2 templates that are not referenced.. not all of them!

**Comment by mekarpeles** [comment]
I just double checked and you're right! This is a different template than the one I was thinking. This is good to go, sorry for leading you astray here!

**Pull request merged**
