### PR TITLE
from six.moves.urllib.parse import quote_plus

### PR DESCRIPTION
**Pull request by cclauss**
Closes #

### CODE REVIEW

**Comment by cclauss** [comment]
This PR progresses our Python 3 build three more steps wild not breaking Python 2.

Once this lands, we are blocked on a bytes vs. str issue which I tried unsuccessfully to solve.
https://travis-ci.org/internetarchive/openlibrary/jobs/636684219#L901

**Comment by hornc** [comment]
@cclauss Thanks, I was able to test this immediately on the Python3 Docker image I was experimenting with today. I've just pushed the branch up to a `python3` branch: https://github.com/internetarchive/openlibrary/compare/python3

It's just meant as an experiment to see what else is left and shouldn't be merged yet. 

It's using Python 3.5 which is the version that comes with Xenial. Bionic comes with 3.6. I'm taking small steps.

I can see the bytes vs. string issue you mention above. I can take a look at it if you like.

I've just raised a PR for infogami to reinstate an import that is used in multiple places by OL: https://github.com/internetarchive/infogami/pull/70 which is an error that this Docker image revealed.

**Comment by cclauss** [comment]
The Docker image sounds like a great idea!  That might help my efficiency greatly.  Py35 EOLs this year so 3.6 strikes me as a better target.

Please look into the bytes if you can.

**Comment by cclauss** [comment]
```
add-apt-repository ppa:deadsnakes/ppa
apt-get update
apt-get install python3.8
```
https://docs.python-guide.org/starting/install3/linux/

**Pull request merged**
