### PR TITLE
Update and store dev db locally

### LINKED ISSUE #693: Dev instance requires librarians usergroup
The dev instance errors because it expects the usergroup `/usergroup/librarians` after #664 .

Here is the error that appears on the homepage: http://bl.ocks.org/cdrini/raw/b93f021e83065ddaf1b9b0f83dafcf83/

### PR DESCRIPTION
**Pull request by cdrini**
Resolves #693

Adds `/usergroup/librarians` to the dev instance db, and also stores the dev instance db locally as opposed to online (it's only 1 MB).

### CODE REVIEW

**Comment by mekarpeles** [comment]
These changes look good (though they do increase the footprint slightly via the db dump). Anyone else have an opinion?

I'm of the mind that these changes are good to go.

**Comment by mekarpeles** [comment]
@cdrini can you provide some context (for records) as to:
1) your process for creating the db dump?
2) steps someone with an existing vagrant setup should do to handle migrations / load latest db?

I'll follow these instructions and add our `reading log`  schema #719

**Comment by cdrini** [comment]
Oh, it's actually *100 K* gzipped; 0.5 M ungzipped. I'll ungzip it so we can have better diffs.

I'll post some instructions once I update the code.

**Comment by hornc** [comment]
@cdrini sorry, late to the party :tada: but I'm slightly concerned this is a big chunk of dev data to commit that isn't strictly necessary.  The dev db should be minimally functional, but it makes sense to me that it be populated via some external script, even using the script that fetches records individually from production, or some loading mechanism that loads specific test items that are included for a reason.

At the very least, the content in the current dev db should be evaluated for usefulness. I think it is probably just a snapshot of one dev's past db and reflects the history of what he had been working on, and was put up on IA for convenience, rather than a thought out attempt to give a minimal set of useful records to dev with. :)

Certainly when I am trying to do anything specific I find I need to download new and appropriate records form production to check anything meaningful in dev.

**Comment by hornc** [comment]
... and an additional concern is this bypasses all the standard set up of an OL instance by using a pre-existing db image. How would one set up an OL db in the first place, what tables and values are necessary, and how can we tell in dev?

I appreciate that this was still an issue before your PR, as the db dump was still loaded from elsewhere, and agree the goal of reducing external stuff necessary for the repo to be usable is a good one...  just raising what might be a bigger issue underlying the use of a db dump for dev!

I have no idea how to (safely) build an OL db from scratch :smile:

**Comment by cdrini** [comment]
I'm liking the convenience of having it in the git repo (updating it becomes as easy as the steps which I will soon write down :P ). I think this file should never get too large (it should be a very basic bare-bones dev db), so keeping it in the repo is good. We can also monitor it for changes, which is nice.

All the current steps for setting up a dev db are in bootstrap.sh (and are run during vagrant provisioning as necessary):

https://github.com/internetarchive/openlibrary/blob/a04637b01ab4109217d8ed143325916ea1d3502c/scripts/bootstrap.sh#L46-L66

The dev db dump is loaded also in boostrap.sh:
https://github.com/internetarchive/openlibrary/blob/a04637b01ab4109217d8ed143325916ea1d3502c/scripts/bootstrap.sh#L68-L71

I agree that it would be useful to re-evaluate what's in the dev db and whether it should be there, but opting on punting that for a future PR :P .

**Comment by cdrini** [comment]
@mekarpeles Not sure where the best place to put these instructions, so I'll just put them here for now:

To update the dev instance dump:

1. Create a new copy of the site (i.e. clone, vagrant up, etc.). This ensures we don't add a lot of cruft to the db. (I know this seems annoying, but it worked almost flawlessly for me).
2. Once it's running, add anything to the db. You can use the UI, copydocs, whatever.
3. Once done, run `/openlibrary/scripts/dev-instance/create-dev-db-pgdump.sh > /openlibrary/scripts/dev-instance/dev_db.pg_dump` to update the db.
4. Check the diff to make sure there wasn't any cruft added.

**Comment by cdrini** [comment]
(Actually I think you might need to create the databases first if they're non-existent, @mekarpeles . Maybe in openlibrary/scripts/bootstrap.sh , where the other dbs are made.

**Comment by hornc** [comment]
Underlying my concerns for now was the usual stuff about committing db dumps and large files into git history means they take up space in the history even when they are trimmed down later. I guess there are ways to remove the files completely later if it really is a problem.

I'm not saying no, just be aware of potential consequences :)

**Comment by mekarpeles** [comment]
merging to un-break dev env

**Pull request merged**
