### PR TITLE
typo fixes

### PR DESCRIPTION
**Pull request by YuriNikolai**
Fixes 2 typos in the new PT translation. I'm new to contributing to repos and don't know how to create a new branch for merging here, so forgive me if something was done wrong and I'm not supposed to pull request into the master branch (though it should be fine for a minimal change like this).

### Testing
Typo can be found on the login screen ("Arquiivo" should be "arquivo").

### CODE REVIEW

**Comment by cdrini** [comment]
Thanks @YuriNikolai ! It looks like you've done everything correctly; you have created a new branch :)

Would you be able to take a look at this one, @ninalencastro ?

**Review by cdrini — APPROVED** [review]
This looks pretty simple; google translate translates "Archive" to arquivo, so I'll assume this is correct! Thank you @YuriNikolai !

**Comment by ninalencastro** [comment]
Aye! It was a typo :) I guess it slipped by me when I wrote it, thank you for catching it @YuriNikolai !

**Comment by YuriNikolai** [comment]
Thank you for all your work in the new translation! I'm glad I could help in a little way :)

**Pull request merged**
