### PR TITLE
Remove inline js from edit_head.html

### LINKED ISSUE #8383: Remove inline js: lib/edit_head.html
Remove the inline JS from this file following the recommended steps in #4474

### Proposal & Constraints

We should remove it! - Previous question [here](https://internetarchive.slack.com/archives/C0ETZV72L/p1696535611003499?thread_ts=1693606929.163359&cid=C0ETZV72L).
Note: this is slightly related to #5807 

### Related files

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/lib/edit_head.html

### PR DESCRIPTION
**Pull request by AdwaitSalankar**
Closes #8383

Removes inline js from edit_head.html.

### Stakeholders
@RayBB

### CODE REVIEW

**Comment by AdwaitSalankar** [comment]
@RayBB Can you please review this?

**Review by RayBB — APPROVED** [review]
LGTM!
@mekarpeles can you merge?

**Comment by AdwaitSalankar** [comment]
@RayBB Can you add hacktoberfest label?🙂

**Comment by scottbarnes** [comment]
> @RayBB Can you add hacktoberfest label?🙂

@AdwaitSalankar, I updated the issue. :)

**Comment by mekarpeles** [comment]
We should keep an eye on this one for our next release to monitor for security implications.

**Pull request merged**
