### PR TITLE
Drops jquery.autocomplete plugin

### LINKED ISSUE #2490: Drop jquery.autocomplete plugin and use jquery ui
The version of jquery.autocomplete we use is outdated, and is available in jQuery UI. It is blocking us upgrading jQuery.

jQuery autocomplete is imported inside index.js
```
import '../../../../vendor/js/jquery-autocomplete/jquery.autocomplete-modified.js';
```
We also include jQuery UI which has autocomplete functionality using:
```
$.ui.autocomplete
```

- [ ] Drop jQuery autocomplete vendor import
- [ ] Update existing usages of the autocomplete function inside openlibrary/plugins/openlibrary/js/autocomplete.js to use $.ui.autocomplete function

### Evidence / Screenshot (if possible)

When sharing your pull request make sure to test the search box in the top right corner and detail what you needed to change to make use of jQuery.Ui

### Expectation
Before and after your pull request it will be possible to search

### Stakeholders
@cdrini

### PR DESCRIPTION
**Pull request by hari-govind**
Closes #2490 

refactor
### Technical

The `jquery.autocomplete` plugin import is removed from `index.js`. The unused `vendor/js/jquery-autocomplete/jquery.autocomplete-modified.js` file is removed.
### Evidence

Welcome to Open Library Open Library

### CODE REVIEW

**Comment by mekarpeles** [comment]
It looks like the `/edit` pages (both editions and works) are using jquery autocomplete to match author names and to move editions to other works.

https://dev.openlibrary.org/works/OL276469W/What_Maisie_knew/edit
jquery.js:248 Uncaught Error: cannot call methods on autocomplete prior to initialization; attempted to call method '/authors/_autocomplete'

**Comment by jdlrobson** [comment]
Sorry @hari-govind this is taking me a while to review. I am having issues testing this locally. Per Mek's bug report I suspect some of this is being used and needs to be extracted and plugged into the jquery autocomplete version of this code.

**Comment by hari-govind** [comment]
@jdlrobson So some code from the removed file needs to be ported to `$.ui.autocomplete` and then plugged into `openlibrary/plugins/openlibrary/js/autocomplete.js`?

**Comment by jdlrobson** [comment]
@hari-govind i will be able to look into this some more on friday.

In the meantime if you are able to debug the issue that @mekarpeles has reported and understand what's happening and why that would be extremely helpful!

**Comment by jdlrobson** [comment]
@hari-govind I'm not sure what's happening here but obviously this is much more complicated then we expected. I think as a result we should deprioritise until we can get to the bottom of this.

Should we close this pull request and record what we've learned on the github issue?

**Comment by hari-govind** [comment]
@jdlrobson I think that would be better. I will try to help in other simple issues and maybe work on this issue later when we have more details.

**Comment by hornc** [comment]
@jdlrobson what's the status on this one? Is the consensus to close?

**Comment by jdlrobson** [comment]
Per @hari-govind let's drop back to the github issue and analyse this task some more.

**Pull request closed without merging**
