### PR TITLE
Creates lessc Makefile function to DRY up Less commands

### LINKED ISSUE #1879: Refactor CSS step in makefile
In preparation of adding the Less clean CSS plugin, refactoring the `lessc` command to a for loop and function call provides a single point of update when updating the flags passed to the plugin.

## Evidence 

> Relevant url?

N/A

> Screenshot (if possible):

N/A

Running `make css` process Less files in the same fashion as before, however editing which Less files are converted becomes much simpler, as does changing the command line argument and flags.

## Details

> Logged in (Y/N)?

N/A

> Browser type/version?

N/A

> Operating system?

All

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

Create a lessc function that works from a single argument to iterate over the targeted Less file names.

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

### PR DESCRIPTION
**Pull request by shaneriley**
> **Description**: What does this PR achieve? [feature|hotfix|refactor]

Closes #1879

> **Technical**: What should be noted about the implementation?

Refactoring to a function eliminated the default terminal output. Added an echo to note which file was being processed.

> **Testing**: Steps for reviewer to reproduce / verify this PR fixes the problem?

Run `docker-compose exec web make css`

> **Evidence**: If this PR touches UI, please post evidence (screenshot) of it behaving correctly:

N/A

### CODE REVIEW

**Comment by brad2014** [comment]
Alternatively, if you wanted to do the old-fashioned make dependency approach, you wouldn't need macros:

```
CSS_PAGES  = admin book edit form home lists plain subject user book-widget design dev 

.PHONY: css 
css: $(patsubst %,$(BUILD)/page-%.css,$(CSS_PAGES)) $(BUILD)/js-all.css

$(BUILD)/%.css : static/css/%.less $(BUILD)
  @echo Compressing $<
  lessc -x $< $@

$(BUILD) :
  mkdir -p $@
```

**Comment by jdlrobson** [comment]
This is cool, but wondering what it would take to move these into package.json ?

**Comment by shaneriley** [comment]
We can go the watcher route instead, which would be great considering you don't have to run make every time you change styles, but it will require some rewriting and reorganization of the Less files. Adding https://www.npmjs.com/package/less-watch-compiler, for example, can allow us to specify the source and destination directories, but it will blindly compile each file individually which will lead to errors. There are a lot of Less files that assume previous Less files have been compiled in before it, and use variables that aren't instantiated in that file.

I'm not sure if we can have a similar setup with existing Less watchers, but when I use Sass I set up Chokidar to ignore files prepended with an underscore to get around that. I'll do some research and see if there's a similar option.

**Comment by jdlrobson** [comment]
I'm hoping to move this into webpack and drop the lessc compiler altogether.

See https://github.com/internetarchive/openlibrary/pull/1936 and #1123 
I've also setup a board to track work for this project of JS modernization.
https://github.com/internetarchive/openlibrary/projects/10?add_cards_query=is%3Aopen

**Comment by mekarpeles** [comment]
It looks like with #2003 this can be closed

**Comment by shaneriley** [comment]
> It looks like with #2003 this can be closed

👍 on it being irrelevant once #2003 is merged.

**Pull request closed without merging**
