### PR TITLE
Solr updater work cleanup

### PR DESCRIPTION
**Pull request by cdrini**
Refactor

### Testing
Before, clear solr's memory: `docker volume rm openlibrary_solr-data openlibrary_solr-updater-data`
- [x] docker-compose exec web make reindex-solr
- [x] solr-updater handles edits
- [x] searching works on the site
- [x] Sending multiple docs in an update request, the third doc doesn't fail, as it used to.
```py
from openlibrary.solr.update_work import solr_update, AddRequest
reqs = [
  AddRequest({
    "key": "/b/foo",
    "type": "work",
    "title": "Dummy Doc 1"
  }),
  AddRequest({
    "key": "BLAH",
    "title": "Dummy Doc 2"
  }),
  AddRequest({
    "key": "/b/glue",
    "type": "work",
    "title": "Dummy Doc 2"
  }),
]
solr_update(reqs, solr_base_url='http://localhost:8983/solr/openlibrary')
```

### **Special Deploy**
In order for the tolerant solr_update to take effect, we need to update the solrconfig file on solr0. Since solr copies the config files over, the config volume mount isn't actually used after the first run. I tested this locally.

```sh
docker cp conf/solr/conf/solrconfig.xml openlibrary_solr_1://var/solr/data/openlibrary/conf/solrconfig.xml
docker exec -it -u root openlibrary_solr_1 chown solr:solr //var/solr/data/openlibrary/conf/solrconfig.xml
```

Then, in the solr admin dashboard, go to "Core Admin" in the left sidebar and click "Reload". That'll reload the config file. Note a docker restart _does not do the trick_.

### CODE REVIEW

**Comment by mekarpeles** [comment]
@cdrini is this ready to be removed from draft?

**Review by mekarpeles — APPROVED** [review]
changes lgtm, assuming nothing changes, feel free to remove from draft and merge when ready

**Review by mekarpeles — APPROVED** [review]
changes lgtm; @cdrini leaving to you to coordinate merge + deploy

**Comment by cdrini** [comment]
Did the necessary steps on ol-solr0 :+1:

**Pull request merged**
