### PR TITLE
More cleanup

### PR DESCRIPTION
**Pull request by jdlrobson**
The home page will now serve 4kb of CSS rather than 20kb. I think that's pretty good.

### CODE REVIEW

**Comment by jdlrobson** [comment]
I need to run npm run lint:fix

**Comment by mekarpeles** [comment]
I think it may need to be rebased against master though

**Comment by jdlrobson** [comment]
Will do later today! Which pages should i target next? Im thinking book/editions pages?

**Comment by jdlrobson** [comment]
Rebased.

**Comment by mekarpeles** [comment]
tested, lgtm!

**Pull request merged**
