### PR TITLE
Remove the extra blank under the Author's search

### PR DESCRIPTION
**Pull request by QuangPhung15**
Closes: #10050 

### This PR does these things:

1. Removes the unnecessary blank space on the author search page.
2. Ensures the layout is consistent with the rest of the pages.

### Technical Details

1. Adjusted HTML by removing a div tag to remove excess margins and padding on the author search page.
2. Reused existing layout styles where possible to maintain consistency and reduce redundancy.
3. Verified that the changes do not affect other pages or components.

### Testing

1. Use the automatic testing.
2. Confirm that the blank space is removed and the layout matches the rest of the pages.
3. Cross-check for any visual inconsistencies on related pages.

### Result
https://github.com/user-attachments/assets/8ab9b24f-e36a-4407-97f2-1eff78bc4d9a

### Stakeholders
@RayBB

### CODE REVIEW

**Comment by RayBB** [comment]
@QuangPhung15 thanks for your contribution it looks like you've found a working solution. Nice job!

A few bits of feedback:
First, it looks like the main solution is removing the id `contentMeta` which prevents the related css from being added. Please remove the relevant css from less files now that `contentMeta` isn't use anywhere.

Second, can we try to minimize the code changes?  I think most of the code can be de-dented by one. A smaller diff is easier  for us to review.

Finally, please return the blank find to the end of the file.

**Comment by QuangPhung15** [comment]
Hi @RayBB, thanks for your suggestions.

I changed the indentation to match the original `author.html` file, which makes it easier for you to review the code. I also deleted the unused `contentMeta` CSS in the `legacy.less` file. Please let me know if you have any further concerns.

Thanks!

**Review by RayBB — APPROVED** [review]
@QuangPhung15 tested the code locally and it's working great.
contentMeta isn't used anywhere else so that's safe to remove.

Change looks great to me. Nice job!

Now we just need @cdrini to review and merge.

**Review by cdrini — APPROVED** [review]
Awesome @QuangPhung15 ! And great catch on noticing contentMeta is no longer used @RayBB !

**Pull request merged**
