### PR TITLE
changed max-width of containers from max 960px to 1200px

### LINKED ISSUE #4269: Increase max-width of the containers
This lies some where in between a bug/feature request. The max width(in css) on the desktop for header(header-bar) and body (test-body-mobile) is 960. These days most folks have screen sizes bigger than this. can we bump it to 1280. Thus giving things a much needed breading room.

### PR DESCRIPTION
**Pull request by nitahieb**
Closes #4269

refactor max-width of containers

### Technical

jamesachamp said to test change on small and large screen and it looks good for me. Tested on 16:9 ratio and 5:4.
Included screenshots of original on screen and change.

### Testing

Can see changes from homepage

### Screenshot

lib3
lib4
openlib
openlib2

### Stakeholders

@jamesachamp

### CODE REVIEW

**Comment by mekarpeles** [comment]
Thanks for submitting this contribution @nitahieb, tagging @jamesachamp as a reviewer :)

**Comment by Yashs911** [comment]
@nitahieb I did a quick review and the following changes are required:
1. Increase max-width for footer 
2. Need to adjust the width of the lists. http://staging.openlibrary.org/lists
3. Need to adjust content on http://staging.openlibrary.org/subjects/architecture
4. Need to resize the containers on the books page. http://staging.openlibrary.org/books/OL25352939M/Too_Ghoul_for_School_Attack_of_the_Zombie_Nits
5. Need to adjust `contentHead` max-width on http://staging.openlibrary.org/people/laciedoyle/lists/OL133511L/Reference
image
6. Need to adjust container width for My Reading log (http://staging.openlibrary.org/people/yashs911/books/want-to-read)

**Comment by nitahieb** [comment]
Thank you, I'll work on this now

**Comment by nitahieb** [comment]
@Yashs911 
for 1 I changed max-width to 1200
2. I wasn't able to add lists to active lists to test it out, I created lists they just don't get added(prechange too)
3. I changed width to max-width(it was going off screen on phone without it) and changed it from 898 to 1138, 1200-(960-898)
4. changed  the width from 70% of content area to 75%
5. changed content head from 918 to 1158
6. and I haven't been able to access the reading log  page, the terminal puts out a KeyError: contact_id from openlibrary/core/civicrm.py I can post the logs but I may try to just reset the files.

I'd really appreciate help on 2 and 6 and general feedback

**Comment by cdrini** [comment]
For (4), can you try removing the `float:left`s, and setting `.workDetails` to be `display: flex`? Then move `.workFooter` out of `.workDetails`. Something sort of like:

```css
/* page-book.css | http://staging.openlibrary.org/static/build/page-book.css?v=0b126c04d6828cc4e586489bf39de629 */

@media only screen and (min-width: 960px) {
  div.editionAbout {
    /* float: left; */
    /* width: 70%; */
    flex: 1;
  }
  div.editionCover {
    /* float: left; */
  }
}

#test-body-mobile {
  /* max-width: 1200px; */
  max-width: 1060px;
}

.header-bar {
  /* max-width: 1200px; */
  max-width: 1060px;
}

.workDetails {
  display: flex;
}

.workFooter {
  /* clear: both; */
}
```

Note we'll likely want to tweak the 1200px, so try to avoid having too many magic values based on it (like "75% of content area").

1200px is looking a touch too wide for me right now; can you try it at 1060px? That should also make a lot of the UI problems disappear as well.

**Comment by Yashs911** [comment]
@nitahieb 
For **2.** one way is to make 3-4 lists locally and add around 7-8 books, and after some time, you will be able to see the active lists.
For **6.** Can you share the ss of the error

**Comment by nitahieb** [comment]
@cdrini I'll try that now, thank you! and I'll try to change all the max-values to be based on 1060px, I used 1200px because #4269

**Comment by nitahieb** [comment]
@Yashs911 thank you the lists thing worked

By ss do you mean screenshot?
image
image

**Comment by cdrini** [comment]
@nitahieb Yes exactly :) We might change it again as we play around with it, cause opinions always change once you start using something :)

**Comment by nitahieb** [comment]
I did all the other changes except for 4 and 6, for 2 i changed the list entry width from 280px to 30% of container, I don't know what others think about that. I also thought it would be good to centre the entries.

**Comment by Yashs911** [comment]
@nitahieb Great! I have updated my initial comment and the only thing that needs to be fixed now is [3]. And For [4] I would suggest you follow https://github.com/internetarchive/openlibrary/pull/4926#issuecomment-809811187.
In [3] I think you should also update the `.contentQuarter` width according to the new max-width
From 215px to ~230px
image

**Review by cdrini — APPROVED** [review]
This has been on testing for a while and working well! Merging 🚀

**Comment by cdrini** [comment]
@nitahieb would you be able to open a PR to fix the author's page? That one looks a little lopsided :) https://testing.openlibrary.org/authors/OL24522A/Jonathan_Swift

image

**Pull request merged**
