### PR TITLE
Travis CI: Add more Py3 pytests that already pass

### PR DESCRIPTION
**Pull request by cclauss**
Continue the process started in #3102 by adding more pytests that __must__ pass on Python 3.

Closes #

### CODE REVIEW

**Comment by cdrini** [comment]
Maybe something this? Not tested

```yaml
scripts:
    - xargs "cat scripts/py3-tests.txt | grep -v '^#'" | pytest
```

**Comment by cdrini** [comment]
or maybe `pytest $(grep -v -e '^\s*#' scripts/py3-tests.txt)`

**Comment by tfmorris** [comment]
I don't see any substantive difference between having the module list inline or in a separate file.

Having said that:
* it looks like two tests are failing due to `string.letters`
* it appears this may have been superseded by #3158, so I'm not sure it should be reviewed at all

**Comment by cclauss** [comment]
Rebasing because ascii_strings was fixed in #3152 

#3158 currently requires that `sys.path.insert(0, "openlibrary/vendor")` be added to a bunch of files.

**Pull request merged**
