### PR TITLE
Added "length-zero-no-unit" and fixed offenders.

### LINKED ISSUE #1101: Stylelint: Add "length-zero-no-unit" and fix offenders.
We can shave bytes off our CSS by dropping the usage of unnecessary units.
For example, in the following the "px" unit are unnecessary as zero is zero whatever units you use.
`
.foo { margin: 0px; }
`
[Stylelint ](https://stylelint.io/user-guide/rules/) (which can be run by using `npm install && npm run lint:fix`)  can detect these if configured with the following:
`
		"length-zero-no-unit": true
`

### Checklist
- [x] Update .stylelintrc.json
- [x] fix any offenders detected via `npm run lint:fix`

### PR DESCRIPTION
**Pull request by tabshaikh**
Closes #1101 
<Optional Picture>

## Description:
In this Pull Request we have made the following changes:
Added "length-zero-no-unit" and fixed offenders. Tested and ready for merge

### CODE REVIEW

**Comment by jdlrobson** [comment]
Reviewed. LGTM!

**Comment by mekarpeles** [comment]
changes lgtm but will need to be rebased to rm conflicts

**Comment by cdrini** [comment]
@mekarpeles I think this had an unresolved merge conflict; the diff has `	<<<<<<< HEAD` in it.

**Comment by tabshaikh** [comment]
@cdrini should i open a new pr or how should i proceed

**Comment by cdrini** [comment]
If possible, @mekarpeles should revert the merge, and then it can be fixed here. If not, it will need another PR.

**Pull request merged**
