### PR TITLE
added flake8 check for unused imports

### LINKED ISSUE #3011: Add stricter Travis tests only on a PR's modified files
I am always frustrated when I see pull requests that modify files that contain:
1. ~Python 3 syntax errors~  Fixed in #3030 
2. ~undefined names~
3. unused imports
4. unsorted imports

### Describe the problem that you'd like solved

If a pull request modifies files then we should try to fix as many issues as we can.

### Proposal & Constraints

Add a new Travis CI test run on Python 3.8 that does the following:
1. `git diff origin/master --name-only`  # provides the file paths of only the modified files
2. `flake8 ${modified_files} --select=E9,F63,F7,F82 --show-source --statistics`
3. `isort --check-only ${modified_files}`

These checks are stricter than `make lint` for the modified files to catch Python 3 syntax errors, Python 3 undefined names (long, unicode, xrange, etc.), unused imports, unsorted imports.

### Stakeholders

@hornc @tfmorris @cdrini @mekarpeles

### PR DESCRIPTION
**Pull request by imskr**
Closes #3011

Check for unused imports
### Stakeholders

@cclauss @cdrini

### CODE REVIEW

**Comment by cclauss** [comment]
Let's first land a PR that finds and removes all unused imports across the codebase.  Only after that one lands should we strictly enforce that no new used imports are added.

**Comment by cclauss** [comment]
Caution (especially in the scripts directory) because some imports are done for their side effects even if the linter can not understand why.

**Comment by imskr** [comment]
@cclauss we need `autoflake` to remove automatically unused imports

**Comment by cclauss** [comment]
Bottom line is that __Travis CI__ fails this PR and no one is going to merge a PR that Travis CI fails.

Let's try to start small and build on that success...  My recommendation is that you start a new PR and in that PR fix [only the 12 unused imports](https://travis-ci.org/github/internetarchive/openlibrary/jobs/661396235#L3062-L3073) in `openlibrary/test`.  Once we have gotten that PR through the review process and landed, we can come back to this PR.

**Comment by imskr** [comment]
@cclauss I have created another PR #3182

**Comment by tfmorris** [comment]
Closing this based on the above discussion.

**Pull request closed without merging**
