### PR TITLE
Delete the master.css in upstream folder 

### LINKED ISSUE #1216: master.css seems to be duplicated in upstream folder
master.css is duplicated in upstream folder and doesnt seem of much functionality

### PR DESCRIPTION
**Pull request by tabshaikh**
Closes #1216 
## Description:
In this Pull Request we have made the following changes:
While checking upstream folder we had a master.css so checking if it is still useful or else deleting it.

### CODE REVIEW

**Comment by tabshaikh** [comment]
@jdlrobson There is all.css and master.css in upstream too and first I thought master.css was the main css file which we were trying to reduce. @mek could help

**Comment by jdlrobson** [comment]
I've been meaning to investigate the upstream folder but i dont think that css is being used anywhere..

**Comment by tabshaikh** [comment]
test_delete
Deleting the master.css doesnt break the dev page atleast @mekarpeles maybe it is of no more use

**Comment by jdlrobson** [comment]
LGTM

**Comment by mekarpeles** [comment]
As a matter of policy and process, let's please leave merges to IA staff because unfortunately they are the ones who will have to deal with the devops consequences at 3am if something accidentally goes wrong :)

**Pull request merged**
