### PR TITLE
Index author alternate_names in Solr

### LINKED ISSUE #848: Author search doesn't search alternate_names
This has been mentioned as a contributing factor in #714 and #756, but it's an issue in its own right.

As can be seen by these examples:

```
https://openlibrary.org/search/authors?q=AEschyle
https://openlibrary.org/search/authors?q=alternate_names%3AEschyle
https://openlibrary.org/search/authors.json?q=name%3A%22Aeschylus%22+AND+work_count%3A%5B5+TO+*%5D 
```
The first two examples return no results despite the fact that the alternate name form is listed in the author record and it doesn't contain any special characters. 

The last query not only works, but demonstrates that full SOLR query language support works.

Interestingly though, the returned results don't include `alternate_names` field and the `text` field doesn't include the alternate names, perhaps hinting at an indexing problem which could be the root cause.

### PR DESCRIPTION
**Pull request by tfmorris**
Closes #848

## Description:
In this Pull Request we have made the following changes:
* author records have their alternate_names fields added to the Solr search index

### CODE REVIEW

**Comment by tfmorris** [comment]
I've got a config set up where I can test this now and the fix isn't sufficient. More digging required.

Here's what the update logs look like:

```
2018-03-17 18:25:54 [openlibrary.solr] [INFO] BEGIN update_keys
2018-03-17 18:25:54 [openlibrary.solr] [INFO] POSTing update to http://localhost:8983/solr/update
2018-03-17 18:25:54 [openlibrary.solr.data_provider] [INFO] preload_documents0 [u'/authors/OL18319A']
2018-03-17 18:25:54 [openlibrary.solr.data_provider] [INFO] preload_redirects ['/authors/OL18319A']
0.0 (1): SELECT * FROM thing WHERE key='/type/redirect'
0.0 (1): SELECT * FROM thing WHERE key='/type/redirect'
0.0 (1): SELECT * FROM property
0.0 (1): SELECT * FROM thing WHERE id IN (1, 41, 11, 12, 13, 14, 50, 46, 56, 57, 31)
0.0 (1): SELECT id FROM thing WHERE key='/type/redirect'
0.0 (1): SELECT * FROM property WHERE type=17 AND name='location'
2018-03-17 18:25:54 [openlibrary.solr] [INFO] updating /authors/OL18319A
2018-03-17 18:25:54 [openlibrary.solr] [INFO] urlopen http://localhost:8983/solr/select?wt=json&json.nl=arrarr&q=author_key:OL18319A&sort=edition_count+desc&rows=1&fl=title,subtitle&facet=true&facet.mincount=1&facet.field=subject_facet&facet.field=time_facet&facet.field=person_facet&facet.field=place_facet
2018-03-17 18:25:54 [openlibrary.solr] [INFO] POSTing update to http://localhost:8983/solr/update
2018-03-17 18:25:54 [openlibrary.solr] [INFO] request: '<add><doc><field name="top_subjects">Accessible book</field><fiel...'
2018-03-17 18:25:54 [openlibrary.solr] [INFO] OK
2018-03-17 18:25:54 [openlibrary.solr] [INFO] END update_keys
2018-03-17 18:25:54 [openlibrary.solr-updater] [INFO] updated 1 documents
2018-03-17 18:25:54 [openlibrary.solr-updater] [INFO] saving offset 2018-03-17:8710
2018-03-17 18:25:54 [openlibrary.solr-updater] [INFO] doing solr commit (1 docs updated, last commit was 82.2 seconds ago)
2018-03-17 18:25:54 [openlibrary.solr-updater] [INFO] BEGIN commit
2018-03-17 18:25:54 [openlibrary.solr] [INFO] POSTing update to http://localhost:8983/solr/update
2018-03-17 18:25:54 [openlibrary.solr-updater] [INFO] END commit
```

**Comment by tfmorris** [comment]
The missing piece was having the alternate_names included the default search field for authors.

I also cleaned up the updater logging to make it much less chatty (and remove the print statements) to make it easier to review logs and see what's going on.

I'm going to move on look at cleaning up other parts of the author updating, but this small piece is ready to be reviewed.

Warning to reviewers - the branch has been rebased, so you'll need to force pull if you had a previous copy.

**Comment by mekarpeles** [comment]
lgtm as well, thank you!

**Comment by LeadSongDog** [comment]
Works moved to a different author still show up under the old author. See "Robert Ellis undifferentiated" for  numerous examples.

**Pull request merged**
