### PR TITLE
Dependabot: Add JavaScript dependency checking

### PR DESCRIPTION
**Pull request by cclauss**
Make automated PRs for JavaScript dependencies like we already have for Python.
https://github.com/internetarchive/openlibrary/pulls/app%2Fdependabot-preview

### CODE REVIEW

**Comment by cdrini** [comment]
hould reduce the amount of PRs, and there should be some time between them. The JS dependabot is already enabled (somehow), and its frequency is better; we should try to use the parameters that the JS dependabot is using. (Here are the JS ones https://github.com/internetarchive/openlibrary/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aapp%2Fdependabot+is%3Aclosed+ )

**Comment by cdrini** [comment]
Also, what's the difference between `app/dependabot` and `app/dependabot-preview`? It looks like the latter is the one doing the python PRs.

**Comment by cclauss** [comment]
https://dependabot.com/docs/config-file/ describes the configuration options.  I set Python to __monthly__ (as opposed to __live__ !) to limit the inflow.  Perhaps you can see other options that we should be using.

I think [dependabot-preview](https://github.com/marketplace/dependabot-preview) is what they call it post-acquisition by GitHub.  My sense is that the JavaScript piece _used_ to be configured but is no longer so this PR is attempting to turn it back on.

**Comment by cdrini** [comment]
Ah, ok. It looks it checks monthly, but it only opens 10 at a time. Once any of those are merged, it will _open more PRs_. That's why it felt like it was doing more than monthly. Also likely because our python dependencies are so out-of-date; that's causing the inundation of PRs. The JS should hopefully be quieter.

(Also, bummer that the config doesn't provide an option to limit the number of PRs per e.g. month :/)

**Comment by cdrini** [comment]
Let's give it a shot; if it's too noisy we can just close all the PRs ¯\\_(ツ)\_/¯

**Pull request merged**
