### PR TITLE
Fixed extra white space issue on book preview modals

### LINKED ISSUE #10095: Weird white gap at bottom of preview dialog
### Problem

image

### Reproducing the bug

1. Go to https://openlibrary.org/books/OL4667107M/Die_Angestellten_vor_dem_Nationalsozialismus
2. Click "Preview"

* Expected behavior: The modal should not have a white 
* Actual behavior: It has a white gap

### Context

- Browser (Chrome, Safari, Firefox, etc): FF
- OS (Windows, Mac, etc): Win
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

### PR DESCRIPTION
**Pull request by DachiCharkviani**
Closes #10095 

Worked with @Graissov and @Khiyami on this issue.

Fix/Refactor excess whitespace on book review pop-ups.

### Testing

Go to this page and click preview(or any other book with preview): http://localhost:8080/works/OL16086453W/Pioneers

### Screenshot

Before:
Screenshot 2024-12-11 at 9 02 59 AM

After:
Screenshot 2024-12-11 at 9 02 33 AM

### Stakeholders

@RayBB

### CODE REVIEW

**Comment by DachiCharkviani** [comment]
@RayBB Could you please review this PR. I believe I am done with issue #10095

**Comment by RayBB** [comment]
@DachiCharkviani my local environment to test changes is broken and I'm working on fixing it.
I hope @cdrini can check this out this week.

**Comment by DachiCharkviani** [comment]
Hello, @RayBB  Thank you for your answer. No rush, but if it is processed as soon as possible that will greatly benefit me since I have to show in my college class that I have successful merge in open source code on git for extra credit. Once, again thanks.

@cdrini  Waiting for your approval then! All the best.

**Review by RayBB — CHANGES_REQUESTED** [review]
Please remove all changes not related to the modal.

**Comment by DachiCharkviani** [comment]
@RayBB done!

**Comment by DachiCharkviani** [comment]
@RayBB Could you please respond for the merge? If everything is on point and satisfies the requirements I would like to proceed as soon as possible because deadline for the credit is today night.

**Comment by DachiCharkviani** [comment]
@cdrini @RayBB I believe the merge is ready. Could you please review?

**Review by RayBB — APPROVED** [review]
@DachiCharkviani great work!

I tested this on desktop and on mobile and it works great.
One small change I pushed up is to remove some unused css after you removed the class.
Removing the floater and the iframe-container class were both needed.

Now we just need one of the staff to review/merge it.
Probably @cdrini but I think he might be on vacation now.

**Pull request merged**
