### PR TITLE
Added "function-url-quotes" rule and fixed offenders

### LINKED ISSUE #1102: Stylelint: Add "function-url-quotes" rule and fix offenders
We can shave bytes off our CSS by dropping the usage of unnecessary quotes in URLS

[Stylelint ](https://stylelint.io/user-guide/rules/) (which can be run by using `npm install && npm run lint:fix`)  can detect these if configured with the following:
`
"function-url-quotes": "never",
`

### Checklist
- [x] Update .stylelintrc.json
- [x] fix any offenders detected via `npm run lint:fix`

### PR DESCRIPTION
**Pull request by tabshaikh**
Closes #1102 
<Optional Picture>

## Description:
In this Pull Request we have made the following changes:
added the function-url-quotes linter and manually changed the css which do not satisfies it

### CODE REVIEW

**Comment by tabshaikh** [comment]
@mekarpeles extensive testing of this pr is remaining

**Comment by mekarpeles** [comment]
If so, please update title to `WIP: ` (work in progress) :)

**Comment by tabshaikh** [comment]
@mekarpeles This pr is ready for merging

**Comment by tabshaikh** [comment]
@jdlrobson Thanks for your feedback.

**Comment by mekarpeles** [comment]
Thanks @tabshaikh!

**Pull request merged**
