### PR TITLE
Fix non-deterministic test causing build failures

### PR DESCRIPTION
**Pull request by cdrini**
It was trying to sort 2 equally lengthed strings and choose the first. This is apparently not deterministic in Python 3

### Technical
- Here's a sample failure: https://travis-ci.org/github/internetarchive/openlibrary/jobs/678015713#L602
- This was passing in the PR that introduced the test, but started failing once merged :/

### Testing
If Travis passes, should be good.

### CODE REVIEW

**Comment by cdrini** [comment]
Here's the pertinent code:

https://github.com/internetarchive/openlibrary/blob/bcf95d72bee58d3b6aeb610fbb8ddac8e4901abd/openlibrary/solr/update_work.py#L533-L539

**Comment by cdrini** [comment]
And the failure:

```
______________ Test_build_data.test_ddcs[Handles alternate DDCs] _______________
self = <solr.test_update_work.Test_build_data object at 0x7fc47b9d5c10>
doc_ddcs = ['132.5 153.6'], solr_ddcs = ['132.5', '153.6'], sort_ddc_index = 0
    @pytest.mark.parametrize("doc_ddcs,solr_ddcs,sort_ddc_index",
                                 DDC_TESTS.values(), ids=DDC_TESTS.keys())
                                 def test_ddcs(self, doc_ddcs, solr_ddcs, sort_ddc_index):
            work = make_work()
                update_work.data_provider = FakeDataProvider([
                        work,
                        make_edition(work, dewey_decimal_class=doc_ddcs),
                    ])
                d = build_data(work)
                if solr_ddcs:
                    assert sorted(d.get('ddc')) == solr_ddcs
            >           assert d.get('ddc_sort') == solr_ddcs[sort_ddc_index]
E           AssertionError: assert '153.6' == '132.5'
E             - 132.5
E             + 153.6
openlibrary/tests/solr/test_update_work.py:423: AssertionError
```

**Comment by cdrini** [comment]
Ahhh, ok, was able to repro locally. Apparently sort order of a set is non-deterministic for values of equal key in python 3:

image

**Comment by cdrini** [comment]
Auto merging this to fix the build; got a ~review from @cclauss over slack, but he's unavailable today.

**Comment by tfmorris** [comment]
Your examples don't show what you think they do.

Sort has been stable since Python 2.3. On the other hand, `set`s are unordered in both Python 2 & 3. If you want items kept in insert order, use an `OrderedDict`, rather than something which is unordered by definition like a `set`.

Changing the data instead of fixing the code just masks the problem.

**Comment by cclauss** [comment]
An all dicts are OrderedDicts in Python 3.6+.

**Comment by cdrini** [comment]
To clarify, the thing I'm showing here is that not only is set traversal order arbitrary (that's a given for a set), but in Python 3, it looks like it is _non-deterministic between runs_. This does not appear to be the case in Python 2.

The code itself doesn't depend on the order; they don't need to be in insertion order. But I don't like the fact that it's non-deterministic though. :/ This means that indexing the same record twice could result in different solr records 👎 . So I agree that needs to be fixed.

**Pull request merged**
