### PR TITLE
fixes OL id writeback/sync to IA

### LINKED ISSUE #950: Problem with ImportBot Writebacks OL -> IA
Discovered a somewhat confusing bug in `plugins/importapi/code.py` -> `openlibrary/catalog/add_book`:

*Background:*
We run a process called `Import Bot` (`scripts/manage-imports.py`) whose job is to discover new books within archive.org which are not within openlibrary.org and create a corresponding work + edition record for the book on OL. The final step in the process is to write back the resulting openlibrary work and edition ID of the book back into the source archive.org item's metadata.

It turns out,  `openlibrary/catalog/add_book` `load` was not hitting `update_ia_metadata_for_ol_edition` and this write-back code had to be moved instead to the end of `openlibrary/catalog/add_book` `load_data`

### PR DESCRIPTION
**Pull request by mekarpeles**
Closes #950

## Description:
Fixes OL id writebacks to IA after new books are imported into Open Library from Archive.org

### CODE REVIEW

**Comment by tfmorris** [comment]
There seem to be a few other changes mixed in (e.g. require_marc, removing if False author code, etc). Is that intentional? It'd be clearer if they were in separate commits.

**Comment by mekarpeles** [comment]
@tfmorris as clarification, these weren't feature inclusions so much as things which were broken (params left out, noticing broken code). That said, I also think you are right -- these should be + I can convert these into different commit, that's a good idea.

**Comment by mekarpeles** [comment]
Updated, removing `WIP`

**Comment by bfalling** [comment]
LGTM

**Comment by tfmorris** [comment]
Thanks for splitting our the commits. I think that will improve understandability for future visitors.

**Pull request merged**
