### PR TITLE
Update containers to Python 3.12.2 + Bookworm

### PR DESCRIPTION
**Pull request by scottbarnes**
Update the Docker containers to Debian Bookworm and Python 3.12.

### Technical

This update is tied to a specific `webpy` commit because although the commit has been merged to master, there is not yet a release. Hence using the git hash in `requirements.txt`.

### Testing

Because of the webpy changes, the major Python version changes, and changes to the underlying Debian distribution, it would be good to test out as many tasks as possible.

### Stakeholders

@cdrini

### CODE REVIEW

**Comment by RayBB** [comment]
Excellent! And when this is merged we can close https://github.com/internetarchive/openlibrary/pull/8790 

Then I can do https://github.com/internetarchive/openlibrary/issues/8851

**Comment by cdrini** [comment]
Sweet! This is up on staging.openlibrary.org/status ; will merge / deploy on Monday! 🤞 !

**Comment by scottbarnes** [comment]
> Sweet! This is up on staging.openlibrary.org/status ; will merge / deploy on Monday! 🤞 !

I just looked on staging and things look quite broken. Abort, abort! https://staging.openlibrary.org/works/OL118388W/Flatland?edition=key%3A/books/OL37044775M

**Comment by RayBB** [comment]
@scottbarnes what's wrong with the page? It looks ok to me

**Comment by scottbarnes** [comment]
> @scottbarnes what's wrong with the page? It looks ok to me

Sorry about that, @RayBB. It turns out the error I saw was unrelated to this PR and was fixed by #8859. I forgot to come back here and update this issue.

Unabort! Unabort!

**Comment by cdrini** [comment]
Marking as needs special deploy since will need to monitor some of our prod-only containers to see if they are working correctly.

**Pull request merged**
