### PR TITLE
Remove dependencies from setup.py

### PR DESCRIPTION
**Pull request by cdrini**
Refactor. Dependencies are no longer managed from this file

### Stakeholders
@dhruvmanila @cclauss

### CODE REVIEW

**Comment by cdrini** [comment]
Would you be able to take a look at this one, @dhruvmanila ?

**Comment by dhruvmanila** [comment]
If you don't mind, can you tell me where does `setup.py` is used? I don't think that openlibrary is a pip package nor it is meant to be used like that, unless I've missed something :)

**Comment by cclauss** [comment]
https://github.com/internetarchive/openlibrary/issues/4994#issuecomment-816692717

**Comment by cdrini** [comment]
Added comment :+1: I think we _might_ be able to remove this entire line if we call cython directly in? Specifically it's used in https://github.com/internetarchive/openlibrary/blob/master/scripts/solr_builder/build-cython.sh . I don't think either of those changes should block this PR though; removing the deps from here still provides value, because now they no longer match when I'm trying to search the codebase for packages :D We can always remove the setup.py file later if we find we can.

**Review by cclauss — APPROVED** [review]
LGTM

**Pull request merged**
