### PR TITLE
Edit instructions on merging pull requests

### PR DESCRIPTION
**Pull request by cdrini**
### Description
Feature. Edit contributing to:
1. Limit merge/PR owner access to maintainers
2. Avoid having author=assignee
3. In the case where a special deploy is required, the assignee will label it as `Needs: Deploy Approval`. The assignee must then get confirmation from the deployer before merging in the PR.

(As discussed on slack)

### CODE REVIEW

**Comment by mekarpeles** [comment]
To be discussed during the next community call! ty @cdrini

**Comment by cdrini** [comment]
Results of community discussion:
- pin down definition of "maintainers" (I.e. list)
- discuss about trimming back on the policy (not blocking this pr)

**Comment by mekarpeles** [comment]
Waiting on defining maintainers explicitly + other feedback from community call

**Comment by mekarpeles** [comment]
@cdrini suggests: Let's merge it; I think we can add maintainers later
I'm a :+1:

**Pull request merged**
