### PR TITLE
Replace: Cleanup use of is_usergroup_member('/usergroup/librarians')

### LINKED ISSUE #9087: Cleanup use of `is_usergroup_member('/usergroup/librarians')`
### Describe the problem that you'd like solved

We currently still use: `is_usergroup_member('/usergroup/librarians')` in a few places.
We should probably refactor them to use `is_librarian()` instead like we do in most places.

### Additional context

image

### PR DESCRIPTION
**Pull request by QuantuM410**
Closes #9087 

Replaces the existing ```is_usergroup_member('/usergroup/librarians')``` with ```is_librarian()```

### Testing

- Given below are the affected paths, the testing has been done and all seems to work similarly
- /admin/*
- /search/?q=the&mode=everything (any search path /search/*)
- /authors/merge (test url: http://localhost:8080/authors/merge?key=OL21093A&key=OL161167A&key=OL19677A&key=OL24638A&key=OL114411A&key=OL20585A&key=OL50694A&key=OL47908A&key=OL29586A&key=OL2688089A&key=OL29388A)
- /authors/* (http://localhost:8080/authors/OL22098A/Lewis_Carroll)

### Stakeholders

@RayBB

### CODE REVIEW

**Review by RayBB — APPROVED** [review]
Fantastic! Want to make a separate issue for cleaning up the super librarians version of this? (And if there are others we can probably do them too)

Now need staff sign off

**Comment by QuantuM410** [comment]
> Fantastic! Want to make a separate issue for cleaning up the super librarians version of this? (And if there are others we can probably do them too)
> 
> Now need staff sign off

Sure! I m up for it :)

**Comment by mekarpeles** [comment]
Thank you @RayBB and @QuantuM410 -- staging on testing and then we can merge once it succeeds.

**Comment by RayBB** [comment]
@mekarpeles do you consider it successful now? Not sure if that's why it was removed from testing.

**Comment by RayBB** [comment]
@mekarpeles can this be merged now?

**Pull request merged**
