### PR TITLE
finish migrating to webpack 5

### PR DESCRIPTION
**Pull request by RayBB**
Closes

* [Update dependency webpack to v5 #8066](https://github.com/internetarchive/openlibrary/pull/8066)
* [Update dependency webpack5 to v5.88.2 #8062](https://github.com/internetarchive/openlibrary/pull/8062)
* [Update dependency webpack-cli to v5 #8067](https://github.com/internetarchive/openlibrary/pull/8067)
* [Update dependency workbox-webpack-plugin to v6.6.0 #8063](https://github.com/internetarchive/openlibrary/pull/8063)

Enables #8257

Follows #5245 

### Technical

I followed the guide here: https://webpack.js.org/migrate/5/

We were pretty much already using webpack 5 thanks to #5245 but now we are fully moved over.

Note: I'm pretty sure we have to upgrade vue cli and webpack together because of the dependency.

We did the babel/eslint upgrade in #8312 

### Testing

Well building works and a quick look at the site thing seem fine.

### Stakeholders

@jimchamp @mekarpeles

### CODE REVIEW

**Comment by mekarpeles** [comment]
I heard on our last staff call that maybe this will be blocked by vue 2->3 and may benefit from Tuesday call discussion

**Comment by RayBB** [comment]
@mekarpeles 
`@vue/cli-service` v5 depends on webpack 5 per [this](https://cli.vuejs.org/migrations/migrate-from-v4.html#vue-cli-service). Also v4 of `@vue/cli-service` doesn't work with webpack 5 so they must be upgraded together.

However, as far as I can tell, this has no impact on vue 2 support and the components compile and work fine.

**Comment by jimman2003** [comment]
I concur that vue-cli v5 is compatible with vue 2, at least according to the vue 2.6 to 2.7 migration guide

**Review by cdrini — APPROVED** [review]
I tossed this on testing and it built successfully and library explorer and the author identifier component work swimmingly! Lgtm!

**Pull request merged**
