### PR TITLE
WIP: Code splitting

### PR DESCRIPTION
**Pull request by jdlrobson**
This feels very rewarding. I've moved all the vendor JS into webpack. AS well as making our coder a little more saner to work with, this shrinks the JS by 60kb after gzipping (better minifier) and makes our JS one single request. This should lead to a noticeable performance improvement.

Context for the curious for the commits so far:
* excanvas is for IE8 and below. We don't support this so should remove it (hopefully no-brainer)
* "Drop backwards compatibility functions" is hopefully self explanatory - drops some functions that are no longer used/functional.
* vendor JS moved into webpack - this probably looks very scary - but is simply moving code around. It's best understood by taking a look at static/js/vendor.jsh. I'm simply moving each of these imports into index.js. Previously these files were pulled from vendor/js and are now loaded from npm (if possible) - or pulled from a new file. It may reduce noise, if I keep loading these from the vendor folder, but that would lead to long import paths e.g. `import '../../../../vendor/js/...'` - thoughts on that appreciated.

### CODE REVIEW

**Comment by cdrini** [comment]
Hey! How did you **test** that this doesn't break anything? How did you **test** that the performance improved as opposed to degraded? Can you give a more **technical** summary about what you've done - Why are there 8000 new lines? Why are there so many "unknown.js" files? It looks like we're storing full copies of other libraries in our repo; why is that?

We can avoid this whole discussion if you'd followed the PR template!

**Comment by cdrini** [comment]
Ohhhh, ok, this is still WIP; that makes more sense. The contributing docs don't explicitly say you need to follow the template for WIP PRs, but I think they should. Because all my questions still apply :P

**Comment by cdrini** [comment]
Now that #2313 is out, can this be closed, or is there something else we should take a look at?

**Comment by jdlrobson** [comment]
Sneak preview of additional patches I'm currently working on in this chain: 1dbf422 and 0126807

**Comment by jdlrobson** [comment]
No longer needing this.
See #2423 and #2360

**Pull request closed without merging**
