### PR TITLE
Remove minicron from codebase

### PR DESCRIPTION
**Pull request by jimman2003**
refactor

### Technical

No usages outside of that script.
Maybe was used instead of cron at some point
### Testing

Everythinng works :)
### Stakeholders

@cdrini

### CODE REVIEW

**Comment by cclauss** [comment]
Is [`openlibrary/core/minicron.py`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/minicron.py) still being used or can it be deleted as well?

**Comment by jimman2003** [comment]
Let me recheck..

**Comment by jimman2003** [comment]
Grep returned no other results for minicron so,  it is unused as well

**Review by cdrini — APPROVED** [review]
Nice! Another one bites the dust :) Confirmed no usages in olsystem either.

**Pull request merged**
