### PR TITLE
Language code updates

### PR DESCRIPTION
**Pull request by hornc**
source:
https://www.loc.gov/marc/languages/language_appendix.pdf

Relates to internetarchive/openlibrary-librarians#80 and a number of other language related comments and issues that are still open.
Relates to internetarchive/openlibrary#8127 , especially the list 1–4

### Technical

@cdrini , commiting this might not be sufficient to update the code pages , e.g. https://openlibrary.org/languages/him 
Do you have a process to update these pages automatically?

### Stakeholders

@tfmorris 
@cdrini

### CODE REVIEW

**Comment by hornc** [comment]
@cdrini I'm not sure how useful this PR is going to be, maybe this needs some discussion before going further.

Is there a definitive `type/language` schema? I see https://openlibrary.org/type/language lists `translated_names[]`, but https://openlibrary.org/languages/eng.json uses `name_translated`.

From looking at the LOC codes I was wondering if we needed a way to group languages under a macrolanguage, or to mark some codes as deprecated, with links to the preferred code, e.g. scc -> srp

 There might be a small risk of over-engineering, but I don't think there is a problem for OL to recognize more codes than LOC by using ISO 639-3 codes, but I'd want to mark out what scheme they belonged to (many will be in both/multiple?). 

I imagine most automated imports won't use ISO 693-3 codes, and the correct code will be added manually to the OL record, which will leave the associated MARC record unmodified with perhaps a less-specific code.

This is an area I could work on further, if there is appetite for it.

**Comment by mekarpeles** [comment]
Changes look good but need to be on yml -- maybe that means we actually remove this file? But then how is it documented and how does anyone know about it?

**Comment by cdrini** [comment]
Nice! Yes unfortunately these files are legacy files that aren't synced with production in any way 😬 .

You'll have to make your edits programmatically via the open library client to the records, or by fetching/saving through other means. Or you can directly edit the languages on prod via .yml , eg https://openlibrary.org/languages/him.yml?m=edit

The schema for these as you deduce isn't great! Use what's defined on `/languages/eng.json` ; that has the most up-to-date/supported schema.

To get the translated names/identifiers/etc for the new languages you've added, you can use/update my colab here: https://colab.research.google.com/drive/1HWG92jo6wM43_iA2dINjnkj4hX5Y6kt5 . That should be idempotent IIRC, so you should be able to run it on everything and it will import what it can.

**Comment by hornc** [comment]
@cdrini I haven't added these to production yet. Merge this, and perhaps create just one issue referring back to this PR. I think it's good to have a checked in list of known good lang codes.

I was thinking of scripting something to check whether a language was present on production, and add it if not, if you didn't already have a tool like that.

**Comment by cdrini** [comment]
Sounds good! Merged. No alas no script like that; my wikidata script above will work only after they've already been created in production.

**Comment by cdrini** [comment]
Voila the issue: #9447

**Pull request merged**
