### PR TITLE
fix commiting from Gitpod

### LINKED ISSUE #6918: Cannot commit in gitpod: "No module named pre_commit"
Add pre_commit to the gitpod environment

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders
@cclauss @bicolino34

### PR DESCRIPTION
**Pull request by RayBB**
Closes #6918

Fixes committing via Gitpod.

### pyenv version

Before: `pyenv install`

After:
```
pyenv install 3.11 --skip-existing
pyenv global 3.11
```

We were running the install command without specifying the version. I assume at one point we had a `.python-version` file it was reading but we removed it. Setting this here now is a bit clearer. 

It is a small bit of work to keep this file in sync with pre-commit yaml but simpler than trying to parse it.
I didn't look now, but some months ago when I looked there was no straightforward way to sync a precommit config file and the `.python-version` file without bash scripts editing files. 
If someone knows otherwise please let me know.

This is the recommended way to set a python version in Gitpod https://www.gitpod.io/docs/introduction/languages/python#python-versions

### installing pre-commit
Before: `pip install pre-commit`

After: `sudo python3 -m pip install pre-commit`

Why? I'm not totally sure, I don't understand Python environments that well. But if we don't have it we'll get the error: `No module named pre_commit`

The way I found the solution to this was by copying the install method from Gitpod itself:
https://github.com/gitpod-io/gitpod/blob/f98e5a2aa1fcae3bdb5e146dc628ad73631d8b5c/dev/image/Dockerfile#L207

### Cosmetic changes

There is now a new task called `dev shell` that opens split to the right side.

Why?
1. The whole reason this was a confusing error to debug was because it was running in the background in the same shell as the docker up command. That made it much more confusing.
2. It makes the shell script to setup Gitpod much simpler.
3. If someone is going to be making changes they'll almost certainly open the terminal anyway.

PS: Sorry I don't know why the python tests are failing in CI and can't see the logs.

### Testing

Open this PR in gitpod here: https://gitpod.io/?editor=code#https://github.com/internetarchive/openlibrary/pull/7468

### Screenshot

https://user-images.githubusercontent.com/921217/215235580-5224cac8-9d8e-47cc-b1a6-77f0b05dd320.mp4

### Stakeholders

@cdrini  @cclauss

### CODE REVIEW

**Comment by cclauss** [comment]
Instead of `sudo python3 -m pip install pre-commit`, please try `python3 -m pip install --user pre-commit` and if that does not work, please revert back to your `sudo` solution.

https://snarky.ca/why-you-should-use-python-m-pip/

**Comment by RayBB** [comment]
@cclauss I tried doing it without sudo and it didn't work. That's why I reverted to sudo in commit [1390359](https://github.com/internetarchive/openlibrary/pull/7468/commits/13903595fdc00b6d6b028b3a9ca84dafdd96b312)

I have a guess that this may be due to some funny business that gitpod does with env stuff but can't say for sure.

PS: this is the way that gitpod installs pre-commit in their official repo.

To confirm that it doesn't work without sudo, on the lastest commit to this branch I ran:
`sudo python3 -m pip uninstall pre-commit`
`python3 -m pip install pre-commit`
`git commit`
And got `/usr/bin/python3: No module named pre_commit`

**Review by cclauss — APPROVED** [review]
Unrelated issues were causing our GitHub Actions to fail, but they have been fixed so we are clean and green!  Perhaps as a ___seperate___ effort, we should consider adding [a `.python_version` file](https://github.com/pyenv/pyenv#understanding-python-version-selection) to the repo because I believe both the official Docker images for Python and pyenv will use that version.  Perhaps even __pre-commit__ is nimble enough to use it as well.

Thank you for doing this -- looks great.

**Comment by mekarpeles** [comment]
@cclauss LGTM, please squash before merge! Ty @RayBB

**Pull request merged**
