### PR TITLE
Add book tags submission indicator

### LINKED ISSUE #5646: Submission feedback missing from Book Tags modal
When a book tag is selected or removed, a message is sent to the server and the change is persisted.  Although this is happening, it is not clear to patrons that their selections are being saved.

Previous iterations of the Book Tags modal displayed toast messages on submission success or failure.  This should still be happening today, but is not.

### Steps to Reproduce

1. While logged in, go to a book page.
2. Open the book tags modal and select some tags.

* Actual: No indication of submission is given.
* Expected: Some visual feedback telling me that selections have been saved.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** N/A
- **Operating system?** N/A
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Display toast messages on submission success or failure.  Remove tag from selected collection if its submission somehow fails.

### PR DESCRIPTION
**Pull request by jimchamp**
Closes #5646

Adds the submission indicator from #4948 to the book tags Vue component.

### Technical

Adds a new Vue component representing a submission status indicator.  A spinner is displayed when a tag is POSTed to the server.  A success or failure message is displayed when the response has been received.

State is managed by an object imported from `ObservationService.js` (I'm not thrilled about this, but it saves a bunch of difficult to follow messaging between components).  The object's state is changed by the `updateObservation` function, which is used to POST observations to the server.

### Screenshot

loading_indicator

### CODE REVIEW

**Comment by RayBB** [comment]
Functionally, I think this serves the purpose of what I was hoping for.
Personally I think it would be better to put the status at the bottom rather than the middleish of modal. Something like [this](https://www.learnrxjs.io/learn-rxjs/recipes/save-indicator).

Additionally, again my own design preference, I think it is information overload to show a spinning loading indicator after every single change. It is a little distracting and for some maybe anxiety producing. [Others](https://uxdesign.cc/stop-using-a-loading-spinner-theres-something-better-d186194f771e) also have done away with loading indicators.

I think we could simplify by not revealing the state of saving. Just have the states of saved or failed. Perhaps a nice indicator of a new save would be to make a checkmark bounce or redraw or something. I'll think on it more.

@jimchamp

**Comment by jimchamp** [comment]
This is great feedback!  Having only success and failure states removes the need for an object to track state.  I also like the idea of using animations to indicate state.

**Comment by RayBB** [comment]
One more thing I forgot to mention in that message is accessibility.
I tried to search briefly but didn't see a whole lot about how do we make this easy for people to understand that are using screen readers? I think putting it at the bottom can help but I don't know if there's something else to do there

**Comment by jimchamp** [comment]
I have removed the spinner and added a message explaining that the tags in the first section have been saved.

tag-saved-message

**Comment by mekarpeles** [comment]
Revisiting this for accessibility may be a good one for your Menu for volunteers @jimchamp

**Pull request merged**
