### PR TITLE
Fixes bookshelves empty on chrome issue

### LINKED ISSUE #4362: Bookshelves appear empty on Chrome
Bookshelves appear empty until scrolling happens.

### Relevant url?
https://openlibrary.org/explore

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### PR DESCRIPTION
**Pull request by nynaalekhya**
Closes #4362 

Fixes bookshelves empty on chrome issue
### Stakeholders

@cdrini

### CODE REVIEW

**Comment by nynaalekhya** [comment]
@cdrini  Please review this PR.

**Comment by mekarpeles** [comment]
@nynaalekhya thank you for submitting this!! @cdrini and I will check this first thing next week. I'm pulling it to staging now.

**Comment by nynaalekhya** [comment]
@mekarpeles Is there anything that I need to fix in this issue?

**Comment by mekarpeles** [comment]
I think this may have been supplanted by a fix which @cdini introduced so I am going to hand this PR to him to review and either close or merge as appropriate. Thank you both!

**Comment by cdrini** [comment]
Yep! That's exactly correct. The issue was related to the fact that when embedded in openlibrary on production, the intersection observer fires in a weird way :/  See https://github.com/internetarchive/openlibrary/pull/4609/commits/6bdead942ab7127ef8ad45086db7224439b49e2d

**Pull request closed without merging**
