### PR TITLE
changed covers to use class instead of id

### LINKED ISSUE #9473: "Add Author Photo" broken on Author page
### Problem

The link to "Add Author Photo" is broken on the Author page.

#### Evidence / Screenshot
image

### Reproducing the bug

1. Go to an author page, e.g. http://localhost:8080/authors/OL20585A/Edwin_Abbott_Abbott
2. Do click on the "Add Author Photo" link by mousing over the author photo box in the upper right.

* Expected behavior: it's possible to upload an image.
* Actual behavior: it's not possible to upload an image.

### Context

_No response_

#### Related files

It looks as a change in 17538fd7255a16ef0a7e9ff69095619fb18cfd55 may be causing this.

#### Stakeholders

<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

### PR DESCRIPTION
**Pull request by deysandip301**
Closes #9473 

### Technical

changed id based rendering to class based rendering in the covers.

### Screenshot

image

### CODE REVIEW

**Comment by scottbarnes** [comment]
@deysandip301, thank you very much for this. I tested it out and it seems to work perfectly on mobile and desktop, and both for cover and author photo uploads.

I pushed another commit to this branch to address an issue _not_ caused by you that I noticed while reviewing your excellent PR. You can see the and specific changes here: 550dac625975f5c17c4c1b1c0544df16fc40f580.

@cdrini, while reviewing @deysandip301's contribution, I noticed that 17538fd7255a16ef0a7e9ff69095619fb18cfd55 caused HTML `id` values to repeat on a single page, which is ultimately what broke author image uploads. @deysandip301 fixed it, but the underlying problem still remained. I attempted to address this in 550dac625975f5c17c4c1b1c0544df16fc40f580 by passing through an optional value to the cover/author image upload templates so that the `id` value wouldn't be repeated.

I wanted to check this with you though for two reasons: (1) I am curious whether this added complexity matters just to make valid HTML, and (2) do we want to support cover uploads on mobile devices? If we do, we may wish to create another issue to display more information to mobile users so they know they can upload images.

**Comment by cdrini** [comment]
Repeated IDs are a problem mainly cause they're usually a sign of bad code/abstractions! This approach seems good for now. Long term, we might need to decouple these pieces; the covers modal and the covers link. That way we can only render the modal once in this case, since they're identical.

**Review by scottbarnes — APPROVED** [review]
This is great, @deysandip301. Thanks for all your work on it.

Also, I'm sorry for the delay in fully reviewing this. When I looked at it last week I noticed there was an issue whereby clicking "cancel" on the "Manage" tab doesn't close the modal, but then I realized it's present on the cover upload/manage page too, so I am considering it out of scope for this issue.

**Comment by deysandip301** [comment]
Hey @scottbarnes thanks for helping me throughout the process and help me learn the things 
looking forward to contribute more... :)

**Pull request merged**
