### PR TITLE
Added:analytics to all book carousels.

### LINKED ISSUE #7301: Add analytics to all book carousels
Currently most carousels don't have analytics. So if we make changes to eg "more like this", we won't see if the change has results in more clicks. Let's add analytics to all books carousels by default, of the shape:

`BookCarousel|{Forward,Backward,CoverClick,CTAClick}` .

For special carousels, like the "MoreLikeThis" carousel, let's give them special names, eg `BooksLikeThisCarousel|{Forward,Backward,CoverClick,CTAClick}`.

The special carousels should be:

- `BooksLikeThis`

That's probably the only one we want to track separately, because we will make changes to that algorithm, and will want to analyze whether the changes resulted in more useful results.

### Stakeholders
@jimchamp

### PR DESCRIPTION
**Pull request by xonx4l**
issue-:#7301

Closes #7301

<!-- What does this PR achieve?
Feature.

### Technical
Adds analytics to all book carousels.

### CODE REVIEW

**Review by cdrini — CHANGES_REQUESTED** [review]
Hi @xonx4l . 

The way the analytics work is by adding an html attribute, `data-ol-link-track` to various elements on the page. Calling `printf` won't achieve this. You will need to add these attributes to various parts of this form, eg `data-ol-link-track="BookCarousel|CTAClick"`.

And again, please follow the template.

**Comment by xonx4l** [comment]
@cdrini can you provide a feedback ?

**Review by cdrini — CHANGES_REQUESTED** [review]
Please follow the PR template and provide details about how you have tested this code. We will not be able to review your pull request unless we can confirm that the changes have been tested.

**Comment by xonx4l** [comment]
hi @cdrini I would like to get some insights in the internet archive GSoC program can i get a slack/discord link to talk . Thanks.

**Comment by cdrini** [comment]
We have GSoC data here: https://github.com/internetarchive/openlibrary/wiki/Google-Summer-of-Code

**Comment by cdrini** [comment]
Closing in favour of #8781 ; the solution is a little bit more complicated!

**Pull request closed without merging**
