### PR TITLE
Use requests in catalog/add_book/__init__.py

### PR DESCRIPTION
**Pull request by cclauss**
Related to #4033  We are having trouble with Unicode URLs and this is made worse on POST requests.  Instead of manual fixes using urllib, let's adopt the Python requests library which properly manages much of this error-prone gorp.

### Testing

On Python 3 create a new book http://staging.openlibrary.org/books/add with Unicode in the title:
* "âêîôû"
* "Chris Clauß: Life in Lüsai, Graubünden"

### Stakeholders

@aasifkhan7

### CODE REVIEW

**Comment by cclauss** [comment]
:-(  Still raises...
```
0.17 (1): 200 POST /openlibrary.org/save_many {'query': '[{"title": "Chris Clau\\u00df: Life in L\\u00fcsai, Graub\\u00fcnden", "authors": [{"author": {"key": ""}}], "key": "/works/OL1W", "type": {"key": "/type/work"}}, {"works": [{"key": "/works/OL1W"}], "title": "Chris Clau\\u00df: Life in L\\u00fcsai, Graub\\u00fcnden", "publishers": ["\\u00e2\\u00ea\\u00ee\\u00f4\\u00fb"], "publish_date": "2021", "key": "/books/OL5M", "type": {"key": "/type/edition"}}]', 'comment': 'Added new book.', 'action': 'add-book', 'data': '{}'}
[2020-11-08 07:23:20 +0000] [216] [ERROR] Error handling request /books/OL5M/Chris_Clau%DF_Life_in_L%FCsai_Graub%FCnden/edit?mode=add-work
Traceback (most recent call last):
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/httpserver.py", line 271, in __call__
    return self.app(environ, start_response)
  File "/openlibrary/openlibrary/core/middleware.py", line 42, in __call__
    data = self.app(environ, new_start_response)
  File "scripts/openlibrary-server", line 118, in wrapper
    return app(environ, start_response)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 313, in wsgi
    self.load(env)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 457, in load
    ctx.path = env.get("PATH_INFO").encode("latin1").decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 22: invalid continuation byte
```

**Comment by cclauss** [comment]
Even with #4049 installed...
```
0.16 (1): 200 POST /openlibrary.org/save_many {'query': '[{"title": "Chris Clau\\u00df: Life in L\\u00fcsai, Graub\\u00fcnden", "authors": [{"author": {"key": ""}}], "key": "/works/OL1W", "type": {"key": "/type/work"}}, {"works": [{"key": "/works/OL1W"}], "title": "Chris Clau\\u00df: Life in L\\u00fcsai, Graub\\u00fcnden", "publishers": ["\\u00e2\\u00ea\\u00ee\\u00f4\\u00fb"], "publish_date": "2021", "key": "/books/OL5M", "type": {"key": "/type/edition"}}]', 'comment': 'Added new book.', 'action': 'add-book', 'data': '{}'}
[2020-11-08 08:16:46 +0000] [212] [ERROR] Error handling request /books/OL5M/Chris_Clau%DF_Life_in_L%FCsai_Graub%FCnden/edit?mode=add-work
Traceback (most recent call last):
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/httpserver.py", line 271, in __call__
    return self.app(environ, start_response)
  File "/openlibrary/openlibrary/core/middleware.py", line 42, in __call__
    data = self.app(environ, new_start_response)
  File "scripts/openlibrary-server", line 118, in wrapper
    return app(environ, start_response)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 313, in wsgi
    self.load(env)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 457, in load
    ctx.path = env.get("PATH_INFO").encode("latin1").decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 22: invalid continuation byte
```

**Comment by tfmorris** [comment]
`requests` is definitely the way to go. It baffles me that the OpenLibrary staff continues to ignore the easiest and most correct solution. Having said that, this code, `encode("latin1").decode("utf8")`, is **always** going to error for non-ASCII characters, because there are encodings in ISO Latin-1 (ie ISO 8859-1) which aren't legal UTF-8.:

```
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 457, in load
    ctx.path = env.get("PATH_INFO").encode("latin1").decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 22: invalid continuation byte
```

Note that the "slug" is completely unnecessary, so if you used "/books/OL5M" for your URL, you wouldn't have to worry about any of this.

If the OpenLibrary staff is going to continue to refuse to use `requests`, the solution is to use the correct encoding/decoding functions:

>>> import urllib.parse
>>> urllib.parse.quote('Chris Clauß: Life in Lüsai, Graubünden'.replace(' ','_'))
'Chris_Clau%C3%9F%3A_Life_in_L%C3%BCsai%2C_Graub%C3%BCnden'

URL encoding is a subset of ASCII, as I mentioned before, so recovering the string reverses the transform and uses `urllib.parse.unquote(url_bytes.decode('ascii'))`

**Comment by cclauss** [comment]
This works with web.py 0.62 if #4049 is NOT applied.

**Comment by cclauss** [comment]
Closing in favor of #4057 which solves this issue in web.py v0.62.

**Pull request closed without merging**
