### PR TITLE
Update test_olmarkdown.py

### PR DESCRIPTION
**Pull request by jack17529**
changed http to https 
solves : #324

### CODE REVIEW

**Comment by mekarpeles** [comment]
See: https://travis-ci.org/internetarchive/openlibrary/builds/214360046
It looks like the test cases need to be updated to match the assertion:

E       assert '' == '<p><a href="https://openlib...//openlibrary.org</a>\n</p>'
E         + <p><a href="https://openlibrary.org" rel="nofollow">https://openlibrary.org</a>
E         + </p>

**Comment by LeadSongDog** [comment]
@jack17529 Thank you for addressing this, but the statement "solves : #324" is a bit optimistic. It addresses one specific case in which http was still being used, but there are many others that still need to be fixed.

**Comment by jack17529** [comment]
@LeadSongDog  I will work on it. No problem

**Comment by mekarpeles** [comment]
pinging on this issue; any updates @jack17529?

**Comment by jack17529** [comment]
@mekarpeles , got time today so I will work on it.

**Comment by jack17529** [comment]
@mekarpeles can you please help me in erasing this error in travis, I don't know how to solve it.

**Comment by hornc** [comment]
I'm not quite sure why this is failing, but it looks like `md("https://openlibrary.org")` is returning an empty string, instead of the expected formatted link.

The file you are editing is a test of the class here: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/olmarkdown.py

Since nothing looked wrong with the code in that class, I had a quick look to see if there could be a problem with `infogami.utils.markdown`, and found this bug report: https://bugs.launchpad.net/infogami/+bug/193622

The modified `AUTOLINK_RE` looks like it should handle https though. Is it that the test is not correctly importing the modified `AUTOLINK_RE`?

**Comment by hornc** [comment]
Seems like https://github.com/internetarchive/openlibrary/issues/457 is related

**Comment by hornc** [comment]
Seems like there is a real issue where the markdown parser cannot handle https, this was raised 4 days ago: https://github.com/internetarchive/openlibrary/issues/457.  This test update is good and shows the markdown failure. Test Driven Development in action!
Write a failing test, now fix olmarkdown.py so that it passes. 

The patches to the markdown parsers in that file, which look like they should handle https, must not be taking effect?

**Comment by mekarpeles** [comment]
Great catch @hornc on #462, thanks for getting us kicked off on this @jack17529

**Pull request merged**
