### PR TITLE
Discard catalog edition number

### LINKED ISSUE #4314: DDC normalizer should ignore dewey decimal catalogue edition number
A lot of books specify the version of the dewey decimal catalogue as part of the dewey decimal:

- `338.9/009171/7 19` https://openlibrary.org/works/OL15597238W/The_economics_of_feasible_socialism
- `332.6 21` https://openlibrary.org/books/OL7454161M/The_Random_Walk_Guide_To_Investing
- `[E] 21` https://openlibrary.org/works/OL14933747W/Geisterstunde_im_Kindergarten

The current ddc indexer treats these as 2 ddcs (e.g. `['332.6', '021']`), causing the 0* section to be polluted with entirely unrelated books.

At another time we should consider what exactly we want to do with the ddc edition, but for now we need to remove during normalization so that these sections are correct.

### Proposal & Constraints

- [ ] Add a clause at the end of `normalize_ddc` that removes 0* numbers if they (1) have no decimal component, and (2) are not the only number in the ddc
- [ ] Add tests for the examples above (and find some more)

### Related files

- https://github.com/internetarchive/openlibrary/blob/master/openlibrary/utils/ddc.py
- https://github.com/internetarchive/openlibrary/blob/master/openlibrary/utils/tests/test_ddc.py

### PR DESCRIPTION
**Pull request by lephemere**
Closes #4314

Discard catalog edition number from DDC number in `normalize_ddc` function.

### Stakeholders

@cdrini

### CODE REVIEW

**Comment by lephemere** [comment]
@cdrini According to [OCLC Support on DDC](https://www.oclc.org/bibformats/en/0xx/082.html) the following case is possible:

`[016.3584] 012` => `012 ǂa [016.3584]`, where `012` is a Dewey number and the bracketed `016.3584` is an alternative Dewey number.

Should we remove 0* numbers only if they are not the only non-bracketed numbers instead? Are they other cases where an extra 0* number would not necessarily be an edition number?

**Review by cdrini — CHANGES_REQUESTED** [review]
Awesome, thank you @lephemere ! Can you add some tests for these here: https://github.com/internetarchive/openlibrary/blob/51ccd171f0502723cf0ca5ca7b9b56d9fe8b5361/openlibrary/utils/tests/test_ddc.py#L41-L46

The format is input string, output dewey decimals, description of test.

**Comment by cdrini** [comment]
I think your solution is good as is; because we usually have multiple dewey decimals per edition, and multiple editions per work, we usually have alternative dewey decimals covered, even if there are some records with that syntax, I imagine it won't cause any issues.

**Comment by lephemere** [comment]
@cdrini, I've added some tests in the `TESTS` array and updated the `Dewey numbers in brackets.` test in the `TESTS_FROM_OCLC` array.

And also for information, as I don't think it's linked to my PR, I've one failed test when running Pytests:

> E       AssertionError: assert '' == '\<Nothing>'
> E         - \<Nothing>
>
> openlibrary/plugins/upstream/tests/test_models.py:65: AssertionError

**Review by cdrini — APPROVED** [review]
Looks good! Yeah, that failure was from an old master and is fixed now. Note these changes will take place with the next full reindex :+1:

**Pull request merged**
