### PR TITLE
UpdateRequest.toxml() should return str, not bytes (alt)

### PR DESCRIPTION
**Pull request by cclauss**
Alternative to #3075

Closes ~6 failing pytest on Python 3.

### CODE REVIEW

**Comment by cdrini** [comment]
Actually, I'll merge now so that you're unblocked tomorrow :+1:

**Comment by cclauss** [comment]
$ `python2`
```
>>> import lxml
>>> lxml.__version__
'4.5.0'
>>> from lxml.etree import tostring, Element
>>> a = Element("a")
>>> for enc in ("unicode", "utf-8", "utf8"):
...     enc, type(tostring(a, encoding=enc)), tostring(a, encoding=enc) == tostring(a).decode('utf-8')
...
('unicode', <type 'unicode'>, True)
('utf-8', <type 'str'>, True)
('utf8', <type 'str'>, True)
```
$ `python3`
```
>>> import lxml
>>> lxml.__version__
'4.5.0'
>>> from lxml.etree import tostring, Element
>>> a = Element("a")
>>> for enc in ("unicode", "utf-8", "utf8"):
...     enc, type(tostring(a, encoding=enc)), tostring(a, encoding=enc) == tostring(a).decode('utf-8')
...
('unicode', <class 'str'>, True)
('utf-8', <class 'bytes'>, False)
('utf8', <class 'bytes'>, False)
```

**Comment by cclauss** [comment]
$ `diff before_sorted.txt after_sorted.txt`
```
< ===== 97 failed, 399 passed, 23 skipped, 10 xfailed, 34 warnings in 6.79s ======
< FAILED openlibrary/tests/solr/test_update_work.py::TestUpdateWork::test_delete_editions
< FAILED openlibrary/tests/solr/test_update_work.py::TestUpdateWork::test_delete_work
< FAILED openlibrary/tests/solr/test_update_work.py::TestUpdateWork::test_redirects
< FAILED openlibrary/tests/solr/test_update_work.py::Test_build_data::test_with_one_inlibrary_edition
< FAILED openlibrary/tests/solr/test_update_work.py::Test_update_items::test_delete_author
< FAILED openlibrary/tests/solr/test_update_work.py::Test_update_items::test_delete_requests
< FAILED openlibrary/tests/solr/test_update_work.py::Test_update_items::test_redirect_author
< FAILED openlibrary/tests/solr/test_update_work.py::Test_update_items::test_update_author
---
> ===== 92 failed, 404 passed, 23 skipped, 10 xfailed, 34 warnings in 6.71s ======
> FAILED openlibrary/tests/solr/test_update_work.py::Test_build_data::test_isbns
> FAILED openlibrary/tests/solr/test_update_work.py::Test_build_data::test_with_multiple_editions
> FAILED openlibrary/tests/solr/test_update_work.py::Test_build_data::test_with_two_lending_editions
```

**Comment by cdrini** [comment]
Ahhh, i meant to merge this yesterday :( my bad.

**Comment by cdrini** [comment]
Thank you for the explanation! That was actually really helpful, and helped fill in a few holes in my python knowledge :)

**Pull request merged**
