### PR TITLE
Remove unused plugins: copyright, heartbeat, scod, theme, and mobile

### PR DESCRIPTION
**Pull request by jdlrobson**
### Description
Deletes dead code.

At an old job we had a backup box that backed up a website for a client. It was a noisy box, so we made the backups during the night. We would turn that box on as we left the office and turn it off when we first went in. I wouldn't be surprised if that box was still being turned on all these years later despite the client being long gone. It was that kind of company.

### Testing
Start openlibrary. Confirm it hasn't exploded/world hasn't ended etc..

### CODE REVIEW

**Comment by mekarpeles** [comment]
I think all of these should be safe to move, i'll pull on dev Monday to confirm

**Comment by hornc** [comment]
Wow, I have never noticed any of this code. The copyright stuff seems potentially interesting, but I don't know how it was ever used by OL. It's probably safe to delete, but I think I'll look back at some of it just for my own interest at some point, to see if any of it might have value elsewhere.

**Comment by mekarpeles** [comment]
@hornc I think I'm ready to merge this, unless a la your last comment you'd like to own it as the assignee?

**Comment by mekarpeles** [comment]
got the green light from @hornc, merging

**Pull request merged**
