### PR TITLE
optimized SVG files

### PR DESCRIPTION
**Pull request by jonbos**
### Technical
SVG files optimized by svgo via the `svg-min` script in package.json. Please see [related comment](https://github.com/internetarchive/openlibrary/pull/4880#issuecomment-807664002) on PR #4880 

### Stakeholders
@jdlrobson

### CODE REVIEW

**Comment by jdlrobson** [comment]
very strange, when I pull down this code, and run `npm run svg-min` the file output for static/images/openlibrary-icon.svg is different. Can you run `npm install` and `git rebase origin/master` and check if this is just me?

The only difference I'm seeing is with this line (you
```
-        <g id="g14" transform="matrix(1.15576 0 0 1.15576 408.982 -121.656)" style="stroke-width: 1.08972156;">
+        <g id="g14" transform="translate(408.982 -121.656) scale(1.15576)" style="stroke-width: 1.08972156;">
```

**Review by jdlrobson — APPROVED** [review]
LGTM but  I want to understand why we are getting different output SVGs.. could be a problem with one of our dependencies not being pinned

**Comment by jonbos** [comment]
@jdlrobson I don't think I'm experiencing what you're describing (provided I understand -and I may not!)

Here is my process:

on my fork of the repo:
```
$ git reset --hard && git clean -dffx 
$ git checkout master
$ git pull upstream
$ git rebase upstream/master
$ npm i
$ npm run svg-min
```
 comparing open-library-icon.svg with the version on the svg-optimize branch...
image

**Comment by jdlrobson** [comment]
not a big deal

**Pull request merged**
