### PR TITLE
Solr 8! Up and running 🚀

### LINKED ISSUE #3317: Update to Solr 8 (Latest)
With the reindex flow largely complete (#1843), we can start looking at the next step, which is updating solr to the latest version. This is largely implemented in #2246 , but needs the last push to get it to production and to be up-to-date with #1843. This will allow:

- Near Real Time updating! New solr lets edits appear in virtually real time, since softCommits allow for data to become searchable significantly faster. Blocking #789 .
- Better built-in non-English character support! ~Blocking #714 , #178
- Partial document updates! We'd be able to update parts of a record without doing a full re-index of the document. Although out of scope of this issue, this would allow us long term to make solr-updater _siginficiantly_ faster. It also unblocks keeping counters like sponsorship status, or reading-log stats in solr. Blocking #3249 .

### Plan
- [x] Get Solr 8 working on local environment
    - [x] `make reindex-solr` works
    - [x] Searching via the UI works
    - [x] PR with cross-solr changes: #4283 
    - [x] Draft PR with solr 8 additions (Subset of @tfmorris ' #2246 )
        - Maybe a non-draft PR with a flag that lets people try using solr 8?
- [x] Try a full reindex with solr 8
    - [x] Switch solr_builder to use solr8
    - [x] Index works
    - [x] Index authors
    - [x] Switching staging to point to newly indexed solr, see what works/doesn't work
    - [x] Index orphans
    - [x] Index subjects: How will we import subjects? 😬 They're currently locked on solr 3.6 . ~Might need to do some sort of programatic import 😞~ Nope! Just built a fresh indexer :) (see comment below)
- [x] Test with solr-updater to catchup
- [x] Attach to testing.openlibrary.org
- [x] Fix bugs
    - [x] `text_general` converts everything to `multiValued`! author_name is now `multiValued` :/
    - [x] `title:` field not working with quotes sometimes
    - [x] search `all` failing for "The Mark of the Crown"
    - [x]  `key:(/works/OL450777W OR /works/OL362289W)` no longer works; need to do `key:("/works/OL450777W" OR "/works/OL362289W")`
- [x] Do another fresh reindex which will then go to prod!
- [x] Test on testing.openlibrary.org
- [x] Trial on one web node
- [x] Trial on both web nodes for a week
- [x] Fix any issues
    - [x] #5209 @finnless noting poor results for "foundation" in all search
- [x] Deploy!
- [ ] #4337 merged, Close this issue :)
- [x] Create issues for fixes/features to be done at a later date
    - [x] #5393 Re-enable english stopword detection for `text_en_splitting`
    - [x] #5343
    - [x] #5394 Delete old solr configs/etc.

### Proposal & Constraints
1. Pull out commits related to solr update from #2246 into separate PR
    - Replace custom solr docker image with latest official solr image
    - Use default schema.xml from latest version, and update to include our schema (Note: doing this as opposed to the other way around since it's been so many versions).
2. Run a full reindex on OJF and audit
3. Connect to dev.openlibrary.org and community audit
4. Place in prod environment hooked up to solr-updater connected to dev and audit
5. Replace live solr with new solr.

### Stakeholders
@tfmorris

### PR DESCRIPTION
**Pull request by cdrini**
Closes #3317 .

### Technical

- No known discrepancies between the old/new solr in terms of results provided.
- Note: Everyone will likely need to run `docker volume rm openlibary_solr-data` to remove the old solr's data.

### Testing
- Running on prod for the past few weeks
- Known issue: sometimes seems to cause sluggishness
- Last full solr reindex ran successfully with this code
- Testing locally: `docker-compose up -d` , going to localhost:8983 shows you the solr 8 dashboard! Searching for stuff works

### Stakeholders
@tfmorris

### CODE REVIEW

**Comment by cdrini** [comment]
TODO: author name somehow became multivalued:
image
image

**Comment by cdrini** [comment]
Errors from indexing logs:

- "Unrecognized type" -- actually work missing title. Skipping from log below, because there were too many.
    - [x] Bunch of empty records from some old bug (e.g. https://openlibrary.org/works/OL17933700W?v=1 ). Deleted with DriniBot
    - [x] #4739 Bunch of works with missing title where editions _did_ have title. Made solr resilient to this case.

---

```log
2021-03-04 20:08:25,498 [ERROR] failed to update work /works/OL22995879W
Traceback (most recent call last):
  File "openlibrary/solr/update_work.py", line 1192, in openlibrary.solr.update_work.update_work
  File "openlibrary/solr/update_work.py", line 712, in openlibrary.solr.update_work.build_data
  File "openlibrary/solr/update_work.py", line 378, in openlibrary.solr.update_work.SolrProcessor.extract_authors
  File "openlibrary/solr/update_work.py", line 363, in openlibrary.solr.update_work.SolrProcessor.get_author
TypeError: string indices must be integers
2021-03-04 22:59:51,075 [WARNING] author redirect error: /works/OL646594W
2021-03-04 23:55:36,866 [ERROR] Bad Request
2021-03-04 23:55:36,866 [ERROR] b'<?xml version="1.0" encoding="UTF-8"?>\n<response>\n\n<lst name="responseHeader">\n  <int name="status">400</int>\n  <int name="QTime">52</int>\n</lst>\n<lst name="error">\n  <lst name="metadata">\n    <str name="error-class">org.apache.solr.common.SolrException</str>\n    <str name="root-error-class">org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException</str>\n  </lst>\n  <str name="msg">Exception writing document id /works/OL822802W to the index; possible analysis error: Document contains at least one immense term in field="subject_facet" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \'[80, 111, 108, 97, 110, 100, 46, 32, 65, 114, 109, 105, 97, 46, 32, 79, 100, 100, 122, 105, 97, -59, -126, 32, 87, 121, 100, 122, 105, 101]...\', original message: bytes can be at most 32766 in length; got 53498. Perhaps the document has an indexed string field (solr.StrField) which is too large</str>\n  <int name="code">400</int>\n</lst>\n</response>\n'
2021-03-04 15:32:16,701 [ERROR] bad identifier key barnes_&_noble barnes_&_noble
2021-03-04 15:32:16,702 [ERROR] failed to update work /works/OL15691218W
Traceback (most recent call last):
  File "openlibrary/solr/update_work.py", line 1192, in openlibrary.solr.update_work.update_work
  File "openlibrary/solr/update_work.py", line 717, in openlibrary.solr.update_work.build_data
  File "openlibrary/solr/update_work.py", line 741, in openlibrary.solr.update_work.build_data2
  File "openlibrary/solr/update_work.py", line 335, in openlibrary.solr.update_work.SolrProcessor.process_editions
AssertionError
2021-03-04 15:59:20,738 [ERROR] failed to update work /works/OL16563770W
Traceback (most recent call last):
  File "openlibrary/solr/update_work.py", line 1192, in openlibrary.solr.update_work.update_work
  File "openlibrary/solr/update_work.py", line 712, in openlibrary.solr.update_work.build_data
  File "openlibrary/solr/update_work.py", line 378, in openlibrary.solr.update_work.SolrProcessor.extract_authors
  File "openlibrary/solr/update_work.py", line 363, in openlibrary.solr.update_work.SolrProcessor.get_author
TypeError: string indices must be integers
2021-03-04 16:09:25,396 [ERROR] failed to update work /works/OL16789647W
Traceback (most recent call last):
  File "openlibrary/solr/update_work.py", line 1192, in openlibrary.solr.update_work.update_work
  File "openlibrary/solr/update_work.py", line 712, in openlibrary.solr.update_work.build_data
  File "openlibrary/solr/update_work.py", line 378, in openlibrary.solr.update_work.SolrProcessor.extract_authors
  File "openlibrary/solr/update_work.py", line 363, in openlibrary.solr.update_work.SolrProcessor.get_author
TypeError: string indices must be integers
2021-03-04 16:25:04,763 [ERROR] failed to update work /works/OL17061179W
Traceback (most recent call last):
  File "openlibrary/solr/update_work.py", line 1192, in openlibrary.solr.update_work.update_work
  File "openlibrary/solr/update_work.py", line 712, in openlibrary.solr.update_work.build_data
  File "openlibrary/solr/update_work.py", line 378, in openlibrary.solr.update_work.SolrProcessor.extract_authors
  File "openlibrary/solr/update_work.py", line 363, in openlibrary.solr.update_work.SolrProcessor.get_author
TypeError: string indices must be integers
2021-03-04 16:30:48,369 [ERROR] failed to update work /works/OL17108351W
Traceback (most recent call last):
  File "openlibrary/solr/update_work.py", line 1192, in openlibrary.solr.update_work.update_work
  File "openlibrary/solr/update_work.py", line 712, in openlibrary.solr.update_work.build_data
  File "openlibrary/solr/update_work.py", line 378, in openlibrary.solr.update_work.SolrProcessor.extract_authors
  File "openlibrary/solr/update_work.py", line 363, in openlibrary.solr.update_work.SolrProcessor.get_author
TypeError: string indices must be integers
```

**Comment by cdrini** [comment]
Orphans indexed successfully!

Errors during process:
- 7599 `[WARNING] author redirect error: /works/OL15106876M`
- 2389 `[ERROR] Work missing title /works/OL14789064M`:

```
2021-03-23 21:49:47,421 [ERROR] Work missing title /works/OL14468747M
2021-03-23 21:49:47,421 [ERROR] failed to update work /works/OL14468747M
Traceback (most recent call last):
  File "openlibrary/solr/update_work.py", line 1198, in openlibrary.solr.update_work.update_work
  File "openlibrary/solr/update_work.py", line 692, in openlibrary.solr.update_work.dict2element
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by jimman2003** [comment]
maybe https://hub.docker.com/_/solr?tab=tags&page=1&ordering=last_updated 
might help (as a base)
?

**Comment by mekarpeles** [comment]
Seems to be working locally, the changes lgtm

**Pull request merged**
