### PR TITLE
Partial proofreading

### PR DESCRIPTION
**Pull request by jpguerard**
## Description:
In this Pull Request we have made the following changes:

- Some style improvements.
- Fixed some typos.

### CODE REVIEW

**Comment by mekarpeles** [comment]
Thank you @jpguerard! It seems there are a 6 merge conflicts we may want to address before proceeding (between different translations). Unfortunately I don't know french well enough to resolve these! Do you mind taking a look?

**Comment by roptat** [comment]
my opinion is that traduc is not where msgid bugs should be reported. I agree with every other change.

Another point: I see the website was updated with the translation. I used a lot of &nbsp; (non breakable spaces) but it seems they're being replaced with &amp;nbsp;, so the html entity is displayed instead of a space. How can I fix that?

**Comment by jpguerard** [comment]
Good point. I read it too quickly as translation error report address...

Le 29 mars 2018 14:09:40 GMT+02:00, roptat <notifications@github.com> a écrit :
>my opinion is that traduc is not where msgid bugs should be reported. I
>agree with every other change.
>
>Another point: I see the website was updated with the translation. I
>used a lot of &nbsp; (non breakable spaces) but it seems they're being
>replaced with &amp;nbsp;, so the html entity is displayed instead of a
>space. How can I fix that?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/internetarchive/openlibrary/pull/914#issuecomment-377215131

-- 
Jean-Philippe Guérard

**Comment by mekarpeles** [comment]
lgtm, thank you!

**Pull request merged**
