### PR TITLE
black --skip-string-normalization ./scripts ./tests *.py

### PR DESCRIPTION
**Pull request by cclauss**
Subtask of #5843 

% `black --version ` # --> black, version 21.10b0
% `black --skip-string-normalization ./scripts ./tests *.py`

Closes #5338
Closes #5841 
Closes #5850

I thought that the above three PRs had run [`psf/black`](https://github.com/psf/black) on these files...

@jimman2003 Your review, please.

### CODE REVIEW

**Comment by jimman2003** [comment]
I did run black on these :) , no clue why it makes changes still

**Comment by jimman2003** [comment]
Oops , ran the two commands with && and pyupgrade returned non-zero os code

**Comment by jimman2003** [comment]
so this fixes my mistake :)

**Review by jimman2003 — APPROVED** [review]
LGTM!

**Review by RayBB — APPROVED** [review]
Looks like black changes to me. A bit more lines but a lot easier to read

**Pull request merged**
