### PR TITLE
Attach keydown listeners to searchbar

### LINKED ISSUE #7916: The accessibility of keyboard navigation of the search bar can be improved
(Not sure if I should report this as a bug. If not, I'll repost this with the more appropriate type of issue.)
The accessibility of keyboard navigation of the search bar can be improved.

1. Currently, the auto-suggested list in the search bar is navigated with the tab key. But it should be navigated via arrow keys. And when the tab key is pressed, the focus should move to the next navigation bar item instead of going into the auto-suggested list.

2. Currently, the auto-suggested list keeps appearing on the screen even after the focus moves out from the search bar. It should disappear when the focus is not on the search bar or on the items of the auto-suggested list.

### Evidence / Screenshot (if possible)
When I input the search word, "design" in this case, it automatically shows suggestions.
Screen Shot 2023-05-31 at 3 56 58 PM

When I press the tab key, the focus moves to the search icon.
Screen Shot 2023-05-31 at 3 57 23 PM

Pressing the tab key again, the focus moves to the barcode-ish icon.
Screen Shot 2023-05-31 at 3 57 28 PM

Then, the problem is that pressing the tab key again moves the focus to the suggested list.
Screen Shot 2023-05-31 at 3 57 34 PM

After focusing on all the items in the suggested list, the focus finally moves to the next focusable nev bar item, which is the user icon and hamburger menu in this case.
Screen Shot 2023-05-31 at 3 57 41 PM

Also, another problem is that the suggested list keeps appearing, even after the focus is off from the search bar (in this case, the focus is on "Books").
Screen Shot 2023-05-31 at 3 58 00 PM

### Relevant url?

https://openlibrary.org/search?q=design&mode=printdisabled&has_fulltext=true&subject_facet=Protected+DAISY

### Steps to Reproduce

1. Go to https://openlibrary.org/search?q=design&mode=printdisabled&has_fulltext=true&subject_facet=Protected+DAISY
2. Input any words in the search bar, and navigate the page with the tab key.

* Actual: Explained as above.
* Expected:
** Auto-suggested list should be navigated using arrow keys.
** Pressing the tab key should navigate the focus through the nav bar elements instead of the inside of the auto-suggested list.
** The list should disappear when the focus moves out from the suggested list.
** When the focus is on the list, users should be able to escape fromit by pressing the Esc key, which I think is a suggested accessible behavior.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome Version 113.0.5672.126 (Official Build) (arm64)
- **Operating system?** macOS Monterey Version 12.3.1
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Search bar keyboard navigation in [Google Scholar](https://scholar.google.com/) and [GitHub](https://github.com/) might be good examples.

### PR DESCRIPTION
**Pull request by schu96**
Closes #7916 
I have implemented the suggested behaviors from #7916 but would like to know if there are additional navigation features/more preferred navigation flows for this component. 

I wasn't entirely sure what the intended behavior should be when a user presses Tab while focused on the Form input field and left it as the default behavior.

Fix

### Technical
Implements the suggested keyboard functionality by attaching jQuery ```.on``` event handlers to listen for ```ArrowUp, ArrowDown, Escape, Tab, and Shift + Tab``` keycodes. ```tabindex``` has been attached to each ```li``` element to allow users to navigate the search bar results with their keyboard.

### Testing
Go to ```localhost:8080``` and use a search term that returns at least 3 titles. 
The expected behaviors are:
Form input <ArrowUp/ArrowDown> - Goes to the first or last item in the results list 
Form input <Escape\> - Removes focus from the search bar input, clears search results

Result li element <ArrowUp/Shift + Tab> - Navigates to the previous list sibling if exists, otherwise will focus on the Form input
Result li element <ArrowDown/Tab> - Navigates to the next list sibling if exists, otherwise will loop focus back to the Form input
Result li element <Enter> - Redirects the user to the title
Result li element <Escape> - Blurs focus from ```input[type="text"]``` and clears the results list.

Search facet <Shift + Tab> - Clears the results list since focus is no longer within the relevant search bar component

### Screenshot
This video demos all but the Result li element <Enter> keyboard behaviors.
https://github.com/user-attachments/assets/aa4c8261-b888-43b6-806a-5b4e28ff7424

### Stakeholders

@RayBB

### CODE REVIEW

**Comment by RayBB** [comment]
@bick-jp do you have any opinions on this solution?

I'm really not so familiar with accessibility changes so I'll have to get some second opinions for sure.

@scottbarnes do you know what the current thoughts are on using jQuery for changes like this? I know in some cases we prefer vanilla JavaScript but I don't know if we are totally avoiding jQuery for new code like this.

**Comment by RayBB** [comment]
@schu96 small update from the weekly meeting.

@cdrini said the jquery probably should be :)
Also Drini will checkout this PR as well for accessibility.

Just to double check @schu96 is this PR ready for review? If so, please mark it as such, but it looks like it is so I'll assume so.

**Comment by schu96** [comment]
@RayBB thanks for the update! I initially had it as a draft in case the navigation behaviors needed some tweaking. Does this mean that all existing jQuery code is ok to update like this?

**Comment by cdrini** [comment]
Nice work @schu96 ! Gave this a test, using wikipedia's search box autocomplete as our "gold standard" expected results, and here's what I noticed:
- ❌ tabbing past the search box should close the autocomplete suggestions and move to the next item. Tabbing _should not_ move through the autocomplete results (see wikipedia searchbox)
- ❌ escape should close the autocomplete results and **return focus to the input field**
- ✅ up down work perfectly

**Review by RayBB — APPROVED** [review]
Tested and it's working on all the things @cdrini recommended.
Now we just need @cdrini to give a final check and merge 👍 

Sorry for the delay in this one. Didn't see that you pushed a commit @schu96

**Review by cdrini — APPROVED** [review]
Lgtm! Ray and I did notice one discrepancy, which is that the autocomplete menu should close when you tab out of it, even if you tab onto the search icon or the barcode scanner icon. But that's a small issue and can be tackled in a future issue!

Thank you for the fix @schu96 !

**Pull request merged**
