### PR TITLE
add description to swagger docs

### LINKED ISSUE #8021: Add description to swagger api
### Describe the problem that you'd like solved

We have this page: https://openlibrary.org/swagger/docs

We should say somethings like:
* These are still in development and may not be perfect
* If you'd like to contribute see https://github.com/internetarchive/openlibrary/blob/master/static/openapi.json
* Please do not use our APIs for bulk download

### Proposal & Constraints

We can edit these lines:
https://github.com/internetarchive/openlibrary/blob/3fcc46d7471a9561a3165e4db6c8de6aa7fc8778/static/openapi.json#L3-L6

Add files to the info object per the spec here https://swagger.io/specification/#info-object

### Additional context

Swagger was recently merged: https://github.com/internetarchive/openlibrary/pull/6018

### Stakeholders

@cclauss @jimchamp @scottbarnes @mekarpeles @cdrini

### PR DESCRIPTION
**Pull request by RayBB**
https://openlibrary.org/swagger/docs

- Closes #8021 
- Adds a description
- Marks the API is unversioned (because version is a required string)

### Next Steps
Better grouping and descriptions of the existing API in swagger

### Technical

It's ugly to have it all on one line but that's a limit of json :/

### Testing

n/a

### Screenshot

image

### Stakeholders

@cclauss

### CODE REVIEW

**Comment by tfmorris** [comment]
Why not use YAML instead of JSON to make it easier to edit?

Also, as I commented in #8021, I think it's very important to warn people that the Swagger API definition is incomplete and doesn't describe the full API available.

**Comment by cclauss** [comment]
Nice to see progress on this again.  Thanks!  This will give me the push to get back to working on #5910...

Naming is tricky in this space because **OpenAPI** is the standard for this information while **Swagger** is a set of tools including Swagger-UI that we are using to display this info to users.

> Marks the API is unversioned

I think before we reach v1.0.0 we are free to use the version as we see fit (as long as it does not decrease!). I would rather be able to look at two files and know which one is the newest so let's keep versioning.  I would be OK with [calender versioning](https://calver.org) but perhaps that is not common practice in OpenAPI-land.

> Why not use YAML instead of JSON to make it easier to edit?

Nice!  In #5910, the file `.github/workflows/codegen_api_docs.yml` kicks out json but that could be modified to yaml because both the OpenAPI spec and the Swagger-UI renderer seem to accept yaml as a first-class citizen.  I have gotten used to the triple-quoted strings of toml but that is probably not an option here.

> It's very important to warn people that the ~Swagger~ OpenAPI API definition is incomplete and doesn't describe the full API available.

I agree.  **Please add that explicit message and bring back our version.**

---

The biggest problem that we have is that we are modifying a file that is autogenerated in #5910.  We need to modify the #5910 code to push these modifications into the generated yaml.

Once the version is re-added, let's merge this PR so we can all see the changes, and then we can modify #5910 to:
* [ ] Generate yaml instead of json
* [ ] Push our new `title` and `description` into the generated file.

**Comment by cclauss** [comment]
Please rebase against `master` and then leave the version as `0.1.0` and add the warning that @tfmorris suggested so we can merge.

**Comment by RayBB** [comment]
1. I agree we should add a better warning to this about the incompleteness.
1. I'd also like to use yaml but didn't wanna make that big change now
1. I'll use the openapi language in the PRs now but also use the word swagger to keep it easy to search both.
1. Good call on the versioning


Was merged via https://github.com/internetarchive/openlibrary/pull/8084 so closing

**Pull request closed without merging**
