### PR TITLE
Fixed XSS in work/edition title

### LINKED ISSUE #3080: XSS issues on books page
XSS issues

### Relevant url?

https://openlibrary.org/books/OL27912983M/'_script_alert(_Ultra_Security_)_script
https://twitter.com/BugsBun75181771/status/1228314510563385346

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### PR DESCRIPTION
**Pull request by the-nine-tail**
**Why is this change necessary:** 
This change fix the severe bug XSS in page add-blog of OpenLibrary"

**How does this commit address the issue:** 
The issue was that the URL in anchor was formatted as string in ungettext which was causing the problem, so removing the ungettext causes the template broken error and disturb the blog title, so alternatively the URL is filtered to remove the bad character from the user input

**What effects does this change have:** 
This change solve the XSS vulnerability and encode the URL and title safely

_My first commit in OpenLibrary, really enjoyed to contribute and looking further for more contribution_

Closes #3080 

### Testing
1.Click  Add Book
2. In Title --->  "'><script>alert(/Ultra Security/)</script>
3. Create and load the page

### CODE REVIEW

**Comment by mekarpeles** [comment]
@the-nine-tail congrats on making your first PR!

**Comment by the-nine-tail** [comment]
@mekarpeles why only one person at a time can borrow a book from openlibrary?

**Comment by tabshaikh** [comment]
Hi @the-nine-tail openlibrary is based on this model https://en.m.wikipedia.org/wiki/Controlled_digital_lending

**Comment by the-nine-tail** [comment]
@tabshaikh Thank you got it.
Sir, can I get your email id because I have an idea regarding the "sponsor button" that you introduced int Gsoc 2019

**Comment by cdrini** [comment]
Hi @the-nine-tail ! It looks like something went wrong when you saved the file. This doesn't look like it's in the right place. Could you move it to the correct directory?

**Comment by the-nine-tail** [comment]
Sure

**Comment by the-nine-tail** [comment]
@cdrini the file is in right path (i.e openlibrary/templates/type/edition/view.html)
Should I commit it again??

**Comment by cdrini** [comment]
Awesome, thank you @the-nine-tail ! That looks correct now. I'll have a review for you this week :+1:

Could you also update your other PRs? I think they all have the same issue.

**Comment by the-nine-tail** [comment]
@cdrini Sure

**Comment by cdrini** [comment]
Awesome, thanks!

Oh, actually just noticed there's still a duplicate file here; let's make sure to delete it. The way you can tell is by clicking on the "Files changed" tab in GitHub: https://github.com/internetarchive/openlibrary/pull/3196/files . This shows you all the changes you've made. The first file is what it should look like (only a few lines should be green/red/modified). The second file, which is _entirely_ green, means that it's an entirely new file. Hope that helps!

**Pull request merged**
