### PR TITLE
addresses homepage NoneType has no len() bug

### PR DESCRIPTION
**Pull request by mekarpeles**
resolves: error in processing template: TypeError: object of type 'NoneType' has no len()

### CODE REVIEW

**Comment by hornc** [comment]
@mek, what fields is this bug triggering on? Just wondering if there is bad data, like blank titles?, that needs to be fixed also.

**Comment by mekarpeles** [comment]
@hornc it seems that this is happening either because a book has no title or no author.

Not sure a great way for us to determine this at scale -- we could likely grep the json in the data dump and flag such works / editions.

For now, this patch should address the issue.

**Comment by bfalling** [comment]
LGTM

**Comment by hornc** [comment]
@mekarpeles I have just checked and there are 218 works without titles, some don't exhibit this bug as they have subtitles e.g. https://openlibrary.org/works/OL15659191W and this https://openlibrary.org/works/OL15168117W/untitled (which seems like non-malicious user error).
The ones that doe show the bug, eg. https://openlibrary.org/works/OL17052688W/ seem also to be possible glitches when users were creating works, https://openlibrary.org/works/OL17052688W/?m=history

**Comment by LeadSongDog** [comment]
That particular user made only three edits, https://openlibrary.org/people/ollybeak 
It looks as if the experiments were all unsuccessful. It might be worthwhile to scan for similar short-stay editors' edits: it is a likely nexus for problem data.

**Pull request merged**
