### PR TITLE
Restyle/omni bar

### LINKED ISSUE #7008: Restyle the omnibar
Our book page omnibar looks pretty bad in both mobile and desktop views:
Screenshot from 2022-12-08 16-35-26
_Our current omnibar component_

Let's restyle the omnibar such that it looks like the following mock-up:
Screenshot from 2022-09-28 11-06-23
_Mock-up for mobile omnibar_

The arrow need not appear in desktop views.

### Related Files:
Omnibar stylesheet: https://github.com/internetarchive/openlibrary/blob/master/static/css/components/work.less
Omnibar HTML: https://github.com/internetarchive/openlibrary/blob/c4d2a52809638a49af1bedf3cdfc0bbf8fc5b14e/openlibrary/templates/type/edition/view.html#L210-L263

### PR DESCRIPTION
**Pull request by Eds-Dbug**
Closes #7008 

It restyles the omni bar to a box layout

### Technical

- Only changes in work.less is present

### Testing

- Visual test for mobile tablet and wide screen

### Screenshot

image
image

### Stakeholders

@jimchamp

### CODE REVIEW

**Comment by Eds-Dbug** [comment]
This is the correct PR.

**Comment by cclauss** [comment]
@Eds-Dbug Please look at the [stylelint](https://stylelint.io) errors listed under `Details` link to the right of the ❌ below.

**Comment by Eds-Dbug** [comment]
I will when I get back this evening.

**Comment by Eds-Dbug** [comment]
Ran linting and fixed all linting issues in Work.less

**Review by cdrini — APPROVED** [review]
Lgtm! Thanks @Eds-Dbug !

**Comment by Eds-Dbug** [comment]
:D

**Pull request merged**
