### PR TITLE
autodetect author ASIN, Youtube, storygraph ids

### LINKED ISSUE #8202: Auto-detect ASINs & StoryGraph identifiers in the author page editor
### Describe the problem that you'd like solved
The author editing page is able to automatically "suggest" that Q57087507 is a Wikidata identifier or 0000 0004 8385 4684 is an ISNI, speeding up the process of adding identifiers to existing author pages. I think this could be done for ASINs & StoryGraph IDs as well, if I correctly understand what a regex is.

### Proposal & Constraints
ASINs are described here: https://inventlikeanowner.com/blog/the-story-behind-asins-amazon-standard-identification-numbers/

I think it would be best to only assume a 10-character code starting with B or B & a number, given the rate at which they're being created as detailed in the link above.

An example StoryGraph ID: 6c67a39f-eae2-4304-a8a3-7309da6560df

I don't know how best to describe this other than 'five alphanumberic chunks with dashes in between'. The middle ones seem to be shorter than the beginning and ending ones in my experience, but that's anecdotal.

### Additional context
This could possibly be extended to other identifiers, but I don't know enough about them to be sure it's worth proposing.

### Stakeholders
@RayBB

### PR DESCRIPTION
**Pull request by davidscotson**
Closes #8202

Autodects ASIN, Youtube and storygraph identifiers on the Author edit page.

### Testing

Pasting in (or typing) one of the above ids should automatically set the dropdown to the appropriate id type. Wikidata and ISNI types should continue to be detected.

One note for testing, if the contents doesn't change, the code isn't triggered, so if you paste in a storygraph id, manually change the type of id in the selector to something else, then paste in the exact same storygraph id then it'll not do anything. Not an issue for real users but something that testers might do and wonder if it is a bug.

### CODE REVIEW

**Review by jimchamp — CHANGES_REQUESTED** [review]
Thanks for this PR, @davidscotson!  With the exception of the Youtube identifier pattern, everything is working as expected.

The conditionals that determine the currently selected identifier type are becoming unwieldy, and will become worse as new identifiers are added in the future.  In order to simplify things a bit, could you make the following changes?

1. Create an object that maps detectable `selectedIdentifier` values to their patterns.  This can be declared on the line following the opening `<script>` tag.
2. Replace the conditionals with a `for...in` loop that iterates over the object's keys. While iterating, if `this.inputValue` is a match, store the current key as the selected identifier and break out of the for loop.

While you work on this, I'll open a separate PR which updates our `pg_dump` file to include the author configs for Youtube, Storygraph, and Amazon identifiers.

**Comment by davidscotson** [comment]
I'll make those changes.

A couple of things I've noticed while using the feature which I might look at too if they don't become tricky:

1. Pasting in an INSI with spaces doesn't trigger the detector.
2. The type selector doesn't reset so its kind of easy to accidentally set a viaf over the top of whatever you just added.

**Comment by jimchamp** [comment]
Thanks!  To your points:
1. I noticed this while testing, but didn't mention it.  I think that this pattern should be changed to include optional whitespaces, but I'll let you decide if that's in the scope of this PR.
2. Do you mean after an identifier has been set by clicking the "set" button?  It's probably a good idea to reset the selector when this happens.

**Comment by davidscotson** [comment]
Pushed a rebased branch that makes the requested change to for .. in seperately, then adds new items, including Youtube handles, also fixes ISNI with spaces.

**Review by jimchamp — APPROVED** [review]
Thanks @davidscotson! This looks good to me.

**Pull request merged**
