### PR TITLE
Replace vendor jquery-ui with npm install

### LINKED ISSUE #4234: Replace vendor/jquery-ui with npm install
### Summary of Requirements

- [x] vendore/jquery-ui deleted
- [x] jquery-ui `npm install`ed to the same version
- [x] package.json does not use `^`, but specifies specific version
- [x] jquery-ui imports in JS updated to point to new module
- [x] JS builds without errors
- [x] Test: searchbox autocomplete still works
- [x] Test: Selecting author on work autocompletes
- [x] Test: Tabs on work edit page work

### Stakeholders
@jamesachamp

### PR DESCRIPTION
**Pull request by jamesachamp**
Closes #4234

Removes two versions of jQuery UI from the vendor directory and replaces tab and dialog widgets with those from the jQuery UI npm install.  jQuery UI has been in our `package.json` for over a year, so nothing new should need to be installed.  Changes to autocomplete were not included in this PR (more details below).  Marking this as a work in progress until a more comprehensive list of OL components that use jQuery UI has been identified and tested.

### Technical

While working on this, I discovered that autocomplete features are using vendor/jquery-autocomplete instead of jQuery UI.  Any attempts to replace this library with jQuery UI's autocomplete resulted in [setup_multi_input_autocomplete](https://github.com/internetarchive/openlibrary/blob/ac709140162a84be9ba4edaf2ede0a71ea9af7c0/openlibrary/plugins/openlibrary/js/autocomplete.js#L83) calls to fail.  This function is used to initialize multiple autocomplete fields in a single page.

### Stakeholders

@mekarpeles 
@cdrini

### CODE REVIEW

**Comment by jdlrobson** [comment]
Yeh I hit this same problem. We should focus efforts on removing jquery ui and this confusion, possibly rewriting search if needed - its a big source of pain in the frontend.

**Comment by jdlrobson** [comment]
(Likely blocked on https://github.com/internetarchive/openlibrary/pull/2734 which itself is blocked on a few things)

**Review by cdrini — APPROVED** [review]
This looks ok for removing the jquery-ui vendor ; Agreed more work needed to remove jquery-autocomplete, but we can do that later. 

Tested:
- Edit book tabs work
- search autocomplete works
- Select author autocomplete works
- cover modal works
- manage-covers modal works
- preview modal works.

This lgtm. Happy to merge if you take this out of WIP, @jamesachamp :)

**Comment by jdlrobson** [comment]
I vaguely remember this code was being used in some unexpected undocumented edit interfaces. Will probably want to make sure some community members are on alert for any search issues in next deploy in case we missed something since we dont log client side errors yet.

**Pull request merged**
