### PR TITLE
Morecss

### LINKED ISSUE #1085: Minify CSS assets
Currently CSS assets (by nature of CSS) are render blocking. They are also not-minified. Right now on a 3G connection from Singapore it can take up to 12 seconds for the user to see anything 
 -https://www.webpagetest.org/result/180907_N8_824f77c230ea0a2939484f3e5657bb18/

Minification of all these assets should be a top priority.

This is easily achieved via LESS (using -x) but given there is also CSS these will need to be built using LESS as well for this to be viable.

We can expect the site to be a lot lot faster with changes in this arena.

### PR DESCRIPTION
**Pull request by jdlrobson**
Closes #1085 (v. v. important!)
Continues work in #1092

### CODE REVIEW

**Comment by mekarpeles** [comment]
@jdlrobson we may have to hold off on this PR until we have a chance to discuss during this Tuesday's call.

`gulp` won't be installed during deploy on our production boxes (ol-web3, ol-web4, ol-www1) so we'll have to manually install this dependency and also update our dockerfile + vagrant `install.sh`

**Comment by jdlrobson** [comment]
Okay. I'm also not attached to using gulp (and given I think at some point we'll want webpack expect it to disappear).

We could instead use the less plugin (less-plugin-clean-css) and running the command:
lessc --clean-css="--s1 --advanced --compatibility=ie8" static/css/all.less $(BUILD)/all.css
for each of the files.

However my Makefile skills are not too good so i'd need some help making that into a one line command.

let me pull out the minification patch from this set of patchsets for now so the rest of this can be merged.

**Comment by mekarpeles** [comment]
Yes please, happy to merge the rest, thank you!

**Comment by mekarpeles** [comment]
EDIT: Updates now LGTM! Fantastic :)

**Pull request merged**
