### PR TITLE
Fix reading list flash on book page load

### LINKED ISSUE #5108: Lists flash on book page when page loads
Following the deployment on 28 April 2021, I noticed my lists flash up onto the page and then disappear when page loads. If that edition is on my list, the relevant list name remains. 

Page load also seems slower than usual.

### Evidence / Screenshot (if possible)

https://user-images.githubusercontent.com/17739465/116588577-03a11980-a91c-11eb-838c-47585d3f6d6c.mov

### Relevant url?
 
Any edition or work url.

### Steps to Reproduce

1. Go to ...an edition or work url.
2. Do ...note the left side of page on load.

* Actual: Patron's lists all load and then disappear.
* Expected: If I have a relevant list it should appear alone. If I have no relevant list, nothing should appear at all.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome Version 90.0.4430.85 (Official Build) (x86_64)
- **Operating system?** MacOS Big Sur
- **Environment (prod/dev/local)?** prod

### Stakeholders

@seabelis

### PR DESCRIPTION
**Pull request by jamesachamp**
Closes #5108

Corrects issue in which all of a patron's lists are briefly displayed under the reading log button on book page load.

### Technical

All lists are briefly displayed due to a call to `render_already_lists` in the template.  This function is later called via Javascript, rendering only lists containing the page's book, which replaced the list.

Removing the initial `render_already_lists` call prevents the flash, and likely improves page performance.

### Testing

While logged in as a patron with multiple reading lists:
1. Find a book that is in at least on of your reading lists, but not in all of the lists.
2. Navigate to that book's page.
3. Verify that all of the lists are not briefly displayed on page load.

### Screenshot

**Page refresh before code change:**
flash-before

**Page refresh after code change:**
flash-after

### Stakeholders

@mekarpeles

### CODE REVIEW

**Review by jdlrobson — COMMENTED** [review]
The HTML is there for non javascript users.

It can be hidden without a flash for JS users by .client-js (selector) { display:none }

**Comment by jamesachamp** [comment]
I'm not sure how much list functionality works correctly when javascript is disabled.  The `[X]` for removing a book from a list  redirects to the list page.  From there, the book still cannot be removed as the "Remove this item?" link relies on JS.

That larger issue aside, I'll work on modifying this so that the filtered list is displayed in the HTML and the JS doesn't update the list on page load.

**Comment by jamesachamp** [comment]
Modified the solution so that lists are only displayed by the `render_already_lists` function if the list's `active` attribute is `true`.  This signifies that the seed is present in the list.

While working on this, I noticed that the JS `update_my_lists()` function is called three times while the page is loading.  This function appears to render updated lists in various parts of the page.  This seems like an excessive amount of calls, but I didn't do a deep dive to see if it is somehow necessary.  Maybe this can be simplified when inline JS is removed from this file?

**Comment by jdlrobson** [comment]
LGTM. If we're concerned at this from a performance angle, we should also look to put a height on the cover, which is causing a repaint of the page.

**Pull request merged**
