### PR TITLE
Removing Dead Features Related to #4474

### PR DESCRIPTION
**Pull request by brett-hardiman**
Works on  #4474 (case.html)

### Technical

open library/plugins/openlibrary/support.py , openlibrary/templates/email/support_case.html , and openlibrary/templates/admin/case.html ended up being dead features. I deleted them to help clean up a bit. So just a small refactor.
### Stakeholders

@jdlrobson

### CODE REVIEW

**Review by cclauss — APPROVED** [review]
Is there an HTML linter that we should be running in our GitHub Actions that could flag this stuff before it gets merged?

**Review by brett-hardiman — COMMENTED** [review]
Sorry I did not mean to include this stuff in my PR (I'm a new to using Github). These changes shouldn't be in this. Only things that should have been in this PR should have been the 3 files I deleted.

**Comment by cclauss** [comment]
Oh, cool!  I am glad to hear that those changes were just local. ;-)

**Comment by brett-hardiman** [comment]
I spoke with Jon and Mek and they said these features could be deleted so that's all what this PR was supposed to be about. I don't want to make those changes to index.js so how should I exclude those changes?

**Comment by jdlrobson** [comment]
I am pretty sure you can delete the entire files here rather than just
those lines of code :)

**Comment by cclauss** [comment]
I am a bit lost here... #4474 does not appear the mention the word `support` yet this PR is removing `support.py` which is imported and `support.setup()` is called by `openlibrary/plugins/openlibrary/code.py`.
1. How does #4474 justify the removal of `support.py`?
2. Our tests correctly detect that `support.py` can not be removed without also modifying `openlibrary/plugins/openlibrary/code.py`

**Review by cclauss — CHANGES_REQUESTED** [review]
openlibrary/plugins/openlibrary/code.py imports support.py

**Comment by brett-hardiman** [comment]
When I asked what was going on with case.html we found that it was a dead code so we wanted to remove all traces of it from the codebase, so that's why I included support.py and support_case.html. I just included them in this. Should it have been separate?

**Comment by jdlrobson** [comment]
@mekarpeles can you clarify the goal here?

My understanding is the Html templates are dead code, but am not sure about which bits of python are..

**Comment by cclauss** [comment]
Does https://openlibrary.org/contact continue to work when [`class contact(delegate.page):`] is deleted?

**Comment by mekarpeles** [comment]
> Does https://openlibrary.org/contact continue to work when [`class contact(delegate.page):`](https://github.com/internetarchive/openlibrary/pull/4863/files#diff-2dd9bfeeec4356013daa7cb8bcb00c14285b7c88dd1d83198b7fd3d05bd5757fL18) is deleted in `openlibrary/plugins/openlibrary/support.py`?

I think this will be the thing to test.

@brett-hardiman I think you idea here is best for the time being, to ignore these files for now and prioritize inlines in other files. We can circle back to this specific set of file removals after we've had a chance to test removing these files on staging (like @cclauss recommends)
https://github.com/internetarchive/openlibrary/pull/4863#issuecomment-802315786

**Comment by brett-hardiman** [comment]
So I should just ignore the other files and submit a PR only concerning the removal of case.html?

**Comment by mekarpeles** [comment]
> @mekarpeles So I should just ignore the other files and submit a PR only concerning the removal of case.html?

@brett-hardiman still supportive of your previous recommendation to split up these PRs, if there's anything else I can do to help unblock, happy to chat!

**Comment by jimchamp** [comment]
Closing this.  Removing `support.py` disables submission of our [contact form](https://openlibrary.org/contact).  Removing `/js/index.js` disables most of our JavaScript.

**Pull request closed without merging**
