### PR TITLE
Travis CI: Start testing on Python 3.7

### PR DESCRIPTION
**Pull request by cclauss**
> **Description**: What does this PR achieve? [feature|hotfix|refactor]

Upgrade Travis runtime from Trusty to Xenial https://blog.travis-ci.com/2018-11-08-xenial-release and upgrade Python from 3.6 to 3.7.

> **Technical**: What should be noted about the implementation?

> **Testing**: Steps for reviewer to reproduce / verify this PR fixes the problem?

> **Evidence**: If this PR touches UI, please post evidence (screenshot) of it behaving correctly:

### CODE REVIEW

**Comment by tfmorris** [comment]
Does this add Xenial testing or swap Xenial for Trusty? I should probably know the answer, but I can't easily tell from the Travis docs or the edits.

Our production stack is still on Trusty, as I understand it, so I think it's important to keep testing. The Docker environment runs Xenial and we want to move production to that too, so it is valuable to start testing on it, but not at the expense of Trusty -- plus, my reading of the Travis docs is that Xenial support isn't fully baked for another month or two.

**Comment by cclauss** [comment]
This commit runs Python 2.7 and 3.6 on Trusty and 3.7 on Xenial in accordance with travis-ci/travis-ci#9069

**Comment by tfmorris** [comment]
I've resolved the merge conflict in the simplest way possible. We can probably just use PyYAML 4.2b4 for all versions of Python, but didn't have a chance to test.

With that resolved and the addition of both Trusty & Xenial to the matrix LGTM.

**Comment by cclauss** [comment]
@tfmorris Is there something more to do on this one?

**Comment by mekarpeles** [comment]
lgtm

**Pull request merged**
