### PR TITLE
Re-balance JS for smaller all.js (444 kb -> 254 kb!)

### LINKED ISSUE #9319: Remove jquery-validate from the critical path of JS
### Problem

We could remove 7.51KB gzipped (124.38KB -> 116.87KB) on the critical path of all.js by only loading jquery-validate when needed (on pages with a html element with the class "validate").

Validate is only needed on pages where there are user inputs like editing/registration/etc.

### PR DESCRIPTION
**Pull request by cdrini**
Closes #9319

### Technical
- Made our usage of jquery tabs consistent behind an `ol-tabs` class
    - Tested: tabs on ✅ edit page, ✅ recent changes work, ✅ /admin/graphs, ✅ covers change modal
- Moved various jquery-ui things (eg jquery ui autocomplete) out of all.js/index.js, into imports for the files that actually directly use it.
    - Tested: Autocomplete on edit page still works (✅ langs, ✅ authors, ✅ works, ✅ subjects)
    - Tested: Autocomplete in ✅ searchbox works
- Dissolved automatic.js into where it made more sense. It was triggering jquery validate, so put that in validate.js. The last two lines I just put in index.js since they were so tiny.
- Deleted bookreader_direct.js ; the css class `borrow-link` was unused in codebase
- Removed `confirmDialog` from dialog.js ; it was only used to expose itself as a jquery fn, `ol_confirm_dialog`, which itself was never used
- Removed jquery.repeat from all.js/index.js ; only used for various forms, so imported it only from where `.repeat(` was called
    - Tested: Can edit ✅ excerpts, ✅ links, ✅ identifiers, ✅ classifications, ✅ contributors
- Removed autocomplete.js from all.js/index.js, and loaded it conditionally when `.multi-input-autocomplete` was called
- Removed all the `window` writing from index.js into a jsdef helper, `exposeGlobally`
     - Note: Can likely move a lot of `python.js` and `utils.js` into this file ; they are only there for this purpose.
- Made validate only load if `form.validate` matches
    - ✅ /books/add validates identifiers + can submit
    - ✅ books edit validates identifiers + can submit
- Moved various dialog/colorbox code out of all.js/index.js, into where it's actually used.
    - Tested create ✅ a new list dialog
- Deleted window.Template and window.Browser ; unused from the window objects or from jsdef
- Deleted `vendor/js/jquery-form/jquery.form.js`; I could find no references to any of the methods it exposed on jquery.
- Moved cta-btn--preview into dialogs file, since it requires colorbox
    - Test previews work on (✅ search pages, ✅ book pages)

### Stakeholders
@RayBB @rebecca-shoptaw

### CODE REVIEW

**Comment by RayBB** [comment]
@cdrini you could add this to your PR here too https://github.com/internetarchive/openlibrary/pull/9320

**Comment by cdrini** [comment]
@RayBB Oh shoot missed that you had a PR open on this!

**Comment by RayBB** [comment]
@cdrini I'm really excited for this one! It also contributes to #2340

**Comment by cdrini** [comment]
I think I've gotten most of the cases tested; I think any general testing of [testing.openlibrary.org](http://testing.openlibrary.org/) for JS errors would be useful!

Also if you have some time to do some before/afters of file size before/after gzipping like you've done for some other pieces, that would be super handy to see if/how this is making a difference! If you could shrink the bundlesize numbers, that would also be a huge help!

Ideally we could show a video before/after of this somehow... but it's a little tough to set up :P

**Comment by RayBB** [comment]
@cdrini I'll try to check it out more in depth later but I noticed one small new error:
https://testing.openlibrary.org/books/OL19808827M/Harry_Potter_ve_Ate%C5%9F_Kadehi
`Uncaught TypeError: window.$.colorbox is undefined`
Doesn't happen on prod or staging.

**Comment by cdrini** [comment]
Good catch! Let me take a look...

**Comment by cdrini** [comment]
Ah seems to be a bug in the way this code operates:

https://github.com/internetarchive/openlibrary/blob/5f55b17319ee0416982a456b1d3de488e659c110/openlibrary/components/ObservationForm.vue#L151-L155

It's resizing the modal even when it's not visible yet :P The observations form opens normally though, and I can't think of a quick fix, so that's something we can tackle in a future PR :+1:

**Comment by RayBB** [comment]
@cdrini here are the gzipped stats!
| File Name                                                                 | Before Uncompressed Size | After Uncompressed Size | Difference in Uncompressed Size |
|----------------------------------------------------------------------------|--------------------------|-------------------------|----------------------------------|
| editions-table.a509ee544db72268a33d.js                                      | 4.17 KB                  | 4.17 KB                 | 0 Bytes                        |
| graphs.4a0a1bd9a5ea79ae6f16.js                                             | 2.1 KB                   | 2.1 KB                  | 0 Bytes                        |
| markdown-editor.891fe11ebdb3366f69d2.js                                    | 10.84 KB                 | 11.94 KB                | +1.1 KB                        |
| carousel.fa30c8f57146d671a291.js                                           | 4.93 KB                  | 4.93 KB                 | 0 Bytes                        |
| carousels-partials.6026e121f3a882f474ee.js                                 | 5.14 KB                  | 5.14 KB                 | 0 Bytes                        |
| covers.b77d1eea74cb56ced865.js                                              | 1.17 KB                  | 2.4 KB                  | +1.23 KB                       |
| add-book.e36787af16669412d396.js                                            | 2.02 KB                  | 2.34 KB                 | +0.32 KB                       |
| readmore.d37b5697c2c54077bfd3.js                                            | 2.09 KB                  | 2.09 KB                 | 0 Bytes                        |
| modal-links.9ee7816338921a0f278f.js                                        | 5.75 KB                  | 5.75 KB                 | 0 Bytes                        |
| user-website.aed957e6c679338152d8.js                                        | 3.67 KB                  | 6.4 KB                  | +2.73 KB                       |
| page-barcodescanner.1168d04bfcf63db16689.js                                | 7.18 KB                  | 7.18 KB                 | 0 Bytes                        |
| realtime-account-validation.f58d453be56ff91c3148.js                        | 805 B                   | 828 B                  | +23 Bytes                      |
| readinglog-stats.07db8faf267c7dc0a00d.js                                  | 4.91 KB                  | 4.91 KB                 | 0 Bytes                        |
| goodreads-import.2a9850bd4e86190a42a9.js                                  | 1.54 KB                  | 1.7 KB                  | +0.16 KB                       |
| admin.8bbb058d644a916b1e0c.js                                              | 1.28 KB                  | 1.28 KB                 | 0 Bytes                        |
| search.0b884aeee3332c030772.js                                             | 614 B                   | 614 B                  | 0 Bytes                        |
| tabs.b7c9e051759504196d7f.js                                               | 4.1 KB                  | 4.37 KB                 | +0.27 KB                       |
| all.js                                                                      | 128.79 KB                | 78.17 KB                | -50.62 KB                      |
| page-admin.css                                                             | 25.04 KB                 | 25.04 KB                | 0 Bytes                        |
| page-book.css                                                              | 13.32 KB                 | 13.32 KB                | 0 Bytes                        |
| page-edit.css                                                              | 24.64 KB                 | 24.64 KB                | 0 Bytes                        |
| page-form.css                                                              | 24.56 KB                 | 24.56 KB                | 0 Bytes                        |
| page-home.css                                                              | 8.08 KB                  | 8.08 KB                 | 0 Bytes                        |
| page-plain.css                                                            | 24.73 KB                 | 24.73 KB                | 0 Bytes                        |
| page-subject.css                                                          | 8.84 KB                  | 8.84 KB                 | 0 Bytes                        |
| page-user.css                                                             | 26.52 KB                 | 26.52 KB                | 0 Bytes                        |


how I made this:
```bash
git switch master
docker compose run --rm home make js
docker compose run --rm home npx bundlesize | grep KB
gh pr checkout 9346
docker compose run --rm home make js
docker compose run --rm home npx bundlesize | grep KB
```
Then basically ask chatgpt to make a before and after with this info: "Based on the provided BEFORE and AFTER data, here's a Markdown table summarizing the file sizes and their differences:"

More testing to come later!

**Comment by cdrini** [comment]
Niiiice! Oh I think those are the sizes after gzip; bundlesizes seems to list those. Darn still not under the 50kb 😁 But 50kb closer, not too shabby! You'll likely need to do a bash command of some sort to get the size ; e.g. `ls -lh *.js` perhaps or `du -sh *.gz`

I was wondering why none of the other files were basically +50kb, and I think that webpack might be under the hood e.g. separation out colorbox into a separate bundle so that it's shared between the multiple entrypoints that need it. Cool!

**Review by RayBB — APPROVED** [review]
I've looked at quite a few of the pages I know with JS and haven't seen anything broken.

I do see a few warning but it seems fine.

One new console warning [here](https://testing.openlibrary.org/books/OL22379155M/Sophie's_world/edit?work_key=/works/OL922430W) when you click manage overs.
`Possible Unhandled Promise Rejection: TypeError: s(...).disableSelection is not a function`

Also [here](https://testing.openlibrary.org/authors/OL1554239A/David_F._Walker/edit) I'm seeing a warning
`Possible Unhandled Promise Rejection: TypeError: c(...).repeat is not a function`

**Comment by cdrini** [comment]
Great catches! Found the issues, pushing up shortly...

**Comment by cdrini** [comment]
Ok! Reran some of the numbers: https://docs.google.com/spreadsheets/d/1NaDL9WOUUvAX21gXMJ6xCISgNQ2SVWC4lmGo-_G5edY/edit#gid=0

So for all.js we went from 132 kb to 80 kb gzipped; that's -52kb or 40% smaller!

Ungzipped, it went from 436 kb to 252 kb, -184kb. That's 42% smaller.

The other js files did increase a little bit naturally, and overall we have 24kb of gzipped production JS ; although the critical path that is all.js is much smaller, and this other JS is only loaded as needed, so this is a net win :+1: Merging up!

**Pull request merged**
