### PR TITLE
Add book titles to carousels

### LINKED ISSUE #2084: Add book titles to carousels
## Is your feature request related to a problem? Please describe.

Should we add titles beneath our carousels? Especially when a book has a non-descript bookcover, it's difficult to tell what the book is.

UPDATE:
The results of the vote suggest adding titles may be a worth-while change (especially for books in carousels without covers)

## Examples
overdrive-carousel-titles

Ideally, the carousels would provide additional information + interactive/clickable elements (e.g. Amazon includes title, author, etc).
www amazon com_s_bbn=1000 rh=n%3A283155%2Cn%3A5267710011 dc qid=1613118991 rnid=1000 ref=lp_1000_nr_n_30.

## Stakeholders
Stakeholders: @jdlrobson, @koderjoker, @hornc, @charstarstars, @seabelis

### PR DESCRIPTION
**Pull request by Yashs911**
Closes #2084
Color Scheme used **background-color: blue**, **color: white**

**Blocker: As the title width is related to the class="book-cover" for viewport width<1200px it will appear outside the cover image**
### Screenshot

https://user-images.githubusercontent.com/64412143/106097561-853aad00-615d-11eb-8e8e-197546397df1.mp4

https://user-images.githubusercontent.com/64412143/106101007-44459700-6163-11eb-9bfc-4b4796560c2e.mp4
### Stakeholders

@mekarpeles

### CODE REVIEW

**Comment by Yashs911** [comment]
@jdlrobson I was wondering if you are free and could review this PR 😄

**Comment by jdlrobson** [comment]
As a volunteer I tend to prioritize based on priorities as I have limited time. I can't commit to this one right now unfortunately but I'll keep you posted.

**Comment by jdlrobson** [comment]
A few things that would likely be helpful to reviewer:
* I think there is room for improvement in the design. It doesn't seem to fit with the rest of the look and feel of the site. Is there anyone we can ask about that?
* What happens for extremely long titles? Could you provide a screenshot or video of that case? Right now the titles you show are three lines maximum. Some to try include https://openlibrary.org/works/OL2965134W/The_Curious_Incident_of_the_Dog_in_the_Night-Time?edition=curiousincidento0000hadd_b4k6 and https://openlibrary.org/works/OL20191343W/Aristotle_and_Dante_Discover_the_Secrets_of_the_Universe?edition=

**Comment by Yashs911** [comment]
> * What happens for extremely long titles? Could you provide a screenshot or video of that case? Right now the titles you show are three lines maximum. Some to try include https://openlibrary.org/works/OL2965134W/The_Curious_Incident_of_the_Dog_in_the_Night-Time?edition=curiousincidento0000hadd_b4k6 and https://openlibrary.org/works/OL20191343W/Aristotle_and_Dante_Discover_the_Secrets_of_the_Universe?edition=

Currently:
image
But we can use **TruncateString**:
image

**Comment by mekarpeles** [comment]
@Yashs911 thank you so much for your effort on this PR (and so many of our other recent contributions)! 

I feel bad but I think I'd like to close the underlying issue, as well as this PR, and wait for a design effort to completely rethink + redesign the carousel component. Right now if a cover is missing, we already see the title as the background (so the utility of this implementation isn't quite there). Sorry! It's my fault for not having more clarity on the right product direction :) thanks for understanding <3

**Pull request closed without merging**
