### PR TITLE
Reading log to v2 for issue #1250

### PR DESCRIPTION
**Pull request by linkel**
Addressing issue #1250, have edited the account.py file in openlibrary/plugins/upstream to apply v2 on the page. Doesn't look like there's any JS functions to wrap in the window.q handler. Wondering if the analytics scripts part is functioning--they are throwing a ReferenceError in the console. 

image

### CODE REVIEW

**Comment by jdlrobson** [comment]
I can't replicate the JS errors locally (good or bad.. I'm not sure haha).

The following widgets are not adapting well on mobile, but we can fix those in another issue/follow up IMO. This is definitely an improvement on status quo!

screen shot 2018-10-23 at 7 48 04 pm

**Comment by linkel** [comment]
In the console when inspecting the page, I see:

```
Uncaught ReferenceError: archive_analytics is not defined
    at send_analytics_pageview (want-to-read:342)
```

That line responsible is the following (341 and 342):
```
    window.addEventListener('DOMContentLoaded', function send_analytics_pageview() {
        archive_analytics.send_pageview({});
```

**Comment by jdlrobson** [comment]
@linkel are there any failed network requests?
For example does a request fire to http://archive.org/includes/analytics.js?v=0c15bbe  ?

I'm not seeing this issue locally. Analytics look like they are working correctly for me. I'm seeing events to https://analytics.archive.org/0.gif

@hornc  @mekarpeles can you reproduce this issue?

@linkel how do you feel about scoping the flex rules of .mybooks component to only apply on tablet resolutions (at the existing tablet threshold). i think this would somewhat improve the mobile display.

**Comment by linkel** [comment]
Thanks for looking into it. I was actually looking at the console log of the docker instance that was running locally on my machine. That wouldn't be able to send anything to analytics, correct? So this is perhaps my misunderstanding. 

Sure, I will explore the flex rule CSS stuff.

**Comment by linkel** [comment]
When I comment out the flex rule in mybooks-list.less:

`.mybooks-list {
  //flex: 1;
  padding: 10px;`

The widget ends up sticking out a lot.

It goes from this:
image

to this:

image

I'm not too well-versed with what is going on here. Maybe another issue should look closer at the CSS?

**Comment by mekarpeles** [comment]
@linkel thanks for working on this!! Here's our latest docker tutorial w/ instructions on how to rebuild css + js:

https://archive.org/embed/openlibrary-developer-docs/zoom_0.mp4?autoplay=1&start=2

I believe .display-flex() is a mix-in which allow a `display: flex` to be expanded into the different variations that are required for different browsers. @jdlrobson please correct me if I'm mis-recalling :)

**Comment by jdlrobson** [comment]
Great question!
The mixin is a LESS concept. It allows you to call a substitution function that outputs several rules.

Our display: flex rules were defined with vendor prefixes which make it a bit repetitive defining this property in multiple places. In the output css it will be converted to the contents of the mixin e.g. display:flex

You'll need to run `make css` after changing any of the css.

Does that help?

**Comment by linkel** [comment]
I went to mixins.less and added this in front of the display flex function.

`@media (min-width: 768px) and (max-width: 1024px)`

When I type `make css` I get this:

```
mkdir -p static/build
lessc -x static/css/page-admin.less static/build/page-admin.css
make: lessc: Command not found
Makefile:22: recipe for target 'css' failed
make: *** [css] Error 127
```

I was already getting this before, previously, when I was trying to build the css according to the instructions with the wiki, but I ignored it since I thought maybe it had to do with the Vagrant stuff and not when using Docker. 

Perhaps a bit of a foolish question...Do I need to have lessc installed on my system in order to build the css?

**Comment by jdlrobson** [comment]
I think the makefile requires a global installation but it should be possible to use `npm install` and `npm test` to generate the css as we.

Npm install -g lessc should make the Makefile work.

In terms of the fix i don't think the mixins is the right place to fix the issue. You'll want to do this in the component itself. https://github.com/internetarchive/openlibrary/blob/master/static/css/components/header.less is a good example!

**Comment by mekarpeles** [comment]
@linkel please stick with this issue, it's so close! :tada: thanks for your hard work :) :)

**Comment by jdlrobson** [comment]
@linkel @mekarpeles also I don't think we need to consider this a blocker.. we can merge the existing patch in and continue to work on the flex box on mobile! The patch as it stands is already a huge improvement to this page!

**Comment by linkel** [comment]
I must still be looking at the wrong thing. 

I went to mybooks-list.less again and tried ```@media only screen and (min-width: @width-breakpoint-tablet) and (max-width: 1024px)``` before the css rules and made a copy of the css rules missing the flex: 1 part without the @media specification at the top, and performed the ```make css``` before checking it via docker and there is no difference. 

When you previously said:

> The display flex (provided by the flex mixin) is probably the thing that needs removing.

What exactly is that? If it isn't anything in mixins.less, and it isn't in mybooks-list.less, where else can I take a look?

**Comment by jdlrobson** [comment]
hey @linkel so on the page I'm seeing the following CSS outputted:
```
mybooks {
    border-top: 1px solid #ededed;
    display: -webkit-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    margin-top: 10px;
}
```

When I search (ag "mybooks" [1]) I see that these styles are coming from the huge static/css/legacy.less file!

In there I'm seeing
```
.mybooks {
  border-top: 1px solid @lightest-grey;
  .display-flex();
  margin-top: 10px;
  &-menu {
....
```
If you remove the line ".display-flex();" you'll remove the flex box styles (just as if you remove border-top you'll remove the top border).

We don't exactly want to move this, but at the bottom of that same file you'll see the following
```
@media all and ( min-width: @width-breakpoint-desktop ) {
```
I think you'll want to move the flex styles down to that breakpoint, after running `make css` to build the new css files this should give you the desired result! Ping me on slack if you need any more help!


[1] off topic but I highly recommend [the silver searcher](https://github.com/ggreer/the_silver_searcher) for anyone wanting to search the codebase :)

**Comment by mekarpeles** [comment]
Following the suggestion of https://github.com/internetarchive/openlibrary/pull/1413#issuecomment-435683015 🎉

**Comment by jdlrobson** [comment]
I've asked @hornc if there's a way to make docker watch for changes to the static/build folder so we can run make css js outside of Docker which would be a little more sane.

**Comment by hornc** [comment]
@jdlrobson `docker/docker-compose exec web make css`  would do it directly in one, from outside the container, we could add a shortcut somewhere.

If you know of any standard tools that monitor static/build folders for changes and trigger re-builds we (/I :) ) can make them work in docker, I don't think that this is particular a docker problem (although docker probably makes things more confusing!) There should be commands to achieve pretty much anything you need, and we can make them easier to run if they are frequently used.

**Pull request merged**
