### PR TITLE
Drop unused template list/editions

### PR DESCRIPTION
**Pull request by jdlrobson**
I can't see any pages using this so believe it is dead code. No obvious users on https://openlibrary.org/developers/routes

Defer to @mekarpeles who has the historic knowledge.

### Description

Closes #

### CODE REVIEW

**Comment by mekarpeles** [comment]
Isn't that this, right here?
https://openlibrary.org/people/amorland/lists/OL47026L/Read_in_Browser/editions

**Comment by hornc** [comment]
Huh, this page can be rendered, but does not appear to be linked from anywhere:
Example:
https://openlibrary.org/people/hornc/lists/OL93118L/About_CUP/editions

**Comment by jdlrobson** [comment]
It also throws exceptions on some cases

https://openlibrary.org/people/jdlrobson/lists/OL126798L/Jon's_recommendations/editions

Can it be removed?

**Comment by cdrini** [comment]
The UI displays the word "Activity" here, so I think this is supposed to display activity?
image

@seabelis is this view useful to you? https://openlibrary.org/people/amorland/lists/OL47026L/Read_in_Browser/editions (or add `/editions` to one of your own lists).

It looks like it shows the latest edits on a list (although currently limited to editions). It shouldn't be a lot of work to expand this to show latest edit for authors/works as well, and rename it to `/activity` or something.

**Comment by seabelis** [comment]
No, I don't think that is anything I've seen. I don't see any useful application for it.

**Comment by jdlrobson** [comment]
@cdrini @mekarpeles so I guess we need to delete the python powering this too. @mekarpeles would you mind taking care of that bit?

**Comment by jdlrobson** [comment]
@mekarpeles bump!

**Pull request merged**
