### PR TITLE
Bulk Tagger: Move "Create subject" affordance to bottom of menu options scroll container

### LINKED ISSUE #8652: Bulk Tagger: Move "Create subject" affordance to bottom of menu options scroll container
### Describe the problem that you'd like solved

Our bulk subject tagging tool allows librarians to search for existing tags and create new tags.  The affordance for creating new tags is initially hidden until some text is added to the search input.  When it is visible, it is pinned to the bottom of the bulk tagger, below the scroll container that holds the subject options.

Since all menu options may not be visible on the screen at once, and the "Create subject" affordance is essentially always  present at the bottom of the bulk tagger, it is very easy for librarians to create a subject that is already represented by a menu option.

### Proposal & Constraints

Move the "Create subject" affordance to the bottom of the scroll container which holds the menu options.  This will force people to look at each available menu option before being able to create a new subject, and will hopefully prevent folks from creating a subject that already exists.

Existing visibility rules for the "Create subject" affordance should remain unchanged:  If the subject search input is empty, the affordance should be hidden.

### Additional context

The root element of the "Create subject" affordance has class `create-new-subject-tag`.  This should be moved into the container that has class `selection-container`.

The bulk tagger is rendered client-side by the `renderBulkTagger` function, [here](https://github.com/internetarchive/openlibrary/blob/ecfd0b137b08b76deac027a9e016ecd80e79b791/openlibrary/plugins/openlibrary/js/bulk-tagger/index.js#L6C17-L6C33).

The affordance should look the same after it is moved the the new container.  If any CSS changes are needed, they should be made to [this file](https://github.com/internetarchive/openlibrary/blob/ecfd0b137b08b76deac027a9e016ecd80e79b791/static/css/components/tagging-menu.less).

For reference, the "Create subject" affordance is labeled as "Create Tag Buttons" in the below image:
bt_labeled

### PR DESCRIPTION
**Pull request by QuantuM410**
Closes #8652 

Moved the "Create subject" affordance to the bottom of the scroll container for better visibility and prevention of duplicate subjects.

### Technical

- Moved the "Create subject" affordance to the bottom of the scroll container.
- The functionality of updating and displaying the affordance remains unchanged and doesn't get affected from the following changes in this PR.
- Ensured that the visibility rules remain unchanged: the affordance is hidden when the subject search input is empty.

### Testing

- Search for a subject in bulk tagger component of ILE
- The behavior of displaying create new subject affordance has been updated as per requested whilst ensuring the visibility rules

### Screenshot

https://github.com/internetarchive/openlibrary/assets/85943021/ffbed116-7583-4e26-b4fa-2c4b4722cd38

### Stakeholders

@jimchamp

### CODE REVIEW

**Comment by jimchamp** [comment]
I was expecting the HTML string, [here](https://github.com/internetarchive/openlibrary/blob/033117b3af38270b9fed9f49733c452e9f19d531/openlibrary/plugins/openlibrary/js/bulk-tagger/index.js#L6), to change.  Did that not work?

**Comment by QuantuM410** [comment]
> I was expecting the HTML string, [here](https://github.com/internetarchive/openlibrary/blob/033117b3af38270b9fed9f49733c452e9f19d531/openlibrary/plugins/openlibrary/js/bulk-tagger/index.js#L6), to change. Did that not work?

Yeh I thought of that and that works fine too. The only issue I had with that waswith  its positioning while searching for a subject when it displays content from ```selected-tag-subjects``` or whenever the searched subject is matched with less similar subjects and the number of subjects cant fill the scroll container the ```create-new-subject affordance``` seems to move just below the last displayed subject making it look weird. 
Also once the user scrolls the entire container, even though the affordance is visible it will again hide if he decides to scroll back up making it a bit tedious to scroll down the entire container again. Scrolling once should be enough for him to skim over the existing subjects according to me. 

Here is how it functions with the moved HTML string
 
[screen-capture (1).webm](https://github.com/internetarchive/openlibrary/assets/85943021/d6f8c544-20d9-48da-9852-28c5c113a6d0)

**Comment by QuantuM410** [comment]
@jimchamp Hey! I made the asked changes. It seems the screen recordings I am uploading are facing some encoding issues in firefox browser.

After Updating the HTML string :

https://github.com/internetarchive/openlibrary/assets/85943021/66981e5f-481e-4f2c-a8a7-389264f2d16c







Also my previous solution seems to work on my local system for all cases including typing __"b"__ and others too
Screenshot from 2024-02-22 20-21-45

I preferred it as it allowed the affordance to display over the searched subjects once the user scrolled the entire container instead of disappearing again if user scrolls back again.

**Review by jimchamp — APPROVED** [review]

**Comment by jimchamp** [comment]
> I preferred it as it allowed the affordance to display over the searched subjects once the user scrolled the entire container instead of disappearing again if user scrolls back again.

Whenever you have a choice between implementing code as per the requirements and implementing the code that you prefer, I recommend choosing to implement what is _required_.

**Pull request merged**
