### PR TITLE
Added max-empty-lines and no-eol-whitespace rule

### PR DESCRIPTION
**Pull request by tabshaikh**
Updates #1100

## Description:
In this Pull Request we have made the following changes:
Added max-empty-lines rule and fixed offenders which builds up to completing our white space issue of css.
Added no-eol-whitespace rule and fixed offenders which builds up to completing our white space issue of css.

### CODE REVIEW

**Comment by tabshaikh** [comment]
Ready for merging at @mekarpeles @jdlrobson

**Comment by tabshaikh** [comment]
As the issue #1100  involves a lot of css change independant pull request would be suitable for each change of rule, then if a breakdown occurs it can be easily debugged

**Comment by mekarpeles** [comment]
Lgtm, going to wait for CI to finish running and then will test on dev. Thanks @tabshaikh!

**Comment by tabshaikh** [comment]
Pull request ready, I added one more rule as it was a no-brainer no need for new pull request for that rule

**Comment by jdlrobson** [comment]
W00t!!

**Pull request merged**
