### PR TITLE
Fixed title wrap merge tool

### LINKED ISSUE #9044: Make long title wrap for merge tool
### Problem

Having the title stretch across the whole page when it's long is annoying. It should wrap at some point.

#### Evidence / Screenshot
image

#### Relevant URL(s)
https://openlibrary.org/works/merge?records=OL6030812W,OL31219436W,OL32006641W,OL29342271W

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

### PR DESCRIPTION
**Pull request by Realmbird**
Closes #9044

Adds text wrap to title in merge tool

### Technical

Changes the css inside of the mergetable.vue
Adds "
 white-space: normal;
 word-wrap: break-word;
 overflow-wrap: break-word;
"
for text wrap
adds min-width: 500px; for setting new width of title column can be different width current implementation of text wrap works in firefox where text-wrap is not valid

### Testing

1. docker compose up
Runs view components
2. docker compose run --rm home npm run build-assets
Wait to finish
Adding book
3. docker compose exec -e PYTHONPATH=. web bash -c "./scripts/copydocs.py /works/OL6030812W /works/OL31219436W /works/OL32006641W /works/OL29342271W"
4. Visit http://localhost:8080/works/merge?records=OL6030812W,OL31219436W,OL32006641W,OL29342271W

### Screenshot

Before:
https://private-user-images.githubusercontent.com/921217/320514509-f53fa20a-5362-49ca-adc6-c3781f7f39a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4OTI1ODUsIm5iZiI6MTcxMzg5MjI4NSwicGF0aCI6Ii85MjEyMTcvMzIwNTE0NTA5LWY1M2ZhMjBhLTUzNjItNDljYS1hZGM2LWMzNzgxZjdmMzlhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxNzExMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDc3MzdiMmNlODljOWE3NmNlZWRhMGRkMDMxZjIyMzNhOWJhOThkODZjZDVlMTIyMDViNTRhOGJjZTRhZmQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d7FlqCIKWXgpXyCifRbXhMlzMML3KjQOhvKQ-gUgg-M
Now:
Screenshot from 2024-04-23 10-15-30

### Stakeholders
@RayBB

### CODE REVIEW

**Comment by RayBB** [comment]
@Realmbird it looks like @mheiman is the lead on this one so I think he'll do the review.

**Comment by Realmbird** [comment]
Ok

**Review by jimchamp — APPROVED** [review]
This looks good to me.  Thanks, @Realmbird!

**Comment by Realmbird** [comment]
Recreated problem
Screenshot from 2024-05-21 12-33-11

**Comment by Realmbird** [comment]
docker compose exec -e PYTHONPATH=. web bash -c "./scripts/copydocs.py /works/OL21868175W /works/OL41495W"

**Pull request merged**
