### PR TITLE
Delete ./openlibrary/core/connections.py

### LINKED ISSUE #1278: ./openlibrary/core/connections.py needs a code review
There are a series of at least three syntax errors in ./openlibrary/core/connections.py that can be found by doing:
* __flake8 ./openlibrary/core/connections.py --show-source --select=E901,E999,F821,F822,F823__. 
 
The first syntax error can be solved merely by adding a __pass__ statement but the ones that follow seem to be more complex to resolve.

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #1278.  As discussed in #1278 the two classes defined in this file do not appear to be used elsewhere in this repo.

Closes #1278

<Optional Picture>

## Description:
In this Pull Request we have made the following changes:
* Delete ./openlibrary/core/connections.py

### CODE REVIEW

**Comment by cclauss** [comment]
@tfmorris @mekarpeles Your reviews please.

**Comment by mekarpeles** [comment]
Isn't 

```
# setup special connection with caching support
import connection
client._connection_types['ol'] = connection.OLConnection
infogami.config.infobase_parameters = dict(type="ol")
```

happening right in `plugins/openlibrary/code.py`?

**Comment by cclauss** [comment]
Yeah but...  Isn’t that just going to _relative_ import of [__plugins/openlibrary/connection.py__](
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/connection.py) which _also_ defines __ConnectionMiddleware__.  That `connection.py` file is in much better shape that the one that this PR proposes deleting.

**Comment by cclauss** [comment]
Doh! One file is connections.py (plural, with a trailing s) and the other is connection.py (singular).  That would indicate that this PR is in the right path.

**Comment by mekarpeles** [comment]
These changes lgtm, I'd appreciate a 2nd pair of eyes from either @tfmorris or @hornc 
Thank you @cclauss for the explanation re: the duplicated `ConnectionMiddleware`

**Comment by mekarpeles** [comment]
reminder to self: Let's test this today @mekarpeles :)

**Comment by mekarpeles** [comment]
connections.py was removed in #1277. The relative import path changes LGTM

**Pull request merged**
