### PR TITLE
Long term solution to CSS minification

### PR DESCRIPTION
**Pull request by jdlrobson**
It's a long time coming! Let's do the simplest possible thing but don't use outdated and unsupported dependencies so we don't see those pesky deprecation notices.

This will require another global install, so I've added that to the Makefile for next deployment.

Fixes: #1123

### CODE REVIEW

**Comment by cdrini** [comment]
I don't like that we're doing a global install inside our makefile; all that stuff should be in the dockerfile. Actually, it would be easier if we use `npx` to access `less` did that here: https://github.com/jdlrobson/openlibrary/pull/2

**Comment by cdrini** [comment]
(doing it this way means we won't need a special deploy plan either :+1:)

**Comment by cclauss** [comment]
Would #2606 help us to keep these kind of dependencies updated or is it unrelated?

**Comment by cdrini** [comment]
@cclauss mostly unrelated to this specific PR (except that it introduces a dependency); I commented on your PR :+1:

**Pull request merged**
