### PR TITLE
WIP: Remove unused JS in lazy.js

### PR DESCRIPTION
**Pull request by jdlrobson**
All the external libraries inside lazy.js are unused in both
templates and JS. Let's remove them.

Changes:
* .hoverIntent not invoked anwywhere inside openlibrary directory
* No usages of .scrollTo, .highlight, .columnize, .jTruncate or
DataTable (https://www.datatables.net/)

Fixes: #1742

> **Description**: What does this PR achieve? [feature|hotfix|refactor]

Closes #

> **Technical**: What should be noted about the implementation?

> **Testing**: Steps for reviewer to reproduce / verify this PR fixes the problem?

> **Evidence**: If this PR touches UI, please post evidence (screenshot) of it behaving correctly:

### CODE REVIEW

**Comment by mekarpeles** [comment]
are none of these active on the works page/table? I'll pull and test

**Comment by jdlrobson** [comment]
I think the dataTables may be being used on https://openlibrary.org/works/OL17906005W/Just_one_touch?debug=true, I just don't know how.. Part of the problem with many of these jQuery plugins is they operate when classes exist, which is great for integration and adding features but not so good for maintenance. Will take a look later this week

**Comment by mekarpeles** [comment]
@jdlrobson any news on this PR?

**Comment by jdlrobson** [comment]
My problem is I don't know where and how these are being used so I can't be 100% sure pulling them won't break something.

Haven't had time to dig more into these libraries and how they work :/

**Comment by jdlrobson** [comment]
Slowly picking this up again 7 months later - https://github.com/internetarchive/openlibrary/pull/2238 is the beginning of a more conservative approach. Keeping this open as a reminder to me of what is possible.

**Comment by mekarpeles** [comment]
@jdlrobson I'm going to close this for now as I believe lazy.js is being used on the works page (for the table)

**Pull request closed without merging**
