### PR TITLE
Unavailable color contrast

### PR DESCRIPTION
**Pull request by bpmcneilly**
This PR updates the 'Join Waitlist' (`class="cta-btn--unavailable"`) & a few other related classes to ensure that they have sufficient color contrast.

### Technical
The current colors involve `@white` text (`#ffffff`) on an `@orange` background (`#ffa238`). These two colors form a color contrast ratio of 2.004:1, which is below the 4.5:1 needed for normal sized text.

This PR updates the background colors for a few of the "waitlist" or "unavailable" content to appear in the existing `@red` less variable. Using this color, (`#de351b`) will have a contrast ratio of 4.534:1. On occasion the darker shade `@dark-red` (`#bf3722`) was used, and this creates a contrast ratio of 5.548:1.

The biggest issue with this PR is the visually breaking nature of the color change. In researching other colors that would create a sufficient color contrast ratio with the white (`#ffffff`) text, fairly few colors appeared as options. A few alternatives included the very similar red-orange `#c44536`, the more burgundy `#a30b37` and the purple-ish `#8e5572`. Unfortunately, orange on white just tends to be a very low color contrast combination. To use a hue similar to what we already had, we'd need something like `#995c16`. As such I think it's best to stick with colors we've previously defined.

### Testing

1. Locate a book that is unavailable or otherwise unused
    1. Alternatively, take a book with `class="cta-btn cta-btn--available cta-btn--read"`
    2. Update the class list to be `class="cta-btn cta-btn--unavailable cta-btn--read"
2. Verify the color contrast ratio using the color contrast tool of choice

### Screenshot
a read button that has had the class "cta-btn--unvailable" and the "cta-btn__bade" manually applied

### Stakeholders
@mekarpeles

### CODE REVIEW

**Review by jdlrobson — APPROVED** [review]

**Comment by cdrini** [comment]
Preparing for a deploy, and this is just too red for me 😅 Makes the button look dangerous, like "Delete all files?" or something. Let's explore some of @bpmcneilly 's other options 👍

Sorry for the runaround, meant to comment on this earlier but it fell off my radar.

**Comment by cdrini** [comment]
If you come up with a few options, that would help. Options I can think off:

1) Make the text not white; maybe a dark orange? And make the background a lighter orange?
2) Make the button into a shell button (like the preview button)
3) Try some more colors, like the burgundy/purple you mentioned. Playing around with some of yours, this one looks nice: `#CB437C`:
image

**Comment by bpmcneilly** [comment]
Ok, I had a little fun with this & came up with 6 options (all displayed alongside a standard "borrow" button in the below image). The table that follows includes the hex values, a 'name' for the color / design, and the color contrast ratio.

a grid of 6 join waitlist & borrow buttons, numbered per the table below

ID	|	Hex Value	|	Name			|	Contrast Ratio
----|---------------|-------------------|-----------------
1	|	`#9C528B`	|	Raspberry		|	5.25:1
2	|	`#820933`	|	Wine			|	10.31:1
3	|	`#C74405`	|	Burnt Sienna	|	4.93:1
4	|	`#214E34`	|	Hunter Green	|	9.52:1
5	|	`#36382E`	|	Wildcard (text)	|	5.92:1
6	|	`#820933`	|	Wildcard (shell)|	8.16:1

I agree I think the red/burgundy tones appeal most to my eye. The shell styling definitely drew my attention (even more so using the default white background), but I'm not necessarily sure that's a good thing. Similarly, darkening the text color to ensure if has sufficient color contrast makes a marked difference with the borrow buttons. Not my cup of tea, but I'm curious what other folks think!

**Comment by cdrini** [comment]
Awesome, thank you @bpmcneilly ! That helps a ton :)
I discussed it with @pezvi on a call, and we like the burnt sienna because it seems to fit the existing colour scheme a little better. Note we both really like the wine colour in general, but that might just be by association :D So Sienna it is! Don't forget to also update the hover color (although that might happen automatically).

**Pull request merged**
