### PR TITLE
Add no-useless-escape rule to eslint

### LINKED ISSUE #1421: Eslint: no-useless-escape
We have eslint linting for our JS. Let's add a rule for [no-useless-escape](https://eslint.org/docs/rules/) for consistency.

- [ ] Add the rule no-useless-escape to .eslintrc.json 
- [ ] Run npm run lint:js and fix all offenders

### PR DESCRIPTION
**Pull request by waghcwb**
Closes #1421

## Description:
This PR adds no-useless-escape rule to eslint config and fixes corresponding issues.

### CODE REVIEW

**Comment by waghcwb** [comment]
@jdlrobson,

I noticed that. But since I'm new to the project I did not question. Another thing that I noticed is that this `lazy.js` has a lot of "vendor" libs.

- jQuery.ScrollTo
- hoverIntent
- jquery.dataTables
- and more..

What you think about implementing a module bundler (webpack for example) for the front-end files?

**Comment by jdlrobson** [comment]
Yep no worries  @waghcwb  i am quite new to so this activity is teaching me a lot :)

Yup we definitely need a bundler. I think webpack is a bit heavy weight for what we need and something more straightforward like rollup might be better but i haven't had much time to think about this as I've been mostly focusing on the css. 

The main blocker for doing this will be getting the deploy and CI scripts working. Please feel free to be bold and make pull requests and open issues/ask in slack to find out which bundle tools people feel comfortable with if it's something that interests you!

**Comment by mekarpeles** [comment]
Not sure about lazy.js, maybe it should indeed be moved to vendor. These changes all look right to me

**Comment by waghcwb** [comment]
I'm working on it. :squirrel:

:construction: I'm building a frontend config with rollup (first time I'm working with it :hear_no_evil:), soon I can open a pull-request with my modifications. 

As I can see, the `Makefile` on the root of the project is building the frontend files.

Here
```
js:
	mkdir -p $(BUILD)
	bash static/js/vendor.jsh > $(BUILD)/vendor.js
	bash static/js/vendor.jsh 2 > $(BUILD)/vendor-v2.js
	bash static/js/all.jsh > $(BUILD)/all.js
```

And here
```
css:
	mkdir -p $(BUILD)
	lessc -x static/css/page-admin.less $(BUILD)/page-admin.css
	lessc -x static/css/page-edit.less $(BUILD)/page-edit.css
	lessc -x static/css/page-form.less $(BUILD)/page-form.css
	lessc -x static/css/page-home.less $(BUILD)/page-home.css
	lessc -x static/css/page-plain.less $(BUILD)/page-plain.css
	lessc -x static/css/page-user.less $(BUILD)/page-user.css
	lessc -x static/css/js-all.less $(BUILD)/js-all.css
	lessc -x static/css/page-book-widget.less $(BUILD)/page-book-widget.css
	lessc -x static/css/page-design.less $(BUILD)/page-design.css
	lessc -x static/css/page-dev.less $(BUILD)/page-dev.css
```

Am I right or there are other config files for deploy and CI??

**Comment by jdlrobson** [comment]
@waghcwb let's get this existing patch rebased and merged!
The roll up changes should be on a separate branch as I expect we'll have lots to think about there!

**Comment by waghcwb** [comment]
@jdlrobson,

Sorry, I'm not comfortable with rebase, and today I will not have time to do it. I can make this later, okay? Then I will open a new branch with the discussion about rollup.

**Comment by jdlrobson** [comment]
See also #1460

**Comment by mekarpeles** [comment]
this looks good, thanks!

**Pull request merged**
