### PR TITLE
WIP: Migrate subject page to v2 (slick, mobile friendly)

### LINKED ISSUE #1207: Migrate subject page to v2
We will upgrade all our major pages to v2 of the template.

Upgrading has various benefits
- serves non-render blocking JavaScript
- more modern version of jQuery
- more mobile friendly
- potential for slimmer render blocking CSS

The home page has currently been migrated.

This task tracks migrating subject pages
https://openlibrary.org/subjects/fantasy
https://openlibrary.org/subjects

A page can be considered migrated when #test-body-mobile is present in the HTML and the page is bug free.

### PR DESCRIPTION
**Pull request by jdlrobson**
Please merge ~~#1233, #1239~~ and #1260 first before this one!!

Closes #1207

This migrates the subject pages to use v2 where
* js is not render blocking
* slick carousels replace jcarousels
* mobile friendliness!!!
* better non-js support

Note, once merged I plan follow ups to 
* clean up the CSS on this page
* improve non-js display

### CODE REVIEW

**Comment by mekarpeles** [comment]
@jdlrobson I think there's 2 easy conflicts which need to be resolved (I think the right one is the js being split into v1, v2. For the css change, I think it's the version which includes `white-space: nowrap;`)

**Comment by jdlrobson** [comment]
Yup I know. I'd like to see #1233 and #1239 land first before resolving this one!

**Comment by jdlrobson** [comment]
and now we are ready for review :)

I present you with a pretty mobile optimised subject page using slick carousels.

**Comment by mekarpeles** [comment]
When I run from dev.openlibrary.org, I'm seeing:
```
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/infogami/utils/template.py", line 146, in saferender
    result = t(*a, **kw)
  File "/opt/openlibrary/venv/local/lib/python2.7/site-packages/web/template.py", line 868, in __call__
    return BaseTemplate.__call__(self, *a, **kw)
  File "/opt/openlibrary/venv/local/lib/python2.7/site-packages/web/template.py", line 781, in __call__
    return self._join_output(out)
  File "/opt/openlibrary/venv/local/lib/python2.7/site-packages/web/template.py", line 787, in _join_output
    for name, value in out:
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/templates/books/custom_carousel.html", line 32, in __template__
    $ cta_url = "/books/%/x/borrow"%book.get('lending_edition')
```

**Comment by mekarpeles** [comment]
Looks like there's a missing `s` in `%s` on line 32

**Comment by mekarpeles** [comment]
Seeing inconsistent messaging: `Borrow this book`, `Read online` -- should be
`Read eBook` or `Borrow eBook` (not a regression)

**Comment by mekarpeles** [comment]
bookcovers not appearing

**Comment by mekarpeles** [comment]
Also, `ebooks` v. `works` js links no longer facet the results. And results no longer lazily load

**Comment by jdlrobson** [comment]
Will look into this once i have a fix for #1258

**Comment by jdlrobson** [comment]
Lazy loading will happen with #1171

Do you consider that a blocker for this?

**Comment by jdlrobson** [comment]
I think this should be fixed and ready for review now, but please review #1260 first.

I've added more logic for the covers and that seems to be working locally for me.
I can't test borrow buttons locally, but I've been careful to copy across the logic, so please be careful when reviewing that.

**Comment by jdlrobson** [comment]
I can't test this locally.. but can we verify the sorting ("Sort by: # of Editions ") still works? If not, any JS errors thrown?

**Comment by mekarpeles** [comment]
It only seems to load 2 sets of 5 at a time :)

**Comment by jdlrobson** [comment]
superseded by https://github.com/internetarchive/openlibrary/pull/1542

**Pull request closed without merging**
