### PR TITLE
Addresses #605: replace google fonts dependency (to avoid 3rd party IP tracking)

### PR DESCRIPTION
**Pull request by Daniel-GabrielN**
#605 replace google fonts dependency

### CODE REVIEW

**Comment by mekarpeles** [comment]
Thanks for the fix @Daniel-GabrielN! Any reason we wouldn't want to serve this file directly from OpenLibrary (as opposed to github)?

**Comment by Daniel-GabrielN** [comment]
@mekarpeles you are right, should I add the font to folder ```https://github.com/internetarchive/openlibrary/tree/master/static/fonts``` and reference it from there?

**Comment by mekarpeles** [comment]
@Daniel-GabrielN sounds fantastic to me! Looking forward to merging your changes in :)

**Comment by Daniel-GabrielN** [comment]
@mekarpeles I'm not sure about the static path

**Comment by mekarpeles** [comment]
@Daniel-GabrielN checking momentarily -- thank you for following up on this!

**Comment by cdrini** [comment]
Do note that it's a bit more work to import a font; the syntax above is for importing a CSS stylesheet.

Out of curiosity, why do you want to stop using the Google Fonts link, @mekarpeles ?

**Comment by mekarpeles** [comment]
/static/fonts should be static/fonts -- and yes we'll need both the stylesheet (e.g. https://fonts.googleapis.com/css?family=Poppins:100,300,500,700 as well as the fonts, e.g. ttf and woff2)

@cdrini I suppose the goal when created was to avoid dependencies on google, but given it's just loading a stylesheet/font perhaps its not a big deal.

**Comment by cdrini** [comment]
Yeah, it might be easier to maintain if we keep the Google Fonts link, because it looks like it's doing a lot of work under the hood.

Thanks for your help though, @Daniel-GabrielN ! I hope your Hacktober has been going well :)

**Comment by Daniel-GabrielN** [comment]
no worries @cdrini , @mekarpeles 
thanks for your patience

**Comment by bfalling** [comment]
@cdrini: We avoid all 3rd party embeds not so much for the fact of dependency as for the potential privacy abuse. If a page in a browser calls out to a 3rd party embed -- like a JS, CSS, font, or image files -- we've just exposed that user's IP address and other info to the 3rd party.

**Comment by mekarpeles** [comment]
That being the case, the solution seems to be to wget over the stylesheet, pull the woff2's and rename the fonts sanely with respect to openlibrary static/fonts paths

**Comment by mekarpeles** [comment]
Tagging as something which can be pushed across the finish line at this weekend's hackathon: #603

**Comment by Daniel-GabrielN** [comment]
@mekarpeles should I try and do that on this pr?

**Comment by mekarpeles** [comment]
You're welcome to! I tried working off your branch and adding some of these changes and ran out of time :)
I'm happy to help as well, especially w/ questions. Thanks!

**Comment by cdrini** [comment]
@bfalling I didn't think of that! That's a fair point. I don't think IPs are uniquely identifying, especially since (I think) dynamic IPs are more common, so I'm not sure if this qualifies as a privacy intrusion of the user. Also note that Google fonts is also not on the `google.com` domain, so it can't use Google's cookies to link the user to a Google account. But, to each their own :)

**Comment by bfalling** [comment]
@cdrini: Re: privacy... The key is not what they currently do, but what they could do. Or what they could be forced to do/reveal by an outside agency or if hacked. And IP addresses *can* be identifying, depending on the network context. So, at IA, we try to stay clean and not knowingly pass along user info to others in the first place.

**Comment by mekarpeles** [comment]
Poppins removed as a dependency, simplest solution.

**Pull request closed without merging**
