### PR TITLE
Update to Node.js 16.x LTS

### LINKED ISSUE #5282: Update to Node 16
Update Node to latest version, Node 16. This isn't LTS yet, but will be in October.

### Stakeholders

@cdrini , @jamesachamp

### PR DESCRIPTION
**Pull request by jimman2003**
security, npm 7/8 improvments, speed , no breaking changes... See https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md for a more detailed changelog

Closes #5282

### Technical

new  node.js , shouldn't break anything
### Testing

Verify everything in JS runs correctly
### Stakeholders

@cdrini

### CODE REVIEW

**Comment by mekarpeles** [comment]
@cdrini mentioned we may need to rebase for precommit hook

**Comment by jimman2003** [comment]
Done!

**Comment by cdrini** [comment]
@jimman2003 Can you do a search for node elsewhere in the codebase? I think the github work flow also needs to be updated to use v16

**Comment by cdrini** [comment]
(Sorry for the messy history :P I'm going to squash these into 1 commit before merging)

**Review by cdrini — APPROVED** [review]
Phew! That took a while. I updated node on our ol-dev server as well, and confirmed that it builds correctly, and the homepage JS/css + Library Explorer work.

**Pull request merged**
