### PR TITLE
DRAFT: Use FastAPI to put asyncio shims on top of OL API calls

### PR DESCRIPTION
**Pull request by cclauss**
Related to #5590
Related to #5910
Related to #5914

DRAFT: Do not merge.

NOTE: `FastAPI/main.py.disabled` --> `FastAPI/main.py` after [FastAPI](https://fastapi.tiangolo.com/) is added to our requirements.

Use FastAPI to put a Python asyncio shim on top of calls to https://openlibrary.org.

Why?
* Start experimenting with asyncio for our API responses.
* Auto-creates OpenAPI (Swagger) docs including "Try it out" mode.
* Auto-validates both inputs and outputs against json schemas with Pydantic.
```
mkdir fastapi_hack
cd fastapi_hack
python3.9 -m venv .venv
source .venv/bin/activate
pip install --upgrade pip
pip install "fastapi[all]"
```
Put the contents of `main.py.disabled` into `main.py`
```
uvicorn main:app --reload
```
This starts an asyncio-based webserver that will auto-reload as changes are saved to `main.py`.

Try:
* http://127.0.0.1:8000/books/OL7353617M
* Other URLs in the comments in `main.py`
* http://127.0.0.1:8000/docs for Swagger docs with _Try it out_ mode.
* http://127.0.0.1:8000/redoc for auto-generated API docs

### Testing

See comments at the top of `FastAPI/test_fastapi_hack.py.disabled`

Also, when the uvicorn server is running go to http://127.0.0.1:8000/docs and do _Try it out_ under various endpoints.

### Screenshot

__Autogenerated content:__
---
# http://127.0.0.1:8000/docs
Screenshot 2021-11-22 at 16 39 59
---
---
FastAPI_2
---
---
# http://127.0.0.1:8000/redoc
Screenshot 2021-11-22 at 21 11 09

### Stakeholders

@bennypowers

### CODE REVIEW

**Comment by RayBB** [comment]
Won't have time to check it out this week but I've been thinking about making OpenAPI docs forever and this would be fantastic! May also expose some inconsistencies in our APIs (like when we return 400 txt responses instead of json)

**Comment by bennypowers** [comment]
Yeah this is 🔥 

We can use this to generate a graphQL api using [graphql mesh](https://www.graphql-mesh.com/)

From there I want to both vend ready-made GraphQL-querying custom elements and create a PWA for library builders using [Apollo Elements](https://apolloelements.dev)

**Comment by cclauss** [comment]
- FastAPI
    - Demo is awesome
    - Maybe a first value-yielding step might be to try to use FastAPI+friends to generate a static html/js site for the docs, which we then server from Open Library? We would the pydantic error messages though.
    - Other thoughts/concerns:
        - fastapi functions are kind of duplicates of the webpy ones ; can we codegen or bring them closer?
        - How to add more docs/helpful context to parameters, functions, etc ;
        - Can we use pydantic in some way to improve the API experience, without getting all of fastapi? Similar to how we did for imports?

**Comment by cclauss** [comment]
Put this code at the bottom of [`openlibrary/plugins/openlibrary/api.py`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/api.py) and then make minor modification and add docstrings.
```
fmt = """
@app.get("{path}")
async def {classname}_get(olid, limit: Optional[int] = None) -> str:{doc}
    return requests.get("https://openlibrary.org{path}.json", params=locals()).json()
"""


def to_docstring(s: str) -> str:
    s = (s or "").replace(" " * 8, " " * 4)  # dedent
    return f'\n    """{s}"""' if s.strip() else ""


def webpy_to_fastapi(cls) -> str:
    if cls is delegate_page:  # Only needed in test file.
        return ""
    if not issubclass(cls, delegate_page):
        return ""
    get = getattr(cls, "GET", getattr(cls, "get", None))
    if not get:
        return ""
    d = {
        "path": cls.path,
        "classname": cls.__name__,
        "doc": to_docstring(get.__doc__),
    }
    return fmt.format(**d)


if __name__ == "__main__":
    print("Start")
    generated = {
        classname: webpy_to_fastapi(cls)
        for classname, cls in inspect.getmembers(sys.modules[__name__], inspect.isclass)
    }
    for code in generated.values():
        if code:
            print(code)
    print("Finish")
```
### Generated code:
```
Start

@app.get("/_tools/amazon_search")
async def amazon_search_api_get(olid, limit: Optional[int] = None) -> str:
    """
    This function is amazon_search_api.get()
    """
    return requests.get("https://openlibrary.org/_tools/amazon_search.json", params=locals()).json()


@app.get("/availability/v2")
async def book_availability_get(olid, limit: Optional[int] = None) -> str:
    """
    This function is book_availability.get()
    """
    return requests.get("https://openlibrary.org/availability/v2.json", params=locals()).json()


@app.get("/browse")
async def browse_get(olid, limit: Optional[int] = None) -> str:
    """
    This function is browse.get()
    """
    return requests.get("https://openlibrary.org/browse.json", params=locals()).json()


@app.get("/works/OL(\d+)W/observations")
async def patrons_observations_get(olid, limit: Optional[int] = None) -> str:
    """
    This function is class patrons_observations.get()
    """
    return requests.get("https://openlibrary.org/works/OL(\d+)W/observations.json", params=locals()).json()


@app.get("/prices")
async def price_api_get(olid, limit: Optional[int] = None) -> str:
    """
    This function is price_api.get()
    """
    return requests.get("https://openlibrary.org/prices.json", params=locals()).json()


@app.get("/observations")
async def public_observations_get(olid, limit: Optional[int] = None) -> str:
    """
    This function is class public_observations.get()
    """
    return requests.get("https://openlibrary.org/observations.json", params=locals()).json()


@app.get("/sponsorship/eligibility/(.*)")
async def sponsorship_eligibility_check_get(olid, limit: Optional[int] = None) -> str:
    """
    This function is sponsorship_eligibility_check.get()
    """
    return requests.get("https://openlibrary.org/sponsorship/eligibility/(.*).json", params=locals()).json()


@app.get("/works/OL(\d+)W/bookshelves")
async def work_bookshelves_get(olid, limit: Optional[int] = None) -> str:
    """
    This function is work_bookshelves.get()
    """
    return requests.get("https://openlibrary.org/works/OL(\d+)W/bookshelves.json", params=locals()).json()


@app.get("(/works/OL\d+W)/editions")
async def work_editions_get(olid, limit: Optional[int] = None) -> str:
    """
    This function is work_editions.get()
    """
    return requests.get("https://openlibrary.org(/works/OL\d+W)/editions.json", params=locals()).json()

Finish
```

**Comment by cclauss** [comment]
This is nasty regex clutter... `@app.get("(/authors/OL\d+A)/works")`

Would it break things if we _manually_ transform it to `/authors/(OL\d+A)/works`?

**Comment by cclauss** [comment]
I updated the [code above](https://github.com/internetarchive/openlibrary/pull/5898#issuecomment-980525459) to add type hints, doctests, and passing of `locals()` only when there are query parameters.

**Comment by cclauss** [comment]
* #4467

**Comment by cclauss** [comment]
Closing in favor of #5910 which automates the code generation.

**Pull request closed without merging**
