### PR TITLE
Remove unused type page templates

### PR DESCRIPTION
**Pull request by jdlrobson**
These do not seem to be accessible via any of the routes on /developers/routes, nor can I see any page that renders them.

Closes #

### CODE REVIEW

**Comment by mekarpeles** [comment]
@jdlrobson all docs in /templates/type are powered by infogami types. Works, Editions, Authors are magically powered by virtue of those underlying types existing. Each type has a `view.html` associated with it (not referenced explicitly by openlibrary code). Those definitely need to stay.

**Comment by mekarpeles** [comment]
I think all the files mentioned are relevant. I'm not the expert on which of those i18n files may be deprecated for other reasons. Will let @tfmorris + @hornc weigh in, but for now I am going to close this PR and expect that cleaning up i18n will be a separate PR which removes specfic i18n files because of their merits (not because they sneakily appear unused)

**Comment by jdlrobson** [comment]
Are there uris associated with these pages? If so how do I set those up/view them? If we keep them I need to understand how to test and preserve them. Lemme know so I can add them to my testing list..

**Comment by cdrini** [comment]
In ~general, `/type` templates are used wherever a type is rendered. For example, https://openlibrary.org/works/OL19710804W.json has `/type/work`, so there should be a template `/type/work/view` for viewing the work, and `/type/work/edit` for editing the work. This is true for all types; `type:edition`, `type: list`, etc.

Although I think there is something funny with our work/edition templates; I think there are 2 editions templates, one of which is unused. But I'm not 100% sure.

**Pull request closed without merging**
