### PR TITLE
Remove legacy Python from requirements*.txt and Docker

### PR DESCRIPTION
**Pull request by cclauss**
Closes #
Subtask of #4384
Blocked by ~#4385, #4324~, #4383

Remove Python 2 from our .python-version, requirements*.txt, and Docker files.

Also upgrades Python 3.9.0 to 3.9.1 based on the new pyenv release https://github.com/pyenv/pyenv/blob/master/CHANGELOG.md.  Py3.9.1 is the first Python that defaults to 64-bit on Windows and also natively supports Apple Silicon M1 CPUs.  The only way to enable Python 3.9 is by setting the `$PYENV_VERSION` environment variable.

### CODE REVIEW

**Comment by cdrini** [comment]
As the issue states, this is blocked by #4324 and #4383 since we still have py2 code in production.

**Comment by cdrini** [comment]
I think we're good to make progress on this :) #4383 is largely completed, and all these pythons slow down our builds/processes. Can you rebase/update, @cclauss ?

**Review by cdrini — COMMENTED** [review]
Still need to test, but this looks good so far! Woohoo!

**Review by cdrini — APPROVED** [review]
Tried a few times to build olbase locally but it was just too slow :P Code lgtm; this shouldn't affect any dev environments. Hello future!

**Comment by cclauss** [comment]
`docker build -t openlibrary/olbase:latest -f docker/Dockerfile.olbase . #` runs in 15 minutes, 4 seconds on an M1 Mac.

**Comment by cdrini** [comment]
I gave up after 45 min :P i think I have too many files or something which is slowing it down.

**Pull request merged**
