### PR TITLE
Made styles of tabs on trending page same as search page.

### LINKED ISSUE #8702: Tabs on Trending page should have same style as those on search page
### Describe the problem that you'd like solved

Trending page:
image

Search page:
image

### Proposal & Constraints
Use the same css structure/classes as the `nav-bar` on the search page.

### Additional context
HTML for the trending page:

https://github.com/internetarchive/openlibrary/blob/5b23175235d15bf6f3e6aec6b7a1a4e72500d174/openlibrary/templates/trending.html

HTML for the search page:

https://github.com/internetarchive/openlibrary/blob/acb61b0a4c0af06596bafba01fce13ed1775c4cb/openlibrary/macros/SearchNavigation.html

### PR DESCRIPTION
**Pull request by Ayush1404**
Added nav-bar class just like in the searching page to make the menu appear exactly as the searching page.Fixes #8702

Closes #8702 

Changes styles of tabs on the trending page to appear same as same as the search page. 

### Technical

nav-bar class is used just like in the searching page.
### Testing

Visit http://localhost:8080/trending/now on local deployment to see the changes and test them out.
### Screenshot

Before:
image
After:
image
### Stakeholders

@cdrini

### CODE REVIEW

**Review by cdrini — CHANGES_REQUESTED** [review]
@Ayush1404 your original changes look correct, but I believe you accidentally pushed up another commit? `Create unassign_inactive_contributors.py` should not be part of the PR.

**Comment by Ayush1404** [comment]
Hey very sorry that I did that, I am a little new to this.I have commited with removed file now, is it okay?

**Comment by Ayush1404** [comment]
Sorry i am a little new to this so i did some mistakes but it should be fine now will be happy to know from you tho

**Review by cdrini — APPROVED** [review]
Lgtm! Tested on testing and works correctly.

**Pull request merged**
