### PR TITLE
move currently used sitemap script out of archive

### LINKED ISSUE #2276: consider moving sitemap script to root scripts dir
### Is your feature request related to a problem? Please describe.

The currently used sitemaps script lives in https://github.com/internetarchive/openlibrary/tree/master/scripts/2009/01/sitemaps

Which looks like an archived script. 

### Describe the solution you'd like

Suggestion: create openlibrary/scripts/sitemaps and move the currently used scripts there.

### PR DESCRIPTION
**Pull request by hornc**
closes #2276

### Description

Moves the sitemap script into a more prominent location.

### Technical

@mekarpeles I have made a corresponding change to olsystem in the cron job script that triggers this. Could please review both changes and only merge when we have a clear plan for deployment to production?

### CODE REVIEW

**Comment by cdrini** [comment]
`scripts/2009/01/sitemaps/index.py → scripts/2009/01/index.py`
Was this on purpose? Should this of have been moved to `scripts/sitemaps`, or is `index.py` unused?

**Comment by cdrini** [comment]
Assigning this to @mekarpeles , since I think he's the only one who can merge this.

**Comment by hornc** [comment]
@cdrini yes, leaving the index script in an archive location was deliberate. Initially I thought it was called by the sitemap script, but they are independent.

 I can't find anywhere it is used. It appears to be generating an HTML index to the site -- I'm not aware of anything that wants an HTML index, and would hope the sitemap is sufficient for all out current indexing and mapping requirements.

**Comment by cdrini** [comment]
Ok, looks like it's unused; it's actually got syntax errors, so it doesn't even parse :P
image

**Comment by hornc** [comment]
Yuck, that index file was worse that I realised :) Archiving without fixing I think is the way to go, there is enough features to work on. Archived scripts are to be treated with caution, which is why it is important to move the known useful and current sitemaps script _out_ of that location!

I've fixed the one print statement, good catch @cdrini ! Should be good to go now.

**Pull request merged**
