### PR TITLE
Python Unused Imports removed from code.py

### LINKED ISSUE #3483: Investigate Python Unused Imports
There are [a lot](https://lgtm.com/query/7596990423930761565/) of unused imports which clutter things.

### Describe the problem that you'd like solved

Refactoring to remove all unused imports.

### Proposal & Constraints

Remove all ununsed imports. This will reduce technical debt, decluttering things to make them clearer.

### Additional context

UPDATE:
As per @cclauss's comments below, for detecting unused imports, we should really be running
```
python3 -m pip install flake8
flake8 --select=F401
```

### Stakeholders

@cclauss @imskr

### PR DESCRIPTION
**Pull request by soham4abc**
Closes #3483 

### Technical
`memcache` import removed from code.py as it is not accessed. 

### Stakeholders
@teymour-aldridge

### CODE REVIEW

**Comment by mekarpeles** [comment]
@dhruvmanila can you take a look? I'll offer a review as well and merge if we think things look good. Ty @soham4abc for this contribution!

**Comment by soham4abc** [comment]
> @dhruvmanila can you take a look? I'll offer a review as well and merge if we think things look good. Ty @soham4abc for this contribution!

Please do let me know if any changes are required!

**Comment by soham4abc** [comment]
@dhruvmanila  Please do review the code!

**Review by dhruvmanila — APPROVED** [review]
I can confirm this is not being used in the module. LGTM!

**Comment by dhruvmanila** [comment]
Hi, @mekarpeles can you restart the Python tests? It seems to be failing for some unknown reason but its passing in the recent PRs.

**Comment by jimman2003** [comment]
the apt ppa seem to have problems..

**Comment by soham4abc** [comment]
Do I need to make any changes? @jimman2003  @dhruvmanila

**Comment by jimman2003** [comment]
I don't think so

**Comment by soham4abc** [comment]
> I don't think so

Thank you! If required pls do let me know!!

**Comment by soham4abc** [comment]
Can anyone re-run the tests?

**Comment by jimman2003** [comment]
You should probably wait until the transition to focal..

**Comment by soham4abc** [comment]
> You should probably wait until the transition to focal..

Does this PR need any changes?

**Comment by jimman2003** [comment]
No, I think 
CI still stuck

**Comment by soham4abc** [comment]
@jimman2003  I guess this PR has no more issues as it has passed all the checks!

**Comment by jimman2003** [comment]
Yep!

**Comment by soham4abc** [comment]
@dhruvmanila  Please have a look. If possible then do merge at your convenience!

**Comment by dhruvmanila** [comment]
I cannot merge :)

The PR looks good to me!

**Comment by soham4abc** [comment]
> I cannot merge :)
> 
> The PR looks good to me!

maybe someone you know who can merge :-)

**Comment by soham4abc** [comment]
@dhruvmanila  Can you pls bring this PR some attention from the people who currently have write access.

**Comment by soham4abc** [comment]
@dhruvmanila @cdrini Any updates or any changes required to this PR?

**Comment by soham4abc** [comment]
@cdrini  Please do let me know if I need to close this PR

**Comment by soham4abc** [comment]
@mekarpeles  Would you have a look at this?

**Comment by soham4abc** [comment]
@dhruvmanila  should I close this one?

**Comment by soham4abc** [comment]
closing

**Pull request closed without merging**
