### PR TITLE
Updated Croatian translation

### PR DESCRIPTION
**Pull request by milotype**
- just some corrections after reviewing the "staging" pages

### Testing
Just as a side note: there are still many untranslated strings in the "staging" pages

### CODE REVIEW

**Review by cdrini — APPROVED** [review]
Lgtm; not testing; the changes here are unlikely to trigger and error.

**Comment by cdrini** [comment]
Thanks @milotype ! The updated translations should be available on staging.openlibrary.org .

Can you provide examples of what's missing? We can make most things that are not being translated available for translation. We also had a re-organizing of the edit page recently, which likely also resulted in some modified strings.

**Comment by milotype** [comment]
I'd like to check the hr-translation for the beta/development/staging pages of the website, but i lost the link (I've been there before).
Currently I'm getting an 502-error page for: 
- http://staging.openlibrary.org
- http://staging.openlibrary.org/?lang=hr

**Comment by cdrini** [comment]
Ah, sorry about that; your links are correct, the staging server must have been having some issues. Should be back now :+1:

**Pull request merged**
