### PR TITLE
Responce to issue #629

### PR DESCRIPTION
**Pull request by BrianMwangi21**
Added the password constraints below the password textbox. 
Added 3 so far, don't know if more are needed

### CODE REVIEW

**Comment by mekarpeles** [comment]
@BrianMwangi21 thanks for your contribution! We'll test this on the dev server and have a code review for you soon. This weekend will be very busy because of the @aaronsw hackathon so thanks in advance for your patience! 🎉

**Comment by BrianMwangi21** [comment]
@mekarpeles Thanks for your comment. No pressure, take your time and all the best at the hackathon!

**Comment by mekarpeles** [comment]
Sorry -- here's the link to the file (copied a path which wasn't accessible to github)
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/i18n/strings.en

@BrianMwangi21 in this case that file just contains a bunch of strings which show you what the possible errors could be.

**Comment by mekarpeles** [comment]
Closing this PR due to lack of activity

**Comment by tfmorris** [comment]
It makes me sad to see a first time contributor get closed out.

@BrianMwangi21 If you'd like to reopen this and get it cleaned up, ping me and I'll be happy to help. Open source / open data is all about the community. Without us it withers and dies.

**Pull request closed without merging**
