### PR TITLE
fixing wiki pages e.g. sponsorship to work on mobile

### PR DESCRIPTION
**Pull request by mekarpeles**
This makes all wiki pages (with large images) fit to the width of parent and not overflow.

Closes #2747

### CODE REVIEW

**Comment by jdlrobson** [comment]
This looks good. I'll test tomorrow. Travis needs to be taken care of though!

**Comment by mekarpeles** [comment]
The CI error is:

```
static/css/layout/index.less
 13:3  ✖  Expected selector "div.contentBody img" to  no-descending-specificity
          come before selector "div#contentBody img"
```

Should I change to:
```
div#contentBody,
div.contentBody {
  padding: 0 20px 20px;
}
div.contentBody img {
  max-width: 100%;
}
```
?

**Comment by mekarpeles** [comment]
I tested on the sponsorship page and also tested our other main pages (author, book, homepage)

**Comment by tabshaikh** [comment]
This also closes the issue 2547

**Pull request merged**
