### PR TITLE
Alternative fixes #580 , services not starting in vagrant dev instance

### LINKED ISSUE #580: infobase server not started automatically on `vagrant-up`
This is a bash bug with bootstrap.sh:

https://github.com/internetarchive/openlibrary/blob/c0cc6a1d7b050303d6019c7d973a99a153525642/scripts/bootstrap.sh#L121-L123

The generate `ol-start` script doesn't escape the `${}`, so only `ol-web` (which `name` is set to earlier in the file) is started multiple times.

### PR DESCRIPTION
**Pull request by hornc**
I started this investigation on the Aaron Swartz hackathon day from discussions with @dvanduzer regarding solr indexing and believe I found the root cause of the scripts not loading after the intial provisioning -- I hadn't updated my scripts to get the previous fix from @cdrini https://github.com/internetarchive/openlibrary/pull/588

my fault for not checking the bug hadn't already been fixed! I'm leaving this here for discussion since there is quite a change in how  the services are started. My fix retains the upstart conf files. The current fix has added a startup script to init.d

If this is to be merged, the changes in https://github.com/internetarchive/openlibrary/pull/588 should be reverted.

### CODE REVIEW

**Comment by cdrini** [comment]
The conf files are still active in #588 ; they're just called *by* `ol-start.sh`. This is pretty much identical to how it was before, just that instead of `ol-start` being `echo`-ed into a file from the bootstrap script, it's just its own file now :P Do you still experience issues with the #588 fix? I think there could still be an edge case where it tries to run `ol-start` before vagrant has been properly mounted, so the symlink doesn't resolve, but I don't think I've encountered that.

**Comment by mekarpeles** [comment]
I don't think these changes are mutually exclusive to the changes made to @cdrini. I'm for these being merged in if it does force a wait until vagrant mounted. Question is; do we have evidence this PR accomplishes? Otherwise we might consider closing.

**Comment by hornc** [comment]
@mekarpeles I'll investigate further, I did get latest which got @cdrini's earlier fix, but I did not regenerate a new vagrant image, so the new bootstrap.sh changes did not take effect.

I did test my fix locally and it seemed to work, but I now think there is still something wrong. the `vagrant-mounted` event does not seem to be occurring like I expected, which may be due to this bug https://github.com/hashicorp/vagrant/issues/6074

I'm now trying to untangle whether the dev image is using sysv or upstart for init. I thought it was upstart and therefore any scripts in init.d were not necessary, but it does seem the init.d script is what has been doing the work. I've marked this as [WIP] and I'll investigate further and try a get a clean init for all the services, hopefully using just upstart.

**Comment by hornc** [comment]
I am withdrawing this PR -- while it fixes the upstart init in a vagrant context, it will probably break production....  I now understand the init.d/ol-start script is there only to get the dev environment started because the upstart script that works in production fails initially because `/openlibrary` is not yet mounted in vagrant. It struck me as wrong that two init methods should be used to start the three scripts, but I now accept there is a need to workaround the vagrant mounting delay for dev, which is likely to involve something a bit hacky regardless. Adding a single `ol-start` script for the dev environment seems reasonable.

If I can think of a cleaner way to fix upstart init without impacting production I'll try again, but now I'll simply verify the `solr-updater` script runs in dev exactly the same way as in production with the original init.d fix, which is all I was trying to do when I opened this :)

thanks @mekarpeles and @cdrini for helping me figure it all out :+1:

**Pull request closed without merging**
