### PR TITLE
10060/fix/waiting list text breaks out of left sidebar

### LINKED ISSUE #10060: Waiting list text breaks out of left sidebar
### Problem

`You are #21 of 21 on the waiting list.` should probably wrap instead of going outside of that box.

image

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N):
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

### PR DESCRIPTION
**Pull request by ronibhakta1**
Closes #10060 

css fix text-wrap: auto;

### Technical

wrapped the text to fit in the div

### Screenshot

Screenshot 2024-11-23 at 9 05 14 PM
### Stakeholders

@RayBB

### CODE REVIEW

**Comment by RayBB** [comment]
@ronibhakta1 please remove the changes to the markdown file. 
Other than that it looks great!

**Comment by RayBB** [comment]
It's still there

**Comment by ronibhakta1** [comment]
> It's still there

sorry for that its done now

**Comment by ronibhakta1** [comment]
> It's still there

Check it out

**Comment by RayBB** [comment]
There are still changes to the readme. Please remove them.

**Comment by ronibhakta1** [comment]
I have removed it and pasted the official readme in it

**Pull request closed without merging**
