### PR TITLE
Rework master.css to master.less, extract color codes to variables

### PR DESCRIPTION
**Pull request by psyked**
Contributes towards #968 

## Description:
In this Pull Request we have made the following changes:

* Renamed `master.css` to `master.less`
* Replaced existing CSS colour codes with LESS variable equivalents
* Consolidated visibly indistinguishable colours

### CODE REVIEW

**Comment by psyked** [comment]
There are a lot of colour code names extracted to variables in this PR, and they could do with better naming conventions or semantics, but this is a start.

**Comment by mekarpeles** [comment]
LGTM, thank you @psyked + congrats on your first openlibrary PR!

**Comment by mekarpeles** [comment]
@psyked one small regression I noticed (retroactively) is the main search box looks like it had its white background color clobbered in the process of us potentially merging colors?

screen shot 2018-06-26 at 00 37 37ampdt

**Comment by psyked** [comment]
@mekarpeles The old background color for the search input was '#fafafa' and it was inconsistently clobbered to '#ffffff' by this PR. I've now updated the PR to revert this back to '#fafafa' for the input.

I've also checked dev vs. live and it looks like the reds were darker than intended across the board, and I've also fixed that. I assume that the issue with the reds occurred as a typo on my part.

**Comment by mekarpeles** [comment]
closes: #968

**Pull request merged**
