### PR TITLE
blog banner for my books

### PR DESCRIPTION
**Pull request by mekarpeles**
https://blog.openlibrary.org/2022/12/27/a-brand-new-my-books-experience/

### CODE REVIEW

**Comment by tfmorris** [comment]
Did this get merged by mistake? It's showing up in production and is SO damn garish and ugly! 

It also isn't showing up in the language that my browser is set for.

AND it's showing up on every single page impression, not just the My Books page.

**Comment by mekarpeles** [comment]
This is patch deployed until tomorrow at which point it will be replaced with a temporary banner for setting yearly reading goals. This is a pattern that we followed on dozens of occasions in the past when we release a relevant new blog post.

Thanks for the feedback about your experience. If there are certain treatments or things we might add (maybe a dismiss btn?) would love to hear.

**Comment by tfmorris** [comment]
Thanks for creating the issue for me. I'll add my product related comments there, but from a process point of view, the entire raison d'etre of pull requests is to provide a mechanism for review and discussion in advance of merging and then deploying. I'm don't understand what the purpose of this PR is if the code's already been deployed.

I would have thought that it goes without saying, but I'll say it anyway, hand patching production servers with unreviewed code is a **really** bad idea.

**Comment by mekarpeles** [comment]
this PR has served its purpose :)

**Comment by tfmorris** [comment]
I'm not sure I understand the outcome of the discussion, but happy new year!

**Pull request closed without merging**
