### PR TITLE
Fix(#10210):  Hide pager when there is only one page (#10210)

### LINKED ISSUE #10210: Stop Showing Pagination Buttons When There is only one page
### Problem

This issue of hiding the pager when there is only one page was proposed by @RayBB. I am raising the issue on his behalf.

I also believe that if certain buttons are unclickable, we should stop giving false indications to users. For example, when we are already on first page, there's no use in showing the 'First' and 'Previous' buttons, as they serve no purpose. It's better to avoid showing these buttons.

What do you think about this, @RayBB, @mekarpeles?

image

### Reproducing the bug

1. Go to ... Any of the Author's works -> View all Editions (https://openlibrary.org/works/OL20929W/The_Spanish_gypsy?mode=all)

* Expected behavior:

image
image
image

* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N):
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

* [Related Slack discussion](https://internetarchive.slack.com/archives/C0ETZV72L/p1734830635395769) 

#### Stakeholders

* @RayBB
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

### PR DESCRIPTION
**Pull request by SharkyBytes**
Closes #10210 

Fix: Hides the pager when there is only one page in the `legacy-datatables` UI. This prevents unnecessary pagination buttons that serve no purpose for users.

### Testing

1. Navigate to any book and go to the "View Editions" tab.
2. If the allowed entries exceed the available data (e.g., only 8 entries), verify that the pager is hidden.
3. If the dataset exceeds the allowed entries, verify that the pager is displayed as expected.

### Screenshot

**Pager Hidden (Single Page):**  
The pager is hidden because the allowed entries are more than the actual dataset (8 entries).  
image
**Pager Visible (Multiple Pages):**  
The pager is shown when the dataset exceeds the allowed entries.  
image

### Stakeholders

@RayBB

### CODE REVIEW

**Comment by SharkyBytes** [comment]
Hi @RayBB & @mekarpeles,

I’ve implemented the fix to hide the pager when there’s only one page. Let me know if any changes are needed or if it’s good to merge.

On a related note, I noticed that other pages like Trending hide the "First/Previous" buttons on the first page and the "Next/Last" buttons on the last page. Would you like me to include this behavior here, or should we address it in a separate issue?

Trending Page Behaviour

image

image

For your reference, I’ve already run the tests locally using:

`docker compose run --rm home make test`

->All tests passed successfully, you can see below 

image


Thanks again for your guidance and support @RayBB —it’s been great working with you!

**Review by RayBB — CHANGES_REQUESTED** [review]
Great work on the feature—it's coming along nicely! I noticed the pager is being hidden using CSS. While that works technically, it might not be the easiest approach for someone looking at the HTML to quickly understand what's going on.

For simplicity and clarity, it’s usually better to handle visibility directly in the HTML whenever possible. This way, if someone is searching for a specific element, they can find all the relevant details in one place without needing to cross-reference the CSS.

Would it be feasible to update this so the pager is hidden within the HTML itself? This small change could make the code easier to maintain and understand for future developers.

**Comment by SharkyBytes** [comment]
Hi @RayBB,

Thanks for your feedback!

I’ve looked for the HTML file where the changes could be applied, but the updates don’t seem to reflect there. It appears the pager behavior is being controlled elsewhere, and I’m not seeing the expected result in the HTML file I modified.

As this is a large codebase, I’m still familiarizing myself with all the intricacies, so it would be really helpful if you could point me to the exact HTML file or location where these changes should be made.

**Comment by RayBB** [comment]
@SharkyBytes please check in `/openlibrary/plugins/openlibrary/js/editions-table/index.js`

**Comment by SharkyBytes** [comment]
I was also looking at the `/openlibrary/plugins/openlibrary/js/editions-table/index.js` file, but I initially thought there might be a dedicated HTML file for the pager behavior, similar to the other pagers we have in the codebase.

@RayBB, Please take a look at the changes I made, and let me know if this approach works or if you'd prefer a different solution.

**Review by RayBB — CHANGES_REQUESTED** [review]
Let's try using the proper JavaScript API instead of adding new css.

**Comment by mekarpeles** [comment]
This is where we deal with pagers in html https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/Pager.html#L4 (this could be `if pages > 1`)

Within js for the editions table, here you can see if/when we are rendering the `DataTable` with `bPaginate` which is currently only if (rowCount < 4), but these conditions may not be sufficient.
https://github.com/internetarchive/openlibrary/blob/1ccea97e1364340defa166f7d455de04733c5478/openlibrary/plugins/openlibrary/js/editions-table/index.js#L69-L93

**Comment by SharkyBytes** [comment]
Hey @RayBB,

I've updated the code to dynamically handle the pagination visibility using the DataTables API. Now, the pagination controls are hidden when the total row count is less than or equal to the selected page length or when 'All' is selected in the dropdown. Let me know if there's anything else you'd like me to tweak!

**Review by RayBB — CHANGES_REQUESTED** [review]
Looks like a step in the right direction!
Can you please remove all the whitespace changes you've made so it's easy to see the needed changes? You might need to disable automatic code formatting in your IDE if it's enabled.
Also there are now failing checks. Please address these (they're small ones).

Thanks for your patience. I know these small things can be a pain.

**Comment by SharkyBytes** [comment]
Hey @RayBB and @mekarpeles ,

Just a quick update — I’ve improved the logic and cleaned up the auto-formatting changes so the code looks cleaner now. All checks have passed, so it’s ready for review. Let me know if you spot anything.

**Review by RayBB — APPROVED** [review]
This seems like a fantastic solution to me! Great job 👍 

Hiding the element isn't ideal but I don't think there's a better way to do it.

Now we just need staff to review/merge.

**Comment by mekarpeles** [comment]
I believe this change set now LGTM. 👍 thank you!

**Comment by SharkyBytes** [comment]
Thanks for merging @RayBB & @mekarpeles! Really loved working on this with you both. Appreciate your support and feedback throughout :)

**Pull request merged**
