### PR TITLE
(hotfix/#1825): Fix links and text UI to make it clean and more reada…

### LINKED ISSUE #1825: Clean UI: more readable LinkBox line-height / text-spacing
The UI currently is not clean. The links and texts are not readable enough.
## Evidence 

> Relevant url?
`https://openlibrary.org/...`
https://openlibrary.org/subjects/fantasy#sort=date_published&ebooks=true

> Screenshot (if possible):
screenshot from 2019-01-17 15-04-35

screenshot from 2019-01-17 15-36-26

## Details

> Logged in (Y/N)?

> Browser type/version?

> Operating system?

## Proposal & Constraints
A couple of changes in CSS will solve the problem. No constraints.
I already have fixed it.

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

### PR DESCRIPTION
**Pull request by feat7**
> **Description**: What does this PR achieve? [feature|hotfix|refactor]

Closes #1825
hotfix for Cleaning UI that makes the text and links more readable.

> **Technical**: What should be noted about the implementation?

Change in .less files.
Changed styles for links and body text.

> **Testing**: Steps for reviewer to reproduce / verify this PR fixes the problem?

build the css with `make css`

> **Evidence**: If this PR touches UI, please post evidence (screenshot) of it behaving correctly:

screenshot from 2019-01-17 15-36-26

### CODE REVIEW

**Comment by mekarpeles** [comment]
This impacts global styles which may impact more pages than just this one. I'm not sure this is what we want

**Comment by feat7** [comment]
@mekarpeles yes I know. And I did it intentionally. All the pages look cleaner with this.
Even for some reason we want underlines to the links, we can work on the line height. It makes the UI cleaner. 
I would want to take your suggestions and improve the UI.

**Comment by jdlrobson** [comment]
There's definitely a clean-ness to this, but it's a big change that we should think through.
While we're at it, I'm a little concerned about the  reliance of color on hover state on links in general. Might I suggest we open an issue to allow some discussion about changing the link color (with screenshots!) before applying it to allow for some conversation first?


I also notice it doesn't apply to links such as Daisy - best to be consistent and make sure this applies everywhere!

 screen shot 2019-01-18 at 9 34 51 pm
screen shot 2019-01-18 at 9 34 54 pm

**Comment by feat7** [comment]
@jdlrobson yes we can think through it.
The current hover color is dark green with underlines. I have not changed anything else it should behave as it is currently. 
We can have detailed discussions in a new issue or maybe in slack? 
The other links which do have underline, we can make them consistent after we come to conclusion about this.

**Comment by tabshaikh** [comment]
This pr would really require extensive testing as @mekarpeles pointed, so @feat7 maybe a good step is to browse through all the templates and see which ones are affected by this change

**Comment by mekarpeles** [comment]
Rescoping #1825 to address line-height specifically of Linkbox component. https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#linkbox
Closing this specific PR

**Pull request closed without merging**
