### PR TITLE
Added: Debug Page redirect if user is librarian

### LINKED ISSUE #8881: Add debug button/link to error page (only for librarians)
### Describe the problem that you'd like solved

This was discussed on the community call.
When some navigates to a page with an error they see something like this:
image

If you append `?debug=true` to the url then you can see a stacktrace with more detailed information.

I propose that we add a button or link that only shows up for librarians that will take them directly to the debug page.

### Proposal & Constraints

Though in many cases it could be as simple as appending the `?debug=true` we want to make sure if there are other queryparams (such as during search) that we append appropriately with `&debug=true`.

This should be done in the python code of the error template.

### Additional context

Related docs:
https://github.com/internetarchive/openlibrary/wiki/Debugging-and-Performance-Profiling

The code for this template lives in the infogami repo here:
https://github.com/internetarchive/infogami/blob/3a6508785487728911252a9df53bcc5f44a4cde1/infogami/utils/template.py#L173-L183

### PR DESCRIPTION
**Pull request by QuantuM410**
Closes #8881 

Librarian is redirected to debug page if an error is encountered

### Testing

- Edit any of the templates (author view page for example) with invalid python or raising an error
- Visiit the error page at the edited template path
### Stakeholders

@RayBB

### CODE REVIEW

**Comment by RayBB** [comment]
@QuantuM410 any luck with this?

**Comment by RayBB** [comment]
@QuantuM410 here's a video of me testing it. Maybe you can try to see if it works in this case?

https://github.com/internetarchive/openlibrary/assets/921217/0360bfaa-ceca-4c6c-97a0-6b96e831beb0

**Comment by QuantuM410** [comment]
> @QuantuM410 here's a video of me testing it. Maybe you can try to see if it works in this case?
> debug.mp4

@RayBB This doesn't seem to work :/. I did some testing and it seems to work when I raise an error like ```raise TypeError("XYZ")``` in a template's python code and some other cases but also doesnt work for cases like these. Also it seems when the error is appearing instead of debug page, the internalerror() function is not being called while for cases like raising exceptions or errors in python code (or something else) it calls the internalerror() function raising the debug page for the librarian. Are there like different type of internal errors? It seems its working for errors with ```
Sorry. There seems to be a problem with what you were just looking at.``` message and don't seem to work for the errors displaying ```Unable to render this page. ```

https://github.com/internetarchive/openlibrary/assets/85943021/c5003ae5-fe14-4996-9eab-381069df6e4e

**Comment by RayBB** [comment]
@QuantuM410 yeah, I'm not sure exactly what the best way to handle this is.
Maybe @mekarpeles has an idea?

You might have to look at the infogami repo
https://github.com/internetarchive/infogami/blob/3a6508785487728911252a9df53bcc5f44a4cde1/infogami/utils/template.py#L173-L183

**Comment by RayBB** [comment]
Closing per https://github.com/internetarchive/openlibrary/issues/8881#issuecomment-2502332328

**Pull request closed without merging**
