### PR TITLE
repr(Nothing()) —> "<Nothing>", not empty str

### PR DESCRIPTION
**Pull request by cclauss**
`assert repr(work.any_attribute) in ('', '<Nothing>')` to align with internetarchive/infogami#151.

Closes #

### CODE REVIEW

**Comment by cdrini** [comment]
Merged infogami#151 :) Can you also update infogami here to the latest SHA?

**Comment by cclauss** [comment]
Why does this one still fail?

**Comment by cdrini** [comment]
Look ~5 lines down from your edit to the test file :P

**Comment by cdrini** [comment]
https://github.com/internetarchive/openlibrary/pull/4972/files#diff-004f15531020b03fc65d6f0ef60e956eb5c86eb4fcbb7749a8d674ab6446e7d8R75

**Comment by cclauss** [comment]
Doh!

**Review by cdrini — APPROVED** [review]
Code Lgtm! Deploying on staging for a sanity check... (I think staging will do the right thing).

**Comment by cclauss** [comment]
Thanks.   Ready for review.

**Comment by cdrini** [comment]
It does not :P Testing locally.

**Comment by cdrini** [comment]
Tested homepage loads; lgtm!

**Pull request merged**
