### PR TITLE
Add author configs to `pg_dump` file

### PR DESCRIPTION
**Pull request by jimchamp**
In support of #8202

Adds Storygraph, Youtube, and Amazon author identifier configurations to the `pg_dump` file which is used to initially populate DBs in developer environments.

**Edit:** Additionally, adds a Wikidata identifier to Mark Twain's author record.

### Technical

Steps taken when making this update:
1. Remove local DB container by running `docker container rm openlibrary-db-1`
2. Populate DB with initial load by bringing the application back up: `docker compose up`
3. Verify that DB has been recreated by visually inspecting the results of `select * from thing order by id desc limit 10`
4. Update the author configuration via http://localhost:8080/config/author.yml?m=edit
5. Confirm that new entries are present in the "Identifiers" dropdown (found on author edit pages)
6. Add Wikidata ID to Mark Twain's record.
7. Generate new `pg_dump` by following the instructions outlined [here](https://github.com/internetarchive/openlibrary/blob/a8796b4952b13b6f12138c3de8e1af0efdea85d7/scripts/dev-instance/create-dev-db-pgdump.sh#L7-L8).

<details><summary>Click to see the configurations that were added</summary>
<code>
-   label: Amazon ID
    name: amazon
    notes: Should be something like B000AQ0842
    url: https://www.amazon.com/-/e/@@@
    website: https://www.amazon.com
-   label: Storygraph
    name: storygraph
    notes: eg 50b7fbd9-84ac-450d-b2ed-78c861d4ef00
    url: https://app.thestorygraph.com/authors/@@@
    website: https://www.thestorygraph.com/
-   label: YouTube
    name: youtube
    notes: Link to the author's official YouTube channel
    url: https://www.youtube.com/@@@
    website: https://www.youtube.com
</code>
</details> 

### Stakeholders

@cdrini 
@davidscotson

### CODE REVIEW

**Comment by RayBB** [comment]
@jimchamp if it's not too hard could you make it so the dump includes the wikidata id `Q7245` for Mark Twain?

This would make it easier for anyone test my work in #8236 and save me time as well when I reset my db.

**Comment by jimchamp** [comment]
Should be good now, @RayBB.  Give it a try if you have a chance.

**Comment by RayBB** [comment]
@jimchamp doesn't seem to have worked. No `Q7245` in the dump or when I pull your branch. Could be because you have to login before editing for the save to work (part of the annoyance I face)?

**Comment by jimchamp** [comment]
I probably didn't click the "Set" button.... one moment

**Comment by jimchamp** [comment]
Should _really_ be good now.
image

The preexisting Wikipedia link threw me off earlier.

**Comment by RayBB** [comment]
Looks good now. Thanks @jimchamp this is a big help :)

**Review by cdrini — APPROVED** [review]
Code lgtm , assigned to @RayBB since he tested it :)

**Pull request merged**
