### PR TITLE
Refactor/Move inline js from books/edit/addfield template

### PR DESCRIPTION
**Pull request by lephemere**
Closes openlibrary/templates/books/edit/addfield.html point from #4474

Move inline JavaScript from books/edit/addfield.html template to index.js and edit.js.

### Technical

Add role, identifier and classification fields are disabled at the moment (EDIT: Since 2011 at least...)

https://github.com/internetarchive/openlibrary/blob/318a20168367a2dd929f60825942015846ec4308/openlibrary/templates/books/edit/edition.html#L249

https://github.com/internetarchive/openlibrary/blob/318a20168367a2dd929f60825942015846ec4308/openlibrary/templates/books/edit/edition.html#L472

https://github.com/internetarchive/openlibrary/blob/318a20168367a2dd929f60825942015846ec4308/openlibrary/templates/books/edit/edition.html#L538

Probably disabled as it is not working. I enabled `__add__` option on the master branch, but no popup displayed.
Could be linked to issue on `add_new_field.js` => To be investigated.

Already existing `error()` function from `edit.js` taken instead of original one. Hence `$.fn.colorbox.resize();` not called anymore.
Anyway, as this part is not really working, it will need further work and investigation.

### Stakeholders

@jdlrobson

### CODE REVIEW

**Comment by lephemere** [comment]
@jdlrobson - Just stumbled on your PR #2496 about this disabled (maybe never enabled...) feature. Should we remove it completely? No point in moving dead code around.

**Comment by jdlrobson** [comment]
@mekarpeles can you help us unblock this by helping us work out what to do with #2496 ? Thanks in advance!

**Comment by jdlrobson** [comment]
Hi @lephemere you should be unblocked now. Can you rebase this patch and resolve the conflicts now the unused JavaScript has been removed? Thanks in advance!

**Comment by lephemere** [comment]
Closing this PR in favor of #2700.

**Pull request closed without merging**
