### PR TITLE
Travis CI: Remove allow_failures on Python 2.7 on bionic

### PR DESCRIPTION
**Pull request by cclauss**
As discussed at https://github.com/internetarchive/openlibrary/issues/2268#issuecomment-520668700

### CODE REVIEW

**Comment by tfmorris** [comment]
LGTM

**Comment by cdrini** [comment]
Any reason we're not testing on xenial any more? All our production servers are still using xenial, so we definitely don't want that to fail. Also, providing a summary of the justification (with the link) is more useful than just providing the link.

**Comment by cclauss** [comment]
I put back the Xenial tests.  I misunderstood and earlier comment and thought the servers were already moved to bionic.  Will try in future to add more comments.

**Comment by cdrini** [comment]
(In fact we still have some on trusty! Those we (might) update straight to bionic, but the plan hasn't been fully cemented).

**Pull request merged**
