### PR TITLE
Remove dead code related to Unicode characters

### LINKED ISSUE #4311: Adding non-Latin character book failing 500:  "UnicodeEncodeError: 'ascii' codec can't encode characters"
### Evidence / Screenshot (if possible)

Screenshot_2020-12-19_13-30-48

### Relevant url?
https://openlibrary.org/books/add

### Steps to Reproduce
1. Log-in with account
2. More -> Add Book
3. Enter title: `Справа Василя Стуса. Збірка документів з архіву колишнього КДБ УРСР`
4. Enter unknown author: `Вахтанг Кіпіані` (Click "create new record for")
5. Enter publisher: `Віват`
6. Enter published date: `2019`
7. Enter USBN13: `9789669429278`
8. Press "Add"

* Actual: Error 500
* Expected: Book added to system

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox latest
- **Operating system?** Debian Linux 10
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
I'm using cyrillic symbols for book and author name. Might be the issue?

### LINKED ISSUE #4869: Internal Server Error - Add Book with Unicode characters
### Evidence / Screenshot (if possible)
add a book -   Internal Server Error

### Relevant url?
https://openlibrary.org/books/add

### Steps to Reproduce
Try to ad d the following book:
- title: `Doi galoşi`
- author: `Camelia Leonte`
- publisher: `Junimea`
- Published: `1988`
- isbn: none
- goodreads record: https://www.goodreads.com/book/show/26099487-doi-galo-i?from_search=true&from_srp=true&qid=EgtiGgQoB7&rank=1

* Actual: Internal Server Error - status code 500
* Expected: Book is successfully added

### Details

- **Logged in (Y/N)?**  Yes
- **Browser type/version?** Vivaldi 3.7.2218.45 (Stable channel) (64-bit)
- **Operating system?** Windows 10 OS Version 2009 (Build 19042.844)
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Not sure.

###### Piggyback

I'm migrating my collection from Goodreads to Openlibrary, due to the removal of API.

1. It would be nice to also add a picture to the book record directly in that form
2. It would be nice that on the import goodreads CSV (https://openlibrary.org/account/import/goodreads) to give the option to create all of those titles which could not be imported due to lack of ISBN , even though they don't have the isbn and afterwards ask me to edit them.

image

### PR DESCRIPTION
**Pull request by cclauss**
Related to #4616

This pull request is a subset of 4616 which only makes the __changes 1 and 5__ as discussed at https://github.com/internetarchive/openlibrary/pull/4616#pullrequestreview-605923373 

Once these changes have been reviewed and landed, 4616 can be rebased to simplify its next review.

### CODE REVIEW

**Comment by hornc** [comment]
@cclauss do we have a stack trace from the original reported errors? I don't see how this normalize() is in the add book code path, or where the error was.

Openlibrary/openlibrary/plugins/upstream/addbook.py doesn't import anything from catalog (which isn't great, it means the UI import is separate from the API import and dupe matching is implemented twice... but that's another problem).  The code modified in this PR is part of API import path.

**Comment by cclauss** [comment]
```
2021-03-25 18:46:56 [openlibrary.logger] [INFO] solr request: http://solr:8983/solr/select?wt=json&q.op=AND&q=title%3A%22Life+in+L%C3%BCsai%2C+Graub%C3%BCnden%22+AND+publisher%3A%22N%C3%A5n%C3%B6%22+AND+publish_date%3A%222022%22&start=0
Traceback (most recent call last):
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 280, in process
    return self.handle()
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 271, in handle
    return self._delegate(fn, self.fvars, args)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 517, in _delegate
    return handle_class(cls)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 495, in handle_class
    return tocall(*args)
  File "/openlibrary/infogami/utils/app.py", line 187, in <lambda>
    HEAD = GET = POST = PUT = DELETE = lambda self: delegate()
  File "/openlibrary/infogami/utils/app.py", line 206, in delegate
    return getattr(cls(), method)(*args)
  File "/openlibrary/openlibrary/plugins/upstream/addbook.py", line 171, in POST
    match = None if created_author else self.find_matches(i)
  File "/openlibrary/openlibrary/plugins/upstream/addbook.py", line 226, in find_matches
    edition = self.try_edition_match(
  File "/openlibrary/openlibrary/plugins/upstream/addbook.py", line 303, in try_edition_match
    result = solr.select(q, doc_wrapper=make_work, q_op="AND")
  File "/openlibrary/openlibrary/utils/solr.py", line 106, in select
    return self._parse_solr_result(
  File "/openlibrary/openlibrary/utils/solr.py", line 119, in _parse_solr_result
    d.docs = [doc_wrapper(doc) for doc in response['docs']]
  File "/openlibrary/openlibrary/utils/solr.py", line 119, in <listcomp>
    d.docs = [doc_wrapper(doc) for doc in response['docs']]
  File "/openlibrary/openlibrary/plugins/upstream/addbook.py", line 73, in make_work
    w.authors = [make_author(key, name) for key, name in zip(doc['author_key'], doc['author_name'])]
KeyError: 'author_key'
error saved to /var/log/openlibrary/ol-errors/2021-03-25/184656376915.html
```

**Comment by hornc** [comment]
@cclauss I just found the trace on #4311 -- from that and the comments on the issue, it looks like it is Unicode in the headers which caused the problem. That looks like the same problem I fixed in #4861 with borrow redirects. I'm not sure if it fixes the redirect locations for adding, I'd noticed the problem specifically in borrows.

**Comment by cclauss** [comment]
I do not understand what the _action_ is.  Are you planning to create a pull request?

**Comment by hornc** [comment]
Is #4311 already fixed in production? If  #4311 and #4869 are fixed on staging, I don't think this PR is the cause.

**Comment by cclauss** [comment]
What is blocking this dead code removal?

**Comment by hornc** [comment]
@cclauss it's not clear that this is dead code or why it is being changed. The commit message is incorrect and unrelated to the code removed. It removes a clearly tested method and modifies the catalog normalize() behaviour with an unclear effect, and with no indication that the previous behaviour was wrong. 

It looks like this catalog code could use refactoring but this PR makes the intent of the existing code _less_ clear and could break things. The original PR description and logs above show that the change was intended to solve an issue unrelated to this code as I commented above in, the problem is from plugins/upstream

The action is to close this PR because it appears to be in error and unrelated to any reported issues.

**Comment by cclauss** [comment]
You must have forgotten what you wrote on changes 1 and 5 of https://github.com/internetarchive/openlibrary/pull/4616#pullrequestreview-605923373

I has been nice working with you.

**Pull request closed without merging**
