### PR TITLE
Remove dead multi-core solr code

### PR DESCRIPTION
**Pull request by cdrini**
WARNING: This PR deletes a lot of files. Looking at the diff on GitHub is **ridiculously slow**. Follow the instructions below to ease your reviewing experience.

Once upon a time we used to have different solr instances (cores) for each datatype: one for `authors`, one for `works`, etc. Sometime around 2013, we switched to a single solr instance with a `type` field. This PR removes most of the dead code related to the old, multi-core solr. Should make understanding how solr works, how it updates, and how we might possibly replace it, easier.

The best way to view these changes is commit-by-commit. The first commit is the slow one (mostly deletions; pay attention to the deleted scripts), so look at the list of deleted files below and open the full diff when needed. Then just click on the commits to view the diff.

I tested vagrant provision and solr reindexing on my local, and they seemed to work fine.

<details>
<summary>List of files changed in the first commit</summary>
<pre>
M	conf/services.ini
D	scripts/install_ol.py
D	scripts/setup_solr.py
D	scripts/solr.sh
D	conf/solr-biblio/authors/conf/admin-extra.html
D	conf/solr-biblio/authors/conf/elevate.xml
D	conf/solr-biblio/authors/conf/mapping-ISOLatin1Accent.txt
D	conf/solr-biblio/authors/conf/protwords.txt
D	conf/solr-biblio/authors/conf/schema.xml
D	conf/solr-biblio/authors/conf/scripts.conf
D	conf/solr-biblio/authors/conf/solrconfig.xml
D	conf/solr-biblio/authors/conf/spellings.txt
D	conf/solr-biblio/authors/conf/stopwords.txt
D	conf/solr-biblio/authors/conf/synonyms.txt
D	conf/solr-biblio/authors/conf/xslt/example.xsl
D	conf/solr-biblio/authors/conf/xslt/example_atom.xsl
D	conf/solr-biblio/authors/conf/xslt/example_rss.xsl
D	conf/solr-biblio/authors/conf/xslt/luke.xsl
D	conf/solr-biblio/editions/conf/admin-extra.html
D	conf/solr-biblio/editions/conf/elevate.xml
D	conf/solr-biblio/editions/conf/mapping-ISOLatin1Accent.txt
D	conf/solr-biblio/editions/conf/protwords.txt
D	conf/solr-biblio/editions/conf/schema.xml
D	conf/solr-biblio/editions/conf/scripts.conf
D	conf/solr-biblio/editions/conf/solrconfig.xml
D	conf/solr-biblio/editions/conf/spellings.txt
D	conf/solr-biblio/editions/conf/stopwords.txt
D	conf/solr-biblio/editions/conf/synonyms.txt
D	conf/solr-biblio/editions/conf/xslt/example.xsl
D	conf/solr-biblio/editions/conf/xslt/example_atom.xsl
D	conf/solr-biblio/editions/conf/xslt/example_rss.xsl
D	conf/solr-biblio/editions/conf/xslt/luke.xsl
D	conf/solr-biblio/inside/conf/admin-extra.html
D	conf/solr-biblio/inside/conf/elevate.xml
D	conf/solr-biblio/inside/conf/mapping-ISOLatin1Accent.txt
D	conf/solr-biblio/inside/conf/protwords.txt
D	conf/solr-biblio/inside/conf/schema.xml
D	conf/solr-biblio/inside/conf/scripts.conf
D	conf/solr-biblio/inside/conf/solrconfig.xml
D	conf/solr-biblio/inside/conf/spellings.txt
D	conf/solr-biblio/inside/conf/stopwords.txt
D	conf/solr-biblio/inside/conf/synonyms.txt
D	conf/solr-biblio/inside/conf/xslt/example.xsl
D	conf/solr-biblio/inside/conf/xslt/example_atom.xsl
D	conf/solr-biblio/inside/conf/xslt/example_rss.xsl
D	conf/solr-biblio/inside/conf/xslt/luke.xsl
D	conf/solr-biblio/jetty.xml
D	conf/solr-biblio/logging.properties
D	conf/solr-biblio/solr.xml
D	conf/solr-biblio/subjects/conf/admin-extra.html
D	conf/solr-biblio/subjects/conf/elevate.xml
D	conf/solr-biblio/subjects/conf/mapping-ISOLatin1Accent.txt
D	conf/solr-biblio/subjects/conf/protwords.txt
D	conf/solr-biblio/subjects/conf/schema.xml
D	conf/solr-biblio/subjects/conf/scripts.conf
D	conf/solr-biblio/subjects/conf/solrconfig.xml
D	conf/solr-biblio/subjects/conf/spellings.txt
D	conf/solr-biblio/subjects/conf/stopwords.txt
D	conf/solr-biblio/subjects/conf/synonyms.txt
D	conf/solr-biblio/subjects/conf/xslt/example.xsl
D	conf/solr-biblio/subjects/conf/xslt/example_atom.xsl
D	conf/solr-biblio/subjects/conf/xslt/example_rss.xsl
D	conf/solr-biblio/subjects/conf/xslt/luke.xsl
D	conf/solr-biblio/works/conf/admin-extra.html
D	conf/solr-biblio/works/conf/elevate.xml
D	conf/solr-biblio/works/conf/mapping-ISOLatin1Accent.txt
D	conf/solr-biblio/works/conf/protwords.txt
D	conf/solr-biblio/works/conf/schema.xml
D	conf/solr-biblio/works/conf/scripts.conf
D	conf/solr-biblio/works/conf/solrconfig.xml
D	conf/solr-biblio/works/conf/spellings.txt
D	conf/solr-biblio/works/conf/stopwords.txt
D	conf/solr-biblio/works/conf/synonyms.txt
D	conf/solr-biblio/works/conf/xslt/example.xsl
D	conf/solr-biblio/works/conf/xslt/example_atom.xsl
D	conf/solr-biblio/works/conf/xslt/example_rss.xsl
D	conf/solr-biblio/works/conf/xslt/luke.xsl
</pre>
</details>
<br><br>

<details>
<summary>Here are some notes about why I deleted some files</summary>
<pre>
- [x] `conf/services.ini`: Removed references to a solr service which set solr home to solr-biblio . This whole file looks like it might be dead; is it used anywhere?
- [x] `scripts/setup_solr.py`: Installs solr 1.4.0; gonna assume dead
- [x] `scripts/solr.sh`: solr service; set solr home to be solr-biblio
- [x] `scripts/install_ol.py`: Calls `scripts/setup_solr.py`, so this must be dead as well
- [x] `openlibrary/solr/index_works.py`: Posts to `'http://localhost:$1/solr/works/update'`; that URL won't work anymore
  - not referenced by any other files
- [x] `openlibrary/solr/index_data.py`: Uses `http://localhost:$2/solr/(publishers|authors)`
  - not referenced by any other files
- [x] `openlibrary/solr/post_authors.py`: Posts to `http://localhost:8983/solr/authors/update`
  - not referenced by any other files
- [x] `openlibrary/solr/update.py`: Uses `http://ol-solr:8983/solr/works/select`
  - referenced by: `scripts/solr_author_merge.py` and `scripts/solr_update.py`
- [x] `scripts/solr_update.py`: Uses `openlibrary/solr/update.py`
  - not referenced by any other files
  - (archived script instead of deleted)
- [x] `scripts/solr_author_merge.py`: Uses `openlibrary/solr/update.py`
  - not referenced by any other files
  - (archived script instead of deleted)
- [x] `openlibrary/solr/work_post.py`: Uses `http://localhost:8983/solr/works/update`
  - not referenced by any other files
</pre>
</details>

### CODE REVIEW

**Comment by tfmorris** [comment]
I don't know if there's any risk that there's other code using these functions/methods, but removing things like def get_works_solr() is a breaking change.

I didn't do an exhaustive review, but, other than the above, things looked fine and you've got the safety net of source control if you need to get something back.

**Comment by cdrini** [comment]
There is a *high* risk of other code using these function/methods :) But I've used every tool at my disposal (mostly PyCharm's "Find references to" feature and lots of "Search All"s) to make sure I fixed any broken references 👍

**Comment by mekarpeles** [comment]
Still processing this one. If I can get additional sets of eyes from the community that would be fantastic

**Comment by tfmorris** [comment]
I've gone through a bit more carefully and am satisfied except for one question.

 Are there up-to-date equivalents or the scripts - `scripts/setup_solr.py`, `solr.sh`,  & `install_ol.py` somewhere else? Should these be updated (or marked as needing an update) to a current version of SOLR instead of being deleted? They sound useful for the dev environment unless they're obsolete.

**Comment by cdrini** [comment]
Thanks for the review, @tfmorris ! Checked out those files, and they look like they're obsolete:

- `scripts/setup_solr.py`: obsolete; the file downloads solr and creates the solr cores. Currently, the dev env uses solr-tomcat which does this stuff automatically and is installed by `bootstrap.sh`.
- `solr.sh`: obsolete; start/stop/restart service which starts the solr server. This is done by solr-tomcat now, I believe.
- `install_ol.py`: obsolete; It looks like this is the previous incarnation of `bootstrap.sh`.

@mek let me know if you have any specific concerns; this is a pretty low-risk merge as far as I'm concerned. Although don't merge it just yet; I need to update this to reflect the recently merged PRs; I know one of mine definitely used one of the methods this PR removed.

**Comment by cdrini** [comment]
Whoops, @mekarpeles :P (I'm pretty sure I've always used `@mek` on GitHub until now)

Alright rebased and fixed the function call; squashed the commit since it was a onliner. Let me know if there's anything you want clarification on!

**Comment by mekarpeles** [comment]
This lgtm!

**Pull request merged**
