### PR TITLE
Revert persona research banner code

### PR DESCRIPTION
**Pull request by jimchamp**
Reverts nearly all of #8192.  Only the changes to the `s3_loan_api` function remain.

### CODE REVIEW

**Comment by mekarpeles** [comment]
LGTM, looks like we have one mypy issue?

```
openlibrary/catalog/get_ia.py:25: error: Item "None" of "Response | None" has
no attribute "status_code"  [union-attr]
                if error.response.status_code in (403, 404, 416):
```

Not sure if related to this PR

**Comment by cdrini** [comment]
@mekarpeles Unrelated ; merging this one through since I'm about to deploy and would love to get this fix in!

**Comment by cdrini** [comment]
Oh shoot just saw this hadn't been tested yet! I'll take a look on staging before deploying :+1:

**Comment by cdrini** [comment]
Testing can log in successfully on staging!

**Pull request merged**
