### PR TITLE
Added: Cache control header & defer taf to IA CDN requests & their script

### LINKED ISSUE #8927: No `Cache-Control` headers on IA CDN requests
### Problem

These two JS load on every page: https://openlibrary.org/cdn/archive.org/donate.js and. https://openlibrary.org/cdn/archive.org/analytics.js

However, they are not cached like the rest of the JS.
This causes a lot (2 seconds) delay when on a very slow connection (only a few 100ms on a decent connection).

Their headers:
```
Content-Encoding: gzip
Content-Type: text/javascript
Date: Wed, 20 Mar 2024 11:48:52 GMT
Referrer-Policy: no-referrer-when-downgrade
Server: nginx/1.18.0 (Ubuntu)
Vary: Accept-Encoding
X-Ol-Stats: ""
```

Headers for all other requests:
```
Cache-Control: max-age=315360000
Content-Encoding: gzip
Content-Type: application/javascript
Date: Wed, 20 Mar 2024 11:03:17 GMT
Etag: W/"65e78c3f-69215"
Expires: Thu, 31 Dec 2037 23:55:55 GMT
Last-Modified: Tue, 05 Mar 2024 21:18:55 GMT
Referrer-Policy: no-referrer-when-downgrade
Server: nginx/1.18.0 (Ubuntu)
```

#### Evidence / Screenshot
image

### Reproducing the bug

_No response_

### Context

_No response_

#### Proposal & constraints

Add cache control headers.

Probably should also add `defer` or `async` to their script tags so they don't block loading when they're not cached but this could be a different issue.
https://javascript.info/script-async-defer

#### Related files

https://github.com/internetarchive/openlibrary/blob/45ed08186221233c04f1859e3b8a703152b01539/openlibrary/plugins/openlibrary/code.py#L425-L430

https://github.com/internetarchive/openlibrary/blob/45ed08186221233c04f1859e3b8a703152b01539/openlibrary/templates/site/footer.html#L41-L42

https://github.com/internetarchive/openlibrary/blob/45ed08186221233c04f1859e3b8a703152b01539/openlibrary/plugins/upstream/utils.py#L1468-L1469

#### Stakeholders

PS: I don't have bandwidth to take this right now.

### PR DESCRIPTION
**Pull request by QuantuM410**
Closes #8927 

This PR adds a cache header to IA CDN requests and provides a defer script tag to the respective scripts

### Testing

- On your browser's network, check for the Request Header to the analytics.js & donate.js to check for Cache-Control header
- Check the duration of the request and response to be relatively less as the defer tag runs the requests in the background instead and loads them once DOM content loaded
### Screenshot

image

### Stakeholders

@RayBB

### CODE REVIEW

**Comment by RayBB** [comment]
Can you please explain why you chose defer vs async for each of the scripts? We should investigate which is best. @QuantuM410

**Comment by QuantuM410** [comment]
@RayBB From what I understood using async and defer does the same job just async doesnt have an order of execution as well as it executes stuff in the background and then doesnt wait while defer wait for the loading of DOM. Async would have been fine if both the files work independently I think and I was not really sure if thats the case hence I used ```defer```. Moreover I think from what I think analytics.js posts the site's analytics data and is independent while donate.js seems to be dependent (as it displays a donation banner?).

**Comment by RayBB** [comment]
@QuantuM410 that makes sense, good explanation.

Can you do a comparison of the page load time on regular internet and "slow 3g" (or similar in your dev tools) of the before and after? So screenshots of:
* Slow 3g before
* slow 3g after change
* regular internet before
* regular internet after

For each request we should already have the loaded the page once before so the scripts are cached. You might need to clear your cache between each screenshot so it's not accidentally left in cache for the "before" tests.

Thanks!

**Comment by QuantuM410** [comment]
> @QuantuM410 that makes sense, good explanation.
> 
> Can you do a comparison of the page load time on regular internet and "slow 3g" (or similar in your dev tools) of the before and after? So screenshots of dev tools loading times of:
> 
> * Slow 3g before
> * slow 3g after change
> * regular internet before
> * regular internet after
> 
> For each request we should already have the loaded the page once before so the scripts are cached. You might need to clear your cache between each screenshot so it's not accidentally left in cache for the "before" tests.
> 
> Thanks!

Hey @RayBB ! I did a page load time comparison and I feel adding defer didn't do much and also @cdrini quotes about removing defer from the analytics script as its being further used in a script, moreover I felt this needed a bit more discussion hence I have removed the tags as for now as I am a bit confused :)

Here are the results

No throttling (before)
Screenshot from 2024-03-22 23-48-01

No throttling (after)
Screenshot from 2024-03-22 23-40-54

slow-3g (before)
Screenshot from 2024-03-22 23-47-38

slow-3g (after)
Screenshot from 2024-03-22 23-41-48

PS: I tested it after removing defer from analytics.js script. I didn't really find any significant change after observing it

**Comment by RayBB** [comment]
@QuantuM410 @cdrini I did [some testing](https://www.loom.com/share/013e05e37a174419a7e6a0c082003edc) of my own and here are the results:

|            | No Throttle | Fast 3G | Slow 3G |
| ---------- | ---------- | ------- | ------- |
| Caching    | 0.47       | 1.07    | 2.60    |
| No Caching | 0.51       | 1.71    | 4.76    |

Overall, we are seeing a very nice improvement in speed when on slow connections :)

@QuantuM410 I think your results are different because the cache is disabled in the devtools.

@cdrini how long do you think the cache time should be? I think one day is very safe but I'm really not sure how likely those libraries are to change.

@QuantuM410 I'll guess that we should only cache for one day in case those libraries do change. So maybe make that change and if Drini agrees he'll merge it and if not he'll ask for a different duration.

**Comment by QuantuM410** [comment]
> @QuantuM410 @cdrini I did [some testing](https://www.loom.com/share/013e05e37a174419a7e6a0c082003edc) of my own and here are the results:
> 
> No Throttle	Fast 3G	Slow 3G
> Caching	0.47	1.07	2.60
> No Caching	0.51	1.71	4.76
> Overall, we are seeing a very nice improvement in speed when on slow connections :)
> 
> @QuantuM410 I think your results are different because the cache is disabled in the devtools.
> 
> @cdrini how long do you think the cache time should be? I think one day is very safe but I'm really not sure how likely those libraries are to change.
> 
> @QuantuM410 I'll guess that we should only cache for one day in case those libraries do change. So maybe make that change and if Drini agrees he'll merge it and if not he'll ask for a different duration.

Ah I though I needed to test the page load storing no cache for each cdn request to test the feasibility of ```defer``` tag :). Great then @RayBB I have updated the cache age to 1 day

**Review by RayBB — APPROVED** [review]

**Pull request merged**
