### PR TITLE
updated messages.pot, updated messages.po for all languages, added german translations and changed som occources of term master to primary

### PR DESCRIPTION
**Pull request by bitnapper**
- updated messages.pot
- updated messages.po for all languages (Issue #5767 )
- added german translations and
- changed som occources of term master to primary

Some German translations could be not ideal and I couldnt figure out inclusive scentences in every translation but I'm happe to fix it later.

### CODE REVIEW

**Comment by mekarpeles** [comment]
@bitnapper thank you for contributing i18n upgrades!

Feedback for us moving forward, when we're adding translations for a language, let's please try to (a) update just the language file we're working on step/commit [this PR may be an exception because an ID changed] and (b) in a separate commit update the translations for a specific language.

This is general advice which I think has come up before, however I'll let @jimchamp review and offer more specific feedback.

In this case, @jimchamp can take it over the finish line.

**Comment by bitnapper** [comment]
@mekarpeles I can try to split it into seperate pull request but I've to figure hout how to reset the changeset without loosing the changes.

**Comment by jimchamp** [comment]
@bitnapper after a quick look, I think that this PR is in pretty good shape --- no need to split it up.  I plan on reverting the non-German `.po` file changes and giving this a closer look within a day's time.

**Comment by jimchamp** [comment]
I was able to make the changes on my machine, but was not able to push them to your branch.  If you are using git in the command line, you can run the following commands to make the necessary changes:

```
# Switch to this PR's branch:
git checkout master

# Reference codebase prior to the most recent commit:
git reset HEAD~

# Stage only German language changes
git add openlibrary/i18n/messages.pot openlibrary/i18n/de/messages.po openlibrary/templates/merge/authors.html openlibrary/templates/recentchanges/merge-authors/comment.html

# Commit the changes (feel free to change the message, if you'd like):
git commit -m "Update German translations"
```

Afterwards, push the changes to your remote GitHub repo.

Hopefully this is helpful.  I'll send you a message on Slack so that you can quickly reach me if the instructions are unclear.

**Comment by bitnapper** [comment]
Thank you @jimchamp for your help. It was easier for creating a completely new PR. Hope [#5927](https://github.com/internetarchive/openlibrary/pull/5927) is a better fit.

**Pull request closed without merging**
