### PR TITLE
don't render works w/ 1 edition as special cases

### PR DESCRIPTION
**Pull request by mekarpeles**
> **Description**: What does this PR achieve? [feature|hotfix|refactor]

Related to #684 

When a work only has 1 edition, it renders a page which is neither a work page nor an edition page. This PR changes that by forcing such work pages to render like an edition (even though the url still shows the work url). This:

- is a big ui improvement
- makes the experience less jarring for users
- moves us away from moving 3 separate experiences (to 2)

> **Technical**: What should be noted about the implementation?

I tested "want to read" button as well to ensure things still work when a work is rendered as an edition.

> **Testing**: Steps for reviewer to reproduce / verify this PR fixes the problem?

Go to a `work` page for a book which only has 1 edition, e.g.:
https://openlibrary.org/works/OL14866014W/Arnold_Schwarzenegger v.
https://dev.openlibrary.org/works/OL14866014W/Arnold_Schwarzenegger

cc: @tabshaikh @leadsondog @seabelis @tfmorris @jdlrobson @hornc

### CODE REVIEW

**Comment by cdrini** [comment]
Gah, I feel like this is really in the wrong direction :( Last I remember, the plan was to make all work pages the same (i.e. works with one edition would show the table of editions just like all works). I feel like this is way more confusing, because you can't tell if it's a work page or an edition page. Also, the "1 edition" link now looks broken since it just returns you to the same page. Also, consider the case where I share this link. If another edition is added, the page changes _completely_, and now I've shared a different page entirely, because I shared a _work_ link when I meant to share the edition link, but because the pages looked identical **temporarily**, I didn't realize I was sharing the wrong thing. Like you said: "render like an edition (even though the url still shows the work url)". This is misleading; you're violating user expectations when any two "work" links point to two entirely different pages.

Has something changed since we discussed this a few months ago? I haven't been to the group calls in a while, so was there a discussion where we decided to do this instead? Why? I feel bad because it seems like a lot of time was put into this PR, but I really don't think this is the right way to go :(

**Comment by tabshaikh** [comment]
@cdrini Our principle towards moving towards canonical books page was:
1. 1 edition per language per work, prioritizing books we have digitized
2. /works pages will become a redirect page to an edition 
as shown in this wiki https://github.com/internetarchive/openlibrary/wiki/Canonical-Books-Page and it was this only which we discussed in the earlier meetings :) . But you have pointed out an important issue about sharing a 1 edition work which would create problems if another edition is added. We should discuss this with everyone

**Comment by LeadSongDog** [comment]
It feels like @cdrini hit the mark.  The wiki which @tabshaikh linked shows a lot of question marks. Perhaps before pouring more effort into coding, a little more discussion there of what to accomplish would be in order.  Even the title is suspect: should it not be the Canonical editions page if we want it to suggest one edition of a work in preference to others?

**Comment by mekarpeles** [comment]
@LeadSongDog @cdrini @hornc your feedback was all heard! That's why the review was open and not merged :P

I spoke with @hornc and we're taking the approach of removing the special purpose template and just rendering the vanilla work page with a table having a single edition entry as the resolution.

The urls in the original PR should show you what these look like on prod v. dev respectively.

Thanks all!

**Comment by tfmorris** [comment]
I tried clicking on those links, but all I got was a giant begging banner which took up most of my screen.

I'm OK with merging from 3 displays to 2 and even (perhaps, depending on the implementation), switching from the default search landing page being a work to being an edition, but that presupposes that we fix a whole bunch of other stuff first -- e.g. we can tell which edition is must appropriate for the user, we have a good way of ranking/ordering other editions which might be nearly as appropriate, we don't ram some arbitrary notion of someone else's "best" (IA, I'm looking at you) down the users' throats, etc.

Removing the special case and just showing the work page, regardless of how many editions there are, seems like a good first step. People will still be confused by us hiding the edition that they searched for and we know about, but aren't in the special default "ebooks" filter, or just burying "their" edition 200 editions down in the list, but we can deal with that separately.

**Comment by mekarpeles** [comment]
If there are no complaints, I'm going to merge

**Pull request merged**
