### PR TITLE
refactor: remove Python 3.8 references

### PR DESCRIPTION
**Pull request by dhruvmanila**
Subtask of: #5128 

This PR removes the reference of Python 3.8 from the following files:
- `.github/workflows/python_tests.yml`
- `.pre-commit-config.yaml`
- `.python-version`
- `docker/Dockerfile.olbase`
- `docker/Dockerfile.oldev`
- `docker/README.md`

Closes #

### Stakeholders

@cdrini @cclauss

### CODE REVIEW

**Review by cclauss — APPROVED** [review]
LGTM

**Comment by cdrini** [comment]
Taking this one since I've been communicating with @dhruvmanila on the given issue :+1:

**Review by cdrini — COMMENTED** [review]
Looking good! One small change: the `solr-updater`s in the  docker-compose files that set `PYENV_VERSION` to 3.9.4 ; we can now remove those variables entirely \o/ Also the Dockerfile of the `solr_builder`

**Review by cdrini — APPROVED** [review]
Nice, thank you @dhruvmanila ! Lgtm. Not testing since nothing looks like it could break too badly.

**Pull request merged**
