### PR TITLE
Add book talks to browse menu

### LINKED ISSUE #7598: Add "Book Talks" to the browse menu
### Describe the problem that you'd like solved

Book Talks should be added to the main Browse dropdown and go to the url https://openlibrary.org/booktalks

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/lib/nav_head.html#L23-L31

After `k-12` and before `random`.

The `track` value (for google analytics) should be `BookTalks`

### PR DESCRIPTION
**Pull request by JaydenTeoh**
Closes #7598 

Added "Book Talks" to browse menu

### Screenshot

image

### Stakeholders

@mekarpeles created issue

### CODE REVIEW

**Comment by mekarpeles** [comment]
change lgtm -- throwing on testing.openlibrary.org to confirm

**Comment by tfmorris** [comment]
Since that's just a redirect, I suggest using the redirect target, https://archive.org/details/booktalks, instead.

**Comment by JaydenTeoh** [comment]
@tfmorris @mekarpeles Sure thing, I have changed the href target to the direct url instead!

**Comment by mekarpeles** [comment]
It is just a redirect, but I prefer we stick with the original openlibrary link for now to keep things consistent on the menu.

This lgtm -- ty!

**Pull request merged**
