### PR TITLE
Replace simplejson with json in openlibrary/plugins (except plugins/u…

### PR DESCRIPTION
**Pull request by dherbst**
…pstream) for 2308

Addresses #2308

Refactor to replace simplejson with json in `openlibrary/plugins` except for `openlibrary/plugins/upstream`.  Will address `upstream` separately.

### Technical

Also change `simplejson.JSONDecodeError` to `ValueError` because `JSONDecodeError` does not exist in the `json` package.

### Testing

Unit tests pass.

### Screenshot

N/A

### Stakeholders

@cclauss

### CODE REVIEW

**Comment by cclauss** [comment]
Please change the variable `json` --> `json_data` so that it does not collide with the module name in these files:
https://github.com/internetarchive/openlibrary/pull/4298/checks?check_run_id=1571227485#step:13:8

**Review by cclauss — APPROVED** [review]
I reverted changes to: `openlibrary/core/helpers.py` and `openlibrary/plugins/worksearch/code.py` which we should revisit in two separate PRs.

**Comment by cclauss** [comment]
Nice work!!  We are getting there.  Please open three single file PRs for:
1. openlibrary/core/helpers.py
2. openlibrary/plugins/worksearch/code.py
3. openlibrary/plugins/ol_infobase.py

**Comment by dherbst** [comment]
The PR for code.py was submitted.  The other two were addressed by other PRs and do not need subsequent PRs.

**Pull request merged**
