### PR TITLE
Create docker-compose for infogami local

### LINKED ISSUE #3690: Docker-compose.yml: conditionally mount a volume
I am frustrated when I want to test OpenLibrary on Python 3 that I always forget to create a new branch from master and then [remove that pesky volume comment](https://github.com/internetarchive/openlibrary/blob/master/docker-compose.yml#L31) for vendor/infogami in the docker-compose.yml file.

Would it be possible to conditionally mount that volume if and only if $PYENV_VERSION was 3.8.5?
https://stackoverflow.com/questions/41777643/mount-a-volume-in-docker-compose-conditionally

This same technique might also allow building `olbase` locally vs. downloading it from Docker Hub.

### PR DESCRIPTION
**Pull request by cdrini**
Closes #3690

### Stakeholders
@cclauss

### CODE REVIEW

**Comment by cdrini** [comment]
I didn't quite have time to test this; would you be able to see if it works, @cclauss ?

**Comment by aasifkhan7** [comment]
@cdrini @cclauss I tested this - and it works. :)
I edited the python version in `docker-compose.yml` to `3.8.5` and ran 
`docker-compose -f docker-compose.yml -f docker-compose.infogami-local.yml up`
and the volume was mounted as well as the python version was `3.8.5`

**Comment by cclauss** [comment]
@aasifkhan7 Please click ___Files changed___ above and then click ___Review changes___ at the upper right of the screen and then __Approve__ or __Request chages__.  Positive reviews give maintainers confidence that you have looked through the changes and you believe that merging this PR would help the project.  Thanks!

**Comment by aasifkhan7** [comment]
Sure @cclauss !! Done. 😄

**Comment by cdrini** [comment]
Yaay! Thanks for helping test folks :) No more local changes 🎉

**Pull request merged**
