### PR TITLE
add link for changing browser prefs

### PR DESCRIPTION
**Pull request by ralevbb**
Closes #<IssueNumber>

<Optional Picture>

## Description:
In this Pull Request we have made the following changes:

### CODE REVIEW

**Comment by ralevbb** [comment]
img-20181005-wa0007

**Comment by ralevbb** [comment]
No

**Comment by mekarpeles** [comment]
What's going on in this thread?..

**Comment by mekarpeles** [comment]
@hornc please re-open when you're ready :)

**Pull request closed without merging**
