### PR TITLE
Partner Imports: Detect low quality publishers

### LINKED ISSUE #6573: Block import from these notebook publishers
@RayBB Found a number of notebook publishers adding noise to our db. Let's create an exclude list to make sure they don't ever get auto imported!

https://openlibrary.org/authors/OL7546088A/Jeryx_Publishing
https://openlibrary.org/authors/OL9607236A/Razal_Koraya
https://openlibrary.org/authors/OL9228328A/Mitch_Allison
https://openlibrary.org/authors/OL9206862A/Punny_Cuaderno
https://openlibrary.org/authors/OL8380258A/Tobias_Publishing

### Relevant code

https://github.com/internetarchive/openlibrary/blob/6ef617b3b616bbcf562fd6aff5189f176e07a8d2/scripts/partner_batch_imports.py#L173-L179

### Stakeholders
@RayBB

### LINKED ISSUE #6604: Block imports matching (title:(illustrated OR annotated OR annoté) AND publisher:Independently Published))
These add loads of useless noise to our classics: eg https://openlibrary.org/search?q=inutile+maupassant&mode=everything

Here's what matches: https://openlibrary.org/search?q=title%3A%28illustrated+OR+annotated+OR+annot%C3%A9%29+AND+publisher%3AIndependently+Published&mode=everything . 25k records of spam!

This subquery should probably have all matches deleted: https://openlibrary.org/search?q=title%3A%28illustrated+OR+annotated+OR+annot%C3%A9%29+AND+publisher%3A%22Independently+Published%22+AND+first_publish_year%3A%5B2018+TO+*%5D&mode=everything . Added to the deletion queue spreadsheet.

### Related files

https://github.com/internetarchive/openlibrary/blob/6ef617b3b616bbcf562fd6aff5189f176e07a8d2/scripts/partner_batch_imports.py#L173-L179

### Stakeholders
@seabelis @LeadSongDog

### PR DESCRIPTION
**Pull request by cclauss**
Closes #6573
Closes #6604

Create a set of `LOW_QUALITY_PUBLISHERS` (is there a better name? SPAM_PUBLISHERS?) and then for each book create a set of publishers.  IF there is `notebook` in the book's title AND there is an intersection between the two sets THEN it is a low-quality book that we should not import.

### Testing

See: `scripts/tests/test_partner_batch_imports.py`
```
>>> a = {p.casefold() for p in ["razal", "tobias publishing", "koraya", "pickleball", "d"]}
>>> b = {p.casefold() for p in ["hol", "mad", "mazz", "mikemi", "tobias publishers"]}
>>> c = {p.casefold() for p in ["pickleball publishing"]}
>>> a & low_quality_publishers
{'tobias publishing'}
>>> b & low_quality_publishers
set()
>>> c & low_quality_publishers
{'pickleball publishing'}
```

### CODE REVIEW

**Review by RayBB — APPROVED** [review]
I really like this approach!

**Comment by cdrini** [comment]
Can you remove the last commit? It looks like an autoformatter ran with it and I can't see the diff anymore

**Comment by cclauss** [comment]
All quotes restored.  Created #6624 to avoid quote grief on future pull requests until the following to #6612 has landed.

**Review by cdrini — APPROVED** [review]
Ok! I believe this should do the trick. Notable changes I made:

1) These publishers are actually (confusingly) imported as _authors_ ; so check the authors field
2) `created` isn't on the record; `publish_date` is the field we seek
3) The publisher-author exclude list is a hard exclude; it doesn't require the title to contain anything. Those publisher-authors should always be excluded

Let me know if anything looks off! If all is good, please feel free to merge :)

**Pull request merged**
