### PR TITLE
Improved Documentation Structure for New Contributors

### PR DESCRIPTION
**Pull request by CodeMaverick2**
# Issue-link -> https://github.com/internetarchive/openlibrary/issues/9091#
## Summary
This PR improves the structure of the README.md file by adding a dedicated "Contributing" section. This section provides a brief introduction to the various ways volunteers can contribute to the Open Library project, making it easier for new contributors to get started and understand how they can help. The changes aim to make the documentation more organized and user-friendly.

## Changes Made
1. **Added a "Contributing" Section in README.md**:
   - Created a new section titled "Contributing" in the README file.
   - Provided a brief introduction to the various ways contributors can participate (e.g., developers, designers, librarians).
   - Included links to relevant documents and pages for each type of contributor:
     - Developers: Linked to `CONTRIBUTING.md`.
     - Librarians: Linked to the [volunteer page](https://openlibrary.org/volunteer).
     - Designers: Suggested checking specific issues.
   - Mentioned the different types of community calls and provided a link to the community call page for more details.

2. **Updated Table of Contents**:
   - Added the new "Contributing" section to the Table of Contents in the README file for better navigation.

## Reason for Changes
These changes are intended to make the README file more informative and welcoming for new contributors. By providing a clear overview of the various ways to contribute and linking to the appropriate resources, we aim to streamline the onboarding process and encourage more community participation.

## Updated Readme screenshot-
Screenshot from 2024-07-16 12-21-24

### CODE REVIEW

**Review by scottbarnes — COMMENTED** [review]
Thanks for this, @CodeMaverick2. I'm not able to leave a suggestion on unedited lines, but the only change I've got to suggest is to edit line 23 so it says:
```diff
-   - [Contributing](CONTRIBUTING.md)
+   - [Contributing](#contributing)
```

**Comment by CodeMaverick2** [comment]
> Thanks for this, @CodeMaverick2. I'm not able to leave a suggestion on unedited lines, but the only change I've got to suggest is to edit line 23 so it says:
> 
> ```diff
> -   - [Contributing](CONTRIBUTING.md)
> +   - [Contributing](#contributing)
> ```

@scottbarnes  I will get that fixed is there something more or is the issue solved and can be merged

**Comment by CodeMaverick2** [comment]
@scottbarnes  Updated what you told in this PR

**Comment by scottbarnes** [comment]
Closing in favor of #9571.

**Pull request closed without merging**
