### PR TITLE
Disable gitpod master branch prebuilds

### PR DESCRIPTION
**Pull request by cdrini**
https://gitpod.io/#https://github.com/internetarchive/openlibrary/ always errors :/ Disable the prebuild.

### Testing
Won't be able to test until merged.

### Stakeholders
@cclauss @RayBB

### CODE REVIEW

**Comment by cdrini** [comment]
Auto-merging; small change only affects gitpod.

**Comment by RayBB** [comment]
Bummer that it was getting problems like that in just the prebuild phase.
Any theories on why?

**Comment by cdrini** [comment]
The error I saw earlier was something about `/work doesn't exist` :/ (I should've taken a screenshot!) I think one of the commands in .gitpod.yml caused this, because the prebuild environment has a different file structure? But also the prebuild was suuuuuper slow to download, and give like 0 visual feedback while it was downloading. It's faster to just do a fresh docker pull.

**Comment by cdrini** [comment]
Oh, now it works! Previously clicking the "open in GitPod" button on the README would try to use the prebuild and error. Now it doesn't! 🚀

**Pull request merged**
