### PR TITLE
pyupgrade + black on `/tests`

### PR DESCRIPTION
**Pull request by jimman2003**
Progress toward #4776 using pyupgrade + black

Related to #5839

fix 
### Technical

Haven't tested locally (dev env broke)
### Testing

Test the changed files :)
### Stakeholders

@dhruvmanila

### CODE REVIEW

**Comment by cdrini** [comment]
Would you be able to take a look at this one, @dhruvmanila ?

**Comment by dhruvmanila** [comment]
Yeah sure!

I believe all of the changes can be made automatically using `pyupgrade`. Did you do it using that tool?

**Comment by jimman2003** [comment]
Yes!

**Comment by jimman2003** [comment]
the command I run was pyupgrade openlibrary/* --py3-only

**Comment by cclauss** [comment]
We run on Python 3.9 so let's try for `pyupgrade --py39-plus`

**Comment by jimman2003** [comment]
pyupgrade on the test admittedly only changed one line ,  hence the batching

**Comment by cdrini** [comment]
(rebased)

**Comment by cdrini** [comment]
Question: What line length did you use, @jimman2003 ? I forget, what number do we use for the codebase, @cclauss ?

**Comment by cdrini** [comment]
Sending this one over to you @cclauss now that we have a linting master plan :)

**Review by cclauss — CHANGES_REQUESTED** [review]
A few issues to address.

**Comment by cclauss** [comment]
> Question: What line length did you use, @jimman2003 ? I forget, what number do we use for the codebase, @cclauss ?

Black loves `--max-line-length=88` so let's run black without config changes and use 88 as our ___eventual___ target.  The new `scripts/flake8-diff.sh` temporarily uses `--max-line-length=256` to quiet those checks.  Please do not abuse this because soon we will move back to 88 for flake8 too and there will be a manual process to wrap all lines to that.

**Pull request merged**
