### PR TITLE
Fixed i18n syntax errors by removing \$_("") in 2 files

### LINKED ISSUE #9097: `i18n` syntax appears on offline error page
### Problem

In the development version of the site, the OL [static offline page](https://github.com/internetarchive/openlibrary/blob/master/static/offline.html) currently shows the internationalization (`i18n`) syntax function to the user.

This is likely because the page is static HTML, and does not have access to the Python `gettext` function that the `$_(" ")` is supposed to call, so there is no need to use the syntax.

#### Evidence / Screenshot
OL_OfflinePage

#### Relevant URL(s)
- `i18n` docs: https://github.com/internetarchive/openlibrary/wiki#Internationalization

### Reproducing the bug

1. Go to any page on the Open Library site (dev version)
2. Turn off your wifi

* Expected behavior (as in live site):
OL_ProdOfflinePage

* Actual behavior:
(see above)

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): 
- Environment (prod, dev, local): dev/local

#### Proposal & constraints

Very simple fix! Simply removing the `$_(" ")` and `$_(' ')` from the lines below should solve the problem!
https://github.com/internetarchive/openlibrary/blob/e8ea2bacc63f491e619747437bc9b91006a222e8/static/offline.html#L16-L19

#### Related files

[static/offline.html](https://github.com/internetarchive/openlibrary/blob/master/static/offline.html)
[static/status-500.html](https://github.com/internetarchive/openlibrary/blob/master/static/status-500.html) - likely rendering with the same issue

### PR DESCRIPTION
**Pull request by Tzinapapadopoulou**
Closes #9097 

fixed a syntax bug 

### Technical

removing the $_(" ") and $_(' ') from the necessary lines (the page is static HTML, and does not have access to the Python gettext function that the $_(" ") is supposed to call, so there is no need to use the syntax)
### Testing

npm test passed

### CODE REVIEW

**Comment by Tzinapapadopoulou** [comment]
Also, i had already made a small change in the Readme.md file that refers to #9091 issue and had merged a pull request so the changes also passed to this commit.

**Comment by rebecca-shoptaw** [comment]
Hi @Tzinapapadopoulou ! Great start here -- the changes to `offline.html` and `status-500.html` look perfect! A few other things to address, though:

A. If you could remove the `README` change from this PR, that would be great. To keep everything clear and organized and make sure that the approval process works properly, we like to limit the scope of each PR -- we'll want to give whoever is assigned to review your markdown issue the opportunity to assess/give feedback on that solution. :) 
B. As you can see from the "changed files" it looks like a number of other changes have been accidentally bundled into your commit, which is likely what's causing the Python tests to fail.
Here's a process for fixing that (and you can see more in the [OL Git documentation](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-updates-to-your-pull-request)):
  1. Switch to your master branch (`git switch master`)
  2. Pull in the current version of the Open Library master branch (`git pull upstream master`)
  3. Push the changes to your remote master branch (`git push origin master`) -- you may need to force-push if this fails, i.e. `git push -f origin master`
  4. Switch to your branch for the fix (`git switch 9097/hotfix/fixing_...`) 
  5. Rebase to match the new master branch (`git rebase -i master`)
* Here, you'll see a list of commits to pick/drop, you can change the text to "drop" for any commit unrelated to this PR (i.e. affecting a file other than `offline.html` or `status-500.html`), then close the file
* If you still have merge conflicts to resolve after this and/or you can see that your commit is still changing files other than `offline.html` and `status-500.html` -- you can see a commit's changed files in "Outgoing" in the VSCode source control tab -- I'd recommend doing:
  * `git rebase --abort` (stops the rebase in progress if necessary)
  * `git reset --soft HEAD~1` (undoes your commit)
  * Revert any staged changes unrelated to the PR 
  * Try rebasing again (`git rebase -i master`)
  * Re-commit (`git commit -m "[your message]"`)
  * Push changes to your remote branch, you'll almost certainly need to force-push here (`git push -f origin HEAD`)
 
Let me know if you have any questions!

**Review by rebecca-shoptaw — CHANGES_REQUESTED** [review]
Hi @Tzinapapadopoulou ! Great start here -- the changes to `offline.html` and `status-500.html` look perfect! A few other things to address, though:

A. If you could remove the `README` change from this PR, that would be great. To keep everything clear and organized and make sure that the approval process works properly, we like to limit the scope of each PR -- we'll want to give whoever is assigned to review your markdown issue the opportunity to assess/give feedback on that solution. :) 

**Note**: To keep your PRs from affecting each other and to keep your master branch in sync with the current OL master branch, you want to avoid merging in any of your PR branches yourself -- once they've been successfully approved and merged into the OL master branch, you can pull them into your master through the `git pull upstream master` process! For now, hopefully the rebase process listed below should successfully remove the `README` changes (and any other unrelated ones) from this commit.

B. As you can see from the "changed files" it looks like a number of other changes have been accidentally bundled into your commit, which is likely what's causing the Python tests to fail.
Here's a process for fixing that (and you can see more in the [OL Git documentation](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-updates-to-your-pull-request)):
  1. Switch to your master branch (`git switch master`)
  2. Pull in the current version of the Open Library master branch (`git pull upstream master`)
  3. Push the changes to your remote master branch (`git push origin master`) -- you may need to force-push if this fails, i.e. `git push -f origin master`
  4. Switch to your branch for the fix (`git switch 9097/hotfix/fixing_...`) 
  5. Rebase to match the new master branch (`git rebase -i master`)
* Here, you'll see a list of commits to pick/drop, you can change the text to "drop" for any commit unrelated to this PR (i.e. affecting a file other than `offline.html` or `status-500.html`), then close the file
* If you still have merge conflicts to resolve after this and/or you can see that your commit is still changing files other than `offline.html` and `status-500.html` -- you can see a commit's changed files in "Outgoing" in the VSCode source control tab -- I'd recommend doing:
  * `git rebase --abort` (stops the rebase in progress if necessary)
  * `git reset --soft HEAD~1` (undoes your commit)
  * Revert any staged changes unrelated to the PR 
  * Try rebasing again (`git rebase -i master`)
  * Re-commit (`git commit -m "[your message]"`)
  * Push changes to your remote branch, you'll almost certainly need to force-push here (`git push -f origin HEAD`)
* OR if the rebase worked, you have no merge conflicts to resolve, and you can confirm by looking at the commit's changed files that the only changes are to `offline.html`, `status-500.html`:
  * Push changes to your remote branch, you'll almost certainly need to force-push here (`git push -f origin HEAD`)
 
Let me know if you have any questions!

**Comment by rebecca-shoptaw** [comment]
Oh and a tiny note re: formatting PRs, since this is your first one!
The "Testing" section is where you can list the steps someone testing should take to determine whether your fix worked correctly; for example, if you changed the color of the login button to be blue, it would look like:
1. Log out (if logged in)
2. Go to the login page (/account/login)
3. Login button should be blue now

And then the "Stakeholders" section is where you want to tag anyone who you've been working with on the issue (usually the issue's lead) so that they'll be notified that the PR is ready. :)

**Comment by Tzinapapadopoulou** [comment]
Hello @rebecca-shoptaw , thank you for all the help and guidance. I did all the commands and everything was working until a point, where for some reason in my vendor/infogami file existed a copy of the whole repository again. The suggested solution was git rm --cached , which i did without knowing it would make git ignore these files. I then deleted the "copied" repository in the infogami file and tried to reset the files but i think my push is still ignoring these files and does not pass pythos tests.

**Comment by rebecca-shoptaw** [comment]
Hi @Tzinapapadopoulou ! That's bizarre indeed -- your version of the master branch looks great and up to date though, so maybe since it's such a small change the simplest course of action will be to make a new branch off `master` for this fix, copy over your changes to the relevant file, then open a new PR with just that fix 🙂 

If you want to go that route, you can close this PR (or I can) as soon as a new one is ready!

**Pull request closed without merging**
