### PR TITLE
Remove add_new_field to role/classifications/identifier dead code

### PR DESCRIPTION
**Pull request by jdlrobson**
This code is also dead. It used to serve some commented out lines
in edition.html that added an option to create new types of role.
When the HTML was commented out (more than 8 years ago! in
16bee3ee1af229acbd65f4357843bc114401810c) the frontend should
also have been cleaned up.

Additional change:
Update ol.analytics documentation so it doesn't reference
add_new_field

Closes #

### CODE REVIEW

**Comment by cdrini** [comment]
Hmmm; actually I think would rather bring this back as a librarian-only feature. (so the `<option>` would only display for librarians). My guess would be that it was disabled because it the lists were growing too quickly, but it might be ok if we just limit access. Could you modify this to limit the access to librarian accounts?

**Comment by jdlrobson** [comment]
IMO and from my personal experience if you have dead code you should remove it. You can always restore the code later from git history and there is a huge risk that if you keep it but don't prioritise it it lingers and the rest of the codebase suffers.

I say delete and create a new task pointing to the pull request that removed it to restore jt.

**Comment by cdrini** [comment]
I'll test enabling it to see if it "just works"; otherwise I'll delete :+1:

**Comment by jdlrobson** [comment]
Ping.
Would love to close this one out so I can work on other things.

**Comment by cdrini** [comment]
My apologies; I let this one slide past me. The reason I want to re-enable this code is because I recall in the past modifying the HTML in devtools to show the commented out options, and then using them; that's why I think they'll work without issue. I'll pull this up for today.

**Comment by cdrini** [comment]
Ok, I tried reanimating the code here: #2700 ; to be honest I'm not sure if this feature is worth it, but I'd like to get input from the librarians who would actually use it. Note that if we do decide to delete it, there are number of dangling references that would need to get deleted. Marking this as blocked in the mean time until there's a decision on #2700 .

**Comment by jdlrobson** [comment]
honestly you should just remove this. 8 years is a long time for useful code to be dormant. By all means create an issue to reanimate the code if useful, but this code should be removed.

**Comment by jdlrobson** [comment]
Reminder that this is still open.
Remove dead code. Don't let it pile up :)

**Comment by jdlrobson** [comment]
@cdrini can this be merged now?

**Comment by jdlrobson** [comment]
@mekarpeles @cdrini this is now blocking work by @lephemere 

Can we merge this it's clear fixing this is not a priority since then has been open for a year now... :)

**Comment by mekarpeles** [comment]
I think it's worth biting the bullet and removing. If we wish to re-instate it, the git history is here, someone can open an issue. For now, I think the greater value is not getting stale code out of the way.

**Comment by cdrini** [comment]
Thanks for bringing to my attention; I'll take a look :+1:

**Comment by jdlrobson** [comment]
Bump.

**Comment by mekarpeles** [comment]
This is my fault, during tomorrow's community call, I will make sure it's on the agenda and we have a resolution for updating the thread.

**Comment by cdrini** [comment]
Howdy! I appreciate your self-lessness Mek, but that one's definitely on me; I haven't forgotten about it (it's literally crossed my mind at least once a day for the past month), but all I remember about that PR was that it was contentious, and I didn't have the emotional energy to open that box up again and deal with it. I was aware of this when I set it to a P1 and shouldn't have done so. But: that's why I took some days off last week, and am now feeling nice and recharged :slightly_smiling_face: I'll aim to have it resolved before the end of the week for you, @jdlrobson :+1:

**Comment by cdrini** [comment]
Ok! Went through this. As I remembered, we'd brought this up to the community way back in Dec of 2019 for feedback, whether we should try to re-animate this code, and with input from the librarians decided we wanted to try: https://github.com/internetarchive/openlibrary/pull/2700#issuecomment-564225113

Taking a look at it now, I tried #2700 , and it seems to be not _quite_ working; I'll give it a bit of love (1 hour) to see if it can be patched; if not I think we should remove the code. Note it's not just _this_ code that makes this process, but also code in `addfield.html`, and an endpoint somewhere that handles the form POST request. If we decide to abandon this feature, there will be a number of deletions we need to do.

Sorry again for the delay! Jumping into a meeting now, but I'll have the final update before EOD :+1:

**Comment by cdrini** [comment]
Ok! Looking now

**Comment by cdrini** [comment]
Sorry, had to jump to something else. Got everything working in ~90min; not too bad! Also noticed that these forms were translated into 5 languages! So I'm glad we were able to use it :) Closing in favour #2700 .

**Comment by cdrini** [comment]
Oh, and I moved the JS over as part of this; `add_new_field.js` was actually entirely for this feature.

**Comment by cdrini** [comment]
Sorry for the long delays and run around 😓 That's my bad organization. So much to do, so little time. I hope everyone is unblocked now!

**Pull request closed without merging**
