### PR TITLE
WIP: requirements.txt: Upgrade to Fabric==2.4.0

### PR DESCRIPTION
**Pull request by cclauss**
Work in Progress:  Do not merge.

### CODE REVIEW

**Comment by tfmorris** [comment]
This is a major version bump and I'm not sure how complete our test coverage is. What, if anything, has been done to verify that things still work correctly?

The Fabric 1 to Fabric 2 upgrade documentation is available here: https://www.fabfile.org/upgrading.html

**Comment by cclauss** [comment]
I am unsure how to test the proposed change because no file in this repo imports fabric.
* https://github.com/internetarchive/openlibrary/search?q=fabric

**Comment by tfmorris** [comment]
So, it sounds like our preferred strategy should be to remove the dependency if possible. Do the tests pass with it removed?

**Comment by mekarpeles** [comment]
It's required for production, it can probably be moved to the olsystem repo.

**Comment by cclauss** [comment]
Is the same true of __supervisor__ #1638?  Is there a down side to moving them to the __olsystem__ repo?

**Comment by tfmorris** [comment]
How is "production" different from the developers' test environment? How do we get test coverage for it? The repo https://github.com/openlibrary/olsystem doesn't appear to exist (nor, even, https://github.com/internetarchive/olsystem for that matter) Where is it hidden?

**Comment by hornc** [comment]
Resolved by removing the Fabric requirement completely in #1907 based on the discussion here. Thanks!

**Pull request closed without merging**
