### PR TITLE
dead_code : Delete openlibrary/templates/contact/spam/sent.html

### LINKED ISSUE #9174: Is openlibrary/templates/contact/spam/sent.html dead code?
### Problem

Best I can tell openlibrary/templates/contact/spam/sent.html is dead code, not used anywhere.
If it is then lets delete it. If it's not, we might want to add internationalization to it?

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

### PR DESCRIPTION
**Pull request by harsh-kumar-patwa**
Closes #9174 

This PR deletes the dead code "openlibrary/templates/contact/spam/sent.html".

### Technical

After investing about the code present in "openlibrary/templates/contact/spam/sent.html", I could conclude that it was not being used anywhere in the whole repositry. So I have removed the file and have updated the exclude list also. 

### Stakeholders

@mekarpeles

### CODE REVIEW

**Comment by rebecca-shoptaw** [comment]
Hi @harsh-kumar-patwa & @mekarpeles! I wanted to give you both a heads-up that this has already been fixed in #9505, which @cdrini is currently reviewing. 

I'd rather keep the fix there if possible to keep all the `i18n` updates a result of the script nicely batched, but if you'd prefer to do it separately, I can remove the fix from that PR! Just let me know what you prefer 🙂

**Review by scottbarnes — APPROVED** [review]
LGTM. Thanks for this, @harsh-kumar-patwa.

@rebecca-shoptaw, during the weekly OL core team meeting we decided to handle this one separately, which is why it is getting merged. Sorry for the rebase this causes. :(

**Comment by cdrini** [comment]
To follow up, I've been having some issues testing #9505 , so I think it'll take a few days to sort out, so didn't want to block this one!

**Comment by rebecca-shoptaw** [comment]
@scottbarnes @cdrini All good!! Rebasing has become basically one of my hobbies with all the i18n and registration PRs, so I don't at all mind doing a little more 🙂 

Glad this is getting out, and excited to continue with the next i18n step as time/testing allows!

**Comment by harsh-kumar-patwa** [comment]
> LGTM. Thanks for this, @harsh-kumar-patwa.
> 
> @rebecca-shoptaw, during the weekly OL core team meeting we decided to handle this one separately, which is why it is getting merged. Sorry for the need to rebase this causes. :(

No problem ! It was was my first pr getting merged as I has started my open source journey recenlty. It's a great achievement for me and motivates me to continue contributing further.
Thanks to whole openlibrary team.

**Pull request merged**
