### PR TITLE
Strip surrounding whitespace when saving a work

### PR DESCRIPTION
**Pull request by jimman2003**
See https://docs.python.org/3/library/stdtypes.html#str.strip

Closes #

fix
### Technical

Is that the correct place...?
### Stakeholders

@BharatKalluri @cdrini

### CODE REVIEW

**Comment by cdrini** [comment]
Ah, I'm afraid it won't make much of a difference here. Solr processes the text and splits on whitespace, so it effectively ignores whitespace already. What is the problem you're trying to solve? Have you seen some records with trailing whitespace in their title on Open Library?

**Comment by jimman2003** [comment]
Yeah I have a new bot to fix them in bulk,https://github.com/internetarchive/openlibrary-bots/pull/108

**Comment by jimman2003** [comment]
Maybe I should look to the ui or db layer?

**Comment by cdrini** [comment]
Ah, so in general there are two places to fix then:

1) Prevent whitespace being added
2) Fix any instances of whitespaces there.


2) is being done by your proposed bot :+1: Nice! (1) Depends on how these whitespaces are being introduced. Do you have any examples of where you've seen these? It might be the case this was already fixed.

**Comment by jimman2003** [comment]
This will ensure this and it will be a noop if not needed so I believe you should merge this..

**Comment by cdrini** [comment]
Or, to be clear, this PR _won't_ do that, since it strips the whitespace _temporarily_ before sending the record to solr. The whitespace will still be in the DB.

In general, code has a cost associated with it; every line of code is a liability! So we try to only add what's needed. If you have noticed this in the wild (by ImportBot, or something else), let's create an issue with some examples; that'll make it easier for us to determine what allowed that whitespace to be entered, and where/how to fix it. Examples are _really_ helpful for us, since if we can't see how an issue is manifesting, we can't reproduce it or begin trying to investigate.

**Pull request closed without merging**
