### PR TITLE
fix: fix overlap between button text and icon

### LINKED ISSUE #8899: Trusted book provider "audiobook" link in carousel on mobile has text overlap with external icon
### Problem

Hard to explain but see screenshot of "audiobook" button

#### Evidence / Screenshot
Screen Shot 2024-03-12 at 17 44 14

#### Relevant URL(s)
https://openlibrary.org/works/OL37473900W/Short_Story_Collection_102

### Reproducing the bug

* Expected behavior: No overlap
* Actual behavior: Overlap

### Context

- Browser (Chrome, Safari, Firefox, etc): FF
- OS (Windows, Mac, etc): Android
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Proposal & constraints

If you want to work on this please confirm that you will read the feedback and progress in the closed PR https://github.com/internetarchive/openlibrary/pull/9066 and incorporate it into the PR you open.

#### Stakeholders

@cdrini

### PR DESCRIPTION
**Pull request by PremBharwani**
Closes #8899 

Fix

### Technical

- Issue: *gutenberg, librivox, openstax, standard_ebooks* read buttons were facing button text & icon "external link" overlap on mobile devices
- Cause: The class `cta-btn--external` was adding the external link as the background image of the `<a>` tag in these cases
Currently the icon was displayed as a background image of the `<a>` tag which allowed the text to appear in front of the icon.
- Fix: Added a new span with the icon as a sibling of the text in the `<a>` tag

### Testing

- You could witness the issue at places where Open Library displays *gutenberg, librivox, openstax, standard_ebooks* read buttons. (examples: [librivox](https://openlibrary.org/works/OL37473900W/Short_Story_Collection_102), [gutenberg](https://openlibrary.org/works/OL17732W/KJV_study_Bible_for_boys?edition=key%3A/books/OL26083434M#details), ...)
- If you want to test locally, you could run the setup from the contributing guidelines and load the books mentioned in examples (please note that you wouldn't be able to load all the books from the script as they're from the trusted book providers. book from librivox example loads fine)
- Use the *Responsive Design Mode* of your browsers developer tools and test the overlap of the buttons by reducing the width

### Screenshot

**After fix** (Click the GIF to view clearly. Idk why some weird lines are appearing):
fix-first-look

### CODE REVIEW

**Review by RayBB — CHANGES_REQUESTED** [review]
Thanks for opening a PR and getting this going, it is a good start.




I tested this PR by following these steps:
1. `docker compose exec -e PYTHONPATH=. web bash -c "./scripts/copydocs.py --search 'author_key:OL9411725A' --search-limit 100"`
2. `docker compose run --rm home make css`
3. Visit http://localhost:8080/works/OL36891831W/

<details>
  <summary>Result here</summary>
  
Screen Shot 2024-03-19 at 20 13 36-fullpage

  
</details> 

My feedback:
* The top button looks good 👍 
* The middle button seems to have the the external icon a bit too far to the right
* The bottom buttons are missing the external icon

**Comment by PremBharwani** [comment]
- Middle button: 
  - I've fixed the padding issue by adding `padding` attribute
- Bottom button: 
  - The cause for the icon not being visible at all was because the `div` with the icon was essentially empty & the icon is a background image for the same (the standard way which is being followed). So while rendering that element was squeezed to 0 width, hence displaying nothing
  - This is fixed by the padding property as well

**Comment by RayBB** [comment]
@PremBharwani can you add screenshots of what it looks like now for all three spots I mentioned in my last comment?

**Comment by PremBharwani** [comment]
<details>
<summary>Desktop screenshots</summary>
* Top & Middle buttons:
  
  desktop-1-2

* Bottom button: 
  
  desktop-3
</details>

<details>
<summary>Mobile screenshots</summary>

* Top button
  
  mobile-1

* Middle button
  
  mobile-2

* Bottom button
  
  mobile-3

</details>

**Comment by RayBB** [comment]
@PremBharwani when the width is at 360 (the galaxy s20 default) the button is still off.
Perhaps the solution here has to do with changing the sizes at which multiple books are shown in carousel.

<details>
  <summary>screenshots</summary>
  
  
image


Also
image

  
</details>

**Comment by PremBharwani** [comment]
Sorry I've got some sudden commitments, should be able to close this next week.

**Comment by RayBB** [comment]
@PremBharwani will you be able to continue working on this or would you like to let someone else take this on?

**Comment by PremBharwani** [comment]
@RayBB you could pass this on to someone else. I don't think so I'll be able to find time.

**Comment by RayBB** [comment]
@PremBharwani thanks for the update and best of luck with everything. You're welcome to pickup another issue any time :)

**Pull request closed without merging**
