### PR TITLE
Use slick from npm, rather than from vendor

### LINKED ISSUE #2362: Replace slick copy with npm version
### Description
We're currently storing a copy of slick 1.6.0 in `vendor/js` folder. Let's replace it by adding it to package.json https://www.npmjs.com/package/slick-carousel/v/1.6.0

### Stakeholders
@jdlrobson

### PR DESCRIPTION
**Pull request by tmcw**
### Description

This installs Slick via NPM and includes it by importing the NPM package, and removes the vendored copy of the library.

Closes #2362

### Technical

The version of Slick is kept at 1.6.0 - updating to 1.8.0 requires updating the CSS too. This keeps the 'vendored' CSS because I'm not sure if this project tends to require CSS from node modules or not.

Note that package-lock.json got updates. I installed via the Docker-recommended command `docker-compose exec web npm install` - if there's a better way that doesn't create unrelated changes, I can switch to that.

### Evidence

The UI is unchanged, this keeps Slick the same.

### CODE REVIEW

**Comment by cdrini** [comment]
Thanks for your contribution, @tmcw ! There's currently a PR for carousels, #2359, which will conflict with this. That one has been waiting for a while, so I'm going to be merging it today. You'll have to do a rebase to make this change work on top of it.

@jdlrobson Do you have the bandwidth to own this PR?

**Comment by cdrini** [comment]
#2359 has been merged; you're good to move ahead :+1:

**Comment by tmcw** [comment]
Cool, rebased up 👍

**Comment by jdlrobson** [comment]
Thanks for taking care of htis @tmcw !

**Pull request merged**
