### PR TITLE
Allow special character to be handled in title search

### LINKED ISSUE #7555: Search within an author's works can't find special characters
### Evidence / Screenshot (if possible)

Screen Shot 2023-02-19 at 4 48 35 PM

Screen Shot 2023-02-19 at 4 49 40 PM

### Relevant url?
https://openlibrary.org/authors/OL1149539A/Harriet_Anne_de_Salis?q=%C2%A9

### Steps to Reproduce

1. Go to https://openlibrary.org/authors/OL1149539A
2. Search for the copyright symbol

* Actual: search results say "1 work" and list zero works
* Expected: all works with a copyright symbol in their title should be listed

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders
@cdrini

### LINKED ISSUE #7568: # symbol is ignored by search
It is not possible to search for the # character, for example "C#". 
### Steps to Reproduce

1. Go to ...openlibrary.org
2. Do ...type "c#" or "c/#" or "c//#" in the search box

* Actual: results ignore the # symbol
* Expected: titles, for example, should be returned if they contain the # character.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cdrini

### PR DESCRIPTION
**Pull request by stardust-s**
Closes #7555 
Closes #7568

Fix the issue with regarding to special character in solr search. 

I'm new to this repo and I'm working together with @karlitto01 in hope to contribute to the repo and learn in the process.

### Technical

The original issue was due to the `wordDelimiterGraph` filter discarding special characters. As specified in its documentation at [here](https://solr.apache.org/guide/solr/latest/indexing-guide/filters.html#word-delimiter-graph-filter), non-alphanumeric characters are usually discarded.

The fix is to use filter.types to specify how to handle each special character. Currently, it is added to the word delimiter graph filter of `text_en_splitting` (the field type that titles is using), and uses the newly created file "wordtypes.txt". 

Currently, only two special characters: "©" and "#" are added, as I'm unaware of other special character that may occur. However, if there are any, they could just be appended to the types file. 

It appears that `text_en_splitting` is also used in other places, some might have no need for special character handling, such as "subject" or "time", but this should not cause issue with them. If it does, creating a new type might be necessary.

### Testing

1. add a few book containing special character ([from the production environment](https://github.com/internetarchive/openlibrary/wiki/Loading-Production-Book-Data)). For example, `/books/OL25609335M` or `/books/OL25609153M`, which are the problematic ones from the original issue #7555.
2. Re-index solr if necessary to make sure it gets the newly imported entry into the search
3. Search for "©" either in the site search or in author-specific search. It should return these book with the "©" character in it, instead of returning nothing like what it currently does on the main site.

### Screenshot

image
image

### Stakeholders

@tfmorris 
@cdrini

### CODE REVIEW

**Comment by cdrini** [comment]
Fantastic work @stardust-s @karlitto01 ! Did not know these options existed! I will test on my local instance and get back to you :+1:

**Review by cdrini — APPROVED** [review]
Ok this looks good to me! Not sure what the best way to handle these ; whether ALPHANUM or ALPHA. But these seem to do the trick. The only difference I notice is that `C#9` delimits to `C#` `9`, whereas `C©9` delimits to `C@9` (stays together). Worth giving a whirl!

Note this will not start taking effect until I do a full reindex in the next few days (see #8234 )

Thanks for taking the time to deep dive into solr!

---

Before:
image

After:
image

---

Before:
image

After:
image

---

Before:
image

After:
image

**Comment by cdrini** [comment]
(Oh in case it's useful, I'm testing by going to http://localhost:8983/solr/#/openlibrary/analysis?analysis.fieldvalue=%C2%A92020&analysis.query=%C2%A92020&analysis.fieldname=title&verbose_output=0 ; the analysis tab has some very hand info!)

**Comment by stardust-s** [comment]
> Not sure what the best way to handle these ; whether ALPHANUM or ALPHA

I went by ALPHANUM for the © symbol because things like "©someone" or "©2000", etc., but "#" for ALPHA because In case it's used to represent a number it can be properly spitted. But that's just my opinion, and it shouldn't be hard to change that anyway!

Also, thanks for the quick review!

**Pull request merged**
