### PR TITLE
Re-enable RUF100 - Removes redundant `# noqa` comments  

### PR DESCRIPTION
**Pull request by drona-gyawali**
**What issue does this PR close?**  
Closes #10196

**What does this PR achieve?**  
- Removes redundant `# noqa` comments from the codebase as part of enabling the `RUF100` rule.
- Ensures the code follows the guidelines set by `Ruff` for improved code quality and maintainability.

### Technical
- Removed unnecessary `# noqa: comments related to unused imports.
- Ensured proper alignment with `RUF100` for consistent code quality.
- No functional changes or new features were introduced in this PR.

### Testing
- Run the pre-commit hooks and verify that all tests pass.
- Ensured no warnings or errors related to the removal of `# noqa` comments.

### Screenshot  
N/A (No UI changes)

### Stakeholders  
- @cdrini

### CODE REVIEW

**Comment by drona-gyawali** [comment]
I’ve removed all redundant `# noqa` comments and enabled `RUF100` as per the proposal. However, I noticed some unrelated errors (e.g., F403, SIM102, FLY002, BLE001) have been flagged by Ruff during the pre-commit checks. These errors were already present before my changes and seem to be outside the scope of my PR. 

Please let me know if you'd like me to address these issues, or if they will be handled separately. 

Thank you for your understanding!

**Review by RayBB — CHANGES_REQUESTED** [review]
Please only change relevant files.
Also this PR removes many noqa statements that are not redundant.

Please read https://docs.astral.sh/ruff/rules/unused-noqa/ closely

We only want to re-enable the rule and then let pre-commit remove the instances it deems irrelevant.

**Review by RayBB — APPROVED** [review]
Great job! Now we just need staff to review/merge

**Comment by cdrini** [comment]
Woah having RUF100 on by default is a huge win!! Thanks you @drona-gyawali and @RayBB !

**Pull request merged**
