### PR TITLE
merge tabs on author edit page

### LINKED ISSUE #9280: Can we get rid of tabs on the author edit page?
### A clear and concise description of what you want to happen
I want to get rid of the "Links" tab (move the content on to the main tab)

Why?
Because it makes the author edit page jump around a bunch.
I don't think it really is all that useful to have it on a separate tab.
It will simplify our code.
Make one less dependency on the jquery tabs 

### Expected behaviour / screenshots (ex: Figma design screenshots for UI feature)
It'll be faster and simpler.

### Additional Context
Example of the slow jumping:
https://github.com/internetarchive/openlibrary/assets/921217/2dc9c90f-203f-4e04-89c1-1deafa8b40f3

### What is the proposed solution / implementation?
Move the links section down under the identifiers.
Remove the tabs stuff.
Will need to remove `tabsAddauthor` from index.js as well.

### Is there a precedent of this approach succeeding elsewhere?
No

### PR DESCRIPTION
**Pull request by RayBB**
Closes #9280 

### Technical

I can fix the indentation in a later commit if needed. For now, just want to show how simple the change is.

### Testing

Exits work fine. UI looks only slightly different. The page could use some general improvements but that's for another pr ;) 

### Screenshot

| Before | After |
|--------|-------|
|image |image |

### CODE REVIEW

**Review by cdrini — CHANGES_REQUESTED** [review]
Nice! Code looks good, could we try to make it look a little more like our work edit page?
image

I think we just need to wrap it in a `<fieldset class="major">` with a `<legend>` and it should look about the same.

**Comment by RayBB** [comment]
@cdrini I edited it as you requested. It is better but doesn't exactly match well.
To avoid scope creep maybe we should just decide how to make links look and then open a different ticket for generally cleaning up the spacing/format of the author edit page.
image

**Review by cdrini — COMMENTED** [review]
Yep! We can of course make changes to it later, but I also want to make sure it looks a little more visually consistent with the rest of the site; t
hat's in scope :+1: Otherwise we're just trading one UI problem for another!

**Comment by cdrini** [comment]
Looking good!
image

**Review by cdrini — APPROVED** [review]

**Pull request merged**
