### PR TITLE
Removed unused imports from /mocks

### PR DESCRIPTION
**Pull request by imskr**
Removes unused imports from openlibrary/mocks

### Stakeholders

@cclauss

### CODE REVIEW

**Comment by cclauss** [comment]
https://travis-ci.org is down for maintenance so your tests have not yet run.
https://travis-ci.com (.com) is working fine.

**Comment by imskr** [comment]
@cclauss https://travis-ci.com/github/imskr/openlibrary/builds/154354689

**Comment by imskr** [comment]
Yes @cclauss TravisCI is down for maintenance, I see one test fails in https://travis-ci.com/github/imskr/openlibrary/builds/154354689

**Comment by cclauss** [comment]
The last test is currently run in allow_failures mode. It currently fails on all builds because we are not yet Py3 compatible.

**Comment by imskr** [comment]
okay

**Comment by imskr** [comment]
Should I wait for this PR merge before creating PR for another imports?  @cclauss

**Comment by cclauss** [comment]
@imskr what is next?

**Pull request merged**
