### PR TITLE
Update to Vue 2.7

### PR DESCRIPTION
**Pull request by jimman2003**
fix

### Technical

I followed the advice of the [Vue 2.7 migration guide](https://v2.vuejs.org/v2/guide/migration-vue-2-7#Vue-CLI-webpack)
I upgraded storybook to help with peer dependencies warnings (it had a old version of vue-loader)

### Testing

Verify that the build process and the bundle works correctly
### Screenshot

Main Page
### Stakeholders

@cdrini @jimchamp

### CODE REVIEW

**Comment by jimman2003** [comment]
Well the works page is broken now
Works Page

**Comment by jimchamp** [comment]
@mekarpeles, adding something to this [README](https://github.com/internetarchive/openlibrary/blob/master/stories/README.md) should trigger the storybook build on merge.

**Comment by jimchamp** [comment]
@jimman2003, could you add the following to the Storybook [README](https://github.com/internetarchive/openlibrary/blob/master/stories/README.md):

```
# Storybook

We are documenting our components [here](internetarchive.github.io/openlibrary).

## Deployment Process

We use GitHub Actions to automatically build and deploy new stories.  The action is triggered when a branch containing changes to the `/stories` directory is merged into `master`. 
This process can also be manually triggered via the Actions [page](https://github.com/internetarchive/openlibrary/actions).
```

This will help us test our automatic Storybook deployment.

**Comment by jimman2003** [comment]
@jimchamp Done!

**Comment by jimman2003** [comment]
@mekarpeles this should be ready..

**Pull request merged**
