### PR TITLE
WIP - Solr enhancements

### PR DESCRIPTION
**Pull request by tfmorris**
### Technical

This is still a work in progress, but creating a PR for the branch to give it some visibility for review.  It is based on @cdrini's PR #1843 which provided the framework.

Things that have been added include:
* Updated schema for the temp database
* performance improvements
* Solr 8.1 support using the official Solr Docker image, updating the schema as necessary (minor)
* Support for ICUFoldingFilter for author names and subject titles (can be expanded) to normalization plus case and diacritic folding so that Hervé and Herve get indexed the same (as well as more complicated cases)
* Blacklisting of all fake subjects as candidates for authors' "Top Subjects" list (can be extended to anyplace these subjects are indexed, but this should give us a big usability boost to start with)

Things remaining to be done:
* Fix delete by query performance issues (~50% time savings?)
* Fix subject indexing (plus clean up some outstanding bugs like merging subjects that differ only in punctuation  #65 )
* Integration of all pieces to be able to download a dump and build an index from scratch in under 12 hours (current time is probably 3x that)

### CODE REVIEW

**Comment by cdrini** [comment]
Ahahaha, we're going to have a ton of conflicts soon once I add the automation support 😅

**Comment by cdrini** [comment]
@tfmorris Could you please use the PR template? I want to know how you've tested this :P

**Comment by tfmorris** [comment]
Testing? What's that? 

Seriously though, I'm happy to use the PR template when this is actually ready for review. I've pasted it in now as a show of good faith.

Testing so far has consisted of:
* one full end to end run with the existing version of Solr and all commits up to Solr 8.1
* ad hoc manual testing of the ICUFoldingFilter indexing / queries for authors & titles

I'm in the process of another full reindex with Solr 8.1 and the current i18n schema and will do a full end-to-end test with the July dump.

The failing CI tests show that the unit tests need to be updated since they apparently depend on the over-the-wire byte stream to Solr.

Other than matching up raw record counts, data integrity is going to be a little bit to tough to verify. Suggestions welcome. The good news is that it's "just" an index, so we can rebuild it to fix any problems found.

**Comment by tfmorris** [comment]
Abandoned years ago (although some pieces were apparently used in other PRs like #4283)

**Pull request closed without merging**
