### PR TITLE
Switch from pystatsd to statsd

### LINKED ISSUE #1486: Upgrade / phase out statsd client
The `pystatsd` module is ancient and hasn't been updated in over 5 years. The only user of it is `openlibrary/core/stats.py` which has only had whitespace changes since 2011. If that program is unused (is there an Etsy `statsd` server anywhere in our configuration?) we can just get rid of the dependency. Otherwise we should probably investigate replacing `pystatsd` with [`statsd`](https://pypi.org/project/statsd/) ie https://github.com/jsocol/pystatsd

### PR DESCRIPTION
**Pull request by tfmorris**
Closes #1486

Switches to a Python 3 compatible statsd client library.

### CODE REVIEW

**Review by cclauss — APPROVED** [review]

**Comment by tfmorris** [comment]
@mekarpeles @hornc This has a new Python module dependency and requires the installation of the `statsd` module on the production servers.

**Comment by tfmorris** [comment]
@hornc @mekarpeles do you have an ETA on this?

**Comment by hornc** [comment]
How are we going to test this? Any ideas?

**Comment by tfmorris** [comment]
There's no test coverage for this functionality (and it requires an external component), so I think we're stuck with manual testing. Is `dev` configured to log stats? If so we could test it there. All that's needed is to make sure that the counters are incrementing.

**Comment by cclauss** [comment]
How can we resolve this and land these changes?  _There's no test coverage for this functionality_ yet `import statsd` is the cause of half of the failing pytests on Python 3.  It is blocking our progress.

**Comment by tfmorris** [comment]
Sketch of suggested test `dev` deployment & test strategy:

```bash
pip uninstall pystatsd # make sure old module is uninstalled
git checkout master
git checkout -b staging # Use a staging branch in case we want to test multiple features
git merge pystatsd-statsd
pip install -r requirements_common.txt
```

Check that stats counters are getting properly incremented (configured/reconfigure statsd server on dev if necessary).

**Comment by tfmorris** [comment]
Abandoning this

**Comment by cclauss** [comment]
Mostly landed in #3006

**Pull request closed without merging**
