### PR TITLE
Use protocol relative URIs for images

### PR DESCRIPTION
**Pull request by jdlrobson**
Never load http on https. Don't assume https either - use whatever
the current protocol is.

Closes #

### CODE REVIEW

**Comment by jdlrobson** [comment]
@mek it looks like https://graphite.us.archive.org/ doesn't support the HTTPS protocol. You'd need to enable HTTPs on that server for this patch to work, otherwise the other graphs will disappear. That said you are sending graphs unsecurely so maybe not sending the graphs is better? (shrug)

**Review by mekarpeles — APPROVED** [review]
ty

**Comment by mekarpeles** [comment]
temporarily reverting -- these graphs only available as http and firefox still works (even if chrome doesn't) given previous code

**Comment by jdlrobson** [comment]
That's correct as I noted in https://github.com/internetarchive/openlibrary/pull/3933#issuecomment-711103143 sorry if i didnt make myself clear!

**Pull request merged**
