### PR TITLE
Upgrade to beautifulsoup4=4.6.3

### LINKED ISSUE #1275: Migrate/port to BeautifulSoup4 (bs4)
The first error thrown by our new Python 3 Travis CI job, thanks to PR #1273, relates to BeautifulSoup.

The current module will never have Python3 support, but its successor does, so we need to move to the new version. It doesn't look like we make very extensive use of the functionality, so this should be straightforward.

Instructions here: https://www.crummy.com/software/BeautifulSoup/bs4/doc/#porting-code-to-bs4

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #1275  __Ready for review.__

BeautifulSoup 3 is currently causing Travis CI builds to fail on Python 3...
* https://travis-ci.org/internetarchive/openlibrary/jobs/447868610#L485
...so this PR upgrades us from BeautifulSoup 3 to the current version of BeautifulSoup 4.

Fixes #1275 but uncovers several more issues with _other_ dependencies...
* Upgrades that break our Python 2.7 tests
    * [Genshi==0.7.1](https://travis-ci.org/internetarchive/openlibrary/jobs/447905524#L1285)
    * itools==0.77.8
* Will not pip install on Python 3
    * [pystatsd==0.1.10](https://travis-ci.org/internetarchive/openlibrary/jobs/447928152#L535)
    * [supervisor==3.3.4](https://travis-ci.org/internetarchive/openlibrary/jobs/447914150#L521)
    * [web.py==0.39](https://travis-ci.org/internetarchive/openlibrary/jobs/447918496#L521)

@tfmorris @mekarpeles Your reviews please.

### CODE REVIEW

**Comment by tfmorris** [comment]
Thanks for the contribution. I know churning through dependencies is tedious. I was initially confused by the Python 2.7 comments since the tests were passing, but then noticed that you'd reverted some earlier changes.

It mostly looks good to me. I'd suggest squashing the commits that got reverted so that they're not making distracting noise.

Similarly are the requirements updates for things like flake8 required for bs4 or just along for the ride? It kind of looks like this started off as an "upgrade everything for Python 3" branch and then got scaled back to just bs4. The flake8, etc stuff is minimal enough that I think it's OK to leave in for this, but generally, for the future, it's better to separate if possible.

If you clean up the commit history by doing an interactive rebase and squashing the unnecessary commits, I think this will be ready to go.

**Comment by cclauss** [comment]
Yes...  Your points are all spot on.  Squashed.

**Comment by tfmorris** [comment]
LGTM @mekarpeles can you merge please? I don't think it touches anything production related, but want to follow the rules... :-)

**Comment by tfmorris** [comment]
The extra commit just merges in a single Python 3 exception syntax change.

@mekarpeles @hornc still LGTM

**Comment by tfmorris** [comment]
@mekarpeles @hornc LGTM from my point of view. Are there outstanding issues preventing merger?

**Comment by hornc** [comment]
@tfmorris don't think so, I will merge

**Comment by mekarpeles** [comment]
Ack! Sorry for not jumping in on this, cc: @hornc -- merges on package upgrades need to happen first on ol-dev0 and then on www1, web3, web4, and ol-home before merge.
Currently we have a broken ol-dev0 :)

**Comment by mekarpeles** [comment]
Should be fixed on all these VMs. bs4 is running on ol-dev0

**Comment by hornc** [comment]
sorry @mekarpeles, I should have thought that through better. I thought I was saving you effort -- thanks for bringing the packages up to date!

**Pull request merged**
