### PR TITLE
Improve privacy settings page i18n/a11y

### LINKED ISSUE #7679: Accessibility issue on Privacy Settings
### Evidence / Screenshot (if possible)
Screenshot 2023-03-17 at 11 24 00

### Relevant url?
https://openlibrary.org/account/privacy

### Steps to Reproduce

1. Go to your privacy settings
2. Click on the **word** yes or no
3. Observe that the radio button doesn't change

* Actual: Radio doesn't toggle
* Expected: Radio should toggle

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox 120
- **Operating system?** MacOs
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

`<label for="u0">Yes</label>`

Should be:

`<label for="r0">Yes</label>`

"no" needs to be changed to "r1"

### PR DESCRIPTION
**Pull request by cdrini**
Closes #7679

### Screenshot
Before:
image

After:
image

### CODE REVIEW

**Review by mekarpeles — APPROVED** [review]
lgtm, adding to testing

**Comment by abelaba** [comment]
Hey @scottbarnes so I checked out https://testing.openlibrary.org/account/privacy and after you change your privacy settings to Yes or No and save it, when you open the link again it defaults to Yes. Is it supposed to be like that?

**Comment by scottbarnes** [comment]
@abelaba, good find and good question.

I am wrapped up with another task just now, but I did quickly pull this branch down, ran `docker-compose exec web make css js` to rebuild js/css, and tried setting my privacy preferences, and in the local environment, after setting a preference subsequent visits to http://localhost:8080/account/privacy default to my selected preference.

That may or may not mean anything, and it doesn't explain why the behavior is different on testing.

**Comment by cdrini** [comment]
Merging up! Thanks for the testing folks. @scottbarnes ' assessment seems correct, this should work correctly once on prod.

**Pull request merged**
