### PR TITLE
Fix spacing issues

### LINKED ISSUE #2087: Consistency: Spacing
Our spacing is inconsistent. Let's apply some  [eslint  rules](https://eslint.org/docs/rules/) and fix these.

[Eslint](https://eslint.org/) can be run by using `npm install && npm run lint:js`

```
    "keyword-spacing": ["error", { "before": true, "after": true } ],
```
At time of writing there are  ✖ 13 problems (13 errors, 0 warnings)

### Checklist
- [ ] Update .eslintrc.json with the correct definition
- [ ] fix any offenders detected via `npm run lint:js` (or eslint openlibrary/plugins/openlibrary/js/ --fix)

Note to implementor: Make sure you coordinate with somebody with merge rights (e.g. in slack) to submit your fixes as there is a high likelihood you might hit merge conflicts. You can autofix these problems so you shouldn't have to worry about merge conflicts!

### PR DESCRIPTION
**Pull request by musayann**
Closes #2087

Adds keyword-spacing rule for code consistency and fixes all 13 spacing issues

### Testing

npm install && npm run lint:js

### CODE REVIEW

**Comment by mekarpeles** [comment]
Thank you @musayann for your contribution! :bowing_man: 

Deferring to + assigning @jdlrobson our FE lead so he can weigh in on style and evaluate this solution #2087. Thanks again for both of your efforts

**Comment by jdlrobson** [comment]
Looks good but needs a rebase and potentially follow up fixes. Once Travis is okay with the change so am I :)

**Comment by tfmorris** [comment]
Let us know if you need help with the rebase process. Once the "This branch has conflicts that must be resolved" error message here goes away, our Travis CI test jobs will get kicked off and report whether or not they passed (also here).

**Comment by jdlrobson** [comment]
See #2521

**Pull request closed without merging**
