### PR TITLE
Make work from an orphaned edition

### LINKED ISSUE #3760: Orphaned editions error
```
/opt/openlibrary/deploys/openlibrary/9afb5a2/openlibrary/templates/type/edition/view.html: error in processing template: IndexError: list index out of range (falling back to default template)
```

### Relevant url?
- https://openlibrary.org/books/OL9773440M/Muertos_Incomodos?v=1
- https://openlibrary.org/books/OL9773440M/Muertos_Incomodos?v=1&debug=true

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF79
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@mekarpeles

### PR DESCRIPTION
**Pull request by cclauss**
Closes #3760, #4051, #4052, #4224

Avoid an index error if not `page.works` and then create a work from an orphaned edition.

### CODE REVIEW

**Comment by cclauss** [comment]
Background:
https://github.com/internetarchive/openlibrary/wiki/Orphaned-Editions-Planning

Test set:
http://staging.openlibrary.org/books/OL21692921M/Catharisme?debug=true

http://staging.openlibrary.org/books/OL11562694M?debug=true

http://staging.openlibrary.org/books/OL9773440M/Muertos_Incomodos?v=1&debug=true

http://staging.openlibrary.org/books/OL18314559M/Nineteen_eighty-four?debug=true
http://staging.openlibrary.org/books/OL14412099M/Nineteen_eighty-four?debug=true
http://staging.openlibrary.org/books/OL9096223M/Nineteen_Eighty-Four?debug=true
http://staging.openlibrary.org/books/OL18314559M/Nineteen_eighty-four?debug=true

**Review by tfmorris — COMMENTED** [review]
It's been many months since I've looked at the code base, so I can't really review this effectively, but my main question would be "what changed between when this work and when it stopped working a few months ago"?

If this patch fixes that problem - great! If this patch addresses a symptom other than the root cause, I'd suggest reviewers evaluate further.

Sorry I can't be of more help. On the surface, all the changes seem fine, but no idea whether they address the real problem.

**Comment by mekarpeles** [comment]
Ideally I think we'd upsert/create a work for the orphaned edition.

The suggested changes seem fine as an interim (not sure where else things could break -- e.g. Lists -- if the Work is not set).

Only blocker I see is that in the `admin_bar` (for admins), the following line breaks

```
work_id = work and work.key.split('/')[2]
```

and may have to be something like

```
work_id = work and work.key and work.key.split('/')[2]
```

**Review by mekarpeles — APPROVED** [review]

**Comment by mekarpeles** [comment]
admin change above is in place, tested this on staging, LGTM

**Comment by hornc** [comment]
@mekarpeles @cclauss I didn't see this earlier, but this code already exists elsewhere in the codebase:

https://github.com/internetarchive/openlibrary/blob/c5838ad682f4068881ce5275d0175059fe1ceb08/openlibrary/plugins/upstream/addbook.py#L738-L746

**Comment by cclauss** [comment]
Yes.  https://github.com/internetarchive/openlibrary/issues/4051#issuecomment-745455124

**Comment by cclauss** [comment]
Remove duplicate orphaned edition code from addbook.py #4307

**Pull request merged**
