### PR TITLE
Remove inline style so that choices in search page are on the same line

### LINKED ISSUE #1224: Search bar extends beyond appropriate limits
Search bar width is getting modified in html template file, so that the third criterion "Print Disabled" spans two lines. 

search-bar

### PR DESCRIPTION
**Pull request by Num170R**
Closes #1224 

## Description:
In this Pull Request we have made the following changes:

* Changed search bar width so that all adjacent choices are on a single line

### CODE REVIEW

**Comment by Num170R** [comment]
I have not adjusted the width in other html files but there are a few with same settings

**Comment by jdlrobson** [comment]
Removing inline styles make me happy.

**Comment by Num170R** [comment]
There are a few other pages that contain the same inline styles. Should I address that in a separate issue?

**Comment by jdlrobson** [comment]
Yes.

Long term we will want to get rid of these inline styles but we should be cautious as they might be important in some situations so we should be careful of ui regressions

**Comment by mekarpeles** [comment]
lgtm

**Pull request merged**
