### PR TITLE
Set optimization.spiltChunks to all on webpack

### LINKED ISSUE #9381: Explore using splitchunks for webpack performance
### Stakeholders

**Note:** Before [making a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) _or_ updating an existing one, please [ensure your branch is up to date](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch).

### PR DESCRIPTION
**Pull request by jimman2003**
Closes #9381

refactor
### Testing

Test overall functionality
### Stakeholders
@cdrini @jdlrobson 
Rellavant webpack docs https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkschunks

### CODE REVIEW

**Comment by jimman2003** [comment]
size stats`512	static/build/654.8a448c3a2729c08756fb.js.LICENSE.txt
284K	static/build/170.js
8.0K	static/build/170.js.LICENSE.txt
52K	static/build/257.c56af3940f9dfbffef15.js
64K	static/build/297.js
512	static/build/297.js.LICENSE.txt
92K	static/build/330.2c14a8d288d154a9ea3e.js
84K	static/build/339.4eba32e7cf4566bca6a4.js
512	static/build/339.4eba32e7cf4566bca6a4.js.LICENSE.txt
20K	static/build/425.5fa2038d6054fad45742.js
44K	static/build/453.8bebddd5f7a56ac9fc2b.js
16K	static/build/538.bd4d01d5a5f092015f46.js
488K	static/build/654.8a448c3a2729c08756fb.js
8.0K	static/build/graphs.dcc9eb85115c574e5fd2.js
36K	static/build/markdown-editor.351b8df463ec7201028f.js
4.0K	static/build/merge.bbaddd187e58537f7906.js
4.0K	static/build/page-barcodescanner.5a997028c0a10385b438.js
16K	static/build/patron-metadata.f667e2b6be2b83a1a47b.js
12K	static/build/readinglog-stats.a0abd06410e603a179a8.js
1.0K	static/build/add-book.3d8233662bc67f8a4c9c.js
1.0K	static/build/admin.c8a72b164333f8ab232f.js
96K	static/build/all.js
512	static/build/carousel.b571214cd92dc525fba7.js
4.0K	static/build/carousels-partials.fd82dec6b254a20cf595.js
28K	static/build/covers.a5cfdceb728f72845b53.js
512	static/build/covers.a5cfdceb728f72845b53.js.LICENSE.txt
24K	static/build/editions-table.1f2ca6f5fd0eaabed006.js
4.0K	static/build/goodreads-import.1767f7910961c68a588f.js
4.0K	static/build/readmore.7e5b2d06250683f5f371.js
4.0K	static/build/realtime-account-validation.82fd336ae666efc31d3d.js
4.0K	static/build/search.fd1b02369870a4b7537e.js
16K	static/build/tabs.b1520f42be90566cee54.js
512	static/build/tabs.b1520f42be90566cee54.js.LICENSE.txt
8.0K	static/build/user-website.b8b3f4d4b4997be60933.js
4.0K	static/build/vue.js`

**Comment by jdlrobson** [comment]
As far as I understand it this patch does not **introduce** code splitting (which we have already but reconfigures it, so that was a little bit confusing to me.

I'm not 100% up to date on Webpack config and looking through https://webpack.js.org/plugins/split-chunks-plugin/ it's not obvious what changes this brings. However, as I would expect optimizations to impact the bundlesizes in `bundlesize.config.json` which haven't been updated. I'm not sure if that's because this is not optimizing anything or if a change there was omitted.

Could you update the description of the pull request to describe what you are looking to achieve in this patchset for the benefit of reviewers not so well versed in Webpack like myself? Thanks in advance.

**Comment by jimman2003** [comment]
I used this [guide](https://webpack.js.org/guides/code-splitting/#splitchunksplugin) to reason about this

**Comment by jimman2003** [comment]
from that guide ``` With the optimization.splitChunks configuration option in place, we should now see the duplicate dependency removed from our index.bundle.js and another.bundle.js. The plugin should notice that we've separated lodash out to a separate chunk and remove the dead weight from our main bundle. ```

**Comment by cdrini** [comment]
The purpose of this is exploratory; so determine the impacts that enabling webpack's stock bundling has, and use that to decide if we want to enable it!

@jimman2003 Would you be able to create a before/after spreadsheet? Similar to https://docs.google.com/spreadsheets/d/1_xzXH3fcNIb85aPIYuF9U8w8Kg-1fejG_SQnqZpYxYc/edit#gid=0 ? That would help us evaluate what's changed. Comparing it to the current master branc should be good :+1:

**Comment by jimman2003** [comment]
spreadsheet for changes:
https://docs.google.com/spreadsheets/d/1xAHYWg24lTwaJpKdGV0VWd8JYZDMUxGODCGWOKeuOxA/edit#gid=0

**Comment by jimman2003** [comment]
oh I get js errors  o(new Error("Problem communicating active modules to the server: ) not sure why..

**Comment by cdrini** [comment]
Oh, we won't be able to use the `lazyCompilation`; our build flow currently depends on the JS files being static (we copy them around a bunch), and we don't run webpack on our static file server.

Can you remove that line? We can then test if `chunk: all` showed improvements.

**Comment by jimman2003** [comment]
Ok,will do!

**Comment by jimman2003** [comment]
Nope,  I think it is difficult to determine whether it has significant impact

**Pull request closed without merging**
