### PR TITLE
adding fundraising messaging re: #799

### PR DESCRIPTION
**Pull request by mekarpeles**

### CODE REVIEW

**Comment by bfalling** [comment]
@mekarpeles: It's confusing to have two adjacent underlined, linked phrases, one of which is bold. Can we remove the underline and link from "Help us build the great digital library."?

**Comment by mekarpeles** [comment]
We can, though we should check w/ @katiebarrett as she is concerned the bold + underline may be construed as not a link but as emphasis.

Maybe we remove the 2nd link and just unbold the 1st link?

**Comment by katiebarrett** [comment]
How about this: let's keep the 'double your donation' *bold* and have the 'Help us build the great digital library' but an underlined link. 

Let me know if that looks better.

**Comment by mekarpeles** [comment]
I think it looks better -- @bfalling thoughts? Also, is `platform=ol` sufficient to add to the /donate link in order for it to be tracked?

@katiebarrett -- does it look ok? https://dev.openlibrary.org

**Comment by katiebarrett** [comment]
Hi @mekarpeles
TEXT UPDATE: 
Is Open Library useful to you? Chip in to keep it growing. Your gift will be matched today. DONATE

Please make DONATE bold, underlined, and a hotlink to https://archive.org/donate/

**Pull request merged**
