### PR TITLE
GitHub Actions: Add mypy for Python type checking

### PR DESCRIPTION
**Pull request by cclauss**
Add [Mypy: Optional Static Typing for Python](https://github.com/python/mypy) running in _allow failures_ mode in our GitHub Actions until we get our code into compliance.  https://docs.python.org/3/library/typing.html

Found 139 errors in 49 files (checked 415 source files)

### CODE REVIEW

**Review by bnewbold — COMMENTED** [review]
Looks reasonable to me. We also use `--ignore-missing-imports`. It is good to include `mypy` in the test requirements, as you have: the package is relatively large on-disk because it includes many annotations (under 'typeshed'). Something like 20 MByte total, not unmanageable but worth skipping when not needed. You could consider easing in enforcement (removing the `|| true`) by specifying specific (sub)directories instead of `.` and expanding to `.` over time.

**Comment by cdrini** [comment]
I don't really see the point of this. If it doesn't fail the build, I don't really see the point in running it in CI (friendly reminder: Just because CI is free doesn't mean wasting cycles on these machines doesn't have a cost :) ). This also 47s = 35% of the total time. Looking at the logged output, there isn't anything actionable either. We also can't add traditional Py3 type annotations until we get ol-home's python stuff moved over to ol-home0. If we want something like this, let's pick the subset of files which are typesafe, and have mypy run on only those to ensure that they stay typesafe. Or if there's a way to check the diff, that might be another option. But either way we should wait until the final ol-home py2 scripts are moved over.

**Comment by mekarpeles** [comment]
main problems are CPU usage + CI takes more time; @cdrini has concerns, we agreed to close for now

**Comment by cclauss** [comment]
@dhruvmanila Would you be willing to help us to implement mypy on this repo and/or it’s dependency `internetarchive/infogami` ?  I know that type hints would help us find bugs but trying to do the whole repo generates a lot of noise.  This is production code used by lots of users worldwide so a "small moves" approach is required.

**Comment by dhruvmanila** [comment]
Yeah, sure. Is there any place where we can start the discussion regarding this?

**Pull request closed without merging**
