### PR TITLE
Added npm command to watch for css changes (watch-css). Resolves #4955.

### LINKED ISSUE #4955: Add a npm command for quicker CSS development
We currently have #2298 to monitor JS files for changes and automatically build them.
I would like the same thing but for the LESS/CSS.

### Describe the problem that you'd like solved
Every time I make a change to CSS I need to run `docker-compose exec web make css js` or was it `docker-compose run --rm home npm run-script build-assets`. One is in frontend guide and one is in the docker guide. I'm not sure which one is preferable in the case of working with CSS.

https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide
https://github.com/internetarchive/openlibrary/blob/master/docker/README.md

Either way, running that command every time I change any CSS is the pain I'd like to resolve.

### Proposal & Constraints

I don't know what the best way to do this is.
Probably not running the commands above in a bash loop.

Perhaps digging into the webpack config and trying to figure out incremental compilation. However, this is far from my area of expertise and I don't think it would be the best use of my time.

Incremental builds for this would be nice but it is fast enough that that isn't needed.
It would be very nice to have one command to monitor all of the frontend files for changes.

### PR DESCRIPTION
**Pull request by everydayanchovies**
Closes #4955

feature

### Technical
This installs a new dev npm dependency (npm-watch).

### Testing
Run `npm run watch-css`, wait for the first compilation to finish and then modify a .less file.
Observe the terminal output and see if the file changes have been detected and the css recompiled.

### CODE REVIEW

**Comment by RayBB** [comment]
@everydayanchovies thanks for opening the PR!

I haven't gotten a chance to test this yet but will try to soon.
As I just commented [here](https://github.com/internetarchive/openlibrary/issues/4955#issuecomment-885058316) it would be preferable to fix the webpack watch command so that it compiles the less but if that turns out to be to hard a solution like yours seems reasonable.

**Comment by RayBB** [comment]
I dug into it mote.

As far as I can tell, there is no way to make webpack watch less files and compile them on change. I'd love to be proven wrong here.

As such, I'm gonna say we should go ahead and use this method which is working nicely.

@everydayanchovies thanks so much for contributing this it is great! 🎉 
One ask is if you could add a note to the documentation [here](https://github.com/internetarchive/openlibrary/blob/master/docker/README.md#code-updates). If not, I'll go ahead and make a separate PR after this one.

For now, I'll tag @cdrini who has the power to merge.

PS: I'll make a separate issue one this is merged but we can easily [extend it](https://github.com/M-Zuber/npm-watch) to watch js files, package.json, requirements.txt and more so that there is less manual running all over the place.

**Comment by everydayanchovies** [comment]
@RayBB I added a mention of the new command :)

In my opinion, webpack is very powerful but the documentation is extremely lacking. I know of no better alternative. But I did also look for a way to achieve this with webpack alone and found none.

You could add more commands in the style of watch-css and run then in parallel with the package 'concurrently'. This could replace webpack's watch and reduce complexity.

Glad I could help :)

**Comment by jimman2003** [comment]
Less loader?

**Comment by jimchamp** [comment]
@everydayanchovies Thanks for this!  This will speed up development a lot.  I changed the webpack5 version to reflect what we are currently using in master.  Will merge this once the tests pass.

**Comment by everydayanchovies** [comment]
@jimchamp yes that slipped through the cracks hahah! Nice

**Pull request merged**
