### PR TITLE
print() is a function in Python 3

### PR DESCRIPTION
**Pull request by cclauss**
This PR ensures that __print()__ function calls work identically in both Python 2 and Python 3.

### CODE REVIEW

**Comment by tfmorris** [comment]
Was a tool used to make this change? If so, which one? I ask because the change is too big to easily review manually, so reviewing the algorithm/tool that was used is probably the best approach.

**Comment by cclauss** [comment]
__futurize -f libfuturize.fixes.fix_print_with_import -w .__
* http://python-future.org/futurize_cheatsheet.html

**Comment by cdrini** [comment]
Could you exclude the `scripts/YYYY` (year) folders? Those are archived scripts and shouldn't really be updated anymore.

**Comment by hornc** [comment]
A general note that relates to this PR, I'd prefer if we deprecated print statements altogether. They seem to exist as manual debugging code from standalone scripts, some of which have been moved into the core codebase. The results of these print statements aren't being logged anywhere sensible, so aren't adding much value.   Also, this flags a number of email error notifications that are not currently user + sending to inactive email addresses. We should remove those too.

**Comment by tfmorris** [comment]
@hornc While I generally agree, I think those issues are orthogonal to allowing the code to run without failure on Python 3. If we block Python 3 support on all general hygiene refactoring that we want to do the code, we'll never be done. We should decouple as much as possible.

**Comment by cclauss** [comment]
The fixes to #1314 are going to touch a _lot_ of files so I believe the early PRs should be simple fixes that are easy to review and commit.  Can you please create a _seperate_ issue on the conversation of print() and pprint() to logging so that it can be attacked in a separate PR.  I am a huge fan of logging so this requirement should not be lost/forgotten.

**Comment by hornc** [comment]
@cclauss, in order to merge this, can we please exclude the archived scripts folders as per @cdrini 's comment?

>Could you exclude the scripts/YYYY (year) folders? Those are archived scripts and shouldn't really be updated anymore.

Once that has been updated I will merge.

**Comment by cclauss** [comment]
Closed in favor of #1450

**Pull request closed without merging**
