### PR TITLE
Removed unused imports

### PR DESCRIPTION
**Pull request by imskr**
Related to #3166 

removes unused imports

### Stakeholders

@cclauss

### CODE REVIEW

**Comment by imskr** [comment]
@cclauss Check this. And sorry for commit name mistake admin.py is stats.py file

**Comment by cclauss** [comment]
Touching 103 files in a single pull request is a bit risky because if the PR is not quickly reviewed and landed, conflicts can appear.  Please look at the two failing Travis tests and revert the changes to those few files.  Those mods can be moved into another future separate PR.

**Comment by cclauss** [comment]
Ouch.  This broke a pile of Python 3 tests.  Hopefully the PR just needs a rebase.

**Comment by imskr** [comment]
This failed many tests. I need to start again and change a few files at a time. @cclauss

**Comment by cclauss** [comment]
Please sync with master and then create a new series of PRs __one at a time__.:
* [ ] openlibrary/mocks
* [ ] openlibrary/accounts and openlibrary/admin
* [ ] openlibrary/code.py and openlibrary/conftest.py
* [ ] openlibrary/coverstore
* [ ] openlibrary/data
* [ ] openlibrary/records
* [ ] openlibrary/solr
* [ ] openlibrary/utils and openlibrary/views

Save for the end:
* [ ] openlibrary/core
* [ ] openlibrary/catalog (perhaps multiple PRs)
* [ ] openlibrary/plugins (perhaps multiple PRs)

**Comment by imskr** [comment]
Sure, thanks @cclauss

**Comment by imskr** [comment]
@mekarpeles These are done!

- [X]  openlibrary/mocks
- [X]  openlibrary/accounts and openlibrary/admin
- [ ]  openlibrary/code.py and openlibrary/conftest.py
- [ ]  openlibrary/coverstore
- [ ]  openlibrary/data
- [ ]  openlibrary/records
- [ ]  openlibrary/solr
- [ ]  openlibrary/utils and openlibrary/views

 Save for the end:

- [ ]  openlibrary/core
- [ ]  openlibrary/catalog (perhaps multiple PRs)
- [ ]  openlibrary/plugins (perhaps multiple PRs)

**Comment by cclauss** [comment]
Cool.  Would you please try __openlibrary/utils__ next?

**Pull request closed without merging**
