### PR TITLE
Fixed the overflow issue of the edit button.

### LINKED ISSUE #5439: Edit button is running away due to long username
Edit button seems to be going far to the side when there are long usernames.

### Evidence / Screenshot (if possible)
image
image

### Relevant url?
https://openlibrary.org/works/OL20600W/Gulliver%27s_Travels
https://openlibrary.org/people/glbw

### Steps to Reproduce

1. Go to the pages

* Actual: Edit button are to the side of page
* Expected: Edit button within the bounds of center div

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

IMO it's probably find to clip the usernames with a `...`. Otherwise maybe try to do a text wrapping.

### PR DESCRIPTION
**Pull request by the-halfbloodprince**
Fixed the overflow issue of the edit button

Closes #5439

fix. This PR fixes the issue of the overflow of the edit button.

### Technical

Though the most obvious thing on my mind was to limit the length of the text near it to a fixed limit and show ellipsis(...) after it.
But going through the CSS in the browser's dev tools, I found that the issue was that we didn't specify any specific bounds from the right which was an obvious thing to do since the container in which it's supposed to have some margin in the x-axis. So just adding some right margin was the solution. This may sound quite trivial but please refer to the screenshots where I have shown the effect of that.

### Testing

Just run it :)

### Screenshot

Screenshot 2021-07-29 000817_LI
Screenshot 2021-07-29 000749
Screenshot 2021-07-29 000850
Screenshot 2021-07-29 000942

### Stakeholders

@RayBB @jimchamp

### CODE REVIEW

**Comment by Yashs911** [comment]
@the-halfbloodprince Thanks for the PR. But I think `margin-right: 10%;` will solve the problem as if you increase the username length, it will again overflow:
(Twice the current length)
image

I think changing `div#editInfo` `whitespace: nowrap;` to `whitespace: normal;` will solve the problem.

**Comment by the-halfbloodprince** [comment]
@Yashs911 yeah right. That make sense. I will try that.

**Comment by the-halfbloodprince** [comment]
@Yashs911 Sorry for the delay for such a simple task, I was thinking of using an ellipsis to trim the text so it will fit there as I thought breaking it into two lines may look weird, but just changing its white-space to normal actually seems to be a better option. Here are the screenshots:

image
image

**Comment by Yashs911** [comment]
@the-halfbloodprince Great
I think you should remove [WIP] now

**Comment by the-halfbloodprince** [comment]
@Yashs911 Right. Done. Thanks a lot for the suggestions. They seriously helped.

**Review by jimchamp — APPROVED** [review]
This lgtm!  Thanks @the-halfbloodprince!

**Pull request merged**
