### PR TITLE
Start i18n .po file for Indonesian

### PR DESCRIPTION
**Pull request by cunninghunter**
Moving to new folder, while I continuing my work

### Stakeholders
@cdrini

### CODE REVIEW

**Review by cdrini — APPROVED** [review]
Awesome this looks like a great start @cunninghunter , thank you!

**Comment by scottbarnes** [comment]
@cunninghunter, thanks for this. Does `nplurals=1; plural=0;` look correct for the [plural forms](https://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html) for Indonesian? See [here](https://www.gnu.org/software/gettext/manual/gettext.html#Plural-forms) for more on the topic.

I know we don't need it yet, but I don't want merge this, start a `.po` file for Indonesian without it, and then overlook it in the future.

**Comment by mekarpeles** [comment]
Ping @cunninghunter? We'd love your feedback so we can move forward with your proposed changes :)

**Comment by cunninghunter** [comment]
Hai, 
Thank you for reaching me. I apologize for this situation. Due to my recent developments, i cannot continue this project. Should things change, I might hope to continue.

Best Regards


    Pada Selasa, 12 Desember 2023 pukul 03.28.13 WIB, Mek ***@***.***> menulis:  
 
 


Ping @cunninghunter? We'd love your feedback so we can move forward with your proposed changes :)

**Comment by tfmorris** [comment]
@scottbarnes `nplurals=1` (ie just one form) agrees with the information at Unicode CLDR and Launchpad:
https://www.unicode.org/cldr/charts/43/supplemental/language_plural_rules.html#id
https://translations.launchpad.net/+languages/id

The header is mostly template info though, so should probably be updated.

**Comment by scottbarnes** [comment]
Thanks you very much for this, @cunninghunter. I integrated your work (9637f73b0d8c0b915982efa4e1a365ecd26a8d8b) into #8121, where you are listed as a co-author.

**Pull request closed without merging**
