### PR TITLE
Books fixups

### PR DESCRIPTION
**Pull request by jdlrobson**
Make http://localhost:8080/books/OL10031082M/UK_Continental_Shelf_Oil_Well_Records look like https://openlibrary.org/books/OL10031082M/UK_Continental_Shelf_Oil_Well_Records

### CODE REVIEW

**Comment by jdlrobson** [comment]
If we change the gray button that will change the button everywhere. happy to do that but want to make sure.

   .cta-section-title {
+    font-size: 12px;

This one shouldn't be needed. I added a rule which did essentially the same (sets 12.5px which is size on production right now). Are you saying you want smaller?

Will look at manage covers styles a little later.

**Comment by jdlrobson** [comment]
I've pushed up a new patch to restore the change covers overlay to match the one on desktop. I'd like to talk more about the suggested further changes (color and font-size change). I think they are improvements but they don't seem to be in the scope of making sure books page matches what's currently in production (unless I'm missing something!)

**Comment by mekarpeles** [comment]
I'm going to merge this and submit a followup :)

**Comment by jdlrobson** [comment]
> I think we should -- the contrast is better (that's currently what we use for the unwait btn)
Sounds good! Note there's a small risk, that there's old HTML using legacy classes which may not pick up the new color - but if we see those in testing that's a good opportunity to DRY things up!

**Pull request merged**
