### PR TITLE
Refactor/minicron.py

### PR DESCRIPTION
**Pull request by mekarpeles**
- Changed '== None' comparisons to 'is None'
- Removed whitespace around = for kwargs

### CODE REVIEW

**Comment by hornc** [comment]
:+1: to accepting these changes even if minicron.py isn't used anymore. This makes the code nicer and easier to search, as @mekarpeles said in the justification above.

 Cleaning up and removing unused scripts can be a separate task. It's not immediately obvious to me where this script is used, if at all, but these changes won't alter any behaviour, but certainly do improve the code. I vote in favour merging rather than discarding, FWIW.

**Comment by tfmorris** [comment]
I'm fine with the changes, although I'd prefer a single PEP-8 pass through all files at once to minimize the commit noise.

**Comment by anandology** [comment]
I don't think minicron is still being used.

**Comment by mekarpeles** [comment]
safe to rm?

**Comment by tfmorris** [comment]
Is there a PEP-8 cleanup PR someplace that can replace this multi-purpose PR, of which, I think,  minicron is the least important piece.

**Comment by mekarpeles** [comment]
@tfmorris want to start one? I'd contribute to it -- there's a variety of files which do singleton comparisons, have various line endings, etc.

maybe refactor/pep8? I can open a new issue and link all these to it

**Pull request merged**
