### PR TITLE
Web.py --> FastAPI codegen for 87 functions from 22 files

### PR DESCRIPTION
**Pull request by cclauss**
Automate the generation of our OpenAPI documentation.  https://openlibrary.org/swagger/docs

1. Use the Python **inspect** module to read a **web.py** API **.get()** method
2. Use the **inspect** info to generate a **FastAPI** method that can be shimmed on top of the **web.py** method. 
3. Use **FastAPI** to generate the **OpenAPI** docs from the new **FastAPI** methods.
4. Enhance the **OpenAPI** docs with manual edits stored in a YAML file.  <-- This is aspirational.

Use the Python [inspect](https://docs.python.org/3/library/inspect.html) module to analyze 75 Open Library [Web.py](https://webpy.org) synchronous GET API calls and codegen [FastAPI](https://fastapi.tiangolo.com) asyncio versions of those same calls.  As discussed in #5590, #5898, and #5914 this would allow FastAPI to auto-generate an `openapi.json` file that could present [Open Library's APIs](https://openlibrary.org/developers/api) in the intuitive [Swagger UI](https://swagger.io/tools/swagger-ui) with functioning `Try it out` mode.  FastAPI's use of Pydantic type validation and intuitive error messages would automate the discovery of type errors and provide more comprehensible error messages.

* `.github/workflows/codegen_api_docs.yml` -- GitHub Action that [___only runs on-demand___](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) to print the FastAPI shims.
* `scripts/codegen_api_docs.py` generates FastAPI async function shims from Web.py functions in 22 different files.

More Open Library API files can be added to `codegen_api_docs.py` in future pull requests.

`PUT`, `POST`, `DELETE` methods can be added to `codegen_api_docs.py` in future pull requests.

Auto-generation of missing docstrings can be added in future pull requests.

$ `scripts/codegen_api_docs.py`
```
@app.get("(/authors/OL\d+A)/edit")
async def author_edit_get(key) -> str:
    """
    openlibrary.plugins.upstream.addbook.author_edit_get(self, key)
    """
    return requests.get("https://openlibrary.org/{key}/authors/OL\d+A)/edit").json()


@app.get("(/authors/OL\d+A)/works")
async def author_works_get(key, limit: int = 50, offset: int = 0) -> str:
    """
    openlibrary.plugins.openlibrary.api.author_works_get(self, key)
    """
    return requests.get("https://openlibrary.org/{key}/authors/OL\d+A)/works", params=locals()).json()


@app.get("(/books/.*)/_borrow_status")
async def borrow_status_get(key, callback: Optional[str] = None) -> str:
    """
    openlibrary.plugins.upstream.borrow.borrow_status_get(self, key)
    """
    return requests.get("https://openlibrary.org/{key}/books/.*)/_borrow_status", params=locals()).json()

[ ... ]

@app.get("/works/_autocomplete")
async def works_autocomplete_get(q: str = "", limit: int = 5) -> str:
    """
    openlibrary.plugins.upstream.addbook.works_autocomplete_get(self)
    """
    return requests.get("https://openlibrary.org/works/_autocomplete", params=locals()).json()

Finished generating 87 functions in 0.0189489 seconds.
```

### Testing

```bash
git checkout add-docstrings-to-apis
docker compose up -d
docker exec -it openlibrary-web-1 bash
# ...
scripts/codegen_api_docs.py
```

### CODE REVIEW

**Comment by cclauss** [comment]
```
________ [doctest] openlibrary.plugins.openlibrary.api.webpy_to_fastapi ________
692 
693     Codegen FastAPI async functions from the web.py GET functions in this file.
694 
695     >>> len(list(webpy_to_fastapi())) != 0  # Ensure paths and docstrings are correct.
Expected:
    True
Got:
    Access to amazon_search_api's docs is blocked by a function @decorator.
    Access to booknotes's docs is blocked by a function @decorator.
    Access to price_api's docs is blocked by a function @decorator.
    Access to ratings's docs is blocked by a function @decorator.
    Access to sponsorship_eligibility_check's docs is blocked by a function @decorator.
    Access to work_bookshelves's docs is blocked by a function @decorator.
    Access to work_delete's docs is blocked by a function @decorator.
    True
```

**Comment by cclauss** [comment]
How should we make progress here?

**Comment by RayBB** [comment]
@cclauss now that #6018 is merged does this PR become any easier?

**Comment by cclauss** [comment]
@RayBB @tfmorris As discussed in #8083, #8084, and #8085 we need to come up with a way to add edits to our OpenAPI file just before we write it out.  If we could put our edits into a yaml or toml file then I could merge those changes into our `openapi_dict` just before we write our OpenAPI file.

I asked ChatGPT:
```
Create a yaml file and a toml file that will set the following values:
["info"]["title"] = "Open Library API",
["tags"] = [
    {
      "name": "books",
      "description": "Retrieve a specific work or edition by identifier",
      "externalDocs": {
        "description": "Find out more",
        "url": "https://openlibrary.org/dev/docs/api/books"
      }
    },
    {
      "name": "authors",
      "description": "Retrieve an author and their works by author identifier",
      "externalDocs": {
        "description": "Find out more",
        "url": "https://openlibrary.org/dev/docs/api/authors"
      }
    }
]
["info"]["description"] = """Open Library API description
    as
    a
    multiline
    string""",
["paths"]["/api/books"]["get"]['parameters"][0]["examples"] = "ABC"
["paths"]["/api/books"]["get"]['parameters"][1]["description"] = "LMN"
["paths"]["/api/books"]["get"]['tags"] = "XYZ"
```

And got back 
```yaml
info:
  title: Open Library API
  description: |
    Open Library API description
    as
    a
    multiline
    string
tags:
  - name: books
    description: Retrieve a specific work or edition by identifier
    externalDocs:
      description: Find out more
      url: https://openlibrary.org/dev/docs/api/books
  - name: authors
    description: Retrieve an author and their works by author identifier
    externalDocs:
      description: Find out more
      url: https://openlibrary.org/dev/docs/api/authors
paths:
  /api/books:
    get:
      parameters:
        - examples: ABC
        - description: LMN
      tags: XYZ
```
Plus a `toml` version that I leave as an exercise to the reader.  This output is NOT tested and perhaps ChatGPT hallucinated how to deal with `/api/books`, etc.

**Review by RayBB — CHANGES_REQUESTED** [review]
A few small suggestions.
In general it is a really awesome approach but I'm still trying to fully wrap my head around how it works.

Some general questions:
It looks like this github action workflow is run manually right now. Is the idea that we'd keep it like that? Or maybe once a month run it? Or run it on every PR and warn people to run the codegen script if there is a discrepancy?

I would guess either approach is fine but running on a schedule probably decreases overall fiction for developers at risk of delay in the docs being updated.

Also, I think we can do a separate PR for the tool to merge stuff from our extra descriptions later. I'd be willing to work on that :)

**Comment by tfmorris** [comment]
I didn't realize that this was generated. I think the most straightforward way to include extra information is to include  it in the source file, hopefully using something like the Python equivalent of these annotations https://www.baeldung.com/swagger-set-example-description

**Pull request closed without merging**
