### PR TITLE
Switch to Python 3.9 as default!

### PR DESCRIPTION
**Pull request by cdrini**
We've been testing on both; let's move forward!

### Testing
- [x] Leave on staging for a few days http://staging.openlibrary.org/status

### Stakeholders
@cclauss @dhruvmanila

### CODE REVIEW

**Review by cclauss — APPROVED** [review]
LGTM Onward and upward...

**Comment by mekarpeles** [comment]
This week we will do a deploy to get everything on master up on production. This PR should be landed in a deploy w/ no / few other changes so we can easily isolate the behavior.

**Comment by mekarpeles** [comment]
Given this is already running on staging, I think we should merge and get this off our plate. It's been 2 weeks and we'll have to rebuild eventually.

**Comment by cdrini** [comment]
Yep; we had other big deploy changes going out in the last deploy. The time is now!

**Pull request merged**
