### PR TITLE
Dependabot: Automated Python dependency updates

### PR DESCRIPTION
**Pull request by cclauss**
### Description

A great many of our Python dependencies are out-of-data and/or insecure.  Manually updating them is a pain across [requirements.txt](../blob/master/requirements.txt), [requirements_common.txt](../blob/master/requirements_common.txt), [requirements_test.txt](../blob/master/requirements_test.txt).

Now that the free service [Dependabot](https://dependabot.com) has been acquired by GitHub, should we use it to automate the process of opening individual pull requests to update each out-of-date dependency so that we can check which upgrades pass our tests?

### Technical

It is a yaml file.
### Testing

Yes.
### Evidence

#2024, #1773, #1772, #1750, #1705, #1700, #1693, #1687, #1686, #1685, #1680, #1679, #1667, #1653, #1638, ...

### CODE REVIEW

**Comment by mekarpeles** [comment]
Before this lands we need to run

Step 1: Sync your fork's master
```git checkout master
git reset --hard HEAD~10 # drop 10 commits from your master
git pull upstream master # sync with upstream
git push -f origin HEAD # update your fork's master
```
Step 2: update your PRs:
```git checkout my-branch
git rebase -i master # Drop any commits you don't expect on the branch
git push -f origin HEAD
```

**Comment by cclauss** [comment]
Done on this PR

**Comment by cclauss** [comment]
Someone with admin rights needs to turn this on at https://app.dependabot.com/accounts/internetarchive

**Comment by tfmorris** [comment]
This has been enabled by mek for both openlibrary and infogami.

**Pull request merged**
