### PR TITLE
Partially fix static images not working in gitpod

### PR DESCRIPTION
**Pull request by cdrini**
### Screenshot

Before:
The covers should be the grey default book cover, and there should be up/down arrows next to the headers
image

After:
image

### CODE REVIEW

**Comment by RayBB** [comment]
@cdrini 
I assume this is to fix #5834 ?

On gitpod it doesn't seem to work:
image

**Comment by jimchamp** [comment]
Is this branch causing this?
image

**Comment by cdrini** [comment]
^ Yep it was causing that issue! @RayBB 's fixes to the service worker have now also fixed this issue, so I have put it back up on testing and it should be working!

@scottbarnes tested on the local environment and confirmed it didn't break
I tested on testing.openlibrary.org and confirmed it is working.
@rebecca-shoptaw Can you check on gitpod?

**Comment by cdrini** [comment]
Ah it only works on a hard refresh, ctrl-shift-r, because the service worker is caching the 300 response incorrectly... darn!

**Comment by cdrini** [comment]
Ok I think I fixed the service worker issues issue with that last commit, so it should work! I unfortunately wasn't able to test since gitpod wasn't coming up for me 🥲  But if you can test it @rebecca-shoptaw , that would be awesome!

Note I think you'll need to run `make js` inside the container before the fix takes affect, but then it should work after a ctrl-shift-r, and after many normal ctrl-r :+1:

**Comment by rebecca-shoptaw** [comment]
@cdrini It seems to be working for me in gitpod! Confirmed the little triangle error icon and the loading indicator for the cover form now appear as on testing -- and this is without needing to build js or hard refresh!

**Review by rebecca-shoptaw — APPROVED** [review]
LGTM! This should be SO helpful in gitpod :)

**Pull request merged**
