### PR TITLE
Refactor/variable font families

### LINKED ISSUE #1103: Stylelint: All fonts should make use of variables
There are a surprising amount of font-family rules in openlibrary
So we can make sense of them, let's pull them out into common variables.

The plugin https://github.com/sh-waqar/stylelint-declaration-use-variable can help us identify them and ensure they make use of a variable

Configuration:
`
		"sh-waqar/declaration-use-variable": [
			[
				"/color/",
				"font-family",
				{
					"ignoreValues": ["inherit", "transparent"]
				}
			]
		],
`

### Checklist
- [ ] Update .stylelintrc.json
- [ ] fix any offenders detected via `npm run lint:fix`
- [ ] Create LESS variables for all the different combinations with temporary variables e.g. font-family-serif-1 or font-family-sans-serif-1
- [ ] Create a single rule combining selectors to apply the font groups
e.g.
`
#home-about-mission { font-family: "Georgia","Times New Roman",serif; }
#home-about-mission-tldr{ font-family: "Georgia","Times New Roman",serif; }
`
becomes
`
#home-about-mission-tldr, #home-about-mission { font-family: @serif-1; }
`

### PR DESCRIPTION
**Pull request by Ozzyz**
Closes #1103
I am still a bit unsure of the naming of font-famiily variables. In addition, many of the variables are quite similar (see below), and I'm not totally sure if these should be replaced by a single variable. 
Any input is appreciated :slightly_smiling_face: 
```
@lucida_sans_serif-1: "Lucida Grande", Verdana, Geneva, Helvetica, Arial, sans-serif;
@lucida_sans_serif-2: "Lucida Grande", Verdana, Geneva, Helvetica, sans-serif;
```

## Description:
In this Pull Request we have made the following changes:
- Add stylelint ruless for detecting font-family declarations that does not use a variable
- Replace all font-family rules that did not use variables with variables defined in `static/css/less/font-families.less`

### CODE REVIEW

**Comment by Ozzyz** [comment]
The build is currently failing since the plugin finds font-families without variables in `static/css/legacy.css`. I have not yet changed this file since I was unsure whether or not refactoring counts as 'new css'.

**Comment by tabshaikh** [comment]
@Ozzyz i recommend you to run the command npm run lint:fix to fix all linting issue so that all checks can pass

**Comment by Ozzyz** [comment]
@tabshaikh  - yeah, I did, I was just unsure whether or not to modify  `legacy.less`.
Will fix `legacy.less` and merge some of the font-families as soon as I have time :slightly_smiling_face:

**Comment by mekarpeles** [comment]
We're so close! Even if it's not perfect, this would be great for us to take across the finish line and we can open up a follow-up issue :)

**Comment by Ozzyz** [comment]
I will finish it tonight :) Just have some minor adjustments and I'll push it

**Comment by Ozzyz** [comment]
@jdlrobson , @mekarpeles 
I encountered a lot of small differences between fonts when i was introducing variables for font families,
so here is a short summary of the changes in fonts that are introduced in this branch.
Where there were multiple font-families that only differed with one font, the longest one was chosen for both.
Example: 
 `"Lucida Grande", "Trebuchet MS", Geneva, Helvetica, sans-serif` => `"Lucida Grande", "Trebuchet MS", Geneva, Helvetica, Arial, sans-serif`
There are still some font-variables that might be combined, but I am unsure whether or not to do so. You can see all the fonts in `static/css/less/font-families.less`.

I appreciate any feedback! :smile:

**Comment by mekarpeles** [comment]
> Where there were multiple font-families that only differed with one font, the longest one was chosen for both.

my 👍 vote in favor of this approach. I imagine it could introduce some issues, but we can deal with those as followup issues.

> There are still some font-variables that might be combined, but I am unsure whether or not to do so. 

Do you have some examples we can discuss?

**Comment by jdlrobson** [comment]
This makes total sense to me!
Rebase needed though before we can merge.

Thanks for being so thorough @Ozzyz  !

**Comment by tfmorris** [comment]
Sorry for being late to the party, but I'd like to suggest that the variable naming scheme be changed:

- if possible use semantic names (but I suspect this is too hard)
- eliminate the _serif / _sanserif suffixes since they don't add value
- merge all -* suffixes into a single definition, since any single font should have a single fallback path
- don't abbreviate names in a way that makes them ambiguous c.f. https://en.wikipedia.org/wiki/Lucida#Lucida_Sans

So for the example above, my proposal would be:

    @lucida_grande: "Lucida Grande", Verdana, Geneva, Helvetica, Arial, sans-serif;

I would also merge the multiple monospace definitions.

**Comment by Ozzyz** [comment]
@tfmorris 
Thank you for your feedback! 
I agree that the naming scheme isn't the best, and your proposal works a lot better in my opinion. I will incorporate the changes as soon as I have time.
However, regarding the single fallback path, what would you do with for example
`a : "Lucida Grande", "Trebuchet MS", Geneva, Helvetica, Arial, sans-serif;`
and 
`b: "Lucida Grande", Verdana, Geneva, Helvetica, Arial, sans-serif;` ? 

Should the resulting font-family be something like ` "Lucida Grande", "Trebuchet MS", Verdana, Geneva, Helvetica, Arial, sans-serif;` ? 

Again, thank you for your input  :)

**Comment by jdlrobson** [comment]
Usually in projects where things cannot be named I give generic names such as @font-family-1. We do this already in openlibrary for many of our colors while we make sense of them.

Right now just identifying them is a big step. I think most of them are not needed. At most I suspect we need 3 font family declarations :)

If they are stored in a variable we can reclassify them and rename them later at lower cost.

**Comment by tfmorris** [comment]
@jdlrobson What do you think about a single fallback path per target font? You probably know more about this space than I do, so I could be off-base, but it seems logical to me.

@Ozzyz In the case of conflicts, we presumably want to single "best" fallback path, but I don't know what it would be in your example.

The other thing that occurred to me is that we may want the name to indicate when the font needs to be able to render Unicode characters (e.g. for book titles, authors, etc). There's probably a smaller set of fallbacks available in that case and I've seen rendering issues where things are rendered with the placeholder glyph because the character wasn't in the font.

**Comment by jdlrobson** [comment]
> @jdlrobson What do you think about a single fallback path per target font? You probably know more about this space than I do, so I could be off-base, but it seems logical to me.

Multiple fallback fonts are usually encouraged to cater for the majority of browsers. That said, we probably do have many. I think all these font stacks can be simplified and we likely only need 1-3 of them.

I think all this can happen later though.
I see this change as an inventory - it prevents the situation from getting any worse than it currently is (by adding linting protection) and shows us what we've got to work with.

**Comment by mekarpeles** [comment]
These changes look good to me so far, agree with the direction. @Ozzyz let us know when you feel comfortable moving it out of `WIP` (work in progress) and I'll throw it on https://dev.openlibrary.org for us to verify

**Comment by mekarpeles** [comment]
Apart from resolving conflicts, how can I help us move this over the finish line :)

**Comment by Ozzyz** [comment]
I'll look over it tomorrow. I think i am comfortable to moving it to dev after that :)

**Comment by Ozzyz** [comment]
@mekarpeles  - I think I feel comfortable moving this out of WIP. As said before, most of the uncertainty is wrt. which font-families should be combined. However, as @jdlrobson mentioned, the key thing with this PR is to add linting protection - the details regarding exactly how many font-families and fallback paths are needed can be decided at a later stage.

**Comment by mekarpeles** [comment]
Congrats @Ozzyz! We'll start reviewing :)

**Comment by jdlrobson** [comment]
Would be great to merge this @mekarpeles on weekend/Monday but looks like we need to do a manual rebase (cc @Ozzyz )!

**Comment by jdlrobson** [comment]
@ozzyz keen to get this one merged sooner rather than later. Would you prefer it if I took care of the rebase? Commits should still have your name on them.

**Comment by Ozzyz** [comment]
@jdlrobson  - Sure, go ahead !

**Comment by jdlrobson** [comment]
superseded by the rebase in #1395 !

**Pull request closed without merging**
