### PR TITLE
Add a text area for raw JSON copy/paste on `/import/batch/new` 

### LINKED ISSUE #9487: Add a text area on the batch import page to allow raw JSONL
### Problem

Currently we have an endpoint https://openlibrary.org/admin/imports/add which takes a list of `ocaid` archive.org identifiers. We want patrons to use the 

https://openlibrary.org/import/batch/new endpoint which we should rename as **imports** to be consistent with /admin/imports/add and /imports.

### A clear and concise description of what you want to happen
One should be able to import a new item by entering raw JSON into a text area in the batch import endpoint at `/import/batch/new` (https://openlibrary.org/import/batch/new).

Once the JSONL is submitted, the same validation that happens with an uploaded JSONL file should be run.

### Additional Context
See #8122, which added the existing endpoint. This issue is to extend that by, e.g., adding a `<textarea>` where the JSONL can be entered instead of attaching it as a file.

It was probably a mistake to have `batch_import` take `bytes` here, as this tightly couples the implementation to a file upload: https://github.com/internetarchive/openlibrary/blob/e7f11e7c41b1a9317814c0e96cc1c9bf905c8b67/openlibrary/core/batch_imports.py#L73

Instead, this should likely take a `list` or perhaps a generator. In any event, by changing the function signature here it should be possible to have the form used for submitting raw JSONL input plug directly into this function, unless the form data comes in as `bytes`, which I think it will not by default. The `batch_imports` endpoint will be need to updated as well to account for this change away from bytes: https://github.com/internetarchive/openlibrary/blob/e7f11e7c41b1a9317814c0e96cc1c9bf905c8b67/openlibrary/plugins/openlibrary/code.py#L502-L504.

### Proposal & Constraints

_No response_

### Stakeholders

<hr>
@mekarpeles 

### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

### PR DESCRIPTION
**Pull request by slimkevo**
Closes #9487

Added a text box on the import endpoint that allows raw json text and saves to the database

### Stakeholders

@scottbarnes

### CODE REVIEW

**Comment by scottbarnes** [comment]
Thanks for this, @slimkevo. Before I fully look at this, are all the changes to `openlibrary/code.py` intentional? I am wondering if some editing oversight occurred.

Please also include some output showing the items in the database. You could do something like:
```
❯ docker compose exec db bash
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string.
root@0651d0872d32:/# psql -U openlibrary
psql (9.3.25)
Type "help" for help.

openlibrary=# SELECT * FROM import_item;
 id | batch_id | added_time | import_time | status | error | ia_id | data | ol_key | comments
----+----------+------------+-------------+--------+-------+-------+------+--------+----------
(0 rows)
```

Except hopefully it won't have zero rows, and instead will have the sample records you intended to import. :)

**Comment by slimkevo** [comment]
sorry that was not intentional, I changed it back and added some screenshots 
Image 8-31-24 at 2 16 PM
Image 8-31-24 at 2 45 PM

**Comment by slimkevo** [comment]
@scottbarnes

**Comment by scottbarnes** [comment]
@slimkevo, I hate to be the bearer of less than optimal news, but it looks as if `openlibrary/plugins/openlibrary/code.py` may still have some unintended modifications, and there's an empty file, `FETCH_HEAD` that's been added.

**Comment by slimkevo** [comment]
> @slimkevo, I hate to be the bearer of less than optimal news, but it looks as if `openlibrary/plugins/openlibrary/code.py` may still have some unintended modifications, and there's an empty file, `FETCH_HEAD` that's been added.
> 
> It looks like it does what it needs to do, though, which is good. :)

So for openlibrary/plugins/openlibrary/code.py I did make some changes, as for FETCH_HEAD I will delete it that was not intended @scottbarnes

**Review by scottbarnes — CHANGES_REQUESTED** [review]
Thanks for this, @slimkevo. I am not sure what happened with `openlibrary/plugins/openlibrary/code.py`, insofar as the `BatchImportView` class got deleted, and parts of the `Partials` class was deleted.

However, I pulled out the changes you made into a diff that I think would work. It is difficult to leave the feedback on the relevant lines, so I'll include it as a diff here against the current `master` for ease of comparison.

Please make changes as follows (plus any changes you see fit, if it's still not quite right):
```diff
diff --git a/openlibrary/plugins/openlibrary/code.py b/openlibrary/plugins/openlibrary/code.py
index 8ece430c8..dafbae622 100644
--- a/openlibrary/plugins/openlibrary/code.py
+++ b/openlibrary/plugins/openlibrary/code.py
@@ -501,8 +501,16 @@ class batch_imports(delegate.page):
             raise Forbidden('Permission Denied.')
 
         # Get the upload from web.py. See the template for the <form> used.
-        form_data = web.input(batchImport={})
-        batch_result = batch_import(form_data['batchImport'].file.read())
+        form_data = web.input()
+        if form_data.get("batchImportFile"):
+            batch_result = batch_import(form_data['batchImportFile'])
+        elif form_data.get("batchImportText"):
+            batch_result = batch_import(form_data['batchImportText'].encode("utf-8"))
+        else:
+            add_flash_message(
+                'error',
+                'Either attach a JSONL file or copy/paste JSONL into the text area.',
+            )
 
         return render_template("batch_import.html", batch_result=batch_result)
 
diff --git a/openlibrary/templates/batch_import.html b/openlibrary/templates/batch_import.html
index cd504b06e..e9efe78e7 100644
--- a/openlibrary/templates/batch_import.html
+++ b/openlibrary/templates/batch_import.html
@@ -6,10 +6,14 @@ $var title: $_("Batch Imports")
  <h1>$_("Batch Imports")</h1>
 </div>
 <div id="contentBody" class="batchImport">
-    <p>$_('Attach a JSONL formatted document with import records.')</p>
+    <p>$_('Attach a JSONL formatted document with import records or copy/paste the JSONL text into the textarea.')</p>
     <p>$:_('See the <a href=\"https://github.com/internetarchive/openlibrary-client/tree/master/olclient/schemata\">olclient import schemata</a> for more.')</p>
     <form method="POST" enctype="multipart/form-data" action="">
-      <input type="file" name="batchImport" required>
+      <p>$_('Attach a file:')</p>
+      <input type="file" name="batchImportFile">
+      <hr/>
+      <p>$_('Or copy/paste JSONL text:')</p>
+      <textarea name="batchImportText" rows="10" cols="70"></textarea>
       <hr/>
       <button type="submit">$_('Import')</button>
     </form>
```

Let's also keep both the original formatting and the internationalization of the strings (the `$_('translatable text here')` stuff).

**Comment by scottbarnes** [comment]
@slimkevo, I would like to move this PR forward. In this situation I would ordinarily force-push a new commit to the PR with the above [changes](https://github.com/internetarchive/openlibrary/pull/9834#pullrequestreview-2274198512), but I think I cannot do that as this PR was created from the `master` branch.

To get around this I created #9862 and made you a co-author. If you'd like to go forward with this PR, please let me know and please also make the above changes. Unless I hear otherwise, #9862 will (likely) be merged on Wednesday, September 11th, with you as the co-author.

**Comment by scottbarnes** [comment]
Hi, @slimkevo. I am going to close this because the issue was closed by #9862, where you're a co-author.

**Comment by slimkevo** [comment]
Hello, sorry for the late reply and that sounds good. Thank you for
assigning me to work on this issue!

**Pull request closed without merging**
