### PR TITLE
enable ruff rule to check for unused imports

### LINKED ISSUE #9181: enable ruff rule: unused-import (F401)
### Problem
I noticed we have quite a few instances of unused imports in our python code.
Perhaps some have side effects but many do not appear to have any side effects.

I think it would be good hygiene for our codebase to enable ruff to unused imports and disable it per line as needed.

We tried this once in #9182 long ago.
Now I'm back with new steps:

1. Remove std library unused imports #9995 
2. Mark unusual imports as noqa #9996 
3. Mark all ol/infogami/web unused imports as noqa and enable rule #9997 
4. Address some feedback from 2 via #10001

With this simple plan we'll no longer be able to merge unused imports :)

#### Relevant URL(s)
https://docs.astral.sh/ruff/rules/unused-import/

### PR DESCRIPTION
**Pull request by RayBB**
Closes #9181

### Testing

The tests are passing, and things work fine locally. But we should be thoughtful about if any of these removed imports have side effects we need.

### CODE REVIEW

**Review by scottbarnes — COMMENTED** [review]
I've been testing this one locally, and on the one hand it appears to be working, but on the other hand is scares me a lot because of the way some of these imports give the appearance of being unused.

I am putting this on testing to see how it goes. Thanks for all your work on this so far, @RayBB. I definitely want to see this merged.

**Comment by RayBB** [comment]
@scottbarnes I agree it is a bit tricky to feel confident in this. I tried to be a bit conservative in keeping many that were kinda odd but would be good to review with someone who knows these imports better.
We could also do this a bit more piecemeal by doing a few smaller PRs to remove the ones we have high confidence in but it would be quite a bit more work.

**Comment by tfmorris** [comment]
It's probably OK to remove unused imports for standard library modules, but anything in the openlibrary/infogami/web.py sphere I'd be exceedingly careful of. The have been multiple attempts to do this and people always end up putting them back when they discover hidden side effect dependencies.

**Comment by mekarpeles** [comment]
Seems like it's in a good state, but we may not know what we don't know, so let's talk once more during 1:1 on Wed @scottbarnes and make sure we're happy with the approach (or whether we want to roll this out in stages)

**Comment by mekarpeles** [comment]
I've done a review, my hesitation would be that there could be prod instances (like crons on other tasks that require these imports in other contexts) however, I think TIAS (try it and see) seems like a reasonable approach given having reviewed the specific contexts of these changes and my perceived risks of them. Especially since it's marked as https://github.com/internetarchive/openlibrary/labels/Needs%3A%20Special%20Deploy let's merge, monitor, and be ready to roll back.

**Comment by mekarpeles** [comment]
@scottbarnes ready to go, my apologies though if you're willing to tweak this pr against the follow changes, we should be good to merge.

**Comment by RayBB** [comment]
@mekarpeles @scottbarnes excellent. I think this will be a big win for keeping the code clean. Fingers crossed to not hit any snags with the deploy

**Pull request merged**
