### PR TITLE
WIP: Update Python dependencies: web.py

### PR DESCRIPTION
**Pull request by cclauss**
https://pypi.org/project/web.py  Does not quite get us to Python 3 support but we should make sure that we are compatible with their current software.

__Fails__ our tests: https://travis-ci.org/internetarchive/openlibrary/jobs/450565334#L1212

### CODE REVIEW

**Comment by anandology** [comment]
Planning to work on web.py release next week. Would that resolve the issue?

**Comment by tfmorris** [comment]
@anandology Awesome! I think a release supporting Python 3 would help significantly. The OL team should be able to sort out any other remaining issues.

**Comment by mariusmucenicu** [comment]
@cclauss yea so that's what I've been using on my personal project... in `requirements.txt` that's exactly what I have... `web.py==0.40-dev1` and it works with Python `3.5.X`, `3.6.X` but not `3.7`. However (big shoutout to you) thanks to your pull request which includes a lot of python 3 fixes which was merged in webpy master Python `3.7` seems to work as well so on the next release that will be supported as well.

@anandology said he's about to drop that release soon so I think if you plan on using web.py you can use your work around with `web.py==0.40-dev1` until the version is bumped on PyPi, and then you can bump you requirements.txt

It all comes down to the needs, if you need a framework with a stable release date well I'm sure you pretty much know all the alternatives...here we only have @anandology one man army :d and a bunch of folks who do some open source work from time to time (like yourself, which webpy is very thankful for)

**Comment by tfmorris** [comment]
> On Python 2, [our tests will fail](https://travis-ci.org/internetarchive/openlibrary/jobs/467331025#L1063) if we upgrade _web.py_ from 0.33 to the current 0.39. _**Any help on resolving that would be greatly appreciated**_.

I believe #1835 addresses this. web.py introduced caching of parsed cookies in 0.37 which causes the open library tests to fail for web.py >= 0.37.

We still want to see a release version of web.py 0.40, but I believe everything else is ready.

**Comment by mariusmucenicu** [comment]
@cclauss nice that you guys kept the webpy, my course of action is to port to flask. I would've loved to stick to webpy but unfortunately it's not maintained.

**Pull request closed without merging**
