### PR TITLE
Moved ajax-loader.gif to achieve better caching

### LINKED ISSUE #9104: Move `ajax-loader.gif` for better caching
### Problem

This PR can't be worked on until the following is merged: 
#8930

Currently we have different loader files:
- `/static/images/ajax-loader.gif` used nowhere
- `static/css/ajax-loader.gif` used in two places. But the it is only gif in this folder.
  - `static/css/lib/slick-theme.css`
  - `static/css/components/tagging-menu.less`

What we should do is:
1. Move `static/css/ajax-loader.gif` -> `/static/images/ajax-loader.gif` (overwriting/deleting the image previously there)
2. Update all the references from to reflect this new move

Why?
When I was working on the service worker caching PR (#8930) I had to make a special case to cache this gif because it is in a weird place.

### Reproducing the bug

_No response_

### Context

_No response_

### PR DESCRIPTION
**Pull request by Spedi**
Closes #9104

Moved `ajax-loader.gif` from the `css` folder to the `images` one, to achieve better caching, and updated all deprecated references to the file.

### Stakeholders
@RayBB

### CODE REVIEW

**Comment by Spedi** [comment]
Hi @RayBB, I'm not sure why there's 3 commits to this PR, since I created a new branch just for the caching issue.
Please see the changes and let me know if I did something wrong (which is highly probable). Also I updated the references on 2 files but I can't see them in the commits here on Github, not sure why though.

**Comment by Spedi** [comment]
Got why I didn't see the update on references, didn't do `git add .`... noob error I suppose.
Nevertheless I can't understand why the other commits (Those about Issue #9135) are on this PR, maybe you can help me on elucidating the issue there.

**Comment by RayBB** [comment]
@Spedi you could just undo the changes related to `old-style-lists` and push that in a new commit.

**Comment by Spedi** [comment]
@RayBB Done that, it was an easy fix indeed.
Nonetheless, do you know why this stuff happened? I'm a newbie to the Git world so I may have messed up something in the process, it'll be very helpful to have some kind of feedback.
Thank you so much for your help and patience, really appreciate it, I'm learning a lot by working on this project! :)

**Review by RayBB — APPROVED** [review]
tested locally and is working great!
Just need staff to merge then I'll update my other PR :)

**Comment by mekarpeles** [comment]
The changes make sense, though I'm confused why we replaced the transparent version of the gif with one having a white background -- that may have some visual consequences.

Cc: @RayBB

**Comment by RayBB** [comment]
@mekarpeles idk why github show sit as not transparent but this is what it looks like in prod already.
image

The "transparent version" isn't used anywhere at all that's why we're removing it.
Personally, I think it would be quite nice to have a fancy svg loading indicator but I'll leave that to the design team to decide on :)

**Pull request merged**
