### PR TITLE
Fix deprecation warnings due to invalid escape sequences.

### LINKED ISSUE #3797: Deprecation warning due to invalid escape sequences
### Steps to Reproduce

Deprecation warnings are raised due to invalid escape sequences. This can be fixed by using raw strings or escaping the literals. pyupgrade also helps in automatic conversion : https://github.com/asottile/pyupgrade/ . I will raise a PR for this.

```
$ find . -iname '*.py' | grep -Ev 'example|scripts'  | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./openlibrary/plugins/ol_infobase.py:67: DeprecationWarning: invalid escape sequence \d
  server.app.add_mapping("/([^/]*)/stats/(\d\d\d\d-\d\d-\d\d)", __name__ + ".stats")
./openlibrary/plugins/upstream/data.py:62: DeprecationWarning: invalid escape sequence \d
  path = "/data/ol_dump(|_authors|_editions|_works)_(\d\d\d\d-\d\d-\d\d).txt.gz"
./openlibrary/plugins/upstream/data.py:74: DeprecationWarning: invalid escape sequence \d
  path = "/data/ol_cdump_(\d\d\d\d-\d\d-\d\d).txt.gz"
./openlibrary/plugins/upstream/jsdef.py:171: DeprecationWarning: invalid escape sequence \(
  b = web.re_compile("loop.setup\((.*)\)").match(b).group(1)
./openlibrary/plugins/upstream/covers.py:19: DeprecationWarning: invalid escape sequence \d
  path = "(/books/OL\d+M)/add-cover"
./openlibrary/plugins/upstream/covers.py:86: DeprecationWarning: invalid escape sequence \d
  path = "(/works/OL\d+W)/add-cover"
./openlibrary/plugins/upstream/covers.py:96: DeprecationWarning: invalid escape sequence \d
  path = "(/authors/OL\d+A)/add-photo"
./openlibrary/plugins/upstream/covers.py:104: DeprecationWarning: invalid escape sequence \d
  path = "(/books/OL\d+M)/manage-covers"
./openlibrary/plugins/upstream/covers.py:136: DeprecationWarning: invalid escape sequence \d
  path = "(/works/OL\d+W)/manage-covers"
./openlibrary/plugins/upstream/covers.py:140: DeprecationWarning: invalid escape sequence \d
  path = "(/authors/OL\d+A)/manage-photos"
./openlibrary/plugins/upstream/account.py:429: DeprecationWarning: invalid escape sequence \.
  if not (email and re.match('.*@.*\..*', email)):
./openlibrary/plugins/upstream/code.py:38: DeprecationWarning: invalid escape sequence \d
  path = "(/books/OL\d+M)/cover"
./openlibrary/plugins/upstream/code.py:47: DeprecationWarning: invalid escape sequence \d
  path = "(/authors/OL\d+A)/photo"
./openlibrary/plugins/upstream/code.py:52: DeprecationWarning: invalid escape sequence \d
  path = "(/works/OL\d+W)/merge"
./openlibrary/plugins/upstream/recentchanges.py:110: DeprecationWarning: invalid escape sequence \d
  path = "/recentchanges/(\d\d\d\d(?:/\d\d)?(?:/\d\d)?)(/[^/]*)?"
./openlibrary/plugins/upstream/recentchanges.py:117: DeprecationWarning: invalid escape sequence \d
  path = "/recentchanges/goto/(\d+)"
./openlibrary/plugins/upstream/recentchanges.py:132: DeprecationWarning: invalid escape sequence \d
  path = "/recentchanges/\d\d\d\d/\d\d/\d\d/[^/]*/(\d+)"
./openlibrary/plugins/admin/code.py:714: DeprecationWarning: invalid escape sequence \d
  register_admin_page('/admin/stats/(\d\d\d\d-\d\d-\d\d)', stats, label='Stats JSON')
./openlibrary/plugins/admin/code.py:730: DeprecationWarning: invalid escape sequence \d
  register_admin_page('/admin/imports/(\d\d\d\d-\d\d-\d\d)', imports_by_date, label="")
./openlibrary/utils/ia.py:4: DeprecationWarning: invalid escape sequence \d
  re_loc = re.compile('^(ia\d+\.us\.archive\.org):(/\d+/items/(.*))$')
./openlibrary/i18n/__init__.py:35: DeprecationWarning: invalid escape sequence \$
  cleaned_string = instring.replace('\$', '')
./openlibrary/catalog/marc/download.py:12: DeprecationWarning: invalid escape sequence \d
  '/(bpl\d+\.mrc):(\d+):(\d+)', 'get',
./openlibrary/catalog/marc/download.py:69: DeprecationWarning: invalid escape sequence \d
  form.regexp('\d+', 'Must be a digit'),
./openlibrary/catalog/marc/download.py:73: DeprecationWarning: invalid escape sequence \d
  form.regexp('\d+', 'Must be a digit'),
./openlibrary/catalog/marc/read_toc.py:13: DeprecationWarning: invalid escape sequence \d
  re_end_num = re.compile('\d[]. ]*$')
./openlibrary/catalog/marc/fast_parse.py:221: DeprecationWarning: invalid escape sequence \(
  re_dates = re.compile('^\(?(\d+-\d*|\d*-\d+)\)?$')
./openlibrary/catalog/marc/build_record.py:14: DeprecationWarning: invalid escape sequence \?
  re_question = re.compile('^\?+$')
./openlibrary/catalog/marc/build_record.py:15: DeprecationWarning: invalid escape sequence \d
  re_lccn = re.compile('(...\d+).*')
./openlibrary/catalog/marc/build_record.py:17: DeprecationWarning: invalid escape sequence \d
  re_isbn = re.compile('([^ ()]+[\dX])(?: \((?:v\. (\d+)(?: : )?)?(.*)\))?')
./openlibrary/catalog/marc/build_record.py:18: DeprecationWarning: invalid escape sequence \(
  re_oclc = re.compile ('^\(OCoLC\).*?0*(\d+)')
./openlibrary/catalog/marc/build_record.py:19: DeprecationWarning: invalid escape sequence \d
  re_int = re.compile ('\d{2,}')
./openlibrary/catalog/marc/build_record.py:20: DeprecationWarning: invalid escape sequence \d
  re_number_dot = re.compile('\d{3,}\.$')
./openlibrary/catalog/amazon/read_serp.py:11: DeprecationWarning: invalid escape sequence \d
  re_title = re.compile('<title>Amazon.com: (.*?)(:?, Page \d+)?</title>')
./openlibrary/catalog/amazon/crawl.py:21: DeprecationWarning: invalid escape sequence \(
  re_personalized = re.compile('Personalized for (.*) \((Boy|Girl)\)', re.I)
./openlibrary/catalog/amazon/crawl.py:35: DeprecationWarning: invalid escape sequence \d
  re_result_count = re.compile('Showing (?:[\d,]+ - [\d,]+ of )?([\d,]+) Result')
./openlibrary/catalog/amazon/crawl.py:37: DeprecationWarning: invalid escape sequence \d
  re_rh_n = re.compile('%2Cn%3A(\d+)')
./openlibrary/catalog/amazon/crawl.py:38: DeprecationWarning: invalid escape sequence \(
  re_facet_count = re.compile(u'^\xa0\(([\d,]+)\)$')
./openlibrary/catalog/amazon/crawl.py:48: DeprecationWarning: invalid escape sequence \d
  re_child_book_param = re.compile(',n:(4|28)(?:&page=\d+)?$')
./openlibrary/catalog/amazon/other_editions.py:10: DeprecationWarning: invalid escape sequence \.
  re_link = re.compile('^http://www\.amazon\.com/(?:(.*)/dp|gp/product)/(\d{9}[\dX]|B[A-Z0-9]+)$')
./openlibrary/catalog/amazon/import.py:18: DeprecationWarning: invalid escape sequence \d
  re_amazon = re.compile('^([A-Z0-9]{10}),(\d+):(.*)$', re.S)
./openlibrary/catalog/amazon/import.py:20: DeprecationWarning: invalid escape sequence \w
  re_normalize = re.compile('[^\w ]')
./openlibrary/catalog/amazon/import.py:21: DeprecationWarning: invalid escape sequence \s
  re_whitespace = re.compile('\s+')
./openlibrary/catalog/amazon/import.py:22: DeprecationWarning: invalid escape sequence \(
  re_title_parens = re.compile('^(.+) \([^)]+?\)$')
./openlibrary/catalog/amazon/import.py:24: DeprecationWarning: invalid escape sequence \.
  re_meta_marc = re.compile('([^/]+)_(meta|marc)\.(mrc|xml)')
./openlibrary/catalog/amazon/arc_view.py:8: DeprecationWarning: invalid escape sequence \d
  '/(\d+\.arc)', 'arc_view',
./openlibrary/catalog/amazon/arc_view.py:9: DeprecationWarning: invalid escape sequence \d
  '/(\d+\.arc)/(\d+)', 'page_view',
./openlibrary/catalog/edition_merge/run_merge.py:12: DeprecationWarning: invalid escape sequence \d
  re_edition_key = re.compile('^/books/OL(\d+)M$')
./openlibrary/catalog/edition_merge/merge_works.py:16: DeprecationWarning: invalid escape sequence \d
  re_edition_key = re.compile('^/books/OL(\d+)M$')
./openlibrary/catalog/edition_merge/merge_works.py:17: DeprecationWarning: invalid escape sequence \d
  re_work_key = re.compile('^/works/OL(\d+)W$')
./openlibrary/catalog/edition_merge/merge_works.py:21: DeprecationWarning: invalid escape sequence \d
  re_iso_date = re.compile('^(\d{4})-\d\d-\d\d$')
./openlibrary/catalog/edition_merge/merge_works.py:22: DeprecationWarning: invalid escape sequence \d
  re_end_year = re.compile('(\d{4})$')
./openlibrary/catalog/edition_merge/merge.py:13: DeprecationWarning: invalid escape sequence \d
  re_edition_key = re.compile('^/books/OL(\d+)M$')
./openlibrary/catalog/edition_merge/find_easy.py:10: DeprecationWarning: invalid escape sequence \d
  re_edition_key = re.compile('^/books/OL(\d+)M$')
./openlibrary/views/showmarc.py:87: DeprecationWarning: invalid escape sequence \.
  re_bad_meta_mrc = re.compile('^([^/]+)_meta\.mrc$')
./openlibrary/views/showmarc.py:88: DeprecationWarning: invalid escape sequence \d
  re_lc_sanfranpl = re.compile('^sanfranpl(\d+)/sanfranpl(\d+)\.out')
./openlibrary/views/showmarc.py:91: DeprecationWarning: invalid escape sequence \d
  path = "/show-records/(.*):(\d+):(\d+)"
./openlibrary/solr/read_dump.py:8: DeprecationWarning: invalid escape sequence \d
  re_author_key = re.compile('^/a/OL(\d+)A$')
./openlibrary/solr/read_dump.py:9: DeprecationWarning: invalid escape sequence \d
  re_work_key = re.compile('^/works/OL(\d+)W$')
./openlibrary/solr/read_dump.py:10: DeprecationWarning: invalid escape sequence \d
  re_edition_key = re.compile('^/b/OL(\d+)M$')
./openlibrary/solr/db_load_works.py:9: DeprecationWarning: invalid escape sequence \d
  re_work_key = re.compile('^/works/OL(\d+)W$')
./openlibrary/solr/db_load_authors.py:6: DeprecationWarning: invalid escape sequence \d
  re_author_key = re.compile('^/a/OL(\d+)A$')
```

### PR DESCRIPTION
**Pull request by tirkarthi**
Closes #3797 

### Technical

Fix warning due to invalid escape sequences by escaping and using raw strings wherever necessary.

### Testing

Following command should produce no warnings : 

```
find . -iname '*.py' | grep -Ev 'example|scripts'  | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
```

### CODE REVIEW

**Comment by cdrini** [comment]
Assigning this to you @cclauss , if you could take a look/test. This looks like a bulk replace; I'm not sure if this might break something,e.g. `'\d' == r'\d'`.

**Comment by polinar68** [comment]
@openlibrary

**Comment by cclauss** [comment]
@tirkarthi @polinar68 These are warnings. not errors but they are worth fixing.  However, there are two issues that we need to deal with:
1. We need to complete our transition to Python 3 only: #4384 and friends
2. As Drini says above this bulk replacement might break something and testing across 27 files is a chore.

If I have not progressed on this PR by mid-February, please feel free to ping me again.  Thx!

**Review by polinar68 — APPROVED** [review]

**Comment by cclauss** [comment]
Please rebase this PR so we can see what still not done.

**Comment by mekarpeles** [comment]
@tirkarthi thank you for these contributions! Are you familiar with the rebase process and is there any direction we may be able to offer to help you through it?

We're excited to land your change!

**Comment by tirkarthi** [comment]
I couldn't reproduce the warnings anymore. Given the conflict I guess the changes were merged in some other commits. Below command produces no warnings now inside the git repo. Closing. Thanks.

```
find . -iname '*.py' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
```

**Comment by cclauss** [comment]
YEAH!!!  Thanks!

**Pull request closed without merging**
