### PR TITLE
Upgrade Node.js to v14

### PR DESCRIPTION
**Pull request by dengliming**
Closes [https://github.com/internetarchive/openlibrary/issues/3749](https://github.com/internetarchive/openlibrary/issues/3749)

### CODE REVIEW

**Comment by jdlrobson** [comment]
@cdrini any blockers for this other than the merge conflict? Using updated Node.js seems like a good thing to me.

**Comment by cclauss** [comment]
In the meantime we have dropped Travis CI in favor of GitHub Action so please...
1. Revert the changes to `.travis.yml` which no longer exists.
2. Change our GitHub Action to upgrade Node.js
    * https://github.com/internetarchive/openlibrary/blob/master/.github/workflows/javascript_tests.yml#L14

**Comment by cclauss** [comment]
@cdrini @mekarpeles @jamesachamp @jdlrobson What would be a good test plan for these changes?

**Comment by jdlrobson** [comment]
> @cdrini @mekarpeles @jamesachamp @jdlrobson What would be a good test plan for these changes? It would be good to land Node.js 14 before [Node.js 16 ships next month](https://github.com/nodejs/release).

I don't think this will impact much since we only use Node to generate assets.

I'd suggest simply verifying that all the npm tasks e.g. `npm run test` run without error, and we'll probably want to diff the assets built via `make css` and `make js` before and after the change.

**Comment by cdrini** [comment]
Rebased; pushing up to docker hub for testing now...

**Review by cdrini — APPROVED** [review]
With the new image, tested:

```
openlibrary@94d986cd0f20:/openlibrary$ node --version
v14.16.0
```
- [x] `npm i`
    - `This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!`
- [x] `make js`
- [x] `make css`
- [x] `make components`
- [x] `npm run test`

```
internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/openlibrary/node_modules/iltorb/build/bindings/iltorb.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```
Doesn't seem to affect GitHub actions; maybe `npm ci` will fix... Yep.

**Pull request merged**
