### PR TITLE
Testing Open Library (Python 2) with Infogami latest master

### PR DESCRIPTION
**Pull request by hornc**
@cdrini as discussed, this is the draft PR to check how current OL master (Python 2) behaves importing from the latest infogami.

### CODE REVIEW

**Comment by cclauss** [comment]
The fix is `from infogami.utils.flash import add_flash_message` in [7 files](https://github.com/internetarchive/openlibrary/search?q=add_flash_message) as I demonstrated at https://github.com/internetarchive/openlibrary/pull/2416#commits-pushed-58c608e

**Comment by cclauss** [comment]
I think you will also need to https://github.com/internetarchive/openlibrary/pull/2416/files#diff-6c781bd59890022cebcef34864903552R57

**Comment by tfmorris** [comment]
> This is kind of a duplicate of #2416

Yes, largely, except that does the infogami update on the fly in Travis and only for Python 3.

> The fix is `from infogami.utils.flash import add_flash_message` in [7 files](https://github.com/internetarchive/openlibrary/search?q=add_flash_message) as I demonstrated at [#2416 (commits)](https://github.com/internetarchive/openlibrary/pull/2416#commits-pushed-58c608e) before [04439ff](https://github.com/internetarchive/openlibrary/commit/04439ff69f611d454196d3c67216bf4575b5a26e)

But wasn't that only needed because of an incompatible change in infogami which later got fixed?

**Comment by tfmorris** [comment]
I've updated #2416 to include the latest infogami master rather than pulling it dynamically in Travis CI for Python 3 only. I also rebased/squashed it to make it easier to review. It includes all the necessary stuff that @cclauss mentioned above.

**Comment by cclauss** [comment]
This is still exhibiting the add_flash_message() issue.

**Comment by cclauss** [comment]
Please fix `add_flash_message()` as mentioned at https://github.com/internetarchive/openlibrary/pull/2947#issuecomment-581043863 so the Travis tests will pass.

**Comment by hornc** [comment]
`add_flash_message()` should be available from `infogami.utils.view` -- I haven't yet worked out why it isn't.

I looks like the code is there in the latest infogami  master https://github.com/internetarchive/infogami/blob/master/infogami/utils/view.py#L17  and at the point production Open Library is using: https://github.com/internetarchive/infogami/blob/7595ae764b045c58c762d303da519e00cfe06078/infogami/utils/view.py

**Comment by cclauss** [comment]
https://github.com/internetarchive/infogami/blob/7595ae764b045c58c762d303da519e00cfe06078/infogami/utils/view.py has not been updated since 2011 and its import statements are not Python 3 compatible.  This is why we have been working for PRs like this to land.  The [function is defined](https://github.com/internetarchive/infogami/blob/master/infogami/utils/flash.py#L21) in `infogami/utils/flash.py` so what is the advantage of importing it indirectly from some other file?

**Comment by hornc** [comment]
@cclauss I figured out the confusion. As I noted, the latest infogami master already has `add_flash_message()` available from `infogami.utils.view` -- it was there 11 years ago, and it's there now, but this testing PR didn't have the last few Infogami commits that fixed the functionality change in Infogami, which @tfmorris mentioned above.

The significance of the 11 year old code SHA is that's what is running in production currently. Unfortunately that is _still_ the last known good code point for the Infogami repo, since these tests were failing up until a few commits ago, and even if these tests pass, #2903 an integration issue with Open Library is not caught by any of the unit tests and will break production if deployed.


Because we haven't given our submodules much attention, and committing and confirming the correct latest SHA took more than one attempt, here are the instructions I used for future reference:

(FWIW, the main source of my confusion was managing the checked out version of Infogami inside the Docker container's mounted vendor's volume for testing, vs. the checked out point available to git for committing. There's probably a way to manage this better.) 

```
# To view the current submodule SHAs:
#  From you local git source repo directory (i.e. NOT in Docker)

git submodule

# To update the submodule

cd vendor/infogami
git fetch
git pull

# go back to OL project and check changes
cd ..
git diff --submodule
# You should see the expected submodule changes logged

git diff 
# Should show a single entry updating the subproject SHA. e.g.

diff --git a/vendor/infogami b/vendor/infogami
index 7595ae764..4a383aace 160000
--- a/vendor/infogami
+++ b/vendor/infogami
@@ -1 +1 @@
-Subproject commit 7595ae764b045c58c762d303da519e00cfe06078
+Subproject commit 4a383aace4e66f9659486c0cb295496d9627afd1
```

**Comment by tfmorris** [comment]
So, is this no longer a draft and ready to be reviewed?

**Comment by hornc** [comment]
Ready to be tested at least. #2903 still needs to be addressed. There may be more issues.

**Comment by cclauss** [comment]
Can this be closed?  Or is it useful in some way?  OL on Py2 is tested on against Infogami master in Travis CI.

**Pull request closed without merging**
