### PR TITLE
Update postgres for dev enviroment

### PR DESCRIPTION
**Pull request by jimman2003**
Newest postgres v9 9.6

fix
### Technical

Nothing  ... We recreate the db every time
### Stakeholders

@mekarpeles ,@cdrini

### CODE REVIEW

**Comment by RayBB** [comment]
@jimman2003 what exactly is this fixing? Can you document any risks or change logs that show there should be nothing to worry about?

**Comment by jimman2003** [comment]
Changelog for 9.6 :https://www.postgresql.org/docs/9.6/release-9-6.html

**Comment by jimman2003** [comment]
From posrgres 'why upgrade': We always recommend that all users run the latest available minor release for whatever major version is in use.

**Comment by RayBB** [comment]
That change log is for version 9.6. Since we're moving up from 9.3 you'll also need to review the change logs from 9.4 and 9.5.

Once that is done please document the steps you use to do the upgrade in your local environment and what you did to test that the database update worked.

This is a lot and it's what we should do to ensure a smooth upgrade for developers.

Hopefully they steps people need to take to upgrade their local environment are simple as doing a rebuild of their docker.

If this is all well documented and clear it will make it simple for core maintainers to review and provide feedback on.

PS: Helping upgrade dependencies is great and probably a bit more tricky since it may not always be easy to see the side effects. We also have a [good first issue](https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22) label that has issues that are good for getting familiar with the system. You may want to check some of those out for your next PR 😃

**Comment by jimman2003** [comment]
Oh... 9.4 and 9.5  don't require pg_upgrade.. so easy upgrades

**Comment by jimman2003** [comment]
Testing in local env..

**Comment by jimman2003** [comment]
Works on local dev env!

**Comment by cdrini** [comment]
Our postgres in production is currently not managed in docker, so this change won't have any affect there 😬 We try to keep the local dev env as close to the prod one as possible to avoid confusing situations where something works locally, but magically break in prod. So opting to close this one for now. Longer term, we might want to see if/how we might want to get postgres in docker on prod?

**Pull request closed without merging**
