### PR TITLE
Affiliate server: Make amazon lookup thread a daemon

### LINKED ISSUE #7569: Affiliate Server: Data Fetch Thread Dies
If run long enough (could be an hour, could be a week), the affiliate server's data-fetch thread can seize up and result in a never-ending queue of of isbns which never get cleared + processed.

This issue calls for a modification to the affiliate-sever which checks the state of the auxiliary data processing thread(s) to check whether it's healthy/alive when isbns are submitted. We can use this check to bootstrap/fix/restart any hung thread(s).

### Related files

https://github.com/internetarchive/openlibrary/blob/master/scripts/affiliate_server.py

### PR DESCRIPTION
**Pull request by cclauss**
Closes #7569

Makes this thread automatically restart.
Adds logging which will appear in Sentry with `amazon_lookup()` for error isolation.
Adds stated logging for:
    1. How many ISBN-10s are batched for processing
    2. How many times does the `amazon_lookup()` thread dies?

### Testing

* https://github.com/internetarchive/openlibrary/wiki/Deployment-Guide#recovering-from-restart-loops
* https://github.com/internetarchive/openlibrary/wiki/Recipes
* HOSTNAME="$HOSTNAME" docker-compose up -d --no-deps affiliate-server

Terminal 1
```
ssh -A ol-home0
docker ps  # Make sure affiliate_server is running
docker logs --tail 20 --follow openlibrary-affiliate-server-1
# Get a sense of how logs look under current conditions.
```

Terminal 0
```
ssh -A ol-home0
docker ps  # Make sure affiliate_server is running
cd /opt/openlibrary
git branch
git status

docker exec -it openlibrary-affiliate-server-1 bash  # Go inside Docker image
vi scripts/affiliate_server.py # make desired changes
exit
COMPOSE_FILE="docker-compose.yml:docker-compose.production.yml" HOSTNAME=$HOST \
    docker-compose restart affiliate-server \
    && docker logs --tail 20 --follow openlibrary_affiliate-server_1
# Test changes
# Go back inside the Docker image

# To revert: Go back inside Docker image
vi scripts/affiliate_server.py  # to be just like the master branch (URL below)
restart 
```
* https://raw.githubusercontent.com/internetarchive/openlibrary/master/scripts/affiliate_server.py

### CODE REVIEW

**Comment by mekarpeles** [comment]
How do we clean up / free hung threads?

**Comment by cclauss** [comment]
https://docs.python.org/3/library/threading.html#threading.Thread.daemon

**Comment by cclauss** [comment]
Ready for review.  Running on ol-home0.

**Comment by mekarpeles** [comment]
I believe this is now good to merge, tested + reviewed with @cclauss

**Pull request merged**
