### PR TITLE
Upgrade jquery and get rid of jquery migrate

### LINKED ISSUE #1732: Remove the need for jquery-migrate and upgrade jQuery to version 3
## Feature

> **Problem**: What problem are we solving?

We are using jquery-1.11.0.min.js which is 5 years old and adds IE < 8 support (if we jump to jquery 2 we can drop that support but that's another story).
However, we are also using jquery-migrate to provide backwards compatibilities to older jQuery versions.

When you use the minified version of jquery-migrate, any errors are quietly silenced.

We should surface these errors in the JavaScript console by replacing the line static/js/vendor.jsh
```
xcat $VENDORJS/jquery-migrate/jquery-migrate-1.2.1.min.js
```
with the non-compressed version
```
xcat $VENDORJS/jquery-migrate/jquery-migrate.min.js  | $JSMIN
```

> **Need**: What evidence do you have this feature is important to this audience? What can't we do because this feature does not exist? What must we do instead because this feature doesn't exist? How many users will be impacted? What is the value to us and/or to each user impacted? How much time/money can be earned/saved?

We are shipping code that is meant to be temporary to help with migrations. We might as well be using an older version of jquery (1.11.0) if we are not doing anything about them!

> **Implementation**: How would you go about implementing this?

= Goal
- [x] switch to uncompressed jquery migrate (we can minify it manually)
- [x] after running `make js` warnings are exposed in the console thanks to us using the development version
- [ ] any deprecation notices are addressed
- [ ] jquery-migrate is dropped from the codebase \o/
- [ ] We make the jump to a newer jQuery version \o/.

### PR DESCRIPTION
**Pull request by jdlrobson**
Closes #1732

- [x] It upgrades jQuery from version 1 to version 3 latest. Quite the time travel.
- [x] It drops jquery-migrate that was helping us with that migration.

### Testing

Everything that uses jQuery will need testing. Every nook and cranny. Unit tests can help increase confidence.

### Stakeholders

@cdrini @mekarpeles

### CODE REVIEW

**Comment by jdlrobson** [comment]
@mekarpeles @cdrini this one is now ready. TO INFINITY... AND BEYOND!

**Review by cdrini — APPROVED** [review]
Finally built up the courage to test this 😅 Sorry for the long delay. Rebased and put on testing again :+1:

Testing on IE11:

- Homepage
    - ✅ search autocomplete on homepage works
    - ✅ menus open/close when clicked
    - ❌ menus close when clicked outside of menu
    - ❌ Only one menu open at a time
    - ✅ Changing search dropdown alters autocomplete results
    - ✅ left/right arrow buttons on carousels
    - ✅ Clicking search autocomplete
    - ✅ Pressing enter in search box
    - ✅ Changing site language in footer
- Search page
    - ✅ less/more buttons work
- Login page
    - ✅ Invalid email is marked as invalid
    - ✅ Logging in works
- Work/Edition page page
    - ✅* Lists dropdown shows user's lists
        - See  #5177
    - ✅ Clicking cover brings up enlarged cover
    - ✅ Clicking close button on cover modal closes it
    - ✅ Clicking outside cover modal closes it
    - ✅ Clicking "manage covers" brings up covers modal
    - ✅ Tabs in covers modal work
    - ✅ Uploading cover works
    - ✅* Preview button brings up modal
        - BR is 100% broken on IE11, but the modal works
    - ✅ Searching editions table
    - ✅ Paging editions table
    - ✅ Increasing editions table rows
    - ✅ Increasing editions table rows persists refresh
    - ✅ Adding to list works
    - ✅ Removing from reading log
    - ✅ Adding to reading log
    - ✅ Adding a rating
    - ✅ Clearing rating
    - ✅ Wikipedia citation
- Work/Edition edit page
    - ✅ Setting book lang
    - ✅ Removing identifier
    - ✅ Removing classification
    - ✅ Adding author
    - ✅ Adding excerpt
    - ✅ Adding links
- Author page
    - ✅ Adding author to list
- Subjects page
    - ✅ Scrolling in carousel works

That looks pretty good to me! Does anything jump out to you about the menus? Seems like it might be a quick fix.

**Comment by jdlrobson** [comment]
jQuery 3 should be compatible with IE11 so if this is broken, it's likely broken on all browsers.

Sure enough, I tracked this down to the use of removeAttr being used on a prop - this no longer works in jQuery and have pushed a fix. Nice catch!

I'm curious why you tested on IE11. Is that something I should be doing more as part of my workflow?

**Comment by cdrini** [comment]
Wonderful! Thanks for the quick fix :) Deploying to testing again to try out that flow, then lgtm! 🎉 

I don't usually test on IE11, but figured I would for this one since I was testing all of JS :P I find IE11 is a really good lowest common denominator; if it works in IE11, it'll likely work anywhere.

We do technically still support IE11, but archive.org has stopped supporting it on their end, so writing's on the wall for us as well. We'll likely do it whenever Wikimedia does it.

**Comment by cdrini** [comment]
✅ Also sorta test import flow as much as I could :P

**Comment by cdrini** [comment]
Woohoo! \o/ Welcome to the future!

**Pull request merged**
