### PR TITLE
Update UI styling of Librarian Merge Queue

### LINKED ISSUE #6816: Librarian Merge Queue Redesign
### Describe the problem that you'd like solved

EDIT: The designs have changed slightly, see figma.

We'd think we'd like to head in the direction of a Merge Queue Dashboard which looks like this:
https://www.figma.com/file/kOQdKg11suMVZrDSAXTYLc/Merge-Queue?node-id=0%3A1

www figma com_file_kOQdKg11suMVZrDSAXTYLc_Merge-Queue_node-id=0%3A1

Some of this redesign work has already been implemented in this draft: https://github.com/internetarchive/openlibrary/pull/6736

Creating a project board (?) for Librarian Merge Queue and creating issues for the following

## Remaining

1. [ ] Adding `sort` label / link which swaps the sort order from `desc` to `asc`
    * remember sort across requests / pages
    * defaults to `desc` 
2. [ ] Merge Queue: Add UI dropdown to filter by `submitter`
     * remembers submitter across requests / pages
3. [ ] Merge Queue: Add UI dropdown to filter by `reviewer`
    * remembers reviewer across requests / pages
4. [ ] Hide Librarian Merge Queue comments by default in MR cards
    * Have a button which shows # of comments
    * clicking btn hides/shows div
    * Show the _latest_ comment below the title in the MR card (as is pictured in mock up)
5. [ ] Update UI to look more like the above picture

## Completed

- [x] #6556 
- [x] #6927
- [x] Add `mrid` visibly to rows (somewhere) **P2**
- [x] #6812
- [x] #6811 
- [x] #6833
- [x] #6883
- [x] #6915

**Punted**
- [ ] #6996 
- [ ] #6882 - seems too challenging to get ID from infobase internals

### Stakeholders

@seabelis @dcapillae

### PR DESCRIPTION
**Pull request by Eds-Dbug**
Closes #6816 updating ui base

It updates the UI styling only 

### Technical

only does base css changes and no functionality (just for looks)

### CODE REVIEW

**Comment by Eds-Dbug** [comment]
testing

**Comment by Eds-Dbug** [comment]
Fixed Linting on less file.

**Comment by Eds-Dbug** [comment]
Testing

**Comment by mekarpeles** [comment]
@Eds-Dbug what are the next steps for this PR to go out of draft? When it's ready we can add it to testing.

**Comment by Eds-Dbug** [comment]
I was hoping I could split up this PR into multiple ones, but at this point
I am almost finished my part in the redesign, this PR will probably go out
of draft by the end of the day.

**Comment by Eds-Dbug** [comment]
Update, I might have to postpone the redesign by maybe a day as I have a
couple of interviews that I have to prepare for tomorrow!

**Pull request closed without merging**
