### PR TITLE
Fix dict.keys() to be compatible with both Python 2 and Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Changes to deal with `dict.keys()` returning a list in Python 2 but an iterator in Python 3.
Where possible, simply remove `.keys()` and where necessary wrap the dict in a `list()`.

This pull request closes ~22 failing pytests on Python 3.

Closes #

### CODE REVIEW

**Comment by tfmorris** [comment]
Also rebased and squashed into 2 commits (primary edits + lint cleanups) instead of 4.

But now CI test is failing, so I guess I'll have to figure out what I messed up...

**Comment by tfmorris** [comment]
Ahhh, it was the recently introduced linting of the diffs that was causing the build to break. Thanks for the tip and fix @cclauss !

@hornc This is ready to merge when you have a moment.

**Comment by cclauss** [comment]
Yes.  Sorry that the Travis CI output on Python 3 is chatty right now while we burn down the last 87 issues.  All those diagnostics help me to make progress.

`make lint-diff` can be run locally to ensure that flake8 is placated.  I also use https://pre-commit.com but have not quite figured out how to make pre-commit run `make`.

**Comment by cdrini** [comment]
This one's a little larger, so we would like @hornc to provide input if he has the time (let us know if not, @hornc ). But we can unblock some of your other PRs :+1: Thanks for the patience!

**Comment by mekarpeles** [comment]
These changes possibly impact:
* db.update_docs :fire: 
* marc parsing @hornc 
* reverting docs @seabelis @cdrini 
* author merging @seabelis @cdrini
* work searching @cdrini @mekarpeles 
* and data dumps @hornc 

Most pages (subjects, editions, works, authors) have been tested using this branch, but marc parsing, author merging, etc have not.

**Pull request merged**
