### PR TITLE
Adds eol-last to eslint rules

### LINKED ISSUE #1417: Eslint: new lines at end of file
We have eslint linting for our JS. Let's add a rule for [eol-last](https://eslint.org/docs/rules/) for consistency.
```
    "eol-last": ["error", "always"]
```

- [ ] Add the rule eol-last to .eslintrc.json 
- [ ] Run npm run lint:js and fix all 7 offenders

### PR DESCRIPTION
**Pull request by waghcwb**
Closes #1417

## Description:
This PR adds `eol-last` rule to eslint config and fixes all corresponding errors.

### CODE REVIEW

**Comment by waghcwb** [comment]
dev@jdlrobson,

Should I open this PR for `dev` or `master` branch?

**Comment by jdlrobson** [comment]
Master.
This looks great @waghcwb !

**Comment by waghcwb** [comment]
@jdlrobson,

Thank you, I'll try to solve more frontend issues.

**Comment by jdlrobson** [comment]
If you want im itching to get some whitespace consistency in the javascript.

Ill raise some issues as soon as im back from my mobile device but patches adding rules for no-trailing-spaces, no-multiple-empty-lines, no-mixed-spaces-and-tabs with sensible defaults (and fixes) would be appreciated!!

**Comment by hornc** [comment]
Thanks for your contribution @waghcwb! Merged.

**Pull request merged**
