### PR TITLE
remove editions search endpoint

### LINKED ISSUE #2460: Remove dead `/search/editions` endpoint
This endpoint https://openlibrary.org/search/editions.json?q=the is dead. There are only 36 books which this can search for. Double check to make sure they're unused, and then let's remove the class (located in `worksearch/code.p`) it's template (`search/editions.html`), and any other related files (maybe CSS). It looks like this commit introduced this code; looking at nearby commits might reveal other related files worth deleting.

- 4d83b943c8183a6734e58c2b7e2019a1bcf931c4

### PR DESCRIPTION
**Pull request by imnotjames**
Closes #2460

Tech Debt: Remove the dead code for search editions.

The search editions has less than 100 of the editions on the site indexed.  As such, it's not helpful to have the separate editions search.

### Technical

This does not remove the records from the SOLR index.

### Testing

Verified that the endpoint does not show HTML any longer.

### Evidence

N/A.

### CODE REVIEW

**Comment by cdrini** [comment]
@imnotjames This looks pretty good to me; what can we do to take it out of `draft` mode?

**Comment by imnotjames** [comment]
Sorry about all that!  I had left it in draft while I was researching if anything for migrations needed to be done - eg, removing the data from the SOLR index.  However, I don't see how it would have been indexed in the first place, so that'd be difficult.

**Comment by cdrini** [comment]
Sweet! I'll review/test it within the next few days.

(if you're curious, the mess that is our solr indexing code is located in [update_work.py](https://github.com/internetarchive/openlibrary/blob/d1f7142db47a6aeeb3f94279d9432a36a9783625/openlibrary/solr/update_work.py); but you're right, that data itself in the solr index will just be dropped when we do a [full reindex](https://github.com/internetarchive/openlibrary/pull/1843) )

**Comment by jdlrobson** [comment]
Tested and this LGTM. I won't merge as @cdrini wanted to take a look.

**Comment by cdrini** [comment]
Tested:
- no occurrences of `edition_search`
- no regex matches for `search/editions`

lgtm!

**Pull request merged**
