### PR TITLE
Updated Readme.md

### PR DESCRIPTION
**Pull request by Atharva-Shinde**
Closes #

### CODE REVIEW

**Review by jimman2003 — APPROVED** [review]
I like the new format!

**Comment by mekarpeles** [comment]
Not sure about this PR as there are a handful of changes requested to the main README that expand the length of the readme; e.g. with installation information (as opposed to updating our installation guide itself).

Also, adding a section for front-end section which just links to the same front-end doc just seems like creating an extra step for patrons

**Comment by mekarpeles** [comment]
Adding

```
The development environment can be set up using the [Docker Instructions](https://github.com/internetarchive/openlibrary/blob/master/docker/README.md). You can also watch the [video tutorial](https://archive.org/embed/openlibrary-developer-docs/openlibrary-docker-set-up.mp4) for a more detailed explanation.
```

to the installation section seems good to me

**Comment by mekarpeles** [comment]
closing as we want to keep main README more of an index.

Happy to approve a PR which just addresses https://github.com/internetarchive/openlibrary/pull/5478#issuecomment-898656818

**Pull request closed without merging**
