### PR TITLE
use requests instead of stdlib

### PR DESCRIPTION
**Pull request by aasifkhan7**
Closes https://github.com/internetarchive/openlibrary/issues/2852

@cclauss used requests instead of urllib as well as removed imports of simplejson whereever possible in multiple files.

### CODE REVIEW

**Comment by cclauss** [comment]
Please move the changes to `openlibrary/catalog/utils/query.py` to a separate PR.
* The [__withKey()__](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/utils/query.py#L130-L138) function is retrying until it times out (20 times) on OL bootup in Docker.

When I revert the changes to query.py and then run OL dev on Docker, the system boots and seems highly functional!!!  More testing ahead...

**Comment by aasifkhan7** [comment]
@cclauss reverted the changes in this and opened a new PR #3666

**Comment by cclauss** [comment]
@aasifkhan7 Can you please rebase this PR?

Can you please put the changes for the file `openlibrary/core/lending.py` into a separate PR?

**Comment by cclauss** [comment]
@aasifkhan7 Can you please move the changes to `openlibrary/plugins/ol_infobase.py` into a separate pull request?

**Comment by aasifkhan7** [comment]
@cclauss Yes sure. I will do that soon.

**Comment by cclauss** [comment]
Too many conflicts.

**Pull request closed without merging**
