### PR TITLE
author page infobox

### PR DESCRIPTION
**Pull request by RayBB**
CLOSED IN FAVOR OF #9130

This contributes to the Wikidata project #8236

This is on testing now: https://testing.openlibrary.org/authors/OL345358A/

It creates an infobox for the author page that includes:
- Author name
- Photo
- Birth
- Death
- "Date" (if neither of the above are available)
  - There are 23005 records with this field. More info on what they are [here](https://internetarchive.slack.com/archives/C0ETZV72L/p1711145830331109).

### Why?
- For the Wikidata project we'd like to have an infobox with lots of the new data from Wikidata
- We don't want patrons to have an inconsistent experience where sometimes there is an infobox and sometimes there isn't.
- As such, we are making this first PR to get an infobox showing on all pages.

### Technical

- This design is heavily inspired from the Wikipedia infobox. [Example](https://en.wikipedia.org/wiki/Chris_Wiggins)
- I am absolutely not tied to the colors/sizes/spacing/ect and would love someone to suggest improvements

### Screenshot

<details>
  <summary>After - using the style of the search results</summary>
  
  #### Dates
image

  #### No Dates
image

  
</details> 

<details>
  <summary>Before</summary>
  
  
image

  
</details> 

<details>
  <summary>Old Mockups after - using wikipedia style</summary>
  
  #### Dates
image

  #### No Dates (doesn't look as nice)
image

  
</details> 

### Stakeholders

@mekarpeles

### CODE REVIEW

**Review by cdrini — CHANGES_REQUESTED** [review]
Nice looks good! I think longer term we might want to have a discussion about how to structure this page; eg the subjects I think _do_ make sense above the list of books on mobile (similar to our books pages with collapsing), but considering out of scope for now, since this is just a stepping stone for some of the wikidata changes we wish to make. As such I'm mainly considering whether this will have negative consequences for any existing workflows. So let's get some librarian eyes since they use birth/death date a lot for deduping authors.

I do think we should move the Author name from above the photo to below and adjust spacing as needed to make things balanced. Otherwise lgtm!

**Comment by RayBB** [comment]
@cdrini I've move the name under the image and fixed the spacing as we discussed.

I also posted in the librarian channel [here](https://internetarchive.slack.com/archives/C0119PRDV46/p1713218761171619) to gather comments.

**Comment by RayBB** [comment]
@cdrini all the changes discussed and approved on the call today are here!
- Remove name under image
- Show date in both places for librarians

Try it out: https://testing.openlibrary.org/authors/OL1394244A/

We are ready to merge 🚀

**Comment by RayBB** [comment]
CLOSED IN FAVOR OF #9130

**Pull request closed without merging**
