### PR TITLE
Upgrade .python-version to the penultimate legacy Python

### PR DESCRIPTION
**Pull request by cclauss**
https://www.python.org/psf/press-release/pr20191220/

Closes #

### CODE REVIEW

**Comment by tfmorris** [comment]
This looks good from my point of view, but I don't know if the ops team wants to keep the CI versions synched with the deployed versions. Obviously there won't be much difference between 2.7.14 and 2.7.17.

**Comment by cdrini** [comment]
The deployed version is 2.7.6 :/

**Comment by hornc** [comment]
What actually reads this file to set the Python version? Travis is using Python 2.7.15 for Xenial (seemingly with and without this PR), and Python 2.7.17 for Bionic , again regardless of this PR.

Docker similarly does not appear to use this file, nor does the current production deploy process.

**Comment by cclauss** [comment]
https://github.com/pyenv/pyenv#choosing-the-python-version  pyevn seems to be the tool that uses this file.  Do we use pyenv?

**Comment by hornc** [comment]
That bashrc file looks like it is unused - do you know @mekarpeles ?

I think this .python-version file is confusing and misleading and should probably be removed

**Pull request closed without merging**
