### PR TITLE
fixes srcset attribute errors

### LINKED ISSUE #2144: Book covers appear fuzzy on high res displays
## Description
Covers on the works/books pages look fuzzy on high res displays. They're getting rendered at 180px and are exactly 180px.

## Relevant url?
e.g. https://openlibrary.org/books/OL45985M/From_Sundials_to_Atomic_Clocks

## Expectation
They shouldn't be fuzzy.

## Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox 68.0a1 (Nightly)
- **Operating system?** Android

## Proposal & Constraints
We can use `srcset`! Showing the `-M.jpg` image by default, and the `-L.jpg` image for `2x` displays. (e.g. `https://covers.openlibrary.org/w/id/8576656-M.jpg, https://covers.openlibrary.org/w/id/8576656-L.jpg 2x`).

## Stakeholders
@jdlrobson

### PR DESCRIPTION
**Pull request by devarshigoswami**
Closes #2144

Fixes issue of Book covers appearing fuzzy on high-resolution displays

Technical
Added srcset attribute alongside src for templates/books/show.html &
templates/books/works-show.html

Testing
Tested on locally run docker container and chrome dev console using toggle device toolbar

Stakeholders
@jdlrobson

### CODE REVIEW

**Comment by devarshigoswami** [comment]
@cdrin sir,  I will perform requested changes asap

**Comment by cdrini** [comment]
I think only `book_cover.html` will need to be updated. There, we should be using the `-M` link as the 1x src, and the `-L` link as the 2x srcset.

**Comment by devarshigoswami** [comment]
book_cover.html has a variable  `cover_lg = book.get_cover_url("L")` which doesn't contain a fallback URL like `$ urlM = book.get_cover_url("M") or "/images/icons/avatar_book-lg.png` what do you suggest I do about that, @cdrini

**Comment by cdrini** [comment]
Where the `img` element is made inside the `$if` block, it is set with `-M`; add a `srcset` to that element that uses `cover_lg` :+1:

**Comment by devarshigoswami** [comment]
@cdrini  please check new PR created

**Pull request closed without merging**
