### PR TITLE
Refactor/colorbox design

### PR DESCRIPTION
**Pull request by tabshaikh**
### Description

Subtask of #659

### Technical

The OL colorbox modal has been resized and redesigned 

### Evidence
Screenshot from 2019-06-20 18-50-58
Screenshot from 2019-06-20 18-50-41

### CODE REVIEW

**Comment by tabshaikh** [comment]
The next steps to refactor the modal will be to change the close arrow to something smaller and its color to black/red as it suits the modal

**Comment by mekarpeles** [comment]
This lgtm so far, let's fix the X before merging into master

**Comment by mekarpeles** [comment]
@koderjoker may be able to propose advice on the best way to replace the clunky "X" graphic in our modal.

Right now the modal uses `a.floaterShut {  background-image: url(/images/icons/icon_close-pop.png); }`

Which is implemented here:
`<a class="floaterShut" href="javascript:;" onclick="$.fn.colorbox.close();"><span class="shift">Close</span></a>`

We may want to instead use:
https://fontawesome.com/v4.7.0/icon/times

Or just a simple x (to avoid loading any new font dependencies)

Thoughts?

**Comment by koderjoker** [comment]
I agree that it would be best to avoid loading any new font dependencies.

How about using the unicode for multiplication `&times;` × as a symbol, since it's centred and symmetric, and include it as a button with an aria-label? 
`<button aria-label="Close Modal">&times;</button>`

**Comment by mekarpeles** [comment]
Yeah, I like @koderjoker's solution, here's what I think we should do:
Screen Shot 2019-06-21 at 12 29 19PMPDT

1) set `floaterHead` to `display: flex` so we don't need floats
2) set `div.floaterHead h2` to `flex: 1` so it takes up all the space (other than the ×)
3) remove `background-image`, `position: absolute`, and `top: 0` and `right: 0` from `a.floaterShut`
4) change the contents of `<a class="floaterShut" href="javascript:;" onclick="$.fn.colorbox.close();">...</a>` to be `<a class="floaterShut" href="javascript:;" onclick="$.fn.colorbox.close();">×</a>`

**Comment by tabshaikh** [comment]
The last commit probably needs more testing from your side @mekarpeles :)

**Comment by mekarpeles** [comment]
:( 
1. a `grep -rli "icon_close" reveals that `icon_close-pop.png` is still referenced in `ui-dialog.less`. 
2. Edit Book Covers, click "Manage". The parent container is not large enough

Let's see if/where #1 is used and come up with a solution to #2.

**Comment by mekarpeles** [comment]
The size/clipping issue was related to the declared size of the iframe. I've fixed this and will push

**Comment by mekarpeles** [comment]
Here's an example of where things break! :) No `×`
Screen Shot 2019-06-22 at 13 15 34PMPDT

**Comment by mekarpeles** [comment]
There are the files affected by the `&times;` change. We should go down the list and make sure each works correctly before merging:

```
templates/covers/change.html
templates/covers/author_photo.html
templates/covers/book_cover_single_edition.html
templates/covers/book_cover.html
templates/covers/book_cover_work.html
templates/type/edition/view.html
templates/lists/widget.html
templates/books/edit/addcover.html
templates/books/edit/addfield.html
templates/lib/markdown.html
macros/databarAuthor.html
```

**Comment by mekarpeles** [comment]
All issues seem resolved + paths working.

**Comment by tabshaikh** [comment]
Great then let's merge that

**Comment by mekarpeles** [comment]
Merged into `master` as well.

**Pull request merged**
