### PR TITLE
change to decode bytes for python 3.9

### PR DESCRIPTION
**Pull request by Dhiraj2905**
Closes #

### Testing

 https://github.com/Dhiraj2905/openlibrary.git

### CODE REVIEW

**Comment by blackdollard100** [comment]
Job well done

**Comment by blackdollard100** [comment]
You have done a great job and it is a pleasure working with you

**Comment by cclauss** [comment]
Do we need to do something like [this](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/importapi/code.py#L461-L465) to continue to support legacy Python?

**Comment by Dhiraj2905** [comment]
I'm a beginner so it was my first contribution thanks for your reply @blackdollard100

**Comment by mekarpeles** [comment]
decodebytes doesn't exist on py2

**Pull request closed without merging**
