### PR TITLE
Start a French translation file

### PR DESCRIPTION
**Pull request by hornc**
On PR #801 @LeadSongDog attached a [strings.fr ](https://github.com/internetarchive/openlibrary/files/1732458/strings.fr.txt) , this is my attempt to move those strings to fr/messages.po  (as per #871) 

Tagging @roptat who expressed interest in helping with a French translation?

Please be aware that the source template has been recently updated, I've tried to tidy it as much as possible, but there will still unfortunately be some near duplicate messaging, probably unused strings, and missing messages. I'd love help to surface these sorts of issues and make the messaging better for _all_ languages (including English!) 

I'd suggest starting small, incremental addtions are prefectly OK at this stage, and focusing on the most important parts of UX.

### CODE REVIEW

**Comment by mekarpeles** [comment]
lgtm

**Comment by tfmorris** [comment]
When will this become live? Where - dev or production?

**Comment by roptat** [comment]
Hi, now that the template has been updated, I am working on a translation. I've translated ~1/3rd of the strings independently. This translation is a bit problematic because it's far from complete (I only saw a few sentences) and has some spelling mistakes… I'll try to finish my translation during the week-end. I'd love to be proof-read when I'll be done. Do you know anyone who can speak French and may be interested?

**Comment by tfmorris** [comment]
@roptat I read French, but am not a native speaker, so probably not the best proofreader. I think we can publish a first pass without in being perfect because a) it'll be better than what's there now (nothing) and b) we'll get many more eyes proofreading.

**Comment by hornc** [comment]
@tfmorris not completely nothing: https://openlibrary.org/non-existent-page?lang=fr  for a live proof that there is _something_  (answering you qn above) The mechanism is live, and the data file is being read, but your point a. still holds ;)

**Comment by LeadSongDog** [comment]
Some further terms to translate:
--------------
Open Library
Vision
Careers
Blog
Terms of Service
Donate
Discover
Home
Books
Authors
Subjects
Advanced Search
Return to Top
Develop
Development Center
API Documentation
Bulk Data Dumps
Writing Bots
Add a Book
Help
Help Center
Report A Problem
Suggesting Edits
-------------
at first approximation these could be:
-------------
Vision
Carrières
Blog
Conditions d'utilisation
Faire un don
Découvrir
Accueil
Livres
Auteurs
Sujets
Recherche Avancée
Retourner en haut
Développer
Centre de développement
A propos de l'API
Bulk Data Dumps
Ecrire des bots
Ajouter un livre
Aidez-moi
Centre d'aide
Signaler un problème
Suggérer des modifications

**Comment by roptat** [comment]
Oh, thanks for this! I'll make a new PR with new translations :)

**Comment by roptat** [comment]
Actually there were no update to the pot file, so there's nothing I can do, sorry.

**Pull request merged**
