### PR TITLE
I18n/support template

### PR DESCRIPTION
**Pull request by lephemere**
Contribution to #791. Split from original PR #4741.

Improve i18n support on support templates.
**Requires further discussion, as support staff may only be able to answer to message written in english.**

### Stakeholders

@cdrini

### CODE REVIEW

**Comment by cdrini** [comment]
@seabelis @JeffKaplan @mekarpeles Would love your thoughts on this one; this PR makes the contact page ( https://openlibrary.org/contact ) translatable into other languages. That could mislead folks into thinking the speaker on the other side can speak whatever language the user sees. Thoughts? We could also add a line specifying "Note our staff can only respond in English, Dutch, ...". What languages are you all comfortable responding in?

**Comment by seabelis** [comment]
I can understand Dutch. Responding in Dutch is more difficult. I'm not sure it's an appropriate offer to make but I'm willing to see how it goes.

As it stands now, we get plenty of correspondence in languages other than English, so I suppose this would not make a significant difference.

**Comment by cdrini** [comment]
To be safe I'll put "Only likely able to respond in English" :+1:

**Review by cdrini — APPROVED** [review]
Lgtm! Put it on staging and it looks good.

**Pull request merged**
