### PR TITLE
Svglogo

### LINKED ISSUE #783: Images are not high-DPI (retina) display friendly
055870b2-b4df-4c46-a88d-993a2b279836
This is how it looks like on iPhone 7 Plus. Ideally converting icons to SVG would make for nice size and future-proof optimization.

### LINKED ISSUE #949: Followup on #867 vectorize Internet Archive header logo
@seabelis, up for another (smaller) challenge to help us vectorize the "Internet Archive" logo in our black header bar?

### PR DESCRIPTION
**Pull request by pranjal9599**
> **Description**: What does this PR achieve? [feature|hotfix|refactor]

Vectorized top logo 
Closes #949 
Closes #783

> **Technical**: What should be noted about the implementation?

Created a svg logo for internet archive and replaced the png one with it in templates/site/alert.html

> **Testing**: Steps for reviewer to reproduce / verify this PR fixes the problem?

> **Evidence**: If this PR touches UI, please post evidence (screenshot) of it behaving correctly:

2019-03-05-005834_1901x648_scrot

Before:
2019-03-05-010913_1895x440_scrot

### CODE REVIEW

**Comment by jdlrobson** [comment]
What is our browser support matrix?
This will not render on older browsers that cannot render SVG, so it's worth considering that situation... do we care?


More practically I believe this is based off another branch... can it be rebased on master (without 
d74188b)?

**Comment by mekarpeles** [comment]
@jdlrobson I think we've already bitten the bullet given our Open Library logo is svg -- so I think this change makes sense.

**Comment by jdlrobson** [comment]
Sounds good with regards to svg! I will make a mental note to document that.

 I think you should be able to cherry pick the necessary commits directly to master without any problems (?)

**Comment by tfmorris** [comment]
Ok, I've got to ask -- why is the "top" logo for an entirely different web site? Usually that pride of place is reserved for the logo that takes one to the current site's home page.

Perhaps it should be moved to the footer or somewhere less intrusive?

When I look at the site on mobile, there's nothing but boilerplate "above the fold" before scrolling.

**Comment by pranjal9599** [comment]
rebased without #d74188b

**Comment by mekarpeles** [comment]
Thank you @pranjal9599 !

**Pull request merged**
