### PR TITLE
Fix Individual Subject Page Color Contrast

### PR DESCRIPTION
**Pull request by Yashs911**
Related to #4522
Contrast ratio due to `#738C35` is **3.79:1**
Changing it to `#647c36` will make the ratio **4.68:1**

### Stakeholders

@bpmcneilly

### CODE REVIEW

**Review by jdlrobson — CHANGES_REQUESTED** [review]
I would suggest changing  seeking to change the value of olive rather than introducing a new color dark-olive for consistency. If the color contrast is bad here, probably bad with other combinations.

I'd advise checking the following files and seeing if switching out olive there also improves contrast:
static/css/components/buttonsAndLinks.less
static/css/components/jquery.autocomplete.less
static/css/legacy-borrowBookForm.less
static/css/base/helpers-misc.less

If not I'd like to see some evidence (screenshots, write up) backing up the need for a new color.

**Comment by Yashs911** [comment]
Yes, there are other pages with olive color contrast issues.

**Comment by Yashs911** [comment]
static/css/components/buttonsAndLinks.less **(Not used anymore)**
static/css/components/jquery.autocomplete.less No idea
static/css/legacy-borrowBookForm.less **(Contrast issue)**
static/css/base/helpers-misc.less **(Contrast Issue)**

**Comment by Yashs911** [comment]
@jdlrobson, I have changed the olive color values.

**Comment by jdlrobson** [comment]
> static/css/components/buttonsAndLinks.less (Not used anymore)

Yeh it looks like that isn't used in either jS or CSS. Please remove that whole chunk of CSS in a follow up.

> static/css/components/jquery.autocomplete.less No idea

This looks like its used openlibrary/templates/books/author-autocomplete.html (Create a new record for label)
Screen Shot 2021-02-11 at 5 09 52 PM

**Pull request merged**
