### PR TITLE
Normalize line endings in repository

### PR DESCRIPTION
**Pull request by tfmorris**
Make sure line endings aren't O/S dependent by adding .gitattributes to normalize line endings.  Commit also does a one-time normalization of all line endings which aren't currently normalized.

### CODE REVIEW

**Comment by bfalling** [comment]
Hey @tfmorris, is this a PR you want to pick up again?

**Comment by tfmorris** [comment]
I can update the PR, but it'd probably be worth some discussion to make sure no ones got anything in process that would be disrupted by such a big commit (although they can use diff -w -b)

@hornc @gdamdam @bfalling others? Any opinions? When's the best time to do this?

**Comment by bfalling** [comment]
@tfmorris: Maybe you just want to restart from `master` HEAD and take care of both normalizing line endings and removing trailing whitespace in the existing files. Doing `git diff -w` should then show no difference.

Do we really need `.gitattributes`? Or at least, do we really need anything beyond `text=auto` in it?

**Comment by tfmorris** [comment]
.gitattributes is needed to so that things don't get corrupted again going
forward, but can be simplified to the minimum.

Happy to rebase against present day code if there's consensus that it's a
good thing and the effort won't be wasted.

**Comment by hornc** [comment]
@tfmorris I am happy for you to proceed with the line endings / whitespace tidy. I'm not actively in the middle of any big structural changes (the last one I did around tests has been merged). I'll hold off doing anything big until this is done.

@bfalling , are you happy for Tom to proceed now / soon?

I do end up spending a fair bit of time manually tidying whitespace in the current code when I work on an area. It would be nice to have it all done in one go if possible.

**Comment by bfalling** [comment]
@tfmorris: I'm also very happy for you to proceed, but let's be definite about the time, and so anyone else making changes can hold off while you complete the task, and we can check it and merge to master.

Would you like to propose a date/time?

**Comment by tfmorris** [comment]
The long weekend might have been a good time, but I'm just seeing this, so perhaps we can do it next weekend, although I'll see about doing an initial update tonight.

**Comment by bfalling** [comment]
Just merged #354 which did a one-time removal of trailing whitespace in *.html and *.py files.

**Comment by skylerbunny** [comment]
Granting that #354 was merged, should https://github.com/tfmorris/openlibrary/blob/713c970179d7c83cb53f15b41034454bb3f8098a/.gitattributes still be added on its own as discussed early in this merge?

(At that point this merge could be closed as redundant.)

**Comment by mekarpeles** [comment]
@tfmorris, I think it's a good change and I welcome it, if you're up for the rebaes.

**Comment by tfmorris** [comment]
Sorry I failed to follow up last fall on this 3 yr old PR. I'll try to get it rebased and updated this week. Please ping me (anyone) if it's not done by the weekend.

**Comment by LeadSongDog** [comment]
This may be the wrong place for it, but also need something done about all the records with trailing punctuation in fields. I can't see any value to this except when author mame is inverted, e.g. "Adams, J. Q." or for abbreviations e.g. "320p. I'll."

**Comment by tfmorris** [comment]
This was rebased and updated Apr. 4. Let me know if anything else is needed.

@LeadSongDog You're talking about data quality issues, while this PR is about improving the code, not the data, so yes, this isn't the correct place to discuss. Perhaps open a new issue, if there isn't one already.

**Comment by mekarpeles** [comment]
LGTM

**Comment by mekarpeles** [comment]
Thank you for your work @tfmorris

**Pull request merged**
